//! The cross-platform PIN for this crate's transcendental sites — the gate `vike-indicators`,
//! `vike-analytics` and `vike-mm` each already carry, and which this crate's conversion landed
//! WITHOUT.
//!
//! IEEE 754 requires `+ - * /` and `sqrt` to be correctly rounded and requires NOTHING of
//! `ln`/`exp`/`pow`/`cos`, so an `f64` METHOD call reaches whichever libm the PLATFORM ships —
//! MSVC's CRT on the Windows dev box, glibc on the the CI box Linux boxes and every CI runner — and the
//! two disagree in the last bit. `crates/vike-backtest/Cargo.toml`'s `libm` rationale block names
//! the four sites this crate converted for that reason, and
//! `docs/decisions/0032-transcendentals-come-from-the-libm-crate-not-the-platform.md` is the
//! accepted verdict.
//!
//! ⚠ **Until this file existed, that conversion rested on an ARGUMENT and on nothing else** — "we
//! replaced `f64::powf` with `libm::pow`, so it must be portable now". Nothing in the tree would
//! have noticed the next edit moving a value back, and the crate where that matters most is this
//! one: two of the four sites decide a FILL rather than a report column.
//!
//! # What each pinned row actually decides — read this before ranking a red row as cosmetic
//!
//! * [`PLATFORM_INVARIANT`]'s `impact::AlmgrenChriss::impact_frac` is a **FILL PRICE**. Its result
//!   is ADDED to the engine's flat slippage and multiplied into the executed price
//!   (`crates/vike-fills/src/broker_sim.rs`'s `adverse_fill_price`, reached through
//!   `crates/vike-backtest/src/engine.rs`'s `SimBroker::slippage_for`), so it lands on the equity
//!   curve of every bar-mode backtest that opts the model in. It is also the worst case under
//!   0032's classify-a-power-by-its-BASE rule: base AND exponent are arbitrary runtime `f64`s
//!   (`AC_ALPHA = 0.891`, `AC_BETA = 0.600`).
//! * `queue_model::ProbQueueModel` decides **WHETHER A RESTING ORDER FILLS**.
//!   `crates/vike-backtest/src/queue_model.rs`'s `ProbFunc` — its `f` weights the front-vs-back
//!   attribution of a depth decrease, so it moves the estimated queue ahead of a resting maker —
//!   a backtest can fill on one box and not on the other.
//! * `objective::multi_metric_score` decides a **RANKING**, not a trade. Stated at its true size
//!   because the site's own doc insists on it: `multi_metric` is OPT-IN (`--rank-by multi`), the
//!   sweep default is `RankMetric::Sharpe` and never reaches it. Two boxes crowning a different
//!   winning config off one grid is a research exposure, not a live-order one.
//! * The TPE sampler's proposal stream was the third row here and is NOT in this file any more:
//!   the ask/tell core moved to `vike_ml::tpe`, and its probe moved with it (see the tombstone
//!   where the table stood). The exposure it describes is unchanged and is worth carrying,
//!   because it is the sharpest mechanism of the three: `SplitMix64::gaussian`'s Box-Muller
//!   (`libm::log` + `libm::cos`) and `gaussian_pdf` (`libm::exp`) sit on top of an integer
//!   stream that was ALWAYS identical on both boxes, so one perturbed draw does not nudge a
//!   number - it re-routes the entire subsequent proposal sequence.
//!
//! # What is deliberately NOT pinned here, and why adding a row would be maintenance for nothing
//!
//! `crates/vike-strategy/src/fair_value.rs`'s `trailing_sigma` — the fifth `libm` site in this
//! crate — has **no row**, and that is a decision rather than an oversight.
//! `crates/vike-strategy/tests/cheap_np_parity.rs`'s
//! `trailing_sigma_matches_the_python_oracle_bit_for_bit` already compares `got.to_bits() ==
//! want.to_bits()` against SIX committed `sigma_bits` constants, and it is neither `#[ignore]`d nor
//! cfg-gated: it runs on the Windows dev box under `just t vike-backtest` and on Linux in CI,
//! against the same committed bytes. That IS a cross-platform bit pin for that function, reached by
//! a different route. A row here would restate a guarantee that exists, and a duplicated pin has to
//! be re-recorded twice for every intended change while preventing no failure the first one misses.
//!
//! `.sqrt()` calls are not covered and need no coverage: IEEE 754 requires `sqrt` correctly
//! rounded, so it is already identical on every box.
//!
//! # ⚠ The corpus is PURE ARITHMETIC, and that is load-bearing
//!
//! Every input is generated by an integer LCG plus `+ - * /`, never by `.sin()`/`.cos()`. Those are
//! themselves platform-dependent (MEASURED — `crates/vike-analytics/tests/libm_platform_probe.rs`'s
//! Part A sweeps them as its control), so generating inputs with them would make every row below
//! diverge because of the INPUTS rather than because of the function under test: a false positive
//! that reads exactly like a real one.
//!
//! ```text
//! <cargo> test -p vike-backtest --test libm_platform_probe
//! <cargo> test -p vike-backtest --features datafusion-store --test libm_platform_probe
//! ```

use vike_backtest::impact::{AlmgrenChriss, ImpactInputs, ImpactModel};
use vike_backtest::objective::{MultiMetricParams, multi_metric_score};
use vike_backtest::queue_model::{ProbQueueModel, QueueModel};
use vike_backtest::report::BacktestReport;
use vike_model::libm_walk::{banned_needles, cfg_test_ranges};

// =================================================================================================
// The hashing/corpus machinery, deliberately a per-crate COPY. Decision 0074 moved the TEXT parser
// the SOURCE half below walks with — and ONLY the text parser — into `vike_model::libm_walk`; the
// hasher and the corpus stay beside the table they pin.
// =================================================================================================

/// FNV-1a over `f64::to_bits`, NaN canonicalised so a NaN's sign and payload — neither of which the
/// architecture pins — cannot report a divergence that is not one. The same hasher the sibling
/// probes use, so a row moved between crates hashes identically.
struct Fnv(u64);

impl Fnv {
    fn new() -> Self {
        Fnv(0xcbf2_9ce4_8422_2325)
    }
    fn push(&mut self, v: f64) {
        let bits = if v.is_nan() { 0x7ff8_0000_0000_0000u64 } else { v.to_bits() };
        for b in bits.to_le_bytes() {
            self.0 ^= u64::from(b);
            self.0 = self.0.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    fn hex(&self) -> String {
        format!("{:016x}", self.0)
    }
}

/// Deterministic pseudo-random `f64` in `(0, 1)` from a pure-integer LCG.
///
/// ⚠ No transcendental anywhere in here, for the reason the module doc gives. The `as f64` of a
/// 53-bit integer is exact and the single division is correctly rounded, so the corpus is
/// bit-identical on every platform BY CONSTRUCTION — which is what makes a divergence in the
/// OUTPUT attributable to the function under test rather than to the inputs.
fn lcg(seed: &mut u64) -> f64 {
    *seed = seed.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
    ((*seed >> 11) as f64) / ((1u64 << 53) as f64)
}

/// Samples per row. Large enough that a last-bit disagreement on a rare input survives into the
/// hash rather than being rounded away — the trap the indicators twin fell into twice with a single
/// series, where two genuinely divergent indicators both reported "identical".
const SAMPLES: usize = 4096;

/// One row's verdict over its own corpus.
struct Row {
    label: &'static str,
    hash: String,
    /// How many samples were folded in.
    n: usize,
    /// ⚠ NON-VACUITY GUARD. A row whose corpus collapses to one value — or to all-NaN — hashes
    /// identically on every platform and reads as a PASS while pinning nothing. This is how many
    /// DISTINCT FINITE values the samples took, so a row reporting `distinct=1` is worthless
    /// rather than reassuring. The analytics twin caught a real instance of exactly that
    /// (`overfit::pbo_cscv`), which is why this is a field on EVERY row rather than a check
    /// hand-applied to a chosen few — `crates/vike-mm/src/platform_probe.rs`'s
    /// `every_pinned_row_is_non_vacuous` covers two of its nine rows, and the seven it skips are
    /// skipped because somebody decided so rather than because they are safe.
    distinct: usize,
}

fn finish(label: &'static str, vals: &[f64]) -> Row {
    let mut h = Fnv::new();
    for &v in vals {
        h.push(v);
    }
    let mut bits: Vec<u64> = vals.iter().filter(|v| v.is_finite()).map(|v| v.to_bits()).collect();
    bits.sort_unstable();
    bits.dedup();
    Row { label, hash: h.hex(), n: vals.len(), distinct: bits.len() }
}

/// Smallest number of DISTINCT finite values a row may carry before its pin is treated as vacuous.
const MIN_DISTINCT: usize = 64;

// =================================================================================================
// The feature-free corpus.
// =================================================================================================

/// Every feature-free covered function, folded over its own corpus.
///
/// Returns rows in a FIXED order; [`PLATFORM_INVARIANT`] is compared positionally, so a reordering
/// is a re-record rather than a silent re-pairing.
fn production_rows() -> Vec<Row> {
    let mut out = Vec::new();

    // --- impact::AlmgrenChriss::impact_frac — `libm::pow(nu * T, alpha)` + `libm::pow(nu, beta)`
    //
    // The published calibration is swept ALONGSIDE randomised coefficient sets rather than alone:
    // `AlmgrenChriss`'s fields are all `pub`, a profile can set any of them, and a site that is
    // portable only at its default parameters is portable by accident. `exec_time` is swept too —
    // it is the one input reaching BOTH `pow` calls (it builds `nu`, and it multiplies back into
    // the permanent term's base).
    {
        let mut s = 0x1234_5678_9abc_def0u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        for i in 0..SAMPLES {
            // Alternate the published calibration with a randomised one, so the row covers the
            // configuration that actually ships AND the space around it.
            let model = if i % 2 == 0 {
                AlmgrenChriss::with_exec_time(0.25 + lcg(&mut s) * 4.0)
            } else {
                AlmgrenChriss {
                    gamma: 0.05 + lcg(&mut s) * 1.0,
                    alpha: 0.30 + lcg(&mut s) * 1.4,
                    eta: 0.02 + lcg(&mut s) * 0.6,
                    beta: 0.20 + lcg(&mut s) * 1.2,
                    exec_time: 0.25 + lcg(&mut s) * 4.0,
                }
            };
            let input = ImpactInputs {
                qty: 1.0 + lcg(&mut s) * 250_000.0,
                avg_volume: 1_000.0 + lcg(&mut s) * 5_000_000.0,
                sigma: 1e-4 + lcg(&mut s) * 0.12,
            };
            vals.push(model.impact_frac(&input));
        }
        out.push(finish("impact::AlmgrenChriss::impact_frac (pow x2)", &vals));
    }

    // --- queue_model::ProbQueueModel — `ProbFunc::f` through the PUBLIC trait verb.
    //
    // ⚠ `ProbFunc::f` is a PRIVATE method and is deliberately not made reachable in order to pin
    // it: the consumer that matters is `on_depth_change`, and driving `f` through the verb the
    // tick-replay engine actually calls is the STRONGER pin — it covers the attribution arithmetic
    // wrapped around the call as well. `st.front_qty` after the fold IS the estimated queue ahead
    // of the order, i.e. the quantity a fill decision reads.
    //
    // Two rows, because the two arms are two different libm calls and one of them has a parameter.
    // `Log` is `libm::log(1 + x)` unconditionally. `Power(n)` is `libm::pow(x, n)`, which returns
    // `x` EXACTLY at the default `n = 1` (libm's `pow` takes a `y is ±1` branch ahead of any
    // arithmetic — the site's own doc says so), and is a real transcendental at every other
    // exponent. The `Power` row therefore sweeps `n` AWAY from 1: pinning `n = 1` would pin the one
    // value at which the site is portable by accident.
    {
        let mut s = 0x0fed_cba9_8765_4321u64;
        let m = ProbQueueModel::log();
        let mut vals = Vec::with_capacity(SAMPLES);
        for _ in 0..SAMPLES {
            let level = 10.0 + lcg(&mut s) * 50_000.0;
            let mut st = m.on_new_order(level);
            // A trade FIRST, so `cum_trade_qty` is non-zero and the `chg_net` netting is exercised
            // rather than short-circuited.
            m.on_trade(&mut st, lcg(&mut s) * level * 0.4);
            let new_qty = level * (0.05 + lcg(&mut s) * 0.9);
            m.on_depth_change(&mut st, level, new_qty);
            vals.push(st.front_qty);
        }
        out.push(finish("queue_model::ProbQueueModel::log (log)", &vals));
    }
    {
        let mut s = 0x2222_3333_4444_5555u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        for _ in 0..SAMPLES {
            // n strictly away from 1.0 — see the note above.
            let n = 1.15 + lcg(&mut s) * 2.5;
            let m = ProbQueueModel::power(n);
            let level = 10.0 + lcg(&mut s) * 50_000.0;
            let mut st = m.on_new_order(level);
            m.on_trade(&mut st, lcg(&mut s) * level * 0.4);
            let new_qty = level * (0.05 + lcg(&mut s) * 0.9);
            m.on_depth_change(&mut st, level, new_qty);
            vals.push(st.front_qty);
        }
        out.push(finish("queue_model::ProbQueueModel::power (pow)", &vals));
    }

    // --- objective::multi_metric_score — `shape` + `shape_max`, both `libm::log(1 + pf)`.
    //
    // ⚠ Both private functions are driven through the PUBLIC scorer rather than pinned directly,
    // for the same reason as `ProbFunc::f`. It matters more here: `shape_max` is `shape`'s clamp
    // AND the losing regime's normalizer, so the two are only meaningful together — a pin on either
    // alone would miss the case where one moves and the clamp absorbs it.
    //
    // BOTH regimes are swept. `base = total_return - max_drawdown` selects them and they are
    // genuinely different arithmetic: profitable multiplies by `shape`, losing multiplies by
    // `1 + weight·(1 - shape/shape_max)`. A corpus of one sign would pin half the function.
    {
        let mut s = 0x6666_7777_8888_9999u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        for i in 0..SAMPLES {
            let params = MultiMetricParams {
                target_trades: 5 + (lcg(&mut s) * 200.0) as usize,
                penalty_floor: lcg(&mut s) * 0.5,
                winrate_floor: lcg(&mut s) * 0.4,
                // Strictly positive: `profit_factor_cap <= 0` collapses `shape_max` onto the `0.0`
                // floor and short-circuits the whole logarithm, which would dilute the row.
                profit_factor_cap: 1.0 + lcg(&mut s) * 400.0,
                loss_quality_weight: lcg(&mut s) * 3.0,
            };
            let total_return = (lcg(&mut s) - 0.45) * 2.0;
            let report = BacktestReport {
                name: None,
                final_equity: 1_000.0 * (1.0 + total_return),
                total_return,
                n_trades: (lcg(&mut s) * 400.0) as usize,
                win_rate: lcg(&mut s),
                sharpe: (lcg(&mut s) - 0.5) * 6.0,
                max_drawdown: lcg(&mut s) * 0.9,
                // Half the corpus below the cap and half above it, so the clamp branch and the
                // pass-through branch are both exercised.
                profit_factor: if i % 2 == 0 {
                    lcg(&mut s) * 12.0
                } else {
                    50.0 + lcg(&mut s) * 900.0
                },
                funding_paid: 0.0,
                per_symbol_pnl: Vec::new(),
                zero_trade: None,
                extended: None,
                honesty: None,
                realism: None,
            };
            vals.push(multi_metric_score(&report, &params));
        }
        out.push(finish("objective::multi_metric_score (log x2)", &vals));
    }

    out
}

/// ⚠ **ONE set of constants for EVERY platform — that is the entire claim.**
///
/// ⚠ **Every hash below is the literal `"RECORD"`, a PLACEHOLDER that fails by construction, and
/// that is deliberate.** The convention is the analytics twin's
/// (`crates/vike-analytics/tests/libm_platform_probe.rs`'s `PLATFORM_INVARIANT`): rows are
/// sometimes written on a box that cannot run cargo, and a plausible-looking hex literal invented
/// there is INDISTINGUISHABLE from a recorded one while pinning nothing — the single worst outcome
/// available here. `"RECORD"` cannot match any FNV output, so
/// [`converted_functions_are_platform_invariant`] stays red until a human RUNS this file on
/// Linux/glibc AND on Windows/MSVC, confirms the two runs agree bit-for-bit, and pastes the agreed
/// hash in. **A red row spelled `"RECORD"` is an UNFINISHED RECORDING, not a regression** — that
/// distinction is why the placeholder is a word rather than a wrong number.
///
/// ⚠ **Re-record by RUNNING, never by editing a digit**, and never from ONE box. If a recorded row
/// later goes red the question is which platform moved and why:
///   (a) an intended numeric change — re-record on both boxes and pin the hash they AGREE on; or
///   (b) a call site went back to the platform's libm, in which case the two boxes will NOT agree
///       and the fix is in the source, not here.
///
/// ⚠ **A per-platform table (`#[cfg(windows)]` / `#[cfg(unix)]`) is NOT a repair and must never be
/// added.** It would make the gate green by asserting the divergence was intended — the one
/// conclusion this whole exercise refutes.
const PLATFORM_INVARIANT: [(&str, &str); 4] = [
    ("impact::AlmgrenChriss::impact_frac (pow x2)", "a42b7a7410b0b803"),
    ("queue_model::ProbQueueModel::log (log)", "2b16a2b6cc394c1a"),
    ("queue_model::ProbQueueModel::power (pow)", "c5a36e38ac3cdc04"),
    ("objective::multi_metric_score (log x2)", "a47914aa74e06841"),
];

/// The cross-platform proof, as a GATE rather than a diff somebody has to remember to run.
///
/// NOT `#[ignore]`d: CI runs it on Linux every PR and `just t vike-backtest` runs it on the Windows
/// dev box, both against the same committed table — so the two platforms are held equal without
/// anyone diffing two terminal windows.
#[test]
fn converted_functions_are_platform_invariant() {
    check(&production_rows(), &PLATFORM_INVARIANT, "PLATFORM_INVARIANT");
}

/// Shared comparison + paste-ready failure block, so the feature-gated table below cannot drift
/// from the feature-free one in how it reports.
fn check(got: &[Row], want: &[(&str, &str)], table: &str) {
    assert_eq!(got.len(), want.len(), "row count drifted from {table} — it must be re-recorded");

    let mut bad = Vec::new();
    for (r, (want_label, want_hash)) in got.iter().zip(want.iter()) {
        assert_eq!(
            &r.label, want_label,
            "row ORDER drifted from {table} — the compare is positional"
        );
        if r.hash != *want_hash {
            bad.push(format!("  {:<48} want={want_hash} got={}", r.label, r.hash));
        }
    }

    // The non-vacuity half is asserted BEFORE the hashes, deliberately: a thin row is a defect
    // whether or not its hash matched, and an author re-recording a `"RECORD"` row must be told
    // about it BEFORE pasting a hash that would pin nothing.
    let thin: Vec<String> = got
        .iter()
        .filter(|r| r.distinct < MIN_DISTINCT)
        .map(|r| format!("  {:<48} {} distinct finite of {} samples", r.label, r.distinct, r.n))
        .collect();
    assert!(
        thin.is_empty(),
        "a pinned row's corpus is too thin to detect a last-bit divergence: it would hash \
         identically on every platform and read as a PASS while proving nothing. WIDEN the input \
         ranges — never lower MIN_DISTINCT ({MIN_DISTINCT}):\n{}",
        thin.join("\n")
    );

    if !bad.is_empty() {
        let paste: String =
            got.iter().map(|r| format!("    (\"{}\", \"{}\"),\n", r.label, r.hash)).collect();
        panic!(
            "\nvike-backtest output moved away from {table}:\n{}\n\n\
             There is no tolerance here to widen, and hand-editing a digit defeats the gate.\n\
             If the want= column reads RECORD this is an UNFINISHED RECORDING rather than a\n\
             regression: run this file on BOTH Windows and Linux, confirm the two agree, paste.\n\
             For an already-recorded row, establish WHY before re-recording:\n\
               (a) an intended numeric change — re-record on BOTH boxes and pin the agreed hash; or\n\
               (b) a call site changed which libm it reaches, in which case the two platforms will\n\
                   NOT agree and the fix is in the source, not here.\n\n\
             const {table}: [(&str, &str); {}] = [\n{paste}];\n",
            bad.join("\n"),
            got.len(),
        );
    }
}

/// The control arm for the non-vacuity threshold itself.
///
/// ⚠ Without this, `MIN_DISTINCT` is an assertion nobody has checked DISCRIMINATES. A `distinct`
/// computation that counted samples rather than distinct values — or a threshold accidentally set
/// to `0` — would pass every row above while the guard did nothing, and catching a check that
/// passes while doing nothing is the guard's entire job.
#[test]
fn the_non_vacuity_check_discriminates() {
    let constant: Vec<f64> = (0..SAMPLES).map(|_| 0.5f64).collect();
    let r = finish("control::constant", &constant);
    assert!(
        r.distinct < MIN_DISTINCT,
        "the non-vacuity check does not discriminate: a constant series reported {} distinct",
        r.distinct
    );
    let nans: Vec<f64> = (0..SAMPLES).map(|_| f64::NAN).collect();
    assert_eq!(
        finish("control::nan", &nans).distinct,
        0,
        "an all-NaN row must report ZERO distinct FINITE values — the analytics twin's vacuous row \
         was all-NaN rather than constant, and a `distinct` that counted NaNs would have passed it"
    );
    let mut s = 0xdead_beef_cafe_babeu64;
    let rich: Vec<f64> = (0..SAMPLES).map(|_| lcg(&mut s)).collect();
    assert!(
        finish("control::rich", &rich).distinct >= MIN_DISTINCT,
        "the corpus generator itself is degenerate — every row above is void"
    );
}

// =================================================================================================
// THE `hist-replay` HALF IS GONE FROM THIS FILE, and so is what it probed.
//
// It pinned `harness::tpe::TpeOptimizer`'s proposal stream. That sampler came DOWN to
// `vike_ml::tpe`, so its probe went with it - `crates/vike-ml/tests/libm_platform_probe.rs`,
// where the row is UNGATED and therefore runs in the default roster lane rather than only in
// the `datafusion-store` one. That is a strict widening: the corpus, the constants and the
// recorded hash are unchanged (both crates' hashing machinery is a byte-identical per-crate
// copy, checked before the move), so the pin did not need re-recording - it needed a home
// beside the code it measures.
//
// What stays HERE is the SOURCE gate below, which is not feature-gated and reads
// `crates/vike-backtest/src` as text. `harness/tpe.rs` still lives in this crate - it is the
// store-touching DRIVER - so a `.exp()` written into it is still caught here.
// =================================================================================================

// =================================================================================================
// The SOURCE half. The tables above prove today's outputs agree; this stops the NEXT edit from
// reintroducing a platform call in a spot no corpus reaches.
// =================================================================================================

/// The ONE production line under `crates/vike-backtest/src` that keeps a `powi`, as
/// `(crate-relative path, the substring that must appear on that line)`.
///
/// ⚠ An exemption keyed on a PATH plus the exempted TEXT, never on a path alone: a whole-file skip
/// stops covering every OTHER line in that file, and `sport_taker.rs` is 714 lines long. Both
/// halves must match, so moving the call keeps it exempt while writing a NEW `.exp()` three lines
/// below it does not.
///
/// The argument is a MEASUREMENT rather than a preference.
/// `docs/decisions/0032-transcendentals-come-from-the-libm-crate-not-the-platform.md`'s 2026-08-26
/// amendment classifies a power by its BASE: `10f64.powi(n)` with a runtime integer exponent was
/// swept across the Windows dev box (MSVC) and the Linux CI runners (glibc) and came back
/// BIT-IDENTICAL for every `n` in `-22..=22` — hash `a87aa0b0905b4eac` on both. That is not luck;
/// powers of ten in that range are exactly representable in `f64`, so there is no rounding for two
/// libms to disagree about. `round_dp`'s callers pass `dp` of 4 and 6, comfortably inside the
/// measured range, and rewriting the line as `libm::pow(10.0, dp as f64)` would swap an exact
/// integer power for the general transcendental path and buy nothing.
const POWI_BASE_TEN_EXEMPT: [(&str, &str); 0] = [];

/// Production code in this crate must reach a transcendental through the `libm` CRATE.
///
/// ⚠ Not redundant with the hash tables. Those pin FIVE functions; this crate carries dozens of
/// source files, and a new call site in any of the others would be invisible to every corpus above
/// while quietly making a fill price depend on which box ran the replay. It also covers `harness/`,
/// which no DEFAULT build compiles — this gate reads text, not the feature-resolved crate graph.
///
/// Scope: every `.rs` under `src/`, recursively, MINUS each file's `#[cfg(test)]` item ranges, MINUS
/// the [`POWI_BASE_TEN_EXEMPT`] lines. The text machinery it walks with — `banned_needles` and
/// `cfg_test_ranges`, from `vike_model::libm_walk` — is shared with the ten sibling probes
/// (decision 0074), and the general argument for each lives there. What could NOT move is the
/// evidence below: every sentence of it is a measurement over `crates/vike-backtest/src`, and it is
/// what makes this gate's green mean something in THIS crate.
///
/// # What the shared needle list cannot see, MEASURED against this crate's `src/`
///
/// `banned_needles` misses three spellings: the angle-bracket one (`<f64>::exp(x)` — what appears
/// is `f64>::exp(`, and no needle ends in `>`), a call reached through a generic bound (`T: Float`,
/// `num_traits::Float::exp`), and a call split across two lines by a `max_width` wrap. **None of
/// the three occurs under `crates/vike-backtest/src` today.** A list of spellings is an enumeration
/// and an enumeration is never a proof, so that sentence is a measurement rather than a
/// reassurance — and it is the per-crate half `vike_model::libm_walk` explicitly declines to
/// state for anybody.
///
/// # Why BOTH marker spellings earn their place here — this crate has an instance of the second
///
/// `crates/vike-backtest/src/harness/run.rs` closes a `#[cfg(test)] mod` and immediately opens
/// `#[cfg(all(test, feature = "datafusion-store"))] mod tests {`, which runs to EOF. A walk knowing
/// only the bare `#[cfg(test)]` spelling would treat those last ~188 lines of TEST code as
/// production and report every banned needle in them — a LOUD false positive on a file nobody
/// touched. (It is green today only because that module happens to call no transcendental.)
///
/// # Why locating an item's end by INDENTATION is exact over this crate
///
/// `cfg_test_ranges` finds an item's end by indentation rather than by counting braces, which is
/// safe only where the tree really is rustfmt output. Verified over this crate 2026-08-29: every
/// test marker under `crates/vike-backtest/src` sits at column 0, and each is followed by a line
/// ending in `{`.
#[test]
fn production_code_calls_libm_not_the_platform() {
    let banned = banned_needles();
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let src = root.join("src");
    let mut found = Vec::new();
    let mut scanned: Vec<String> = Vec::new();
    // A `#[cfg(test)]` item whose end could not be located swallows the rest of its file exactly
    // the way a `break` would. That is the one QUIET failure of the range walk, so it is collected
    // and asserted rather than absorbed.
    let mut unclosed: Vec<String> = Vec::new();
    // Which exemptions actually matched. A stale exemption is an un-gated line waiting to happen.
    let mut used_exempt: Vec<&str> = Vec::new();
    let mut stack = vec![src];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).expect("crate has a src/ directory") {
            let path = entry.expect("readable dir entry").path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                continue;
            }
            // `\` -> `/` so an exemption can be written one way and still match on the Windows box.
            let rel = path.strip_prefix(root).unwrap_or(&path).to_string_lossy().replace('\\', "/");
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            let text = std::fs::read_to_string(&path).expect("readable source file");
            scanned.push(name);
            let lines: Vec<&str> = text.lines().collect();
            let test_items = cfg_test_ranges(&lines);
            for &(start, _, closed) in &test_items {
                if !closed {
                    unclosed.push(format!("  {rel}:{}", start + 1));
                }
            }
            for (i, line) in lines.iter().enumerate() {
                if test_items.iter().any(|&(start, end, _)| i >= start && i < end) {
                    continue; // inside a `#[cfg(test)]` item — not shipped
                }
                let code = line.trim_start();
                if code.starts_with("//") {
                    continue; // a doc comment naming `exp` is prose, not a call
                }
                if let Some((_, needle)) =
                    POWI_BASE_TEN_EXEMPT.iter().find(|(p, n)| *p == rel && code.contains(n))
                {
                    used_exempt.push(needle);
                    continue;
                }
                for pat in &banned {
                    if line.contains(pat.as_str()) {
                        found.push(format!("  {rel}:{} {code}", i + 1));
                    }
                }
            }
        }
    }
    // Non-vacuity, aimed at the failure this scan is most likely to have: `src/` NESTS here
    // (`harness/`, `laws/`), so a walk that stopped at the top level would still open dozens of
    // files and report a confident zero while never reading the sampler.
    for must in ["impact.rs", "queue_model.rs", "objective.rs", "tpe.rs"] {
        assert!(
            scanned.iter().any(|s| s == must),
            "the scan never opened {must}, so an empty result proves nothing about the files this \
             gate exists for. Scanned {} files.",
            scanned.len()
        );
    }
    assert!(
        unclosed.is_empty(),
        "a `#[cfg(test)]` item's closing line could not be located, so everything below it went \
         UNSCANNED — the exact hole a `break` leaves, wearing a different cause. See \
         `vike_model::libm_walk::cfg_test_ranges`: the end is the item's own indentation followed \
         by a lone `}}`, or a `;` for a `mod NAME;` declaration. An empty `#[cfg(test)] mod x \
         {{}}` on one line, or a hand-formatted item rustfmt did not touch, lands here.\n{}",
        unclosed.join("\n")
    );
    // ⚠ There is deliberately NO "some production line below a test module was scanned" assertion
    // here, and its absence is a MEASURED fact about this tree rather than an oversight. Measured
    // 2026-08-29 over `crates/vike-backtest/src`: every file's `#[cfg(test)]` module is the LAST
    // item in it — not one of the ~85 files puts one in the middle, and no file carries two — so
    // such an assertion would be FALSE today and could only be written by weakening it into
    // something that proves nothing. The mechanism is held by a PLANTED FIXTURE instead — and
    // since decision 0074 there is one of those rather than ten: the fixture that used to sit in
    // this file now lives beside the parser it proves, in
    // `crates/vike-model/tests/libm_walk_selftest.rs`, which is where a walk that stopped reading
    // below a marker would be caught for every crate at once.
    // (`crates/vike-mm/src/platform_probe.rs` CAN assert it on the tree, because that crate has
    // five mid-file test modules and two `libm` sites below one of them.) The range walk is used
    // here anyway: the property it buys is that the day somebody DOES add a mid-file test module —
    // `tpe.rs` is 1010 lines and already close to wanting one — the gate does not silently go blind
    // to the third of the file below it.
    //
    // A stale exemption is worse than none: it reads as a considered carve-out while covering a
    // line that no longer exists, and the next author copies it.
    for (p, n) in POWI_BASE_TEN_EXEMPT.iter() {
        assert!(
            used_exempt.contains(n),
            "POWI_BASE_TEN_EXEMPT names `{n}` in {p}, and the scan matched no such production \
             line. Either the call moved (update the entry) or it is gone (delete the entry) — a \
             carve-out nothing uses is an un-gated line waiting to happen."
        );
    }
    assert!(
        found.is_empty(),
        "production code must call the `libm` CRATE rather than `f64`'s platform-libm methods, so a \
         FILL PRICE does not depend on which box ran the replay — `crates/vike-backtest/Cargo.toml`'s \
         `libm` rationale block names the four sites and what each one's last bit decides. BOTH \
         spellings are banned, `x.exp()` and `f64::exp(x)`: same inherent method, same libcall (see \
         `vike_model::libm_walk::banned_needles`). `powi` is banned too — on MSVC a `dev` build \
         makes it a `pow()` libcall — and its cure is a MULTIPLICATION rather than `libm`; the \
         one base-ten production site that keeps it is named in `POWI_BASE_TEN_EXEMPT` with the \
         measurement behind it:\n{}",
        found.join("\n")
    );
}
