//! The cross-platform PIN for this crate's transcendental sites — the gate `vike-indicators`,
//! `vike-analytics` and `vike-mm` each already carry, and which this crate's conversion landed
//! WITHOUT.
//!
//! IEEE 754 requires `+ - * /` and `sqrt` to be correctly rounded and requires NOTHING of
//! `ln`/`exp`/`pow`/`cos`, so an `f64` METHOD call reaches whichever libm the PLATFORM ships —
//! MSVC's CRT on the Windows dev box, glibc on the the CI box Linux boxes and every CI runner — and the
//! two disagree in the last bit. `crates/vike-backtest/Cargo.toml`'s `libm` rationale block names
//! the four sites this crate converted for that reason, and
//! `docs/decisions/0032-transcendentals-come-from-the-libm-crate-not-the-platform.md` is the
//! accepted verdict.
//!
//! ⚠ **Until this file existed, that conversion rested on an ARGUMENT and on nothing else** — "we
//! replaced `f64::powf` with `libm::pow`, so it must be portable now". Nothing in the tree would
//! have noticed the next edit moving a value back, and the crate where that matters most is this
//! one: two of the four sites decide a FILL rather than a report column.
//!
//! # What each pinned row actually decides — read this before ranking a red row as cosmetic
//!
//! * [`PLATFORM_INVARIANT`]'s `impact::AlmgrenChriss::impact_frac` is a **FILL PRICE**. Its result
//!   is ADDED to the engine's flat slippage and multiplied into the executed price
//!   (`crates/vike-fills/src/broker_sim.rs`'s `adverse_fill_price`, reached through
//!   `crates/vike-backtest/src/engine.rs`'s `SimBroker::slippage_for`), so it lands on the equity
//!   curve of every bar-mode backtest that opts the model in. It is also the worst case under
//!   0032's classify-a-power-by-its-BASE rule: base AND exponent are arbitrary runtime `f64`s
//!   (`AC_ALPHA = 0.891`, `AC_BETA = 0.600`).
//! * `queue_model::ProbQueueModel` decides **WHETHER A RESTING ORDER FILLS**.
//!   `crates/vike-backtest/src/queue_model.rs`'s `ProbFunc` — its `f` weights the front-vs-back
//!   attribution of a depth decrease, so it moves the estimated queue ahead of a resting maker —
//!   a backtest can fill on one box and not on the other.
//! * `objective::multi_metric_score` decides a **RANKING**, not a trade. Stated at its true size
//!   because the site's own doc insists on it: `multi_metric` is OPT-IN (`--rank-by multi`), the
//!   sweep default is `RankMetric::Sharpe` and never reaches it. Two boxes crowning a different
//!   winning config off one grid is a research exposure, not a live-order one.
//! * [`HIST_REPLAY_INVARIANT`]'s `harness::tpe` row is the same class of exposure, one step
//!   further removed — but with a sharper mechanism. `SplitMix64::gaussian`'s Box–Muller
//!   (`libm::log` + `libm::cos`) and `gaussian_pdf` (`libm::exp`) sit on top of an integer stream
//!   that was ALWAYS identical on both boxes, so one perturbed draw does not nudge a number: it
//!   re-routes the entire subsequent proposal sequence. That module's own
//!   `same_seed_same_proposals` test cannot see it — it runs one closure twice in ONE process,
//!   which any single platform satisfies.
//!
//! # What is deliberately NOT pinned here, and why adding a row would be maintenance for nothing
//!
//! `crates/vike-backtest/src/fair_value.rs`'s `trailing_sigma` — the fifth `libm` site in this
//! crate — has **no row**, and that is a decision rather than an oversight.
//! `crates/vike-backtest/tests/cheap_np_parity.rs`'s
//! `trailing_sigma_matches_the_python_oracle_bit_for_bit` already compares `got.to_bits() ==
//! want.to_bits()` against SIX committed `sigma_bits` constants, and it is neither `#[ignore]`d nor
//! cfg-gated: it runs on the Windows dev box under `just t vike-backtest` and on Linux in CI,
//! against the same committed bytes. That IS a cross-platform bit pin for that function, reached by
//! a different route. A row here would restate a guarantee that exists, and a duplicated pin has to
//! be re-recorded twice for every intended change while preventing no failure the first one misses.
//!
//! `.sqrt()` calls are not covered and need no coverage: IEEE 754 requires `sqrt` correctly
//! rounded, so it is already identical on every box.
//!
//! # ⚠ The corpus is PURE ARITHMETIC, and that is load-bearing
//!
//! Every input is generated by an integer LCG plus `+ - * /`, never by `.sin()`/`.cos()`. Those are
//! themselves platform-dependent (MEASURED — `crates/vike-analytics/tests/libm_platform_probe.rs`'s
//! Part A sweeps them as its control), so generating inputs with them would make every row below
//! diverge because of the INPUTS rather than because of the function under test: a false positive
//! that reads exactly like a real one.
//!
//! ```text
//! <cargo> test -p vike-backtest --test libm_platform_probe
//! <cargo> test -p vike-backtest --features datafusion-store --test libm_platform_probe
//! ```

use vike_backtest::impact::{AlmgrenChriss, ImpactInputs, ImpactModel};
use vike_backtest::objective::{multi_metric_score, MultiMetricParams};
use vike_backtest::queue_model::{ProbQueueModel, QueueModel};
use vike_backtest::report::BacktestReport;

// =================================================================================================
// The shared hashing/corpus machinery. Deliberately a per-crate COPY — see `cfg_test_ranges`'s doc.
// =================================================================================================

/// FNV-1a over `f64::to_bits`, NaN canonicalised so a NaN's sign and payload — neither of which the
/// architecture pins — cannot report a divergence that is not one. The same hasher the sibling
/// probes use, so a row moved between crates hashes identically.
struct Fnv(u64);

impl Fnv {
    fn new() -> Self {
        Fnv(0xcbf2_9ce4_8422_2325)
    }
    fn push(&mut self, v: f64) {
        let bits = if v.is_nan() { 0x7ff8_0000_0000_0000u64 } else { v.to_bits() };
        for b in bits.to_le_bytes() {
            self.0 ^= u64::from(b);
            self.0 = self.0.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    fn hex(&self) -> String {
        format!("{:016x}", self.0)
    }
}

/// Deterministic pseudo-random `f64` in `(0, 1)` from a pure-integer LCG.
///
/// ⚠ No transcendental anywhere in here, for the reason the module doc gives. The `as f64` of a
/// 53-bit integer is exact and the single division is correctly rounded, so the corpus is
/// bit-identical on every platform BY CONSTRUCTION — which is what makes a divergence in the
/// OUTPUT attributable to the function under test rather than to the inputs.
fn lcg(seed: &mut u64) -> f64 {
    *seed = seed.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
    ((*seed >> 11) as f64) / ((1u64 << 53) as f64)
}

/// Samples per row. Large enough that a last-bit disagreement on a rare input survives into the
/// hash rather than being rounded away — the trap the indicators twin fell into twice with a single
/// series, where two genuinely divergent indicators both reported "identical".
const SAMPLES: usize = 4096;

/// One row's verdict over its own corpus.
struct Row {
    label: &'static str,
    hash: String,
    /// How many samples were folded in.
    n: usize,
    /// ⚠ NON-VACUITY GUARD. A row whose corpus collapses to one value — or to all-NaN — hashes
    /// identically on every platform and reads as a PASS while pinning nothing. This is how many
    /// DISTINCT FINITE values the samples took, so a row reporting `distinct=1` is worthless
    /// rather than reassuring. The analytics twin caught a real instance of exactly that
    /// (`overfit::pbo_cscv`), which is why this is a field on EVERY row rather than a check
    /// hand-applied to a chosen few — `crates/vike-mm/src/platform_probe.rs`'s
    /// `every_pinned_row_is_non_vacuous` covers two of its nine rows, and the seven it skips are
    /// skipped because somebody decided so rather than because they are safe.
    distinct: usize,
}

fn finish(label: &'static str, vals: &[f64]) -> Row {
    let mut h = Fnv::new();
    for &v in vals {
        h.push(v);
    }
    let mut bits: Vec<u64> = vals.iter().filter(|v| v.is_finite()).map(|v| v.to_bits()).collect();
    bits.sort_unstable();
    bits.dedup();
    Row { label, hash: h.hex(), n: vals.len(), distinct: bits.len() }
}

/// Smallest number of DISTINCT finite values a row may carry before its pin is treated as vacuous.
const MIN_DISTINCT: usize = 64;

// =================================================================================================
// The feature-free corpus.
// =================================================================================================

/// Every feature-free covered function, folded over its own corpus.
///
/// Returns rows in a FIXED order; [`PLATFORM_INVARIANT`] is compared positionally, so a reordering
/// is a re-record rather than a silent re-pairing.
fn production_rows() -> Vec<Row> {
    let mut out = Vec::new();

    // --- impact::AlmgrenChriss::impact_frac — `libm::pow(nu * T, alpha)` + `libm::pow(nu, beta)`
    //
    // The published calibration is swept ALONGSIDE randomised coefficient sets rather than alone:
    // `AlmgrenChriss`'s fields are all `pub`, a profile can set any of them, and a site that is
    // portable only at its default parameters is portable by accident. `exec_time` is swept too —
    // it is the one input reaching BOTH `pow` calls (it builds `nu`, and it multiplies back into
    // the permanent term's base).
    {
        let mut s = 0x1234_5678_9abc_def0u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        for i in 0..SAMPLES {
            // Alternate the published calibration with a randomised one, so the row covers the
            // configuration that actually ships AND the space around it.
            let model = if i % 2 == 0 {
                AlmgrenChriss::with_exec_time(0.25 + lcg(&mut s) * 4.0)
            } else {
                AlmgrenChriss {
                    gamma: 0.05 + lcg(&mut s) * 1.0,
                    alpha: 0.30 + lcg(&mut s) * 1.4,
                    eta: 0.02 + lcg(&mut s) * 0.6,
                    beta: 0.20 + lcg(&mut s) * 1.2,
                    exec_time: 0.25 + lcg(&mut s) * 4.0,
                }
            };
            let input = ImpactInputs {
                qty: 1.0 + lcg(&mut s) * 250_000.0,
                avg_volume: 1_000.0 + lcg(&mut s) * 5_000_000.0,
                sigma: 1e-4 + lcg(&mut s) * 0.12,
            };
            vals.push(model.impact_frac(&input));
        }
        out.push(finish("impact::AlmgrenChriss::impact_frac (pow x2)", &vals));
    }

    // --- queue_model::ProbQueueModel — `ProbFunc::f` through the PUBLIC trait verb.
    //
    // ⚠ `ProbFunc::f` is a PRIVATE method and is deliberately not made reachable in order to pin
    // it: the consumer that matters is `on_depth_change`, and driving `f` through the verb the
    // tick-replay engine actually calls is the STRONGER pin — it covers the attribution arithmetic
    // wrapped around the call as well. `st.front_qty` after the fold IS the estimated queue ahead
    // of the order, i.e. the quantity a fill decision reads.
    //
    // Two rows, because the two arms are two different libm calls and one of them has a parameter.
    // `Log` is `libm::log(1 + x)` unconditionally. `Power(n)` is `libm::pow(x, n)`, which returns
    // `x` EXACTLY at the default `n = 1` (libm's `pow` takes a `y is ±1` branch ahead of any
    // arithmetic — the site's own doc says so), and is a real transcendental at every other
    // exponent. The `Power` row therefore sweeps `n` AWAY from 1: pinning `n = 1` would pin the one
    // value at which the site is portable by accident.
    {
        let mut s = 0x0fed_cba9_8765_4321u64;
        let m = ProbQueueModel::log();
        let mut vals = Vec::with_capacity(SAMPLES);
        for _ in 0..SAMPLES {
            let level = 10.0 + lcg(&mut s) * 50_000.0;
            let mut st = m.on_new_order(level);
            // A trade FIRST, so `cum_trade_qty` is non-zero and the `chg_net` netting is exercised
            // rather than short-circuited.
            m.on_trade(&mut st, lcg(&mut s) * level * 0.4);
            let new_qty = level * (0.05 + lcg(&mut s) * 0.9);
            m.on_depth_change(&mut st, level, new_qty);
            vals.push(st.front_qty);
        }
        out.push(finish("queue_model::ProbQueueModel::log (log)", &vals));
    }
    {
        let mut s = 0x2222_3333_4444_5555u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        for _ in 0..SAMPLES {
            // n strictly away from 1.0 — see the note above.
            let n = 1.15 + lcg(&mut s) * 2.5;
            let m = ProbQueueModel::power(n);
            let level = 10.0 + lcg(&mut s) * 50_000.0;
            let mut st = m.on_new_order(level);
            m.on_trade(&mut st, lcg(&mut s) * level * 0.4);
            let new_qty = level * (0.05 + lcg(&mut s) * 0.9);
            m.on_depth_change(&mut st, level, new_qty);
            vals.push(st.front_qty);
        }
        out.push(finish("queue_model::ProbQueueModel::power (pow)", &vals));
    }

    // --- objective::multi_metric_score — `shape` + `shape_max`, both `libm::log(1 + pf)`.
    //
    // ⚠ Both private functions are driven through the PUBLIC scorer rather than pinned directly,
    // for the same reason as `ProbFunc::f`. It matters more here: `shape_max` is `shape`'s clamp
    // AND the losing regime's normalizer, so the two are only meaningful together — a pin on either
    // alone would miss the case where one moves and the clamp absorbs it.
    //
    // BOTH regimes are swept. `base = total_return - max_drawdown` selects them and they are
    // genuinely different arithmetic: profitable multiplies by `shape`, losing multiplies by
    // `1 + weight·(1 - shape/shape_max)`. A corpus of one sign would pin half the function.
    {
        let mut s = 0x6666_7777_8888_9999u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        for i in 0..SAMPLES {
            let params = MultiMetricParams {
                target_trades: 5 + (lcg(&mut s) * 200.0) as usize,
                penalty_floor: lcg(&mut s) * 0.5,
                winrate_floor: lcg(&mut s) * 0.4,
                // Strictly positive: `profit_factor_cap <= 0` collapses `shape_max` onto the `0.0`
                // floor and short-circuits the whole logarithm, which would dilute the row.
                profit_factor_cap: 1.0 + lcg(&mut s) * 400.0,
                loss_quality_weight: lcg(&mut s) * 3.0,
            };
            let total_return = (lcg(&mut s) - 0.45) * 2.0;
            let report = BacktestReport {
                name: None,
                final_equity: 1_000.0 * (1.0 + total_return),
                total_return,
                n_trades: (lcg(&mut s) * 400.0) as usize,
                win_rate: lcg(&mut s),
                sharpe: (lcg(&mut s) - 0.5) * 6.0,
                max_drawdown: lcg(&mut s) * 0.9,
                // Half the corpus below the cap and half above it, so the clamp branch and the
                // pass-through branch are both exercised.
                profit_factor: if i % 2 == 0 {
                    lcg(&mut s) * 12.0
                } else {
                    50.0 + lcg(&mut s) * 900.0
                },
                funding_paid: 0.0,
                per_symbol_pnl: Vec::new(),
                zero_trade: None,
            };
            vals.push(multi_metric_score(&report, &params));
        }
        out.push(finish("objective::multi_metric_score (log x2)", &vals));
    }

    out
}

/// ⚠ **ONE set of constants for EVERY platform — that is the entire claim.**
///
/// ⚠ **Every hash below is the literal `"RECORD"`, a PLACEHOLDER that fails by construction, and
/// that is deliberate.** The convention is the analytics twin's
/// (`crates/vike-analytics/tests/libm_platform_probe.rs`'s `PLATFORM_INVARIANT`): rows are
/// sometimes written on a box that cannot run cargo, and a plausible-looking hex literal invented
/// there is INDISTINGUISHABLE from a recorded one while pinning nothing — the single worst outcome
/// available here. `"RECORD"` cannot match any FNV output, so
/// [`converted_functions_are_platform_invariant`] stays red until a human RUNS this file on
/// Linux/glibc AND on Windows/MSVC, confirms the two runs agree bit-for-bit, and pastes the agreed
/// hash in. **A red row spelled `"RECORD"` is an UNFINISHED RECORDING, not a regression** — that
/// distinction is why the placeholder is a word rather than a wrong number.
///
/// ⚠ **Re-record by RUNNING, never by editing a digit**, and never from ONE box. If a recorded row
/// later goes red the question is which platform moved and why:
///   (a) an intended numeric change — re-record on both boxes and pin the hash they AGREE on; or
///   (b) a call site went back to the platform's libm, in which case the two boxes will NOT agree
///       and the fix is in the source, not here.
///
/// ⚠ **A per-platform table (`#[cfg(windows)]` / `#[cfg(unix)]`) is NOT a repair and must never be
/// added.** It would make the gate green by asserting the divergence was intended — the one
/// conclusion this whole exercise refutes.
const PLATFORM_INVARIANT: [(&str, &str); 4] = [
    ("impact::AlmgrenChriss::impact_frac (pow x2)", "a42b7a7410b0b803"),
    ("queue_model::ProbQueueModel::log (log)", "2b16a2b6cc394c1a"),
    ("queue_model::ProbQueueModel::power (pow)", "c5a36e38ac3cdc04"),
    ("objective::multi_metric_score (log x2)", "a47914aa74e06841"),
];

/// The cross-platform proof, as a GATE rather than a diff somebody has to remember to run.
///
/// NOT `#[ignore]`d: CI runs it on Linux every PR and `just t vike-backtest` runs it on the Windows
/// dev box, both against the same committed table — so the two platforms are held equal without
/// anyone diffing two terminal windows.
#[test]
fn converted_functions_are_platform_invariant() {
    check(&production_rows(), &PLATFORM_INVARIANT, "PLATFORM_INVARIANT");
}

/// Shared comparison + paste-ready failure block, so the feature-gated table below cannot drift
/// from the feature-free one in how it reports.
fn check(got: &[Row], want: &[(&str, &str)], table: &str) {
    assert_eq!(got.len(), want.len(), "row count drifted from {table} — it must be re-recorded");

    let mut bad = Vec::new();
    for (r, (want_label, want_hash)) in got.iter().zip(want.iter()) {
        assert_eq!(
            &r.label, want_label,
            "row ORDER drifted from {table} — the compare is positional"
        );
        if r.hash != *want_hash {
            bad.push(format!("  {:<48} want={want_hash} got={}", r.label, r.hash));
        }
    }

    // The non-vacuity half is asserted BEFORE the hashes, deliberately: a thin row is a defect
    // whether or not its hash matched, and an author re-recording a `"RECORD"` row must be told
    // about it BEFORE pasting a hash that would pin nothing.
    let thin: Vec<String> = got
        .iter()
        .filter(|r| r.distinct < MIN_DISTINCT)
        .map(|r| format!("  {:<48} {} distinct finite of {} samples", r.label, r.distinct, r.n))
        .collect();
    assert!(
        thin.is_empty(),
        "a pinned row's corpus is too thin to detect a last-bit divergence: it would hash \
         identically on every platform and read as a PASS while proving nothing. WIDEN the input \
         ranges — never lower MIN_DISTINCT ({MIN_DISTINCT}):\n{}",
        thin.join("\n")
    );

    if !bad.is_empty() {
        let paste: String =
            got.iter().map(|r| format!("    (\"{}\", \"{}\"),\n", r.label, r.hash)).collect();
        panic!(
            "\nvike-backtest output moved away from {table}:\n{}\n\n\
             There is no tolerance here to widen, and hand-editing a digit defeats the gate.\n\
             If the want= column reads RECORD this is an UNFINISHED RECORDING rather than a\n\
             regression: run this file on BOTH Windows and Linux, confirm the two agree, paste.\n\
             For an already-recorded row, establish WHY before re-recording:\n\
               (a) an intended numeric change — re-record on BOTH boxes and pin the agreed hash; or\n\
               (b) a call site changed which libm it reaches, in which case the two platforms will\n\
                   NOT agree and the fix is in the source, not here.\n\n\
             const {table}: [(&str, &str); {}] = [\n{paste}];\n",
            bad.join("\n"),
            got.len(),
        );
    }
}

/// The control arm for the non-vacuity threshold itself.
///
/// ⚠ Without this, `MIN_DISTINCT` is an assertion nobody has checked DISCRIMINATES. A `distinct`
/// computation that counted samples rather than distinct values — or a threshold accidentally set
/// to `0` — would pass every row above while the guard did nothing, and catching a check that
/// passes while doing nothing is the guard's entire job.
#[test]
fn the_non_vacuity_check_discriminates() {
    let constant: Vec<f64> = (0..SAMPLES).map(|_| 0.5f64).collect();
    let r = finish("control::constant", &constant);
    assert!(
        r.distinct < MIN_DISTINCT,
        "the non-vacuity check does not discriminate: a constant series reported {} distinct",
        r.distinct
    );
    let nans: Vec<f64> = (0..SAMPLES).map(|_| f64::NAN).collect();
    assert_eq!(
        finish("control::nan", &nans).distinct,
        0,
        "an all-NaN row must report ZERO distinct FINITE values — the analytics twin's vacuous row \
         was all-NaN rather than constant, and a `distinct` that counted NaNs would have passed it"
    );
    let mut s = 0xdead_beef_cafe_babeu64;
    let rich: Vec<f64> = (0..SAMPLES).map(|_| lcg(&mut s)).collect();
    assert!(
        finish("control::rich", &rich).distinct >= MIN_DISTINCT,
        "the corpus generator itself is degenerate — every row above is void"
    );
}

// =================================================================================================
// The `hist-replay` half: `harness::tpe`, which a DEFAULT build does not compile at all.
// =================================================================================================

/// The TPE table, kept SEPARATE from [`PLATFORM_INVARIANT`] rather than appended to it.
///
/// ⚠ The separation is structural, not stylistic. `harness/` sits behind the `hist-replay` feature
/// (`crates/vike-backtest/src/lib.rs`'s `#[cfg(feature = "hist-replay")] pub mod harness`), so a
/// default `cargo test -p vike-backtest` — the CI roster lane — cannot see `tpe` at all. A single
/// table would then have to change LENGTH with the feature set, and a positional compare against a
/// table whose length depends on how it was built is not a pin.
///
/// Reached by `cargo test -p vike-backtest --features datafusion-store` (the lane that RUNS tests
/// over the harness tree; `hist-replay` alone is clippy-only in `scripts/ci_feature_suite.sh`).
/// ⚠ **The SOURCE gate below is NOT feature-gated and covers `tpe` either way** — it reads the file
/// as text, so a `.exp()` reintroduced under a feature no lane compiles is still caught.
#[cfg(feature = "hist-replay")]
const HIST_REPLAY_INVARIANT: [(&str, &str); 1] =
    [("harness::tpe::TpeOptimizer (gaussian log+cos, gaussian_pdf exp)", "d80ed29b912b84e0")];

/// Drive the TPE ask/tell loop and hash every proposed coordinate.
///
/// ⚠ The loop is driven rather than `gaussian`/`gaussian_pdf` called directly, and not only because
/// both are private. Driving the loop is the STRONGER pin: the failure that matters is not "the pdf
/// is one ulp out", it is "a different one of the `n_candidates` draws won the Expected-Improvement
/// argmax, and every proposal after it differs". A row over the pdf alone would report a last bit;
/// this row reports the re-routed search.
///
/// `n_startup` is deliberately small and the trial count large: `ask` samples UNIFORMLY — no
/// transcendental at all — until `trials.len() >= n_startup.max(2)`, so a corpus dominated by
/// startup draws would pin the LCG and call it a pin of the Parzen sampler. The assertion at the
/// bottom measures that ratio rather than trusting this paragraph.
#[cfg(feature = "hist-replay")]
fn tpe_rows() -> Vec<Row> {
    use vike_backtest::harness::tpe::{ParamDomain, TpeOptimizer};

    const TRIALS: usize = 64;
    const SEEDS: u64 = 48;
    const STARTUP: usize = 4;
    const DIMS: usize = 3;

    let mut vals = Vec::with_capacity(SEEDS as usize * TRIALS * DIMS);
    let mut startup_draws = 0usize;
    for seed in 0..SEEDS {
        let space = vec![
            ("x".to_string(), ParamDomain::continuous(-4.0, 6.5)),
            ("y".to_string(), ParamDomain::continuous(0.001, 25.0)),
            // An INTEGRAL axis beside the two continuous ones: it is rounded on the way out, so it
            // exercises the quantised path a real `[sweep]` table produces — where a last-bit move
            // in a proposal becomes a WHOLE-STEP move in the config that gets run.
            ("k".to_string(), ParamDomain::continuous_integral(1.0, 40.0)),
        ];
        let mut opt =
            TpeOptimizer::new(space, seed, 0.25).with_n_startup(STARTUP).with_n_candidates(24);
        for t in 0..TRIALS {
            let params = opt.ask();
            // ⚠ A PURE-ARITHMETIC objective. A `.sin()` bowl here would make the SCORES
            // platform-dependent, the good/bad split differ, and this row diverge because of the
            // objective rather than because of the sampler — the false positive the module doc
            // warns about, planted in the one place it would be hardest to see.
            let mut score = 0.0f64;
            for (i, v) in params.values().enumerate() {
                let centre = 0.5 + i as f64;
                score -= (v - centre) * (v - centre);
                vals.push(*v);
            }
            opt.tell(&params, score);
            if t < STARTUP {
                startup_draws += DIMS;
            }
        }
    }
    // Non-vacuity SPECIFIC to this row, beyond the shared `distinct` floor: prove the corpus is
    // mostly TPE proposals rather than uniform startup draws. Without it the row could pin the LCG
    // — portable by construction — and report a confident pass about a sampler it never reached.
    assert!(
        startup_draws * 4 < vals.len(),
        "startup (uniform, transcendental-free) draws are {startup_draws} of {} samples — this row \
         would be pinning the LCG rather than the Parzen sampler. Raise TRIALS or lower STARTUP.",
        vals.len()
    );
    vec![finish("harness::tpe::TpeOptimizer (gaussian log+cos, gaussian_pdf exp)", &vals)]
}

#[cfg(feature = "hist-replay")]
#[test]
fn tpe_proposals_are_platform_invariant() {
    check(&tpe_rows(), &HIST_REPLAY_INVARIANT, "HIST_REPLAY_INVARIANT");
}

// =================================================================================================
// The SOURCE half. The tables above prove today's outputs agree; this stops the NEXT edit from
// reintroducing a platform call in a spot no corpus reaches.
// =================================================================================================

/// The `f64` methods whose last bit is the PLATFORM's business rather than IEEE 754's, as bare
/// names. [`banned_needles`] renders each into the two spellings that reach it.
///
/// `sqrt` is deliberately absent and must stay absent: IEEE 754 requires it correctly rounded, so
/// it is identical on every box and there is nothing to convert it TO. `to_degrees`/`to_radians`
/// are absent for the same reason wearing a different disguise — std lowers each to one
/// multiplication by a constant, so they are ordinary arithmetic rather than a libcall.
///
/// `powi` IS here: MEASURED on MSVC, a `dev` build lowers `llvm.powi` to the CRT's `pow()`, so it
/// is a libcall rather than the free multiply chain its name suggests. Its cure is a
/// MULTIPLICATION rather than `libm` — see `crates/vike-indicators/src/math.rs`'s `sq`/`cube`/
/// `quart` — and [`POWI_BASE_TEN_EXEMPT`] carries the one production site here that keeps it.
const BANNED_FNS: [&str; 26] = [
    "powf", "ln", "log", "log2", "log10", "exp", "exp2", "exp_m1", "ln_1p", "sin", "cos", "tan",
    "powi", "atan", "atan2", "asin", "acos", "sinh", "cosh", "tanh", "cbrt", "hypot", "asinh",
    "acosh", "atanh", "sin_cos",
];

/// Every [`BANNED_FNS`] name in BOTH spellings that reach the platform's libm.
///
/// ⚠ The UFCS half is not decoration. A gate that bans `.exp(` and nothing else walks straight past
/// `f64::exp(x)` — the same inherent method, called through its fully-qualified path, compiling to
/// the same libcall. Neither spelling is more correct Rust and rustfmt rewrites neither into the
/// other, so which one an author reaches for is a coin flip. The `f64::NAME(` needle also covers
/// `std::primitive::f64::NAME(` and `core::primitive::f64::NAME(` for free, because both END with
/// exactly that pattern.
///
/// ⚠ **What it still cannot see, stated rather than implied:** `<f64>::exp(x)` (the angle-bracket
/// spelling — `f64>::exp(` is what appears, and no needle here ends in `>`), a call reached through
/// a generic bound (`T: Float`, `num_traits::Float::exp`), and a call split across two lines by a
/// `max_width` wrap. None of the three occurs under this crate's `src/` today. A list of spellings
/// is an enumeration, and an enumeration is never a proof.
fn banned_needles() -> Vec<String> {
    BANNED_FNS.iter().flat_map(|f| [format!(".{f}("), format!("f64::{f}(")]).collect()
}

/// The ONE production line under `crates/vike-backtest/src` that keeps a `powi`, as
/// `(crate-relative path, the substring that must appear on that line)`.
///
/// ⚠ An exemption keyed on a PATH plus the exempted TEXT, never on a path alone: a whole-file skip
/// stops covering every OTHER line in that file, and `sport_taker.rs` is 714 lines long. Both
/// halves must match, so moving the call keeps it exempt while writing a NEW `.exp()` three lines
/// below it does not.
///
/// The argument is a MEASUREMENT rather than a preference.
/// `docs/decisions/0032-transcendentals-come-from-the-libm-crate-not-the-platform.md`'s 2026-08-26
/// amendment classifies a power by its BASE: `10f64.powi(n)` with a runtime integer exponent was
/// swept across the Windows dev box (MSVC) and the Linux CI runners (glibc) and came back
/// BIT-IDENTICAL for every `n` in `-22..=22` — hash `a87aa0b0905b4eac` on both. That is not luck;
/// powers of ten in that range are exactly representable in `f64`, so there is no rounding for two
/// libms to disagree about. `round_dp`'s callers pass `dp` of 4 and 6, comfortably inside the
/// measured range, and rewriting the line as `libm::pow(10.0, dp as f64)` would swap an exact
/// integer power for the general transcendental path and buy nothing.
const POWI_BASE_TEN_EXEMPT: [(&str, &str); 1] =
    [("src/sport_taker.rs", "let f = 10f64.powi(dp as i32);")];

/// Every `#[cfg(test)]` item's line range in one file, as `(start, end, closed)` — `start`
/// inclusive, `end` EXCLUSIVE, both zero-based; `closed` says whether the item's end was actually
/// LOCATED rather than assumed, so the one silent failure mode can be asserted on.
///
/// ⚠ **RANGES, never a `break` at the first marker.** A `break` says "the shipped half of a file
/// ends at its first test module", which is true only when that module is LAST.
/// `crates/vike-mm/src/platform_probe.rs`'s twin measured what it costs when it is not: 1,612
/// production lines discarded across five files, two `libm` sites among them, and the resulting
/// undercount copied into that crate's prose as a confident inventory.
///
/// ⚠ **Measured on THIS crate 2026-08-29, and the honest answer is that the `break` would change
/// no verdict here today**: with the marker set below, every test item under
/// `crates/vike-backtest/src` is the last thing in its file — no file has a production line beneath
/// one. So the ranges are insurance rather than a fix, and the property they buy is that the day
/// somebody splits a long file (`harness/tpe.rs` is 1010 lines) and leaves a test module in the
/// middle, this gate does not silently stop reading everything below it while still reporting a
/// confident zero. That is exactly how `vike-mm` lost sight of two `libm` sites, and it is written
/// up as insurance rather than as a finding because overstating it would make the next reader
/// distrust the parts that ARE measured.
///
/// ⚠ **TWO marker spellings are recognised, and the second is not decoration — this crate has an
/// instance of it.** `crates/vike-backtest/src/harness/run.rs` closes a `#[cfg(test)] mod` at line
/// 434 and immediately opens `#[cfg(all(test, feature = "datafusion-store"))] mod tests {`, which
/// runs to EOF. A walk that knows only the bare `#[cfg(test)]` spelling treats those last ~188
/// lines of TEST code as production and reports every banned needle in them — a LOUD false positive
/// on a file nobody touched. (It is green today only because that module happens to call no
/// transcendental.) `#[cfg(all(test, …))]` is unambiguously test-only, so it is a range.
///
/// ⚠ **`#[cfg(any(test, feature = "…"))]` is deliberately NOT a marker**, and treating it as one
/// would be a real hole rather than a convenience. That attribute marks code that SHIPS whenever
/// the feature is on — `crates/vike-model/src/strategy/mod.rs`'s `MockBroker` and
/// `crates/vike-data/src/exec_index.rs` are the workspace's examples — so it is production for the
/// purposes of this gate and must be scanned. ⚠ `#[cfg(all(feature = "x", test))]`, the same
/// attribute with its operands in the other order, is NOT recognised either; nothing in the tree
/// spells it that way today, and a mis-ordered one would fail LOUD (its test code gets scanned),
/// which is the safe direction for a miss.
///
/// ⚠ **And the cut is LINE BY LINE with the comment filter FIRST.** A whole-file
/// `text.find("#[cfg(test)]")` truncates at the first occurrence of that string ANYWHERE, a doc
/// comment included, and a `//`-skipping filter applied afterwards cannot rescue it because it runs
/// on already-truncated text. Not hypothetical: `crates/vike-mm/src/xemm/basis.rs` opens with a
/// house-style line spelling the attribute in backticks forty lines above any real marker, and a
/// survey that cut there missed the `powf` below it.
///
/// # How an item's end is found, and why by INDENTATION rather than by counting braces
///
/// A brace count needs to know which braces are code, which puts a Rust string/char/comment lexer
/// inside a gate — and this workspace's test modules are full of `format!("{}")` and of assert
/// messages continued with a trailing `\`, so a naive count is not merely imprecise, it is wrong on
/// exactly the files that matter. Indentation needs no lexer and is exact here for a STRUCTURAL
/// reason: `cargo fmt --check` is CI's first gate, so every file in the tree is rustfmt output, and
/// rustfmt closes a block with a `}` alone on a line at the block's OWN indentation. Verified over
/// this crate 2026-08-29: every test marker under `crates/vike-backtest/src` sits at column 0, and
/// each is followed by a line ending in `{`.
///
/// Two ways it can be wrong, and only one is quiet. A line INSIDE the item that IS the closing
/// pattern (a `}` at the item's indentation inside a multi-line string, or inside a
/// `#[rustfmt::skip]` block) ends the range early — the scan then resumes over test code, which is
/// full of banned spellings, so that failure is a LOUD false positive naming the line. No closing
/// pattern at ALL runs the range to EOF and is SILENT, which is the `break`'s behaviour; that is
/// what `closed` is for and why the caller asserts on it.
///
/// ⚠ **This is a per-crate COPY of a shape that now exists in several crates, and the duplication
/// is deliberate rather than unnoticed.** Sharing it needs a crate every one of these test targets
/// can depend on; none has one, and adding the edge costs a manifest change in every pinned crate
/// to save eleven lines of string handling. A gate that lives in another crate is also a gate the
/// owning crate can be moved out from under — the same reason `vike-indicators`, `vike-analytics`
/// and `vike-mm` each hold their own rather than sharing one.
fn cfg_test_ranges(lines: &[&str]) -> Vec<(usize, usize, bool)> {
    /// The attribute spellings that open a TEST-ONLY item. See the doc above for why
    /// `#[cfg(any(test, …))]` is absent: that code SHIPS when its feature is on.
    const TEST_ITEM_ATTRS: [&str; 2] = ["#[cfg(test)]", "#[cfg(all(test,"];

    let mut items = Vec::new();
    let mut i = 0usize;
    while i < lines.len() {
        let trimmed = lines[i].trim_start();
        // Prose FIRST, for the reason the doc gives: a comment naming the attribute in backticks
        // must not be able to open a range.
        if trimmed.starts_with("//") || !TEST_ITEM_ATTRS.iter().any(|a| trimmed.starts_with(a)) {
            i += 1;
            continue;
        }
        let mut closing = " ".repeat(lines[i].len() - trimmed.len());
        closing.push('}');
        let mut opened = false;
        let mut end = lines.len();
        let mut closed = false;
        for (j, line) in lines.iter().enumerate().skip(i) {
            let tail = line.trim_end();
            if !opened {
                // The header may span lines (further attributes, the `mod` on the next line). It
                // ends either by opening a block or, for `#[cfg(test)] mod tests;`, at the `;`.
                if tail.ends_with('{') {
                    opened = true;
                } else if tail.ends_with(';') {
                    end = j + 1;
                    closed = true;
                    break;
                }
                continue;
            }
            if tail == closing {
                end = j + 1;
                closed = true;
                break;
            }
        }
        items.push((i, end, closed));
        i = end;
    }
    items
}

/// The RANGE walk, proved on a synthetic file rather than on the tree it happens to run against.
///
/// ⚠ **A tree-shaped assertion cannot cover this AT ALL in this crate, which is why the fixture is
/// the only proof there is.** Measured 2026-08-29: every test item under
/// `crates/vike-backtest/src` is the last thing in its file, so "some production line below a
/// marker was scanned" is FALSE here and could only be written by weakening it into something
/// vacuous. This fixture holds the mechanism directly instead, and it holds all four properties the
/// walk actually needs: production before a test module, a banned call INSIDE it, production after
/// it, the `;` header form (`#[cfg(test)] mod tests;` — which no brace-matching walk would handle
/// by accident), the `#[cfg(all(test, …))]` spelling `harness/run.rs` really uses, and the
/// `#[cfg(any(test, …))]` spelling that must NOT be excluded because it SHIPS.
#[test]
fn the_test_module_cut_excludes_only_the_test_module() {
    // Every fixture row is a string literal, so the needles inside them are data rather than calls;
    // this file lives under `tests/` and the scan below reads `src/` only, so it never sees them.
    let file = [
        "//! House style: naïve f64 folds, pure, in-file `#[cfg(test)]`.",
        "fn shipped_before() -> f64 {",
        "    x.exp()",
        "}",
        "",
        "#[cfg(test)]",
        "mod first_tests {",
        "    fn fixture() -> f64 {",
        "        y.ln()",
        "    }",
        "}",
        "",
        "fn shipped_after() -> f64 {",
        "    f64::powf(z, 2.0)",
        "}",
        "",
        "#[cfg(all(test, feature = \"datafusion-store\"))]",
        "mod store_tests {",
        "    fn fixture() -> f64 {",
        "        y.log10()",
        "    }",
        "}",
        "",
        "#[cfg(any(test, feature = \"test-support\"))]",
        "pub fn a_shipped_double() -> f64 {",
        "    q.tanh()",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests;",
        "",
        "fn shipped_last() -> f64 {",
        "    w.sin_cos().0",
        "}",
    ];
    let items = cfg_test_ranges(&file);
    assert_eq!(items.len(), 3, "all three TEST-ONLY items must be found: {items:?}");
    assert_eq!(items[0], (5, 11, true), "the braced module spans its own lines only");
    assert_eq!(items[1], (16, 22, true), "the `all(test, …)` module is test-only and is a range");
    assert_eq!(items[2], (28, 30, true), "the `mod tests;` declaration ends at its semicolon");
    // The control arm: the module doc on line 1 NAMES the attribute in backticks. If prose could
    // open a range, `items[0]` would start at 0 and every assertion here would still pass while the
    // gate scanned nothing at all.
    assert_eq!(items[0].0, 5, "a `#[cfg(test)]` inside a comment must not open a range");

    let banned = banned_needles();
    let hits: Vec<usize> = file
        .iter()
        .enumerate()
        .filter(|(i, line)| {
            !items.iter().any(|&(s, e, _)| *i >= s && *i < e)
                && !line.trim_start().starts_with("//")
                && banned.iter().any(|p| line.contains(p.as_str()))
        })
        .map(|(i, _)| i)
        .collect();
    assert_eq!(
        hits,
        [2, 13, 25, 32],
        "the scan must see the production call BEFORE the first test module (line 3), the one AFTER \
         it (line 14), the one inside the `any(test, …)` item that SHIPS (line 26), and the one \
         after the `mod tests;` declaration (line 33) — and must NOT see either fixture call \
         (lines 9 and 20). A `break` at the first marker sees only line 3; a walk that treats \
         `any(test, …)` as test-only loses line 26, which is shipped code. \
         Saw (zero-based): {hits:?}"
    );
}

/// Production code in this crate must reach a transcendental through the `libm` CRATE.
///
/// ⚠ Not redundant with the hash tables. Those pin FIVE functions; this crate carries dozens of
/// source files, and a new call site in any of the others would be invisible to every corpus above
/// while quietly making a fill price depend on which box ran the replay. It also covers `harness/`,
/// which no DEFAULT build compiles — this gate reads text, not the feature-resolved crate graph.
///
/// Scope: every `.rs` under `src/`, recursively, MINUS each file's `#[cfg(test)]` item ranges, MINUS
/// the [`POWI_BASE_TEN_EXEMPT`] lines.
#[test]
fn production_code_calls_libm_not_the_platform() {
    let banned = banned_needles();
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let src = root.join("src");
    let mut found = Vec::new();
    let mut scanned: Vec<String> = Vec::new();
    // A `#[cfg(test)]` item whose end could not be located swallows the rest of its file exactly
    // the way a `break` would. That is the one QUIET failure of the range walk, so it is collected
    // and asserted rather than absorbed.
    let mut unclosed: Vec<String> = Vec::new();
    // Which exemptions actually matched. A stale exemption is an un-gated line waiting to happen.
    let mut used_exempt: Vec<&str> = Vec::new();
    let mut stack = vec![src];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).expect("crate has a src/ directory") {
            let path = entry.expect("readable dir entry").path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                continue;
            }
            // `\` -> `/` so an exemption can be written one way and still match on the Windows box.
            let rel = path.strip_prefix(root).unwrap_or(&path).to_string_lossy().replace('\\', "/");
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            let text = std::fs::read_to_string(&path).expect("readable source file");
            scanned.push(name);
            let lines: Vec<&str> = text.lines().collect();
            let test_items = cfg_test_ranges(&lines);
            for &(start, _, closed) in &test_items {
                if !closed {
                    unclosed.push(format!("  {rel}:{}", start + 1));
                }
            }
            for (i, line) in lines.iter().enumerate() {
                if test_items.iter().any(|&(start, end, _)| i >= start && i < end) {
                    continue; // inside a `#[cfg(test)]` item — not shipped
                }
                let code = line.trim_start();
                if code.starts_with("//") {
                    continue; // a doc comment naming `exp` is prose, not a call
                }
                if let Some((_, needle)) =
                    POWI_BASE_TEN_EXEMPT.iter().find(|(p, n)| *p == rel && code.contains(n))
                {
                    used_exempt.push(needle);
                    continue;
                }
                for pat in &banned {
                    if line.contains(pat.as_str()) {
                        found.push(format!("  {rel}:{} {code}", i + 1));
                    }
                }
            }
        }
    }
    // Non-vacuity, aimed at the failure this scan is most likely to have: `src/` NESTS here
    // (`harness/`, `laws/`), so a walk that stopped at the top level would still open dozens of
    // files and report a confident zero while never reading the sampler.
    for must in ["impact.rs", "queue_model.rs", "objective.rs", "fair_value.rs", "tpe.rs"] {
        assert!(
            scanned.iter().any(|s| s == must),
            "the scan never opened {must}, so an empty result proves nothing about the files this \
             gate exists for. Scanned {} files.",
            scanned.len()
        );
    }
    assert!(
        unclosed.is_empty(),
        "a `#[cfg(test)]` item's closing line could not be located, so everything below it went \
         UNSCANNED — the exact hole a `break` leaves, wearing a different cause. See \
         `cfg_test_ranges`: the end is the item's own indentation followed by a lone `}}`, or a \
         `;` for a `mod NAME;` declaration. An empty `#[cfg(test)] mod x {{}}` on one line, or a \
         hand-formatted item rustfmt did not touch, lands here.\n{}",
        unclosed.join("\n")
    );
    // ⚠ There is deliberately NO "some production line below a test module was scanned" assertion
    // here, and its absence is a MEASURED fact about this tree rather than an oversight. Measured
    // 2026-08-29 over `crates/vike-backtest/src`: every file's `#[cfg(test)]` module is the LAST
    // item in it — not one of the ~85 files puts one in the middle, and no file carries two — so
    // such an assertion would be FALSE today and could only be written by weakening it into
    // something that proves nothing. The mechanism is held by
    // `the_test_module_cut_excludes_only_the_test_module`'s fixture instead, which is the same
    // answer `crates/vike-analytics/tests/libm_platform_probe.rs` reached for the same reason.
    // (`crates/vike-mm/src/platform_probe.rs` CAN assert it on the tree, because that crate has
    // five mid-file test modules and two `libm` sites below one of them.) The range walk is used
    // here anyway: the property it buys is that the day somebody DOES add a mid-file test module —
    // `tpe.rs` is 1010 lines and already close to wanting one — the gate does not silently go blind
    // to the third of the file below it.
    //
    // A stale exemption is worse than none: it reads as a considered carve-out while covering a
    // line that no longer exists, and the next author copies it.
    for (p, n) in POWI_BASE_TEN_EXEMPT.iter() {
        assert!(
            used_exempt.contains(n),
            "POWI_BASE_TEN_EXEMPT names `{n}` in {p}, and the scan matched no such production \
             line. Either the call moved (update the entry) or it is gone (delete the entry) — a \
             carve-out nothing uses is an un-gated line waiting to happen."
        );
    }
    assert!(
        found.is_empty(),
        "production code must call the `libm` CRATE rather than `f64`'s platform-libm methods, so a \
         FILL PRICE does not depend on which box ran the replay — `crates/vike-backtest/Cargo.toml`'s \
         `libm` rationale block names the four sites and what each one's last bit decides. BOTH \
         spellings are banned, `x.exp()` and `f64::exp(x)`: same inherent method, same libcall (see \
         `banned_needles`). `powi` is banned too — on MSVC a `dev` build makes it a `pow()` libcall \
         — and its cure is a MULTIPLICATION rather than `libm`; the one base-ten production site \
         that keeps it is named in `POWI_BASE_TEN_EXEMPT` with the measurement behind it:\n{}",
        found.join("\n")
    );
}
