//! The full-pipeline gate: drive the FIXTURE registry (`tests/fixture_user_data/`, committed —
//! generated by the same `build.rs` run that generates the real one) end to end. This is what
//! makes the mechanism CI-proven even though CI checkouts carry no `user_data/`: every run scans,
//! generates, COMPILES two fixture strategies and constructs+drives one through the generated
//! resolver. The real registry (`vike_user_strategies::USER_STRATEGIES`) is asserted empty-safe
//! separately below — in CI it IS empty, and that must be a working state, not a degenerate one.

use vike_model::{Bar, Broker, HftBroker};

// The generated fixture registry: `user_strategy_by_name`, `USER_STRATEGIES`,
// `USER_LIVE_CAPABLE` over tests/fixture_user_data/. Shadows nothing — this include is scoped to
// this test crate.
include!(concat!(env!("OUT_DIR"), "/fixture_registry.rs"));

/// A ~30-line `HftBroker` double (vike-model's `MockBroker` implements only `Broker` — the tagged
/// verbs the generated bound requires are inert here; the test asserts market submits).
#[derive(Default)]
struct TestBroker {
    markets: Vec<(String, i32, f64)>,
}

impl Broker for TestBroker {
    fn submit_market(&mut self, symbol: &str, side: i32, qty: f64) {
        self.markets.push((symbol.to_string(), side, qty));
    }
    fn submit_limit(&mut self, _symbol: &str, _side: i32, _qty: f64, _price: f64) {}
    fn position(&self, _symbol: &str) -> f64 {
        0.0
    }
    fn price(&self, _symbol: &str) -> f64 {
        0.0
    }
    fn equity(&self) -> f64 {
        0.0
    }
    fn bars(&self, _symbol: &str) -> &[Bar] {
        &[]
    }
    fn index(&self) -> usize {
        0
    }
    fn now(&self) -> i64 {
        0
    }
}

impl HftBroker for TestBroker {
    fn position(&self) -> f64 {
        0.0
    }
    fn submit_limit_tagged(&mut self, _tag: &str, _side: i32, _qty: f64, _price: f64) {}
    fn modify_tagged(&mut self, _tag: &str, _new_qty: Option<f64>, _new_price: Option<f64>) {}
    fn cancel_tagged(&mut self, _tag: &str) {}
}

fn bar(symbol: &str) -> Bar {
    // `Bar` derives no `Default` — spell every field (the struct is small and stable).
    Bar {
        ts: 0,
        open: 1.0,
        high: 1.0,
        low: 1.0,
        close: 1.0,
        volume: 0.0,
        funding: None,
        bid: None,
        ask: None,
        symbol: Some(symbol.to_string()),
    }
}

/// The rosters are DERIVED from the folder listing: both entry-file folders present (sorted),
/// the presets-only folder skipped silently, and only the manifest-opted one live-capable.
#[test]
fn fixture_rosters_are_derived_from_the_tree() {
    assert_eq!(USER_STRATEGIES, ["fixture_hold", "fixture_live"]);
    assert_eq!(USER_LIVE_CAPABLE, ["fixture_live"]);
}

/// Resolve → construct → drive: the generated arm calls the entry file's `build`, params reach
/// the lenient reader, and the strategy trades through the broker it was handed.
#[test]
fn fixture_strategy_resolves_builds_and_trades() {
    let params: toml::Value = toml::from_str("qty = 2.5").unwrap();
    let mut strat = user_strategy_by_name::<TestBroker>("fixture_hold", &params)
        .expect("fixture_hold is in the generated registry");
    let mut broker = TestBroker::default();
    strat.on_bar(&mut broker, &bar("BTCUSDT"));
    strat.on_bar(&mut broker, &bar("BTCUSDT")); // holds: no second order
    assert_eq!(broker.markets, [("BTCUSDT".to_string(), 1, 2.5)]);
}

/// Unknown name → `None`: the caller keeps its own error wording, and built-ins (tried before
/// this registry by every consumer) can never be shadowed.
#[test]
fn unknown_name_is_none() {
    let params: toml::Value = toml::from_str("").unwrap();
    assert!(user_strategy_by_name::<TestBroker>("buy_hold", &params).is_none());
    assert!(user_strategy_by_name::<TestBroker>("nope", &params).is_none());
}

/// The REAL registry (whatever this checkout's `user_data/` holds — in CI: nothing) must be a
/// working state: resolving an unknown name answers `None`, never panics, and the rosters agree
/// with each other.
#[test]
fn real_registry_is_empty_safe() {
    let params: toml::Value = toml::from_str("").unwrap();
    assert!(vike_user_strategies::user_strategy_by_name::<TestBroker>(
        "definitely_not_a_strategy",
        &params
    )
    .is_none());
    for live in vike_user_strategies::USER_LIVE_CAPABLE {
        assert!(
            vike_user_strategies::USER_STRATEGIES.contains(live),
            "live-capable {live:?} missing from the roster"
        );
    }
}
