//! The cross-platform PIN for this crate's transcendental sites — the gate `vike-indicators`,
//! `vike-analytics` and `vike-mm` each carry, and which vike-options' conversion landed WITHOUT.
//!
//! IEEE 754 requires `+ - * /` and `sqrt` to be correctly rounded and requires NOTHING of
//! `ln`/`exp`/`erf`, so an `f64` METHOD call reaches whichever libm the PLATFORM ships — MSVC's CRT
//! on the Windows dev box, glibc on the CI box and every CI runner — and the two disagree in the last
//! bit. `crates/vike-options/src/greeks.rs`'s module doc carries this crate's own version of the
//! argument, including the sentence worth repeating here: a `libm::erf` sitting two lines above an
//! `x.ln()` ANSWERS the question "is this file converted?" — wrongly — and the next reader stops
//! looking. `docs/decisions/0032-transcendentals-come-from-the-libm-crate-not-the-platform.md` is
//! the accepted verdict.
//!
//! # ⚠ This crate HAS a parity gate, and it CANNOT see what this file sees
//!
//! `crates/vike-options/tests/oracle_parity.rs` compares against CPython-pinned bit patterns, so it
//! looks like the pin this crate already has. It is not, and the difference is a TOLERANCE stated
//! in its own header: **pure-arithmetic paths assert EXACT bits; every erf/exp/log-derived output —
//! BS price, greeks, implied vol, theor — gates at `<= 1e-12` RELATIVE.** A last-bit disagreement
//! between MSVC and glibc is four orders inside that tier and passes it in silence, on both boxes,
//! forever. Only a BIT comparison can see it, which is what this file adds. Do not read a green
//! `oracle_parity` as evidence about the question this file asks.
//!
//! # What each row reaches
//!
//! Everything in this crate flows through `greeks::norm_cdf` (`libm::erf`) and
//! `greeks::norm_pdf` (`libm::exp`), so those two `pub(crate)` helpers are the crate's real hot
//! spot. They are driven through the PUBLIC functions rather than pinned directly — which is also
//! the stronger pin, because it covers the `d1`/`d2` logarithm and the `e^{-rt}` discount that sit
//! either side of them.
//!
//! * `black_scholes_price` / `black_scholes_greeks` are the crate's OUTPUT.
//! * `implied_vol` is the one place a last bit could AMPLIFY rather than stay a last bit — it is a
//!   64-step BISECTION, i.e. a discrete search, so a flipped comparison returns a neighbouring
//!   `mid`. That function's own doc bounds the flip at ~1e-10 to 1e-8 in sigma and says plainly
//!   that the bound is "an argument from the arithmetic and **not a measurement**". This row is
//!   what turns it into one.
//! * `EwmaVol` / `RollingVol` fold `libm::log(price / prev)` across a series, so a last bit
//!   COMPOUNDS rather than washing out.
//! * `Basket::probability_of_profit` and `Basket::expected_value` are the two consumers of
//!   `TerminalDist::log_params` — the second integrates over thousands of quadrature nodes, which
//!   is the most `exp`/`log` calls any single value in this crate depends on.
//!
//! # ⚠ Declared coverage gaps — sites the SOURCE gate holds and the table does not
//!
//! * `vol::atm_iv`'s `libm::exp(r * t)` forward. Pinning it needs a constructed `OptionChain` with
//!   `StrikeRow`s, which is a different test with different failure modes; and the forward only
//!   SELECTS a strike (the site's own comment says so), so a last bit there changes an answer only
//!   when it moves the selection to a different strike. [`production_code_calls_libm_not_the_platform`]
//!   still stops it being respelled as `(r * t).exp()`.
//! * `second_order`'s five greeks carry NO transcendental of their own — measured 2026-08-29,
//!   `crates/vike-options/src/second_order.rs` contains no `libm::` call and no `f64` method call
//!   from `vike_model::libm_walk::BANNED_FNS`; it composes `norm_pdf`/`norm_cdf` and `d1`/`d2`
//!   with `+ - * /`. So they are covered TRANSITIVELY by the greeks rows rather than being an
//!   uncovered gap.
//!
//! # ⚠ The corpus is PURE ARITHMETIC, and that is load-bearing
//!
//! Every input is generated by an integer LCG plus `+ - * /`, never by `.sin()`/`.cos()`. Those are
//! themselves platform-dependent (MEASURED — `crates/vike-analytics/tests/libm_platform_probe.rs`'s
//! Part A sweeps them as its own control), so generating inputs with them would make every row
//! diverge because of the INPUTS rather than because of the function under test.
//!
//! ```text
//! <cargo> test -p vike-options --test libm_platform_probe
//! ```

use vike_model::libm_walk::{banned_needles, cfg_test_ranges};
use vike_options::{
    Basket, EvGrid, EwmaVol, Leg, OptionKind, RollingVol, TerminalDist, black_scholes_greeks,
    black_scholes_price, implied_vol,
};

// =================================================================================================
// The hashing/corpus machinery. Deliberately a per-crate COPY: unlike the text walk (which moved to
// `vike_model::libm_walk` under decision 0074), these rows ARE this crate's gate — see the SOURCE
// half's own note on what is shared and what deliberately is not.
// =================================================================================================

/// FNV-1a over `f64::to_bits`, NaN canonicalised so a NaN's sign and payload — neither of which the
/// architecture pins — cannot report a divergence that is not one. The same hasher the sibling
/// probes use, so a row moved between crates hashes identically.
struct Fnv(u64);

impl Fnv {
    fn new() -> Self {
        Fnv(0xcbf2_9ce4_8422_2325)
    }
    fn push(&mut self, v: f64) {
        let bits = if v.is_nan() { 0x7ff8_0000_0000_0000u64 } else { v.to_bits() };
        for b in bits.to_le_bytes() {
            self.0 ^= u64::from(b);
            self.0 = self.0.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    fn hex(&self) -> String {
        format!("{:016x}", self.0)
    }
}

/// Deterministic pseudo-random `f64` in `(0, 1)` from a pure-integer LCG. No transcendental
/// anywhere in here, for the reason the module doc gives.
fn lcg(seed: &mut u64) -> f64 {
    *seed = seed.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
    ((*seed >> 11) as f64) / ((1u64 << 53) as f64)
}

/// Samples per row for the cheap rows.
const SAMPLES: usize = 4096;

/// Samples for the QUADRATURE row.
///
/// ⚠ Deliberately far smaller, and the reason is cost rather than taste: `Basket::expected_value`
/// evaluates the payoff `(kinks + 1) * (steps + 1)` times per call. This test is NOT `#[ignore]`d —
/// it runs on every PR and on the Windows dev box — so a 4096-sample row at the default
/// `EvGrid { steps: 4096 }` would be tens of millions of payoff evaluations for one hash. The grid
/// is shrunk too (see the row), which is safe here because what is being pinned is whether the
/// SAME arithmetic happens on both boxes, not whether the quadrature has converged.
const EV_SAMPLES: usize = 384;

/// One row's verdict over its own corpus.
struct Row {
    label: &'static str,
    hash: String,
    n: usize,
    /// ⚠ NON-VACUITY GUARD — how many DISTINCT FINITE values the samples took. A row that collapses
    /// to one value hashes identically on every platform and reads as a PASS while pinning nothing.
    /// The analytics twin caught a real instance of exactly that (`overfit::pbo_cscv`). In THIS
    /// crate the shape to watch is different and just as easy to hit: every public function here
    /// returns `None` on an out-of-domain input, and a corpus that mostly missed the domain would
    /// hash a wall of canonical NaNs — perfectly stable on every platform.
    distinct: usize,
}

fn finish(label: &'static str, vals: &[f64]) -> Row {
    let mut h = Fnv::new();
    for &v in vals {
        h.push(v);
    }
    let mut bits: Vec<u64> = vals.iter().filter(|v| v.is_finite()).map(|v| v.to_bits()).collect();
    bits.sort_unstable();
    bits.dedup();
    Row { label, hash: h.hex(), n: vals.len(), distinct: bits.len() }
}

/// Smallest number of DISTINCT finite values a row may carry before its pin is treated as vacuous.
const MIN_DISTINCT: usize = 64;

/// A `None` is hashed as a canonical NaN rather than skipped: WHETHER a function answers is part of
/// the behaviour being pinned, and skipping the misses would hide a platform that stopped solving.
fn or_nan(v: Option<f64>) -> f64 {
    v.unwrap_or(f64::NAN)
}

// =================================================================================================
// The corpus.
// =================================================================================================

/// Every covered function, folded over its own corpus.
///
/// Returns rows in a FIXED order; [`PLATFORM_INVARIANT`] is compared positionally, so a reordering
/// is a re-record rather than a silent re-pairing.
fn production_rows() -> Vec<Row> {
    let mut out = Vec::new();

    // A shared option-parameter domain: near-the-money to deep wings, a week to two years, 5% to
    // 200% vol, and rates either side of zero (a negative rate is a real quote on some underlyings
    // and it flips the sign inside the `e^{-rt}` discount).
    fn params(s: &mut u64) -> (f64, f64, f64, f64, f64, OptionKind) {
        let spot = 20.0 + lcg(s) * 120_000.0;
        let strike = spot * (0.4 + lcg(s) * 1.4);
        let t = 0.02 + lcg(s) * 2.0;
        let sigma = 0.05 + lcg(s) * 1.95;
        let r = -0.02 + lcg(s) * 0.12;
        let kind = if lcg(s) < 0.5 { OptionKind::Call } else { OptionKind::Put };
        (spot, strike, t, sigma, r, kind)
    }

    // --- greeks::black_scholes_price — `libm::log` (in d1/d2) + `libm::exp` (the discount) +
    // `libm::erf` (norm_cdf, twice).
    {
        let mut s = 0x1234_5678_9abc_def0u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        for _ in 0..SAMPLES {
            let (sp, k, t, sig, r, kind) = params(&mut s);
            vals.push(or_nan(black_scholes_price(sp, k, t, sig, kind, r)));
        }
        out.push(finish("greeks::black_scholes_price (log + exp + erf)", &vals));
    }

    // --- greeks::black_scholes_greeks — the same log, TWO `libm::exp` (norm_pdf and the theta
    // discount) and `libm::erf`. All four components are hashed: delta comes from `norm_cdf` while
    // gamma/vega come from `norm_pdf`, so a row that hashed only one would cover only one of the
    // two helpers this whole crate rests on.
    {
        let mut s = 0x0fed_cba9_8765_4321u64;
        let mut vals = Vec::with_capacity(SAMPLES * 4);
        for _ in 0..SAMPLES {
            let (sp, k, t, sig, r, kind) = params(&mut s);
            match black_scholes_greeks(sp, k, t, sig, kind, r) {
                Some((d, g, th, v)) => {
                    vals.push(d);
                    vals.push(g);
                    vals.push(th);
                    vals.push(v);
                }
                None => vals.push(f64::NAN),
            }
        }
        out.push(finish("greeks::black_scholes_greeks (log + exp x2 + erf)", &vals));
    }

    // --- greeks::implied_vol — up to 64 `black_scholes_price` evaluations per solve, and the ONE
    // site in this crate where a last bit can amplify (a flipped `(pm - price).abs() < 1e-6` exit
    // returns a neighbouring `mid`).
    //
    // ⚠ The probe price is DERIVED from a forward `black_scholes_price` call rather than drawn at
    // random, and that is what makes the row non-vacuous. `implied_vol` returns `None` unless
    // `p_lo <= price <= p_hi` — the no-arbitrage band at sigma in `[1e-4, 5.0]` — so a random price
    // is almost always outside it, and a corpus of random prices would be a wall of NaNs: stable on
    // every platform, and pinning nothing. Round-tripping a real price keeps every sample inside
    // the band by construction and makes the row a genuine test of the SEARCH.
    //
    // ⚠ This row uses a NARROWER domain than the two above, and the reason is the same one: a deep
    // wing with a small `sigma·sqrt(t)` prices to EXACTLY 0.0 (`norm_cdf(-83)` underflows), and
    // `implied_vol` refuses a non-positive price on its first line. Such a probe is not a hard case
    // for the bisection — it is not a case for the bisection at all, and a corpus full of them
    // would dilute the row with samples that cannot report anything. The moneyness is held inside
    // ±40% and `sigma`/`t` away from their floors so essentially every probe reaches the search.
    // The WIDE domain still gets exercised: `black_scholes_price` is what produces these probes,
    // and its own row above sweeps the full range.
    {
        let mut s = 0x2222_3333_4444_5555u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        let mut solved = 0usize;
        for _ in 0..SAMPLES {
            let sp = 20.0 + lcg(&mut s) * 120_000.0;
            let k = sp * (0.6 + lcg(&mut s) * 0.8);
            let t = 0.08 + lcg(&mut s) * 1.9;
            let sig = 0.10 + lcg(&mut s) * 1.4;
            let r = -0.02 + lcg(&mut s) * 0.12;
            let kind = if lcg(&mut s) < 0.5 { OptionKind::Call } else { OptionKind::Put };
            let price = or_nan(black_scholes_price(sp, k, t, sig, kind, r));
            let iv = if price.is_finite() && price > 0.0 {
                implied_vol(price, sp, k, t, kind, r)
            } else {
                None
            };
            if iv.is_some() {
                solved += 1;
            }
            vals.push(or_nan(iv));
        }
        assert!(
            solved * 2 > SAMPLES,
            "only {solved}/{SAMPLES} implied-vol probes solved — a corpus dominated by `None` \
             hashes a wall of canonical NaNs, which is identical on every platform and pins \
             nothing. Check the price round-trip before re-recording."
        );
        out.push(finish("greeks::implied_vol (bisection over price)", &vals));
    }

    // --- vol::EwmaVol::update — `libm::log(price / prev)`, folded across a series.
    //
    // STATEFUL, so it is driven as a sequence rather than as independent samples: the variance
    // carries every previous return, which is what makes a last bit COMPOUND here instead of
    // washing out. `value()` is read after every update and every reading is hashed.
    //
    // ⚠ The price walk is multiplicative with a purely arithmetic step. A `.sin()`-driven walk
    // would put a platform call in the INPUT and make this row diverge for the wrong reason.
    {
        let mut s = 0x6666_7777_8888_9999u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        let mut folded = 0usize;
        while vals.len() < SAMPLES {
            // A lambda across the useful range rather than only RiskMetrics' 0.94: the constructor
            // takes any value in (0, 1) and a site portable only at its default is portable by
            // accident.
            let lambda = 0.5 + lcg(&mut s) * 0.49;
            let mut ewma = EwmaVol::new(lambda);
            let mut price = 50.0 + lcg(&mut s) * 5_000.0;
            for _ in 0..64 {
                price *= 1.0 + (lcg(&mut s) - 0.5) * 0.05;
                ewma.update(price);
                if let Some(v) = ewma.value() {
                    vals.push(v);
                    folded += 1;
                }
            }
        }
        assert!(
            folded > SAMPLES / 2,
            "the EwmaVol row folded only {folded} readings — `value()` is `None` until the fold has \
             seen two prices, and a row that mostly skips is a row that mostly pins nothing."
        );
        vals.truncate(SAMPLES);
        out.push(finish("vol::EwmaVol::update (log)", &vals));
    }

    // --- vol::RollingVol::update — the same `libm::log(price / prev)` over a bounded window.
    //
    // Not redundant with the EWMA row: the estimator is different arithmetic on the same logarithm
    // (a sample stdev over a `VecDeque`, `None` until the window is FULL), so one could move while
    // the other did not.
    {
        let mut s = 0xaaaa_bbbb_cccc_ddddu64;
        let mut vals = Vec::with_capacity(SAMPLES);
        let mut folded = 0usize;
        while vals.len() < SAMPLES {
            let window = 2 + (lcg(&mut s) * 30.0) as usize;
            let mut roll = RollingVol::new(window);
            let mut price = 50.0 + lcg(&mut s) * 5_000.0;
            // Comfortably more updates than the widest window, so the `None`-until-full phase is a
            // small minority of the samples rather than most of them.
            for _ in 0..80 {
                price *= 1.0 + (lcg(&mut s) - 0.5) * 0.05;
                roll.update(price);
                if let Some(v) = roll.value() {
                    vals.push(v);
                    folded += 1;
                }
            }
        }
        assert!(
            folded > SAMPLES / 2,
            "the RollingVol row folded only {folded} readings — `value()` is `None` until the \
             window is full, and a row that mostly skips is a row that mostly pins nothing."
        );
        vals.truncate(SAMPLES);
        out.push(finish("vol::RollingVol::update (log)", &vals));
    }

    // A three-leg basket with two distinct strikes, so `expected_value`'s window is split at real
    // kinks and `probability_of_profit` has more than one break-even to walk.
    fn basket(s: &mut u64) -> (Basket, TerminalDist) {
        let spot = 50.0 + lcg(s) * 4_000.0;
        let k1 = spot * (0.75 + lcg(s) * 0.2);
        let k2 = spot * (1.05 + lcg(s) * 0.2);
        let b = Basket::new(
            vec![
                Leg::new(1.0, k1, true, spot * 0.03 * (0.5 + lcg(s))),
                Leg::new(-2.0, k2, true, spot * 0.01 * (0.5 + lcg(s))),
                Leg::new(1.0, k1, false, spot * 0.02 * (0.5 + lcg(s))),
            ],
            spot,
        );
        let dist = TerminalDist {
            spot,
            sigma: 0.08 + lcg(s) * 1.2,
            tau: 0.02 + lcg(s) * 2.0,
            r: -0.02 + lcg(s) * 0.12,
        };
        (b, dist)
    }

    // --- basket::probability_of_profit — `libm::log` in `log_params` plus one `libm::log` and one
    // `libm::erf` per `cdf` call, several per basket.
    {
        let mut s = 0x5555_6666_7777_8888u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        for _ in 0..SAMPLES {
            let (b, dist) = basket(&mut s);
            vals.push(or_nan(b.probability_of_profit(&dist)));
        }
        out.push(finish("basket::probability_of_profit (log x2 + erf)", &vals));
    }

    // --- basket::expected_value — `libm::log` for the window and `libm::exp` at EVERY quadrature
    // node. The single value in this crate that depends on the most transcendental calls.
    //
    // ⚠ The grid is deliberately COARSE (`steps: 64` against the default 4096, `n_sigma: 6.0`
    // against 10.0) and the sample count small — see `EV_SAMPLES`. That does NOT weaken the pin:
    // the question is whether both boxes perform the same arithmetic, and 65 nodes per panel is
    // already 65 `exp` calls per sample. It does mean this row must not be read as a statement
    // about the quadrature's CONVERGENCE, which is what `EvGrid`'s own doc and this crate's EV
    // tests are for.
    {
        let mut s = 0x9999_aaaa_bbbb_ccccu64;
        let grid = EvGrid { n_sigma: 6.0, steps: 64 };
        let mut vals = Vec::with_capacity(EV_SAMPLES);
        for _ in 0..EV_SAMPLES {
            let (b, dist) = basket(&mut s);
            vals.push(or_nan(b.expected_value(&dist, &grid)));
        }
        out.push(finish("basket::expected_value (log + exp per node)", &vals));
    }

    out
}

/// ⚠ **ONE set of constants for EVERY platform — that is the entire claim.**
///
/// ⚠ **Every hash below is the literal `"RECORD"`, a PLACEHOLDER that fails by construction, and
/// that is deliberate.** The convention is the analytics twin's
/// (`crates/vike-analytics/tests/libm_platform_probe.rs`'s `PLATFORM_INVARIANT`): rows are
/// sometimes written on a box that cannot run cargo, and a plausible-looking hex literal invented
/// there is INDISTINGUISHABLE from a recorded one while pinning nothing. `"RECORD"` cannot match
/// any FNV output, so [`converted_functions_are_platform_invariant`] stays red until a human RUNS
/// this file on Linux/glibc AND on Windows/MSVC, confirms the two runs agree bit-for-bit, and
/// pastes the agreed hash in. **A red row spelled `"RECORD"` is an UNFINISHED RECORDING, not a
/// regression.**
///
/// ⚠ **Re-record by RUNNING, never by editing a digit**, and never from ONE box.
///
/// ⚠ **A per-platform table (`#[cfg(windows)]` / `#[cfg(unix)]`) is NOT a repair and must never be
/// added.**
///
/// ⚠ **A red row here is NOT automatically a re-record, and this crate is the one where that
/// matters most.** `docs/decisions/0021` keeps every frozen fixture's comparison EXACT, and
/// `crates/vike-options/tests/oracle_parity.rs` is such a fixture set. If a row here moves AND
/// `oracle_parity` stays green, the change is inside that suite's `1e-12` tier and this table is
/// the only thing that saw it. If BOTH move, 0021 governs — read it before touching either.
const PLATFORM_INVARIANT: [(&str, &str); 7] = [
    ("greeks::black_scholes_price (log + exp + erf)", "e08bbb78440b980f"),
    ("greeks::black_scholes_greeks (log + exp x2 + erf)", "5be39ee5680c1aaa"),
    ("greeks::implied_vol (bisection over price)", "63e57bc1f80c9b06"),
    ("vol::EwmaVol::update (log)", "fa1791dd34b29d60"),
    ("vol::RollingVol::update (log)", "7f8caa391f68cafd"),
    ("basket::probability_of_profit (log x2 + erf)", "ed9797fcbb81bc91"),
    ("basket::expected_value (log + exp per node)", "84ba698dcf42a020"),
];

/// The cross-platform proof, as a GATE rather than a diff somebody has to remember to run.
///
/// NOT `#[ignore]`d: CI runs it on Linux every PR and `just t vike-options` runs it on the Windows
/// dev box, both against the same committed table.
#[test]
fn converted_functions_are_platform_invariant() {
    let got = production_rows();
    assert_eq!(
        got.len(),
        PLATFORM_INVARIANT.len(),
        "row count drifted from PLATFORM_INVARIANT — it must be re-recorded"
    );

    let mut bad = Vec::new();
    for (r, (want_label, want_hash)) in got.iter().zip(PLATFORM_INVARIANT.iter()) {
        assert_eq!(&r.label, want_label, "row ORDER drifted — the compare is positional");
        if r.hash != *want_hash {
            bad.push(format!("  {:<50} want={want_hash} got={}", r.label, r.hash));
        }
    }

    // Non-vacuity BEFORE the hashes: a thin row is a defect whether or not its hash matched, and an
    // author re-recording a `"RECORD"` row must be told about it before pasting.
    let thin: Vec<String> = got
        .iter()
        .filter(|r| r.distinct < MIN_DISTINCT)
        .map(|r| format!("  {:<50} {} distinct finite of {} samples", r.label, r.distinct, r.n))
        .collect();
    assert!(
        thin.is_empty(),
        "a pinned row's corpus is too thin to detect a last-bit divergence: it would hash \
         identically on every platform and read as a PASS. In THIS crate the usual cause is a \
         corpus that fell outside a function's domain — every public function here returns `None` \
         out of domain, and a wall of canonical NaNs is perfectly stable everywhere. WIDEN or \
         re-centre the inputs; never lower MIN_DISTINCT ({MIN_DISTINCT}):\n{}",
        thin.join("\n")
    );

    if !bad.is_empty() {
        let paste: String =
            got.iter().map(|r| format!("    (\"{}\", \"{}\"),\n", r.label, r.hash)).collect();
        panic!(
            "\nvike-options output moved away from the platform pin:\n{}\n\n\
             There is no tolerance here to widen, and hand-editing a digit defeats the gate.\n\
             ⚠ Do NOT reach for `oracle_parity.rs` to decide whether the move matters: its\n\
             erf/exp/log tier is 1e-12 RELATIVE, so a last-bit move passes it in silence. That is\n\
             why this file is a BIT comparison.\n\
             If the want= column reads RECORD this is an UNFINISHED RECORDING rather than a\n\
             regression: run this file on BOTH Windows and Linux, confirm they agree, paste.\n\
             Otherwise establish WHY first:\n\
               (a) an intended numeric change — read docs/decisions/0021 before re-recording, then\n\
                   re-record on BOTH boxes and pin the agreed hash; or\n\
               (b) a call site went back to `(…).exp()` / `(…).ln()`, in which case the two\n\
                   platforms will NOT agree and the fix is in the source, not here.\n\n\
             const PLATFORM_INVARIANT: [(&str, &str); {}] = [\n{paste}];\n",
            bad.join("\n"),
            got.len(),
        );
    }
}

/// The control arm for the non-vacuity threshold itself.
///
/// ⚠ Without this, `MIN_DISTINCT` is an assertion nobody has checked DISCRIMINATES. A `distinct`
/// computation that counted samples rather than distinct values — or one that counted NaNs — would
/// pass every row above while the guard did nothing. The NaN arm is not decoration here: it is the
/// exact shape a mis-centred corpus takes in this crate, because every public function returns
/// `None` out of domain and `or_nan` hashes that as a canonical NaN.
#[test]
fn the_non_vacuity_check_discriminates() {
    let constant: Vec<f64> = (0..SAMPLES).map(|_| 0.5f64).collect();
    assert!(
        finish("control::constant", &constant).distinct < MIN_DISTINCT,
        "the non-vacuity check does not discriminate: a constant series passed it"
    );
    let all_none: Vec<f64> = (0..SAMPLES).map(|_| or_nan(None)).collect();
    assert_eq!(
        finish("control::all-none", &all_none).distinct,
        0,
        "a corpus that fell entirely outside every domain must report ZERO distinct FINITE values"
    );
    let mut s = 0xdead_beef_cafe_babeu64;
    let rich: Vec<f64> = (0..SAMPLES).map(|_| lcg(&mut s)).collect();
    assert!(
        finish("control::rich", &rich).distinct >= MIN_DISTINCT,
        "the corpus generator itself is degenerate — every row above is void"
    );
}

// =================================================================================================
// The SOURCE half. The table above proves today's outputs agree; this stops the NEXT edit from
// reintroducing a platform call in a spot the corpus never reaches — `vol::atm_iv` above all, which
// the table declares as an uncovered gap.
// =================================================================================================

/// Production code in this crate must reach a transcendental through the `libm` CRATE.
///
/// ⚠ Not redundant with the hash table, and in this crate the gap it fills is NAMED: `vol::atm_iv`
/// has no row (see the module doc's declared gaps), so this gate is the only thing standing between
/// that forward and a respelling as `(r * t).exp()`.
///
/// The text machinery this gate walks with — `banned_needles` and `cfg_test_ranges` — is
/// `vike_model::libm_walk`, shared by all eleven probes under decision 0074, and that module's own
/// docs carry the GENERAL argument for each: why BOTH the method and the UFCS spelling are banned,
/// why the test-item cut is RANGES rather than a `break` at the first marker, why the comment
/// filter runs FIRST, and why an item's end is found by INDENTATION rather than by counting
/// braces. The walk's proof is the planted fixture at
/// `crates/vike-model/tests/libm_walk_selftest.rs`. What stays below is the per-crate EVIDENCE
/// that machinery was measured AGAINST — facts about `crates/vike-options/src` and about nothing
/// else, which is why they could not move with the parser.
///
/// Scope: every `.rs` under `src/`, recursively, MINUS each file's test-item ranges. There are NO
/// exemptions and there should not need to be: measured 2026-08-29, `crates/vike-options/src`
/// contains not one call to any `vike_model::libm_walk::BANNED_FNS` name — inside a test module or
/// outside one — so this gate starts at a clean zero rather than at a grandfathered list. The same
/// sweep found no `powi`, which is why this crate carries no `powi` exemption table even though
/// `powi` is on the banned list (MEASURED on MSVC, a `dev` build lowers `llvm.powi` to the CRT's
/// `pow()`, so it is a libcall rather than the free multiply chain its name suggests).
///
/// # ⚠ Measured on THIS crate 2026-08-29 — what the shared walk buys here, and what it does not
///
/// * **Every test item under `crates/vike-options/src` is the last thing in its file**, so a
///   `break` at the first marker would change no verdict here TODAY. The ranges are insurance
///   rather than a fix: the property they buy is that the day somebody adds a mid-file test module
///   to `vol.rs` or `basket.rs`, this gate does not silently stop reading everything below it
///   while still reporting a confident zero. It is also why this crate can state no tree-shaped
///   "some production line below a marker was scanned" assertion — that sentence is FALSE here and
///   could only be written by weakening it into something vacuous, so the shared fixture is the
///   only proof of the walk there is.
/// * **Every marker under `crates/vike-options/src` sits at column 0**, which is what makes the
///   indentation-based end-finding exact against THESE files rather than merely plausible.
/// * **None of the three spellings the needle list cannot see occurs under this crate's `src/`
///   today** — `<f64>::exp(x)` (the angle-bracket form), a call reached through a generic bound
///   (`T: Float`), and a call split across two lines by a `max_width` wrap. A list of spellings is
///   an enumeration and an enumeration is never a proof, which is why the shared module leaves
///   this sentence to each crate instead of claiming it for all of them.
/// * **`sqrt` is deliberately NOT banned** — IEEE 754 requires it correctly rounded, so it is
///   identical on every box and there is nothing to convert it TO. This crate leans on that
///   exemption at three named sites and says so at each: `d1_d2`'s `t.sqrt()`, `norm_pdf`'s
///   `(2·π).sqrt()`, and `TerminalDist::log_params`' `tau.sqrt()`.
#[test]
fn production_code_calls_libm_not_the_platform() {
    let banned = banned_needles();
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let src = root.join("src");
    let mut found = Vec::new();
    let mut scanned: Vec<String> = Vec::new();
    // A test item whose end could not be located swallows the rest of its file exactly the way a
    // `break` would. That is the one QUIET failure of the range walk, so it is collected and
    // asserted rather than absorbed.
    let mut unclosed: Vec<String> = Vec::new();
    let mut stack = vec![src];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).expect("crate has a src/ directory") {
            let path = entry.expect("readable dir entry").path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                continue;
            }
            // `\` -> `/` so a reported path reads the same on the Windows dev box and on Linux.
            let rel = path.strip_prefix(root).unwrap_or(&path).to_string_lossy().replace('\\', "/");
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            let text = std::fs::read_to_string(&path).expect("readable source file");
            scanned.push(name);
            let lines: Vec<&str> = text.lines().collect();
            let test_items = cfg_test_ranges(&lines);
            for &(start, _, closed) in &test_items {
                if !closed {
                    unclosed.push(format!("  {rel}:{}", start + 1));
                }
            }
            for (i, line) in lines.iter().enumerate() {
                if test_items.iter().any(|&(start, end, _)| i >= start && i < end) {
                    continue; // inside a test item — not shipped
                }
                let code = line.trim_start();
                if code.starts_with("//") {
                    continue; // a doc comment naming `exp` is prose, not a call
                }
                for pat in &banned {
                    if line.contains(pat.as_str()) {
                        found.push(format!("  {rel}:{} {code}", i + 1));
                    }
                }
            }
        }
    }
    // Non-vacuity: an empty `found` is indistinguishable from a scan that opened nothing. The four
    // named files are the ones carrying a `libm::` call today — `vol.rs` above all, because it is
    // the file with the row-less site.
    for must in ["greeks.rs", "vol.rs", "basket.rs", "second_order.rs"] {
        assert!(
            scanned.iter().any(|s| s == must),
            "the scan never opened {must}, so an empty result proves nothing about the files this \
             gate exists for. Scanned {} files.",
            scanned.len()
        );
    }
    assert!(
        unclosed.is_empty(),
        "a test item's closing line could not be located, so everything below it went UNSCANNED — \
         the exact hole a `break` leaves, wearing a different cause. See `cfg_test_ranges`: the end \
         is the item's own indentation followed by a lone `}}`, or a `;` for a `mod NAME;` \
         declaration.\n{}",
        unclosed.join("\n")
    );
    assert!(
        found.is_empty(),
        "production code must call the `libm` CRATE rather than `f64`'s platform-libm methods. This \
         crate's own greeks module doc states the trap: a `libm::erf` two lines above an `x.ln()` \
         makes a HALF-converted file read as done. BOTH spellings are banned, `x.exp()` and \
         `f64::exp(x)`: same inherent method, same libcall (see `banned_needles`). `sqrt` is \
         deliberately NOT banned — `d1_d2`, `norm_pdf` and `TerminalDist::log_params` each rely on \
         that exemption and each says so at the line:\n{}",
        found.join("\n")
    );
}
