use super::*;
use crate::ctx::ScriptCtx;
use vike_model::Bar;

/// Every (indicator, line name, function name, line index) the bridge actually binds.
///
/// Derived from [`line_accessors`] — the same function `register_indicators` and the vike-cli
/// listing consume — rather than re-filtering the registry here. A local copy of the predicate
/// would drift the moment a rule changed, and it DID: adding the arity ceiling silently left
/// this helper claiming `kst_kst` was bound when nothing registered it.
fn generated() -> Vec<(&'static str, &'static str, String, usize)> {
    vike_indicators::registry()
        .iter()
        .flat_map(|m| {
            line_accessors(m.name)
                .into_iter()
                .enumerate()
                .map(move |(i, (line, fname))| (m.name, line, fname, i))
        })
        .collect()
}

/// The sanitiser is lossy in principle, so this proves it is not lossy in fact.
///
/// `%K` and `%D` both sanitise by dropping a character; two different line names collapsing onto
/// one accessor would give that accessor two meanings, silently. Green across today's registry —
/// it exists to fail on the future indicator that breaks it, which is the only moment anyone
/// could act on it.
#[test]
fn generated_line_names_are_unambiguous() {
    let mut seen: std::collections::HashMap<String, (&str, &str)> =
        std::collections::HashMap::new();
    for (ind, line, fname, _) in generated() {
        if let Some((pi, pl)) = seen.insert(fname.clone(), (ind, line)) {
            panic!(
                "`{fname}` is generated by BOTH {pi}'s `{pl}` and {ind}'s `{line}` — one \
                     accessor cannot mean two lines. Rename a line in the registry, or make \
                     `sanitize_line` injective."
            );
        }
    }
}

/// Every generated name must be BINDABLE: a legal rhai identifier, not a host function, and not
/// another indicator's name. `register_indicators` skips one that is not — this says loudly
/// which, rather than letting a line quietly vanish from the callable set.
#[test]
fn generated_line_names_are_bindable() {
    let probe = rhai::Engine::new_raw();
    for (ind, line, fname, _) in generated() {
        assert!(
            probe.compile(format!("{fname}()")).is_ok(),
            "{ind}'s `{line}` generates `{fname}`, which rhai cannot parse as a call"
        );
        assert!(
            !HOST_FN_NAMES.contains(&fname.as_str()),
            "{ind}'s `{line}` generates `{fname}`, which would shadow a host function"
        );
        assert!(
            !vike_indicators::registry().iter().any(|m| m.name == fname),
            "{ind}'s `{line}` generates `{fname}`, which is another indicator's own name"
        );
    }
}

/// The `%K`/`%D` family, named. Not redundant with the sweep above: it pins that these specific,
/// real line names produce these specific, callable spellings — so a change to `sanitize_line`
/// that still passed the generic sweep but renamed `stochastic_k` would fail here, where a
/// script author would notice.
#[test]
fn the_percent_named_lines_get_the_spelling_users_will_type() {
    assert_eq!(line_fn_name("stochastic", "%K"), "stochastic_k");
    assert_eq!(line_fn_name("stochastic", "%D"), "stochastic_d");
    assert_eq!(line_fn_name("williams", "%R"), "williams_r");
    // ...and an ordinary multi-word line name is untouched.
    assert_eq!(line_fn_name("adx", "plus_di"), "adx_plus_di");
    assert_eq!(line_fn_name("bollinger", "mid"), "bollinger_mid");
}

fn line_series(n: usize) -> Vec<Bar> {
    (0..n)
        .map(|i| {
            let f = i as f64;
            let c = 100.0 + (f * 0.7).sin() * 10.0 + f * 0.05;
            Bar {
                ts: i as i64 * 60_000,
                open: c - 0.3,
                high: c + 1.1,
                low: c - 1.2,
                close: c,
                volume: 1_000.0 + f * 3.0,
                funding: None,
                bid: None,
                ask: None,
                symbol: Some("X".into()),
            }
        })
        .collect()
}

/// The core correctness gate: each accessor returns ITS OWN line.
///
/// Folds every generated accessor through the real bridge and compares against a directly-fed
/// streaming oracle's `on_bar()[line]`, bit-for-bit. An off-by-one in the line index — or the
/// old `.first()` behaviour surviving anywhere — is precisely a silently-wrong number, and it
/// would be invisible to a test that only checked the value was finite.
#[test]
fn every_line_accessor_returns_its_own_line_bit_for_bit() {
    let bars = line_series(120);
    for (ind, line, fname, idx) in generated() {
        let meta =
            vike_indicators::registry().iter().find(|m| m.name == ind).expect("registry entry");
        let ctx = ScriptCtx::new();
        let mut engine = rhai::Engine::new();
        register_indicators(&mut engine, &ctx);

        let mut oracle = meta.build_with(&vike_indicators::coerce(meta.params, &[]));
        let ast = engine.compile(format!("{fname}()")).expect("compiles");

        for (i, b) in bars.iter().enumerate() {
            {
                let mut g = ctx.write().unwrap();
                g.cur_bar = b.clone();
                g.fed_this_bar.clear();
            }
            let got: f64 = engine.eval_ast(&ast).expect("evaluates");
            let want = oracle.on_bar(b).get(idx).copied().unwrap_or(f64::NAN);
            assert_eq!(
                got.to_bits(),
                want.to_bits(),
                "{fname} (= {ind} line {idx} `{line}`) diverged at bar {i}: {got} != {want}"
            );
        }
    }
}

/// All lines of one indicator share ONE instance, fed ONCE per bar.
///
/// Three `bollinger_*` reads in a bar must advance bollinger once. Non-vacuous by construction:
/// the oracle is fed exactly once per bar too, so if the bridge fed per-accessor the three reads
/// would come from bars 1, 2 and 3 of a triple-advanced instance and none would match.
#[test]
fn reading_three_lines_in_one_bar_feeds_the_indicator_once() {
    let bars = line_series(60);
    let meta = vike_indicators::registry().iter().find(|m| m.name == "bollinger").unwrap();
    let ctx = ScriptCtx::new();
    let mut engine = rhai::Engine::new();
    register_indicators(&mut engine, &ctx);
    let ast = engine
        .compile("[bollinger_upper(20), bollinger_mid(20), bollinger_lower(20)]")
        .expect("compiles");
    let mut oracle = meta.build_with(&vike_indicators::coerce(meta.params, &[20.0]));

    for (i, b) in bars.iter().enumerate() {
        {
            let mut g = ctx.write().unwrap();
            g.cur_bar = b.clone();
            g.fed_this_bar.clear();
        }
        let got: rhai::Array = engine.eval_ast(&ast).expect("evaluates");
        let want = oracle.on_bar(b);
        for (l, w) in want.iter().enumerate() {
            let g = got[l].as_float().unwrap();
            assert_eq!(g.to_bits(), w.to_bits(), "bar {i} line {l}: {g} != {w}");
        }
        // ...and one cache slot, not three.
        assert_eq!(
            ctx.read().unwrap().fed_this_bar.len(),
            1,
            "bar {i}: three lines must share ONE fed_this_bar slot"
        );
    }
}

/// The band indicators keep their BARE name refused — the hazard that motivated the original
/// rule is untouched by lifting it for the namesake case.
#[test]
fn a_band_indicator_still_has_no_bare_name_but_now_has_its_lines() {
    for band in ["bollinger", "donchian", "keltner", "envelopes", "std_error_bands"] {
        let why = unbound_reason(band);
        assert!(why.is_some(), "{band}'s bare name must stay refused: line 0 is `upper`");
        assert!(
            why.unwrap().contains("_<line>"),
            "{band}'s refusal must point at the accessor that DOES work: {why:?}"
        );
    }
    let ctx = ScriptCtx::new();
    let mut engine = rhai::Engine::new();
    register_indicators(&mut engine, &ctx);
    ctx.write().unwrap().cur_bar = line_series(1)[0].clone();
    assert!(engine.eval::<f64>("bollinger_mid(20)").is_ok(), "the accessor must resolve");
    assert!(engine.eval::<f64>("bollinger(20)").is_err(), "the bare name must not resolve");
}

/// The namesake indicators gain their bare name, and it is line 0 — the same value the
/// `<name>_<name>` accessor returns. If those disagreed, one spelling would be lying.
#[test]
fn a_namesake_indicator_binds_its_bare_name_to_the_same_value_as_its_own_line() {
    let bars = line_series(80);
    let mut checked = 0;
    for m in vike_indicators::registry().iter().filter(|m| m.outputs.len() >= 2 && !m.batch_only) {
        if line_fn_name(m.name, m.outputs[0].name) != format!("{}_{}", m.name, m.name) {
            continue; // not a namesake indicator
        }
        // ...and a namesake can still be refused for an UNRELATED rule — `kst` is one, at 9
        // parameters. The rules compose, so this test asserts the namesake rule only where it
        // is the deciding one.
        if line_accessors(m.name).is_empty() {
            continue;
        }
        assert!(unbound_reason(m.name).is_none(), "{} must now bind its bare name", m.name);
        let own = line_fn_name(m.name, m.outputs[0].name);

        let ctx = ScriptCtx::new();
        let mut engine = rhai::Engine::new();
        register_indicators(&mut engine, &ctx);
        let ast = engine.compile(format!("[{}(), {own}()]", m.name)).expect("compiles");
        for b in &bars {
            {
                let mut g = ctx.write().unwrap();
                g.cur_bar = b.clone();
                g.fed_this_bar.clear();
            }
            let got: rhai::Array = engine.eval_ast(&ast).expect("evaluates");
            let (a, c) = (got[0].as_float().unwrap(), got[1].as_float().unwrap());
            assert_eq!(a.to_bits(), c.to_bits(), "{}() != {own}()", m.name);
        }
        checked += 1;
    }
    assert!(checked >= 4, "expected several namesake indicators, found {checked}");
}

/// ⚠ ONE namesake rule, asked from two sides. [`bare_name_binds`] is what [`exclusion`]'s rule
/// 4 consults about a REGISTRY entry and what [`user_bare_name_binds`] consults about a user
/// file, and it sanitises the INDICATOR name — which the registry side never needed, because
/// every registry name is already a bare lowercase identifier while a file stem is whatever the
/// filesystem allowed.
///
/// This replaced a test that asserted the sanitisation premise ALONE. That one passed with the
/// whole user-indicator change reverted — it touched nothing the change introduced — and its
/// stated justification was false besides: it claimed the two spellings would "disagree about a
/// BUILT-IN", which they could not, because the user-side spelling was never asked about one.
/// Sharing the function is what makes the premise load-bearing, and this is what gates it.
///
/// Non-vacuous in TWO directions, and the middle assertion is honestly a third thing: the
/// identity assertion fails the day a registry entry takes a capital, a dash or a `%` (which is
/// when sharing the rule would start CHANGING a built-in's verdict); and the counts fail if the
/// predicate ever answers one way for everything.
///
/// ⚠ The AGREEMENT assertion cannot fail today, and saying so is the point.
/// `user_bare_name_binds(name, lines)` is defined as
/// `bare_name_binds(name, lines.len(), lines.first())`, and this test feeds both from the same
/// `m.outputs` — so it compares one call against itself. It is a DELEGATION-DRIFT guard: it
/// bites only if somebody later re-implements the user-side spelling independently, which is
/// exactly the moment "one rule, two callers" would stop being true. An earlier draft of this
/// comment claimed it "fails if either spelling drifts from the other", which overstated what
/// the code can do.
#[test]
fn one_namesake_rule_serves_the_registry_and_the_user_files() {
    let (mut binds, mut refused) = (0usize, 0usize);
    for m in vike_indicators::registry() {
        assert_eq!(
            sanitize_line(m.name),
            m.name,
            "`{}` does not survive sanitisation, so sharing the namesake rule with the user \
                 side would CHANGE whether its bare name binds",
            m.name
        );
        let shared = bare_name_binds(m.name, m.outputs.len(), m.outputs.first().map(|o| o.name));
        let lines: Vec<String> = m.outputs.iter().map(|o| o.name.to_string()).collect();
        assert_eq!(
            shared,
            user_bare_name_binds(m.name, &lines),
            "the two sides must be ONE rule, and they disagree about `{}`",
            m.name
        );
        if shared {
            binds += 1;
        } else {
            refused += 1;
        }
    }
    assert!(
        binds > 0 && refused > 0,
        "a predicate that answered one way for the whole registry would prove nothing: \
             {binds} bind, {refused} refused"
    );
}

/// `ichimoku` and `williams_fractal` are multi-output AND `batch_only`. Lifting the multi-output
/// refusal must NOT lift the future-reading one — an `ichimoku_tenkan()` would hand back a value
/// the batch path later revises, which is the whole reason rule 3 exists.
#[test]
fn a_future_reading_indicator_gets_no_line_accessors_either() {
    let ctx = ScriptCtx::new();
    let mut engine = rhai::Engine::new();
    register_indicators(&mut engine, &ctx);
    ctx.write().unwrap().cur_bar = line_series(1)[0].clone();
    let mut checked = 0;
    for m in vike_indicators::registry().iter().filter(|m| m.batch_only && m.outputs.len() >= 2) {
        assert!(line_accessors(m.name).is_empty(), "{} must expose no accessors", m.name);
        for o in m.outputs {
            let f = line_fn_name(m.name, o.name);
            assert!(
                engine.eval::<f64>(&format!("{f}()")).is_err(),
                "{f} must NOT resolve: {} reads future bars",
                m.name
            );
            checked += 1;
        }
    }
    assert!(checked >= 2, "expected ichimoku + williams_fractal lines, checked {checked}");
}
