//! The build-script DRIVER (`vike_model::host_build::driver`): the scan-root rule, and the whole
//! body run over a fake host — the directives in order, both registries written, warnings
//! labelled, a malformed folder failing the build before anything is written.

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{Duration, UNIX_EPOCH};

use vike_model::host_build::driver::{self, Built, Host, user_data_root};
use vike_model::host_build::render::{header, quoted_list};
use vike_model::host_build::scan::{EntryPolicy, scan_tier};

use super::{folder, scratch};

#[test]
fn a_non_blank_override_wins_and_a_blank_one_is_ignored() {
    let manifest = Path::new("/ws/crates/host");
    let default = manifest.join("..").join("..").join("user_data");
    assert_eq!(user_data_root(manifest, None), default, "the fixed hop to the workspace root");
    assert_eq!(user_data_root(manifest, Some("")), default);
    assert_eq!(user_data_root(manifest, Some("  \t")), default, "blank is unset");
    assert_eq!(user_data_root(manifest, Some("/proj/user_data")), PathBuf::from("/proj/user_data"));
    assert_eq!(
        user_data_root(manifest, Some("rel/ud")),
        PathBuf::from("rel/ud"),
        "kept as spelled"
    );
}

/// A fixed `not_after`: the driver tests below do not age anything, so no clock is needed.
const NOT_AFTER: Duration = Duration::from_secs(1_700_000_000);

fn fake_scanned_dirs(root: &Path) -> Vec<PathBuf> {
    vec![root.join("tier")]
}

/// A host whose registry is the shared pieces over one tier — enough to see what was scanned.
fn fake_build(root: &Path) -> Built {
    let scan = scan_tier(&root.join("tier"), "thing", EntryPolicy::SkipEntryless);
    let names: Vec<&str> = scan.found.iter().map(|f| f.name.as_str()).collect();
    let rendered = format!("{}FOUND = [{}]\n", header("fake-host"), quoted_list(&names));
    Built { rendered, errors: scan.errors, warnings: Vec::new() }
}

fn fake_host() -> Host<'static> {
    Host { label: "fake-host", noun: "thing", scanned_dirs: fake_scanned_dirs, build: fake_build }
}

/// `<scratch>/ws/crates/host` with `tests/fixture_user_data/tier/fix/fix.rs` and an OUT_DIR.
fn fake_package(dir: &Path) -> (PathBuf, PathBuf) {
    let manifest = dir.join("ws").join("crates").join("host");
    folder(&manifest.join("tests/fixture_user_data/tier"), "fix", &["fix.rs"]);
    let out = dir.join("out");
    fs::create_dir_all(&out).unwrap();
    (manifest, out)
}

fn run_collecting(host: &Host<'_>, manifest: &Path, out: &Path, over: Option<&str>) -> Vec<String> {
    let mut lines = Vec::new();
    driver::run_with(host, manifest, out, over, UNIX_EPOCH + NOT_AFTER, &mut |l: &str| {
        lines.push(l.to_string());
    });
    lines
}

/// The whole build-script body over the default root: the watch over the host's read set (the
/// default hop, joined onto the manifest dir), then the fixture tree's directive, and both
/// registries written into OUT_DIR from their own trees.
#[test]
fn run_writes_both_registries_and_emits_the_watch_then_the_fixture_directive() {
    let dir = scratch("driver-default");
    let (manifest, out) = fake_package(&dir);
    let user_data = manifest.join("..").join("..").join("user_data");
    folder(&user_data.join("tier"), "mine", &["mine.rs"]);

    let lines = run_collecting(&fake_host(), &manifest, &out, None);
    let fixtures = manifest.join("tests").join("fixture_user_data");
    assert_eq!(
        lines,
        [
            format!("cargo:rerun-if-changed={}", user_data.join("tier").display()),
            format!("cargo:rerun-if-changed={}", fixtures.display()),
        ]
    );
    let read = |f: &str| fs::read_to_string(out.join(f)).unwrap();
    assert!(
        read("user_registry.rs").ends_with("FOUND = [\"mine\"]\n"),
        "{}",
        read("user_registry.rs")
    );
    assert!(read("fixture_registry.rs").ends_with("FOUND = [\"fix\"]\n"));
    assert!(read("user_registry.rs").starts_with("// @generated by fake-host/build.rs"));
}

/// A RELATIVE override is watched as an absolute path under the manifest dir (a link target must
/// not resolve against OUT_DIR), while the host's scan is handed the override as spelled.
#[test]
fn a_relative_override_is_watched_under_the_manifest_dir() {
    let dir = scratch("driver-relative");
    let (manifest, out) = fake_package(&dir);
    fs::create_dir_all(manifest.join("rel/ud/tier")).unwrap();
    let lines = run_collecting(&fake_host(), &manifest, &out, Some("rel/ud"));
    assert_eq!(
        lines[0],
        format!("cargo:rerun-if-changed={}", manifest.join("rel/ud").join("tier").display())
    );
}

fn warning_build(_: &Path) -> Built {
    Built { rendered: "// w\n".into(), errors: Vec::new(), warnings: vec!["ambiguous twin".into()] }
}

/// Every warning becomes one `cargo:warning=<label>: <text>` line per registry, and the registry is
/// still written.
#[test]
fn warnings_become_labelled_cargo_warnings_and_still_build() {
    let dir = scratch("driver-warnings");
    let (manifest, out) = fake_package(&dir);
    let host = Host { build: warning_build, ..fake_host() };
    let lines = run_collecting(&host, &manifest, &out, None);
    let warnings: Vec<&String> = lines.iter().filter(|l| l.starts_with("cargo:warning=")).collect();
    assert_eq!(warnings, ["cargo:warning=fake-host: ambiguous twin"; 2], "{lines:?}");
    assert_eq!(fs::read_to_string(out.join("user_registry.rs")).unwrap(), "// w\n");
    assert_eq!(fs::read_to_string(out.join("fixture_registry.rs")).unwrap(), "// w\n");
}

fn failing_build(_: &Path) -> Built {
    Built {
        rendered: String::new(),
        errors: vec!["/a/Bad: first".into(), "/a/Worse: second".into()],
        warnings: Vec::new(),
    }
}

/// Any error FAILS THE BUILD, with the host's label and noun and every error on its own line.
#[test]
#[should_panic(
    expected = "fake-host: refusing to build with malformed thing folders:\n  /a/Bad: first\n  /a/Worse: second"
)]
fn a_malformed_folder_fails_the_build_naming_every_error() {
    let dir = scratch("driver-errors");
    let (manifest, out) = fake_package(&dir);
    let host = Host { build: failing_build, ..fake_host() };
    run_collecting(&host, &manifest, &out, None);
}

/// The failure comes BEFORE the registry is written: a malformed tree leaves no registry behind.
#[test]
fn a_malformed_folder_writes_no_registry() {
    let dir = scratch("driver-errors-nowrite");
    let (manifest, out) = fake_package(&dir);
    let host = Host { build: failing_build, ..fake_host() };
    let failed = std::panic::catch_unwind(|| run_collecting(&host, &manifest, &out, None));
    assert!(failed.is_err());
    assert!(!out.join("user_registry.rs").exists());
}

/// The driver hands its `not_after` to the watch, which stamps an absent tier's stand-in with it.
#[test]
fn the_driver_hands_not_after_to_the_watch() {
    let dir = scratch("driver-not-after");
    let (manifest, out) = fake_package(&dir);
    // The tier is absent, so on Unix the watch plants a stand-in and sets its mtime to NOT_AFTER;
    // off Unix it names the absent tier directly.
    let lines = run_collecting(&fake_host(), &manifest, &out, None);
    let first = PathBuf::from(lines[0].strip_prefix("cargo:rerun-if-changed=").unwrap());
    if cfg!(unix) {
        assert_eq!(first, out.join(vike_model::host_build::watch::WATCH_DIR).join("tier"));
        let stamped = fs::metadata(&first).unwrap().modified().unwrap();
        assert_eq!(stamped, UNIX_EPOCH + NOT_AFTER);
    } else {
        assert_eq!(first, manifest.join("..").join("..").join("user_data").join("tier"));
    }
}
