//! The full-pipeline gate: drive the FIXTURE registry (`tests/fixture_user_data/`, committed —
//! generated by the same `build.rs` run that generates the real one) end to end. This is what
//! makes the mechanism CI-proven even though CI checkouts carry no `user_data/`: every run scans,
//! generates, COMPILES two fixture studies and RUNS both through the generated resolver — one
//! against a real `HistStore`, one against a real `vike_ml::Learner`. The real registry
//! (`vike_user_research::USER_STUDIES`) is asserted empty-safe separately below; in CI it IS
//! empty, and that must be a working state rather than a degenerate one.
//!
//! ⚠ Both doubles are the workspace's OWN shared ones — `vike_data::test_support::MemHistStore`
//! and `vike_ml::test_support::ScriptedLearner` — so this test proves the contract against the
//! same objects a study will meet in a real run, on a box with no LightGBM binary and no
//! DataFusion. That is every CI runner and every Windows box.

use std::sync::Arc;

use vike_data::test_support::MemHistStore;
use vike_data::{HistStore, TsRange};
use vike_ml::FitImportance;
use vike_ml::test_support::ScriptedLearner;
use vike_model::Bar;
use vike_user_research::{StudyContext, StudyError};

// The generated fixture registry: `user_study_entry`, `run_user_study`, `USER_STUDIES` over
// tests/fixture_user_data/. Scoped to this test crate; shadows nothing.
include!(concat!(env!("OUT_DIR"), "/fixture_registry.rs"));

const VENUE: &str = "binance";
const SYMBOL: &str = "BTCUSDT";
const INTERVAL: &str = "1m";

fn bar(ts: i64, close: f64) -> Bar {
    // `Bar` derives no `Default` — spell every field (the struct is small and stable).
    Bar {
        ts,
        open: close,
        high: close,
        low: close,
        close,
        volume: 1.0,
        funding: None,
        bid: None,
        ask: None,
        symbol: Some(SYMBOL.to_string()),
    }
}

/// A seeded store plus the window that covers it.
fn seeded_store() -> (Arc<dyn HistStore + Send + Sync>, TsRange) {
    let store = MemHistStore::new();
    let bars: Vec<Bar> = (0..5).map(|i| bar(60_000 * i, 100.0 + i as f64)).collect();
    store
        .append_bars(VENUE, SYMBOL, INTERVAL, &bars, Some("fixture"))
        .expect("MemHistStore accepts the fixture bars");
    (Arc::new(store), TsRange::of(0, 60_000 * 4))
}

fn scratch() -> std::path::PathBuf {
    std::env::temp_dir().join(format!("vike-user-research-pipeline-{}", std::process::id()))
}

/// The roster is DERIVED from the folder listing: both entry-file folders present (sorted), the
/// recipes-only folder skipped silently.
#[test]
fn fixture_roster_is_derived_from_the_tree() {
    assert_eq!(USER_STUDIES, ["fixture_bars", "fixture_fit"]);
}

/// Resolve → run: the generated arm calls the entry file's `run`, the params reach the lenient
/// reader, the store read goes through the context, and metrics + artifacts come back.
#[test]
fn a_fixture_study_resolves_reads_the_store_and_returns_a_result() {
    let (store, window) = seeded_store();
    let ctx = StudyContext::new(store, window, scratch());
    let params: toml::Value = toml::from_str("period = 2").unwrap();

    let out = run_user_study("fixture_bars", &ctx, &params)
        .expect("fixture_bars is in the generated registry")
        .expect("it runs against the seeded store");

    assert_eq!(out.metric_value("bars"), Some(5.0));
    assert_eq!(out.metric_value("mean_close"), Some(102.0));
    assert!(out.metric_value("sharpe").is_some(), "the analytics call produced a number");
    let names: Vec<&str> = out.artifacts().iter().map(|(n, _)| n.as_str()).collect();
    assert_eq!(names, ["closes.tsv"]);
    let body = &out.artifacts()[0].1;
    assert!(body.starts_with("ts\tclose\tmean_gap\n"), "{body}");
    assert_eq!(body.lines().count(), 6, "header + one line per bar: {body}");
}

/// The STUDY↔STRATEGY seam, end to end: a feature a USER wrote, inside a user_data study folder,
/// pushed through the platform's own parity harness. That harness exists in
/// `crates/vike-indicators/src/test_support.rs` rather than in a `tests/` binary precisely so it is
/// reachable from outside this repository — from the study repo whose features it checks. This is
/// the in-tree proof that the reach is reachable: an under-declared `ColumnFeature::reach` is the
/// silent divergence where a live strategy feeds a model a number it was never trained on, and
/// nothing else in this crate would notice it.
#[test]
fn a_user_authored_feature_passes_the_platform_parity_harness() {
    vike_indicators::test_support::assert_feature_parity(
        "fixture_bars::MeanGap",
        &user_fixture_bars::MeanGap::new(4),
    );
}

/// The params are the RECIPE: a different table steers the same study, and an unknown series is a
/// study-level refusal rather than a silent empty result.
#[test]
fn params_steer_the_study_and_an_uncovered_series_refuses() {
    let (store, window) = seeded_store();
    let ctx = StudyContext::new(store, window, scratch());
    let params: toml::Value = toml::from_str(r#"symbol = "ETHUSDT""#).unwrap();

    let err = run_user_study("fixture_bars", &ctx, &params)
        .expect("still in the registry")
        .expect_err("the store holds no ETHUSDT bars");
    match err {
        StudyError::Study(m) => assert!(m.contains("ETHUSDT"), "{m}"),
        other => panic!("expected a study-level refusal, got {other:?}"),
    }
}

/// The LEARNER seam, present: a real `vike_ml::Learner` reaches the study through the erased
/// `StudyLearner`, the fit happens, and the importance the double reports comes back as an
/// artifact.
#[test]
fn a_fitting_study_reaches_a_real_learner_through_the_erasure() {
    let (store, window) = seeded_store();
    let learner = ScriptedLearner::constant(0.75).with_importance(FitImportance {
        n_features: 2,
        gain: vec![1.5, 0.5],
        splits: vec![3, 1],
    });
    let ctx = StudyContext::new(store, window, scratch()).with_learner(Arc::new(learner));
    let params: toml::Value = toml::from_str("seed = 7").unwrap();

    let out = run_user_study("fixture_fit", &ctx, &params)
        .expect("fixture_fit is in the generated registry")
        .expect("it fits against the scripted learner");

    assert_eq!(out.metric_value("rows"), Some(3.0));
    assert_eq!(out.metric_value("p_first_row"), Some(0.75));
    assert_eq!(out.metric_value("importance_features"), Some(2.0));
    let names: Vec<&str> = out.artifacts().iter().map(|(n, _)| n.as_str()).collect();
    // No `model.txt`: `ScriptedLearner` reports no model TEXT (the trait's documented default),
    // and the study records that absence rather than writing an empty file.
    assert_eq!(names, ["importance.tsv"]);
    assert!(out.artifacts()[0].1.contains("f0\t1.5\t3"), "{}", out.artifacts()[0].1);
}

/// The LEARNER seam, absent: the documented ceiling of a host with no LightGBM binary is a TYPED
/// refusal a caller can act on, not a number computed without a model.
#[test]
fn a_fitting_study_refuses_when_the_host_supplied_no_learner() {
    let (store, window) = seeded_store();
    let ctx = StudyContext::new(store, window, scratch());
    assert!(ctx.learner().is_none());
    let params: toml::Value = toml::from_str("").unwrap();

    let err = run_user_study("fixture_fit", &ctx, &params)
        .expect("still in the registry")
        .expect_err("no learner was supplied");
    match err {
        StudyError::NoLearner(what) => {
            assert!(!what.is_empty(), "the refusal names what it wanted to fit");
            assert!(err_text(&StudyError::NoLearner(what)).contains("LightGBM"));
        }
        other => panic!("expected NoLearner, got {other:?}"),
    }
}

fn err_text(e: &StudyError) -> String {
    e.to_string()
}

/// Unknown name → `None`: the caller keeps its own error wording, and the two generated resolvers
/// agree by construction (one is a line over the other).
#[test]
fn unknown_name_is_none_from_both_resolvers() {
    let (store, window) = seeded_store();
    let ctx = StudyContext::new(store, window, scratch());
    let params: toml::Value = toml::from_str("").unwrap();
    assert!(user_study_entry("nope").is_none());
    assert!(run_user_study("nope", &ctx, &params).is_none());
    assert!(user_study_entry("fixture_bars").is_some());
}

/// The REAL registry (whatever this checkout's `user_data/` holds — in CI: nothing) must be a
/// working state: resolving an unknown name answers `None` and never panics, and the roster and
/// the resolver agree with each other.
#[test]
fn real_registry_is_empty_safe() {
    assert!(vike_user_research::user_study_entry("definitely_not_a_study").is_none());
    for name in vike_user_research::USER_STUDIES {
        assert!(
            vike_user_research::user_study_entry(name).is_some(),
            "roster names {name:?} but the resolver does not"
        );
    }
}
