//! The cross-platform PIN for this crate's transcendental sites — the gate `vike-indicators`,
//! `vike-analytics` and `vike-mm` each carry. THREE call sites, pinned by TWO rows:
//! `crates/vike-ml/src/model/infer.rs`'s `predict_proba` (`libm::exp`), and the TPE sampler's
//! `crates/vike-ml/src/search/tpe.rs`'s `gaussian` (`libm::log` and `libm::cos`) and `gaussian_pdf`
//! (`libm::exp`), which the one `tpe::TpeOptimizer` row drives together.
//!
//! An `f64` METHOD call reaches whichever libm the PLATFORM ships — MSVC's CRT on the Windows dev
//! box, glibc on the CI box and every CI runner — and the two disagree in the last bit
//! (`docs/decisions/0032-transcendentals-come-from-the-libm-crate-not-the-platform.md`). Every site
//! routes through the `libm` CRATE; this file is what notices an edit moving one back.
//!
//! # What each row reaches
//!
//! * `infer::GbdtModel::predict_proba` is **the probability a live binary decides on**. Everything
//!   UNDER the `exp` is portable already, so this row is what makes the value itself a property of
//!   the model rather than of the box.
//! * `tpe::TpeOptimizer` is the ask/tell proposal stream: `gaussian`'s `log`+`cos` and
//!   `gaussian_pdf`'s `exp` feed an Expected-Improvement argmax, so a last-bit difference can crown
//!   a DIFFERENT candidate and fork every proposal after it. Hence the row drives the loop (see
//!   `tpe_rows`).
//!
//! ⚠ Not redundant with this crate's other gates, because of a TOLERANCE:
//! `crates/vike-ml/tests/train_infer_equality.rs` and `crates/vike-ml/tests/real_model_golden.rs`
//! both budget `1e-12` for "one `exp` through two libms", so a last-bit move passes them silently.
//! Only a BIT comparison can see it.
//!
//! # ⚠ The corpus is PURE ARITHMETIC, and that is load-bearing
//!
//! Every input is generated by an integer LCG plus `+ - * /`, never by `.sin()`/`.cos()`, which are
//! themselves platform-dependent (MEASURED — `crates/vike-analytics/tests/libm_platform_probe.rs`'s
//! Part A sweeps them as its own control): a row would diverge because of its INPUTS.
//!
//! ```text
//! <cargo> test -p vike-ml --test libm_platform_probe
//! ```

use vike_ml::parse_model_text;
use vike_model::libm_walk::{banned_needles, cfg_test_module_files_under, cfg_test_ranges};

/// The same committed two-tree binary model `crates/vike-ml/src/model/infer.rs`'s own unit tests parse.
///
/// ⚠ Its tree 1 has THREE leaves and its tree 0 has one, so `raw_score` takes at most THREE
/// distinct values however many feature rows are thrown at it — what shapes the `predict_proba`
/// row below.
const FIXTURE: &str = include_str!("fixtures/two_trees_binary_v4.txt");

// =================================================================================================
// The hashing/corpus machinery. Deliberately a per-crate COPY (see `Fnv`'s doc); only the TEXT
// machinery is shared, in `vike_model::libm_walk` (decision 0074).
// =================================================================================================

/// FNV-1a over `f64::to_bits`, NaN canonicalised so a NaN's sign and payload — neither of which the
/// architecture pins — cannot report a divergence that is not one. The same hasher the sibling
/// probes use, so a row moved between crates hashes identically.
struct Fnv(u64);

impl Fnv {
    fn new() -> Self {
        Fnv(0xcbf2_9ce4_8422_2325)
    }
    fn push(&mut self, v: f64) {
        let bits = if v.is_nan() { 0x7ff8_0000_0000_0000u64 } else { v.to_bits() };
        for b in bits.to_le_bytes() {
            self.0 ^= u64::from(b);
            self.0 = self.0.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    fn hex(&self) -> String {
        format!("{:016x}", self.0)
    }
}

/// Deterministic pseudo-random `f64` in `(0, 1)` from a pure-integer LCG. No transcendental
/// anywhere in here, for the reason the module doc gives.
fn lcg(seed: &mut u64) -> f64 {
    *seed = seed.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
    ((*seed >> 11) as f64) / ((1u64 << 53) as f64)
}

/// Samples per row.
const SAMPLES: usize = 4096;

/// One row's verdict over its own corpus.
struct Row {
    label: &'static str,
    hash: String,
    n: usize,
    /// ⚠ NON-VACUITY GUARD — how many DISTINCT FINITE values the samples took. A row that collapses
    /// to one value hashes identically on every platform and reads as a PASS while pinning nothing.
    /// The analytics twin caught a real instance of exactly that (`overfit::pbo_cscv`).
    distinct: usize,
}

fn finish(label: &'static str, vals: &[f64]) -> Row {
    let mut h = Fnv::new();
    for &v in vals {
        h.push(v);
    }
    let mut bits: Vec<u64> = vals.iter().filter(|v| v.is_finite()).map(|v| v.to_bits()).collect();
    bits.sort_unstable();
    bits.dedup();
    Row { label, hash: h.hex(), n: vals.len(), distinct: bits.len() }
}

/// Smallest number of DISTINCT finite values a row may carry before its pin is treated as vacuous.
const MIN_DISTINCT: usize = 64;

// =================================================================================================
// The corpus.
// =================================================================================================

/// The covered function, folded over its own corpus.
///
/// Returns rows in a FIXED order; [`PLATFORM_INVARIANT`] is compared positionally, so a reordering
/// is a re-record rather than a silent re-pairing.
///
/// Each corpus is built and folded INDEPENDENTLY, so adding or removing a row cannot move
/// another's hash.
fn production_rows() -> Vec<Row> {
    let mut out = Vec::new();

    // --- infer::GbdtModel::predict_proba — `libm::exp(-sigmoid * raw_score)`.
    //
    // ⚠ The SIGMOID is swept, not just the feature row — a non-vacuity requirement: the fixture's
    // `raw_score` takes at most THREE distinct values, so a corpus over rows alone would report
    // `distinct = 3` and hash identically on any two platforms that agreed on three numbers.
    // `sigmoid` is a genuine header-parsed parameter (`objective=binary sigmoid:N`), so this is
    // the real configuration space, not manufactured variety. A model is parsed per sigmoid
    // because `Objective::Binary { sigmoid }` has no public setter, and that also covers the
    // header path.
    {
        let mut s = 0x0fed_cba9_8765_4321u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        // Three features (`feature_infos` `[0:1] [0:9] [0:2]`): the rows span each range and
        // overshoot it, because a row outside the training range is an ordinary inference input.
        let rows: [[f64; 3]; 8] = [
            [0.0, 0.0, 0.0],
            [1.0, 9.0, 2.0],
            [0.0, 3.0, 2.0],
            [1.0, 4.5, 0.0],
            [0.5, 4.4999, 1.0],
            [0.5, 4.5001, 1.0],
            [-3.0, -1.0, -1.0],
            [7.0, 40.0, 11.0],
        ];
        while vals.len() < SAMPLES {
            // Strictly positive: the parser refuses `sigmoid <= 0`.
            let sigmoid = 0.01 + lcg(&mut s) * 8.0;
            let text = FIXTURE.replace("sigmoid:1", &format!("sigmoid:{sigmoid}"));
            let model = parse_model_text(&text).expect("the committed fixture parses");
            for row in &rows {
                vals.push(model.predict_proba(row));
            }
        }
        vals.truncate(SAMPLES);
        out.push(finish("infer::GbdtModel::predict_proba (exp)", &vals));
    }

    // --- tpe::TpeOptimizer - the ask/tell proposal stream. Ungated: the default roster lane runs it.
    out.extend(tpe_rows());

    out
}

/// Drive the TPE ask/tell loop and hash every proposed coordinate.
///
/// ⚠ The loop is driven rather than `gaussian`/`gaussian_pdf` called directly (both private) because
/// it is the STRONGER pin: the failure that matters is a different `n_candidates` draw winning the
/// Expected-Improvement argmax and every later proposal differing, not one ulp in the pdf.
///
/// `n_startup` is deliberately small and the trial count large: `ask` samples UNIFORMLY — no
/// transcendental at all — until `trials.len() >= n_startup.max(2)`, so a corpus dominated by
/// startup draws would pin the LCG. The assertion at the bottom measures that ratio.
fn tpe_rows() -> Vec<Row> {
    use vike_ml::search::tpe::{ParamDomain, TpeOptimizer};

    const TRIALS: usize = 64;
    const SEEDS: u64 = 48;
    const STARTUP: usize = 4;
    const DIMS: usize = 3;

    let mut vals = Vec::with_capacity(SEEDS as usize * TRIALS * DIMS);
    let mut startup_draws = 0usize;
    for seed in 0..SEEDS {
        let space = vec![
            ("x".to_string(), ParamDomain::continuous(-4.0, 6.5)),
            ("y".to_string(), ParamDomain::continuous(0.001, 25.0)),
            // An INTEGRAL axis: the quantised path, where a last-bit move in a proposal becomes a
            // WHOLE-STEP move in the config that gets run.
            ("k".to_string(), ParamDomain::continuous_integral(1.0, 40.0)),
        ];
        let mut opt =
            TpeOptimizer::new(space, seed, 0.25).with_n_startup(STARTUP).with_n_candidates(24);
        for t in 0..TRIALS {
            let params = opt.ask();
            // ⚠ A PURE-ARITHMETIC objective: a `.sin()` bowl would make the SCORES, and so the
            // good/bad split, platform-dependent — the module doc's false positive, well hidden.
            let mut score = 0.0f64;
            for (i, v) in params.values().enumerate() {
                let centre = 0.5 + i as f64;
                score -= (v - centre) * (v - centre);
                vals.push(*v);
            }
            opt.tell(&params, score);
            if t < STARTUP {
                startup_draws += DIMS;
            }
        }
    }
    // Non-vacuity SPECIFIC to this row: the corpus is mostly TPE proposals, not uniform startup
    // draws that would pin only the (portable) LCG.
    assert!(
        startup_draws * 4 < vals.len(),
        "startup (uniform, transcendental-free) draws are {startup_draws} of {} samples — this row \
         would be pinning the LCG rather than the Parzen sampler. Raise TRIALS or lower STARTUP.",
        vals.len()
    );
    vec![finish("tpe::TpeOptimizer (gaussian log+cos, gaussian_pdf exp)", &vals)]
}

/// ⚠ **ONE set of constants for EVERY platform — that is the entire claim.**
///
/// ⚠ **`"RECORD"` is the PLACEHOLDER a NEW row takes while it is unrecorded — a word that fails by
/// construction, deliberately — and both rows below carry RECORDED hashes.** The convention is the
/// analytics twin's (`crates/vike-analytics/tests/libm_platform_probe.rs`'s `PLATFORM_INVARIANT`):
/// a plausible hex literal written on a box that cannot run cargo is INDISTINGUISHABLE from a
/// recorded one, while `"RECORD"` keeps [`converted_functions_are_platform_invariant`] red until a
/// human RUNS this file on Linux/glibc AND on Windows/MSVC, confirms they agree bit-for-bit, and
/// pastes the agreed hash. **A red row spelled `"RECORD"` is an UNFINISHED RECORDING, not a
/// regression.**
///
/// ⚠ **Re-record by RUNNING, never by editing a digit**, and never from ONE box.
///
/// ⚠ **A per-platform table (`#[cfg(windows)]` / `#[cfg(unix)]`) is NOT a repair and must never be
/// added.** It would make the gate green by asserting that a probability may depend on the box.
///
/// RETIRED with its function, not a value somebody failed to re-record:
/// `("metrics::binary_logloss (log x2)", "b4aa8b5ff07afed5")`. Do not re-add it.
const PLATFORM_INVARIANT: [(&str, &str); 2] = [
    ("infer::GbdtModel::predict_proba (exp)", "cd322ade65352484"),
    ("tpe::TpeOptimizer (gaussian log+cos, gaussian_pdf exp)", "d80ed29b912b84e0"),
];

/// The cross-platform proof, as a GATE rather than a diff somebody has to remember to run.
///
/// NOT `#[ignore]`d: CI runs it on Linux every PR and `just t vike-ml` runs it on the Windows dev
/// box, both against the same committed table.
#[test]
fn converted_functions_are_platform_invariant() {
    let got = production_rows();
    assert_eq!(
        got.len(),
        PLATFORM_INVARIANT.len(),
        "row count drifted from PLATFORM_INVARIANT — it must be re-recorded"
    );

    let mut bad = Vec::new();
    for (r, (want_label, want_hash)) in got.iter().zip(PLATFORM_INVARIANT.iter()) {
        assert_eq!(&r.label, want_label, "row ORDER drifted — the compare is positional");
        if r.hash != *want_hash {
            bad.push(format!("  {:<40} want={want_hash} got={}", r.label, r.hash));
        }
    }

    // Non-vacuity BEFORE the hashes: a thin row is a defect whether or not its hash matched.
    let thin: Vec<String> = got
        .iter()
        .filter(|r| r.distinct < MIN_DISTINCT)
        .map(|r| format!("  {:<40} {} distinct finite of {} samples", r.label, r.distinct, r.n))
        .collect();
    assert!(
        thin.is_empty(),
        "a pinned row's corpus is too thin to detect a last-bit divergence: it would hash \
         identically on every platform and read as a PASS. For `predict_proba` the usual cause is \
         a sigmoid sweep that stopped sweeping — the fixture's trees give only THREE distinct raw \
         scores on their own. WIDEN the corpus, never lower MIN_DISTINCT ({MIN_DISTINCT}):\n{}",
        thin.join("\n")
    );

    if !bad.is_empty() {
        let paste: String =
            got.iter().map(|r| format!("    (\"{}\", \"{}\"),\n", r.label, r.hash)).collect();
        panic!(
            "\nvike-ml output moved away from the platform pin:\n{}\n\n\
             There is no tolerance here to widen, and hand-editing a digit defeats the gate.\n\
             ⚠ Do NOT reach for this crate's other gates to decide whether the move matters:\n\
             `train_infer_equality.rs` and `real_model_golden.rs` both budget 1e-12 for one `exp`\n\
             through two libms, so a last-bit move passes them silently. That is why this file is\n\
             a BIT comparison.\n\
             If the want= column reads RECORD this is an UNFINISHED RECORDING rather than a\n\
             regression: run this file on BOTH Windows and Linux, confirm they agree, paste.\n\
             Otherwise establish WHY first:\n\
               (a) an intended numeric change — re-record on BOTH boxes and pin the agreed hash; or\n\
               (b) a call site went back to `(…).exp()` / `(…).ln()`, in which case the two\n\
                   platforms will NOT agree and the fix is in the source, not here.\n\n\
             const PLATFORM_INVARIANT: [(&str, &str); {}] = [\n{paste}];\n",
            bad.join("\n"),
            got.len(),
        );
    }
}

/// The control arm for the non-vacuity threshold itself.
///
/// ⚠ Without this, nobody has checked that `MIN_DISTINCT` DISCRIMINATES: a `distinct` that counted
/// samples rather than distinct values would pass both rows while guarding nothing.
#[test]
fn the_non_vacuity_check_discriminates() {
    let constant: Vec<f64> = (0..SAMPLES).map(|_| 0.5f64).collect();
    assert!(
        finish("control::constant", &constant).distinct < MIN_DISTINCT,
        "the non-vacuity check does not discriminate: a constant series passed it"
    );
    let nans: Vec<f64> = (0..SAMPLES).map(|_| f64::NAN).collect();
    assert_eq!(
        finish("control::nan", &nans).distinct,
        0,
        "an all-NaN row must report ZERO distinct FINITE values — the shape a broken corpus takes \
         here, since a model that failed to parse would fold NaNs rather than refusing outright"
    );
    // The degenerate corpus the sigmoid sweep avoids — one model, many rows — as a real control.
    // If THIS ever passes the floor, the fixture has grown and the sweep's comment needs rewriting.
    let model = parse_model_text(FIXTURE).expect("the committed fixture parses");
    let mut s = 0x2222_3333_4444_5555u64;
    let vals: Vec<f64> = (0..SAMPLES)
        .map(|_| {
            let row = [lcg(&mut s) * 2.0, lcg(&mut s) * 12.0, lcg(&mut s) * 3.0];
            model.predict_proba(&row)
        })
        .collect();
    assert!(
        finish("control::one-model", &vals).distinct < MIN_DISTINCT,
        "one fixture model over many rows produced {} distinct probabilities — the committed \
         two-tree fixture should give at most three. If it has grown, update the `predict_proba` \
         row's comment; do not simply delete this control.",
        finish("control::one-model", &vals).distinct
    );
}

// =================================================================================================
// The SOURCE half. The table above proves today's outputs agree; this stops the NEXT edit from
// reintroducing a platform call in a spot the corpus never reaches.
// =================================================================================================

/// Production code in this crate must reach a transcendental through the `libm` CRATE.
///
/// ⚠ Not redundant with the hash table, which pins TWO functions: a new transcendental in the
/// learner, the importance or the fit cache would be invisible to the corpus above.
///
/// Scope: every `.rs` under `src/`, recursively, MINUS each file's test-item ranges. NO exemptions:
/// the only `vike_model::libm_walk::BANNED_FNS` calls in `crates/vike-ml/src` are inside
/// `gbdt_learner.rs`'s test module (its synthetic `sin`/`cos` feature fixture).
///
/// # What holds on THIS crate
///
/// The text machinery (`banned_needles`, `cfg_test_ranges`) and the GENERAL argument for each of
/// its choices live in `vike_model::libm_walk` (decision 0074). The per-crate evidence:
///
/// * **`powi` needs no exemption here.** It is banned because a MSVC `dev` build lowers
///   `llvm.powi` to the CRT's `pow()`; `crates/vike-ml/src` has none outside a test module.
///
/// * **The needle list's three blind spots do not occur here** — `<f64>::exp(x)` (the text carries
///   `f64>::exp(`, which neither needle matches), a call through a generic bound (`T: Float`), and
///   a call split across two lines by a `max_width` wrap. An enumeration is never a proof; this
///   measurement stands in for one and must be retaken the day it stops holding.
///
/// * **The RANGES are INSURANCE here, not a fix.** Every test item under `crates/vike-ml/src` is
///   the last thing in its file today; the ranges cover the day somebody leaves production code
///   below a marker, so the gate does not silently stop reading it.
///
/// * **The `any(test, …)` spelling is deliberately NOT a range.** `crates/vike-ml/src/seam/test_support.rs`
///   is gated that way and SHIPS to any consumer enabling `test-support`.
///
/// * **The comment filter has to run FIRST.** `gbdt_learner.rs`'s module doc names the
///   `#[cfg(test)]` attribute in backticks, so a whole-file `text.find` cut would discard most of
///   that file and report a confident zero.
///
/// * **The indentation rule is exact here**: every marker under `crates/vike-ml/src` sits at
///   column 0, where rustfmt puts the lone `}` that ends each block this gate cuts.
///
/// * **No tree-shaped assertion here could cover the range walk**, since every test item is last in
///   its file; the walk's proof is the planted fixture in
///   `crates/vike-model/tests/libm_walk_selftest.rs`. The `unclosed` assertion below is the part
///   this crate CAN check against its own tree.
#[test]
fn production_code_calls_libm_not_the_platform() {
    let banned = banned_needles();
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let src = root.join("src");
    let mut found = Vec::new();
    let mut scanned: Vec<String> = Vec::new();
    // A test item whose end could not be located swallows the rest of its file like a `break`:
    // the range walk's one QUIET failure, so it is collected and asserted.
    let mut unclosed: Vec<String> = Vec::new();
    // A file a `#[cfg(test)] mod NAME;` declaration pulls in is test code WHOLE, with no marker
    // inside it for `cfg_test_ranges` to find — skipped before it is read, like any test module.
    let test_files = cfg_test_module_files_under(&src);
    let mut stack = vec![src];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).expect("crate has a src/ directory") {
            let path = entry.expect("readable dir entry").path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                continue;
            }
            if test_files.contains(&path) {
                continue;
            }
            // `\` -> `/` so a reported path reads the same on the Windows dev box and on Linux.
            let rel = path.strip_prefix(root).unwrap_or(&path).to_string_lossy().replace('\\', "/");
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            let text = std::fs::read_to_string(&path).expect("readable source file");
            scanned.push(name);
            let lines: Vec<&str> = text.lines().collect();
            let test_items = cfg_test_ranges(&lines);
            for &(start, _, closed) in &test_items {
                if !closed {
                    unclosed.push(format!("  {rel}:{}", start + 1));
                }
            }
            for (i, line) in lines.iter().enumerate() {
                if test_items.iter().any(|&(start, end, _)| i >= start && i < end) {
                    continue; // inside a test item — not shipped
                }
                let code = line.trim_start();
                if code.starts_with("//") {
                    continue; // a doc comment naming `exp` is prose, not a call
                }
                for pat in &banned {
                    if line.contains(pat.as_str()) {
                        found.push(format!("  {rel}:{} {code}", i + 1));
                    }
                }
            }
        }
    }
    // Non-vacuity: an empty `found` is indistinguishable from a scan that opened nothing. The
    // witnesses are the converted site and the file whose test module holds the crate's only
    // `sin`/`cos` calls (a broken range walk reports a LOUD false positive there). ⚠ Named by hand
    // on purpose — this assertion caught a deleted witness once; a count is what a deletion
    // trivially satisfies.
    for must in ["infer.rs", "gbdt_learner.rs"] {
        assert!(
            scanned.iter().any(|s| s == must),
            "the scan never opened {must}, so an empty result proves nothing about the files this \
             gate exists for. Scanned {} files.",
            scanned.len()
        );
    }
    assert!(
        unclosed.is_empty(),
        "a test item's closing line could not be located, so everything below it went UNSCANNED — \
         the exact hole a `break` leaves, wearing a different cause. See `cfg_test_ranges`: the end \
         is the item's own indentation followed by a lone `}}`, or a `;` for a `mod NAME;` \
         declaration.\n{}",
        unclosed.join("\n")
    );
    assert!(
        found.is_empty(),
        "production code must call the `libm` CRATE rather than `f64`'s platform-libm methods, so a \
         PROBABILITY out of this crate is a property of the model rather than of the box that ran \
         it. BOTH spellings are banned, `x.exp()` and `f64::exp(x)`: same inherent method, same \
         libcall (see `banned_needles`). `powi` is banned too — on MSVC a `dev` build makes it a \
         `pow()` libcall — and its cure is a MULTIPLICATION rather than `libm` when the base is a \
         literal:\n{}",
        found.join("\n")
    );
}
