//! The cross-platform PIN for this crate's TWO transcendental sites — the gate `vike-indicators`,
//! `vike-analytics` and `vike-mm` each carry, and which vike-ml's conversion landed WITHOUT.
//!
//! IEEE 754 requires `+ - * /` and `sqrt` to be correctly rounded and requires NOTHING of
//! `ln`/`exp`, so an `f64` METHOD call reaches whichever libm the PLATFORM ships — MSVC's CRT on
//! the Windows dev box, glibc on the CI box and every CI runner — and the two disagree in the last bit.
//! `crates/vike-ml/Cargo.toml`'s `libm` line names both sites as this crate's whole share of
//! `docs/decisions/0032-transcendentals-come-from-the-libm-crate-not-the-platform.md`, and both
//! already route through the `libm` CRATE. Nothing in the tree would have noticed the next edit
//! moving either one back.
//!
//! # What each row reaches, stated at its true size
//!
//! * `infer::GbdtModel::predict_proba` is **the probability a live binary decides on** — the whole
//!   point of this crate is that a trading binary predicts with no native dependency, so this is
//!   the number that leaves it. Everything UNDER the `exp` was already portable: `raw_score` is a
//!   plain `+` fold over leaf values and the walk selecting them is comparisons and integer bit
//!   tests. So the site's own doc is right that the conversion moves the probability by at most an
//!   ulp and cannot move a routing decision by itself — but "cannot move a routing decision" is a
//!   statement about a threshold nobody has pinned, and this row is what makes the value itself a
//!   property of the model rather than of the box.
//! * `metrics::binary_logloss` has **no caller in this workspace**, and that is written on the
//!   function itself rather than discovered here. It is latent public-API surface, so the first
//!   caller will be measuring `libm`'s answer from its first run — which is exactly the moment a
//!   pin is cheapest to have and most annoying to add.
//!
//! ⚠ Neither row is redundant with this crate's existing gates, and the reason is a TOLERANCE.
//! `crates/vike-ml/tests/train_infer_equality.rs` and `crates/vike-ml/tests/real_model_golden.rs`
//! both budget `1e-12` for "one `exp` through two libms", stated in those words — so a last-bit
//! move is four orders inside their budget and passes them silently. Only a BIT comparison can see
//! it, which is what this file adds.
//!
//! # ⚠ The corpus is PURE ARITHMETIC, and that is load-bearing
//!
//! Every input is generated by an integer LCG plus `+ - * /`, never by `.sin()`/`.cos()`. Those are
//! themselves platform-dependent (MEASURED — `crates/vike-analytics/tests/libm_platform_probe.rs`'s
//! Part A sweeps them as its own control), so generating inputs with them would make both rows
//! diverge because of the INPUTS rather than because of the function under test.
//!
//! ```text
//! <cargo> test -p vike-ml --test libm_platform_probe
//! ```

use vike_ml::metrics::{binary_logloss, LOGLOSS_EPS};
use vike_ml::parse::parse_model_text;

/// The same committed two-tree binary model `crates/vike-ml/src/infer.rs`'s own unit tests parse.
///
/// ⚠ Its tree 1 has THREE leaves and its tree 0 has one, so `raw_score` takes at most THREE
/// distinct values however many feature rows are thrown at it. That single fact is what shapes the
/// `predict_proba` row below — see its comment.
const FIXTURE: &str = include_str!("fixtures/two_trees_binary_v4.txt");

// =================================================================================================
// The shared hashing/corpus machinery. Deliberately a per-crate COPY — see `cfg_test_ranges`'s doc.
// =================================================================================================

/// FNV-1a over `f64::to_bits`, NaN canonicalised so a NaN's sign and payload — neither of which the
/// architecture pins — cannot report a divergence that is not one. The same hasher the sibling
/// probes use, so a row moved between crates hashes identically.
struct Fnv(u64);

impl Fnv {
    fn new() -> Self {
        Fnv(0xcbf2_9ce4_8422_2325)
    }
    fn push(&mut self, v: f64) {
        let bits = if v.is_nan() { 0x7ff8_0000_0000_0000u64 } else { v.to_bits() };
        for b in bits.to_le_bytes() {
            self.0 ^= u64::from(b);
            self.0 = self.0.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    fn hex(&self) -> String {
        format!("{:016x}", self.0)
    }
}

/// Deterministic pseudo-random `f64` in `(0, 1)` from a pure-integer LCG. No transcendental
/// anywhere in here, for the reason the module doc gives.
fn lcg(seed: &mut u64) -> f64 {
    *seed = seed.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
    ((*seed >> 11) as f64) / ((1u64 << 53) as f64)
}

/// Samples per row.
const SAMPLES: usize = 4096;

/// One row's verdict over its own corpus.
struct Row {
    label: &'static str,
    hash: String,
    n: usize,
    /// ⚠ NON-VACUITY GUARD — how many DISTINCT FINITE values the samples took. A row that collapses
    /// to one value hashes identically on every platform and reads as a PASS while pinning nothing.
    /// The analytics twin caught a real instance of exactly that (`overfit::pbo_cscv`).
    distinct: usize,
}

fn finish(label: &'static str, vals: &[f64]) -> Row {
    let mut h = Fnv::new();
    for &v in vals {
        h.push(v);
    }
    let mut bits: Vec<u64> = vals.iter().filter(|v| v.is_finite()).map(|v| v.to_bits()).collect();
    bits.sort_unstable();
    bits.dedup();
    Row { label, hash: h.hex(), n: vals.len(), distinct: bits.len() }
}

/// Smallest number of DISTINCT finite values a row may carry before its pin is treated as vacuous.
const MIN_DISTINCT: usize = 64;

// =================================================================================================
// The corpus.
// =================================================================================================

/// Both covered functions, folded over their own corpora.
///
/// Returns rows in a FIXED order; [`PLATFORM_INVARIANT`] is compared positionally, so a reordering
/// is a re-record rather than a silent re-pairing.
fn production_rows() -> Vec<Row> {
    let mut out = Vec::new();

    // --- metrics::binary_logloss — `libm::log(p)` and `libm::log(1 - p)`.
    //
    // One call per sample over a SHORT vector rather than one call over a long one: the function
    // returns a single scalar, so a long vector would fold thousands of logarithms into one hashed
    // value and the row would be a corpus of size one. Short vectors, many calls, is what makes the
    // hash sensitive to any individual logarithm moving.
    //
    // The probability domain deliberately includes the CLAMP boundaries. `p` is clamped into
    // `[LOGLOSS_EPS, 1 - LOGLOSS_EPS]`, and `log(1e-15)` is the largest term this function can
    // produce — the value its own unit tests pin. A corpus that never reached the clamp would leave
    // the arm carrying the biggest magnitude untested.
    {
        let mut s = 0x1234_5678_9abc_def0u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        for i in 0..SAMPLES {
            let n = 1 + (lcg(&mut s) * 12.0) as usize;
            let mut labels: Vec<f32> = Vec::with_capacity(n);
            let mut probs: Vec<f64> = Vec::with_capacity(n);
            for j in 0..n {
                // Labels are 0/1 in the ordinary case; the fold multiplies by `y` and `1 - y`, so a
                // fractional label exercises BOTH logarithms on the same sample rather than
                // selecting one. Every sixth row is fractional for exactly that reason.
                labels.push(if (i + j) % 6 == 0 {
                    lcg(&mut s) as f32
                } else {
                    ((i + j) % 2) as f32
                });
                probs.push(match (i + j) % 16 {
                    // The clamp arms: below the floor and above the ceiling.
                    0 => -1.0,
                    1 => 2.0,
                    2 => LOGLOSS_EPS * 0.5,
                    3 => 1.0 - LOGLOSS_EPS * 0.5,
                    _ => lcg(&mut s),
                });
            }
            vals.push(binary_logloss(&labels, &probs));
        }
        out.push(finish("metrics::binary_logloss (log x2)", &vals));
    }

    // --- infer::GbdtModel::predict_proba — `libm::exp(-sigmoid * raw_score)`.
    //
    // ⚠ The SIGMOID is swept, not just the feature row, and that is a non-vacuity requirement
    // rather than thoroughness. The committed fixture's trees have one leaf and three leaves, so
    // `raw_score` takes at most THREE distinct values no matter how many rows are fed in — a corpus
    // over rows alone would report `distinct = 3` and hash identically on any two platforms that
    // happened to agree on three numbers. `sigmoid` is a genuine header-parsed parameter (LightGBM
    // writes `objective=binary sigmoid:N` and it is "not always 1.0", per `parse.rs`'s own doc), so
    // sweeping it is exercising the real configuration space, not manufacturing variety.
    //
    // Parsing a model per sigmoid is the honest way to do it: `Objective::Binary { sigmoid }` is
    // built by the parser and there is no public setter, and re-parsing also keeps the row covering
    // the header path that produces the value.
    {
        let mut s = 0x0fed_cba9_8765_4321u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        // Three features (`max_feature_idx=2`), with `feature_infos` of `[0:1] [0:9] [0:2]` — the
        // rows below span each range and overshoot it, because a split threshold is a `<=` and a
        // row outside the training range is an ordinary inference input rather than an error.
        let rows: [[f64; 3]; 8] = [
            [0.0, 0.0, 0.0],
            [1.0, 9.0, 2.0],
            [0.0, 3.0, 2.0],
            [1.0, 4.5, 0.0],
            [0.5, 4.4999, 1.0],
            [0.5, 4.5001, 1.0],
            [-3.0, -1.0, -1.0],
            [7.0, 40.0, 11.0],
        ];
        while vals.len() < SAMPLES {
            // Strictly positive: the parser refuses `sigmoid <= 0`, so a non-positive draw would be
            // an `unwrap` panic rather than a sample.
            let sigmoid = 0.01 + lcg(&mut s) * 8.0;
            let text = FIXTURE.replace("sigmoid:1", &format!("sigmoid:{sigmoid}"));
            let model = parse_model_text(&text).expect("the committed fixture parses");
            for row in &rows {
                vals.push(model.predict_proba(row));
            }
        }
        vals.truncate(SAMPLES);
        out.push(finish("infer::GbdtModel::predict_proba (exp)", &vals));
    }

    out
}

/// ⚠ **ONE set of constants for EVERY platform — that is the entire claim.**
///
/// ⚠ **Every hash below is the literal `"RECORD"`, a PLACEHOLDER that fails by construction, and
/// that is deliberate.** The convention is the analytics twin's
/// (`crates/vike-analytics/tests/libm_platform_probe.rs`'s `PLATFORM_INVARIANT`): rows are
/// sometimes written on a box that cannot run cargo, and a plausible-looking hex literal invented
/// there is INDISTINGUISHABLE from a recorded one while pinning nothing. `"RECORD"` cannot match
/// any FNV output, so [`converted_functions_are_platform_invariant`] stays red until a human RUNS
/// this file on Linux/glibc AND on Windows/MSVC, confirms the two runs agree bit-for-bit, and
/// pastes the agreed hash in. **A red row spelled `"RECORD"` is an UNFINISHED RECORDING, not a
/// regression.**
///
/// ⚠ **Re-record by RUNNING, never by editing a digit**, and never from ONE box.
///
/// ⚠ **A per-platform table (`#[cfg(windows)]` / `#[cfg(unix)]`) is NOT a repair and must never be
/// added.** It would make the gate green by asserting that a probability may depend on the box.
const PLATFORM_INVARIANT: [(&str, &str); 2] = [
    ("metrics::binary_logloss (log x2)", "b4aa8b5ff07afed5"),
    ("infer::GbdtModel::predict_proba (exp)", "cd322ade65352484"),
];

/// The cross-platform proof, as a GATE rather than a diff somebody has to remember to run.
///
/// NOT `#[ignore]`d: CI runs it on Linux every PR and `just t vike-ml` runs it on the Windows dev
/// box, both against the same committed table.
#[test]
fn converted_functions_are_platform_invariant() {
    let got = production_rows();
    assert_eq!(
        got.len(),
        PLATFORM_INVARIANT.len(),
        "row count drifted from PLATFORM_INVARIANT — it must be re-recorded"
    );

    let mut bad = Vec::new();
    for (r, (want_label, want_hash)) in got.iter().zip(PLATFORM_INVARIANT.iter()) {
        assert_eq!(&r.label, want_label, "row ORDER drifted — the compare is positional");
        if r.hash != *want_hash {
            bad.push(format!("  {:<40} want={want_hash} got={}", r.label, r.hash));
        }
    }

    // Non-vacuity BEFORE the hashes: a thin row is a defect whether or not its hash matched, and an
    // author re-recording a `"RECORD"` row must be told about it before pasting.
    let thin: Vec<String> = got
        .iter()
        .filter(|r| r.distinct < MIN_DISTINCT)
        .map(|r| format!("  {:<40} {} distinct finite of {} samples", r.label, r.distinct, r.n))
        .collect();
    assert!(
        thin.is_empty(),
        "a pinned row's corpus is too thin to detect a last-bit divergence: it would hash \
         identically on every platform and read as a PASS. For `predict_proba` the usual cause is \
         a sigmoid sweep that stopped sweeping — the fixture's trees give only THREE distinct raw \
         scores on their own. WIDEN the corpus, never lower MIN_DISTINCT ({MIN_DISTINCT}):\n{}",
        thin.join("\n")
    );

    if !bad.is_empty() {
        let paste: String =
            got.iter().map(|r| format!("    (\"{}\", \"{}\"),\n", r.label, r.hash)).collect();
        panic!(
            "\nvike-ml output moved away from the platform pin:\n{}\n\n\
             There is no tolerance here to widen, and hand-editing a digit defeats the gate.\n\
             ⚠ Do NOT reach for this crate's other gates to decide whether the move matters:\n\
             `train_infer_equality.rs` and `real_model_golden.rs` both budget 1e-12 for one `exp`\n\
             through two libms, so a last-bit move passes them silently. That is why this file is\n\
             a BIT comparison.\n\
             If the want= column reads RECORD this is an UNFINISHED RECORDING rather than a\n\
             regression: run this file on BOTH Windows and Linux, confirm they agree, paste.\n\
             Otherwise establish WHY first:\n\
               (a) an intended numeric change — re-record on BOTH boxes and pin the agreed hash; or\n\
               (b) a call site went back to `(…).exp()` / `(…).ln()`, in which case the two\n\
                   platforms will NOT agree and the fix is in the source, not here.\n\n\
             const PLATFORM_INVARIANT: [(&str, &str); {}] = [\n{paste}];\n",
            bad.join("\n"),
            got.len(),
        );
    }
}

/// The control arm for the non-vacuity threshold itself.
///
/// ⚠ Without this, `MIN_DISTINCT` is an assertion nobody has checked DISCRIMINATES. A `distinct`
/// computation that counted samples rather than distinct values would pass both rows above while
/// the guard did nothing.
#[test]
fn the_non_vacuity_check_discriminates() {
    let constant: Vec<f64> = (0..SAMPLES).map(|_| 0.5f64).collect();
    assert!(
        finish("control::constant", &constant).distinct < MIN_DISTINCT,
        "the non-vacuity check does not discriminate: a constant series passed it"
    );
    let nans: Vec<f64> = (0..SAMPLES).map(|_| f64::NAN).collect();
    assert_eq!(
        finish("control::nan", &nans).distinct,
        0,
        "an all-NaN row must report ZERO distinct FINITE values — and `binary_logloss` returns NaN \
         for an empty input, so this is the shape a broken corpus would actually take here"
    );
    // The degenerate `predict_proba` corpus this file's sigmoid sweep exists to avoid, run as a
    // real control: one model, many rows. If THIS ever passes the floor, the fixture has grown more
    // trees and the sigmoid sweep's justification needs rewriting rather than deleting.
    let model = parse_model_text(FIXTURE).expect("the committed fixture parses");
    let mut s = 0x2222_3333_4444_5555u64;
    let vals: Vec<f64> = (0..SAMPLES)
        .map(|_| {
            let row = [lcg(&mut s) * 2.0, lcg(&mut s) * 12.0, lcg(&mut s) * 3.0];
            model.predict_proba(&row)
        })
        .collect();
    assert!(
        finish("control::one-model", &vals).distinct < MIN_DISTINCT,
        "one fixture model over many rows produced {} distinct probabilities — the committed \
         two-tree fixture should give at most three. If it has grown, update the `predict_proba` \
         row's comment; do not simply delete this control.",
        finish("control::one-model", &vals).distinct
    );
}

// =================================================================================================
// The SOURCE half. The table above proves today's outputs agree; this stops the NEXT edit from
// reintroducing a platform call in a spot the corpus never reaches.
// =================================================================================================

/// The `f64` methods whose last bit is the PLATFORM's business rather than IEEE 754's, as bare
/// names. [`banned_needles`] renders each into the two spellings that reach it.
///
/// `sqrt` is deliberately absent and must stay absent: IEEE 754 requires it correctly rounded, so
/// it is identical on every box and there is nothing to convert it TO. `to_degrees`/`to_radians`
/// are absent for the same reason wearing a different disguise — std lowers each to one
/// multiplication by a constant.
///
/// `powi` IS here: MEASURED on MSVC, a `dev` build lowers `llvm.powi` to the CRT's `pow()`, so it
/// is a libcall rather than the free multiply chain its name suggests. Its cure is a MULTIPLICATION
/// where the base is a literal and `libm::pow` where it is a runtime `f64`
/// (`crates/vike-model/src/strategy/maker_params.rs`'s `ladder_size_mult` is the workspace's one
/// MEASURED instance of the latter). `crates/vike-ml/src` has no `powi` outside a test module to
/// exempt today.
const BANNED_FNS: [&str; 26] = [
    "powf", "ln", "log", "log2", "log10", "exp", "exp2", "exp_m1", "ln_1p", "sin", "cos", "tan",
    "powi", "atan", "atan2", "asin", "acos", "sinh", "cosh", "tanh", "cbrt", "hypot", "asinh",
    "acosh", "atanh", "sin_cos",
];

/// Every [`BANNED_FNS`] name in BOTH spellings that reach the platform's libm.
///
/// ⚠ The UFCS half is not decoration. A gate that bans `.exp(` and nothing else walks straight past
/// `f64::exp(x)` — the same inherent method, called through its fully-qualified path, compiling to
/// the same libcall. Neither spelling is more correct Rust and rustfmt rewrites neither into the
/// other. The `f64::NAME(` needle also covers `std::primitive::f64::NAME(` and
/// `core::primitive::f64::NAME(` for free, because both END with exactly that pattern.
///
/// ⚠ **What it still cannot see, stated rather than implied:** `<f64>::exp(x)` (the angle-bracket
/// spelling), a call reached through a generic bound (`T: Float`), and a call split across two
/// lines by a `max_width` wrap. None of the three occurs under this crate's `src/` today. A list of
/// spellings is an enumeration, and an enumeration is never a proof.
fn banned_needles() -> Vec<String> {
    BANNED_FNS.iter().flat_map(|f| [format!(".{f}("), format!("f64::{f}(")]).collect()
}

/// Every TEST-ONLY item's line range in one file, as `(start, end, closed)` — `start` inclusive,
/// `end` EXCLUSIVE, both zero-based; `closed` says whether the item's end was actually LOCATED
/// rather than assumed, so the one silent failure mode can be asserted on.
///
/// ⚠ **RANGES, never a `break` at the first marker.** A `break` says "the shipped half of a file
/// ends at its first test module", which holds only when that module is LAST.
/// `crates/vike-mm/src/platform_probe.rs`'s twin measured what it costs when it is not: 1,612
/// production lines discarded across five files, two `libm` sites among them, and the resulting
/// undercount copied into that crate's prose as a confident inventory.
///
/// ⚠ **Measured on THIS crate 2026-08-29, and the honest answer is that a `break` would change no
/// verdict here today**: every test item under `crates/vike-ml/src` is the last thing in its file.
/// So the ranges are insurance rather than a fix, and the property they buy is that the day
/// somebody splits `gbdt_learner.rs` (1677 lines, with its test module opening at 718) and leaves
/// production code below the marker, this gate does not silently stop reading it while still
/// reporting a confident zero.
///
/// ⚠ **TWO marker spellings are recognised.** `#[cfg(all(test, …))]` is unambiguously test-only and
/// is a range. `#[cfg(any(test, feature = "…"))]` is deliberately NOT — and this crate is precisely
/// where that matters, because `crates/vike-ml/src/test_support.rs` is gated exactly that way and
/// SHIPS to any consumer enabling `test-support`. Treating it as test-only would take a shipped
/// module out of this gate's view.
///
/// ⚠ **And the cut is LINE BY LINE with the comment filter FIRST.** A whole-file
/// `text.find("#[cfg(test)]")` truncates at the first occurrence of that string ANYWHERE, a doc
/// comment included, and a `//`-skipping filter applied afterwards cannot rescue it because it runs
/// on already-truncated text. This crate has one such prose mention today, in `gbdt_learner.rs`'s
/// module doc at line 110 — so a whole-file cut would discard 1,567 of that file's 1,677 lines and
/// report a confident zero for it.
///
/// # How an item's end is found, and why by INDENTATION rather than by counting braces
///
/// A brace count needs to know which braces are code, which puts a Rust string/char/comment lexer
/// inside a gate — and this workspace's test modules are full of `format!("{}")` and of assert
/// messages continued with a trailing `\`, so a naive count is wrong on exactly the files that
/// matter. Indentation needs no lexer and is exact here for a STRUCTURAL reason: `cargo fmt
/// --check` is CI's first gate, so every file in the tree is rustfmt output, and rustfmt closes a
/// block with a `}` alone on a line at the block's OWN indentation. Verified over this crate
/// 2026-08-29: every marker under `crates/vike-ml/src` sits at column 0.
///
/// Two ways it can be wrong, and only one is quiet. A line INSIDE the item that IS the closing
/// pattern ends the range early — the scan then resumes over test code, which is full of banned
/// spellings, so that failure is a LOUD false positive naming the line. No closing pattern at ALL
/// runs the range to EOF and is SILENT, which is the `break`'s behaviour; that is what `closed` is
/// for and why the caller asserts on it.
///
/// ⚠ **This is a per-crate COPY, deliberately rather than unnoticed.** Sharing it needs a crate
/// every one of these test targets can depend on; none has one, and adding the edge costs a
/// manifest change in every pinned crate to save eleven lines of string handling. A gate that lives
/// in another crate is also a gate the owning crate can be moved out from under.
fn cfg_test_ranges(lines: &[&str]) -> Vec<(usize, usize, bool)> {
    /// The attribute spellings that open a TEST-ONLY item. See the doc above for why
    /// `#[cfg(any(test, …))]` is absent: that code SHIPS when its feature is on, and this crate's
    /// `test_support` module is the example.
    const TEST_ITEM_ATTRS: [&str; 2] = ["#[cfg(test)]", "#[cfg(all(test,"];

    let mut items = Vec::new();
    let mut i = 0usize;
    while i < lines.len() {
        let trimmed = lines[i].trim_start();
        // Prose FIRST, for the reason the doc gives: a comment naming the attribute in backticks
        // must not be able to open a range.
        if trimmed.starts_with("//") || !TEST_ITEM_ATTRS.iter().any(|a| trimmed.starts_with(a)) {
            i += 1;
            continue;
        }
        let mut closing = " ".repeat(lines[i].len() - trimmed.len());
        closing.push('}');
        let mut opened = false;
        let mut end = lines.len();
        let mut closed = false;
        for (j, line) in lines.iter().enumerate().skip(i) {
            let tail = line.trim_end();
            if !opened {
                // The header may span lines (further attributes, the `mod` on the next line). It
                // ends either by opening a block or, for `#[cfg(test)] mod tests;`, at the `;`.
                if tail.ends_with('{') {
                    opened = true;
                } else if tail.ends_with(';') {
                    end = j + 1;
                    closed = true;
                    break;
                }
                continue;
            }
            if tail == closing {
                end = j + 1;
                closed = true;
                break;
            }
        }
        items.push((i, end, closed));
        i = end;
    }
    items
}

/// The RANGE walk, proved on a synthetic file rather than on the tree it happens to run against.
///
/// ⚠ **A tree-shaped assertion cannot cover this AT ALL in this crate, which is why the fixture is
/// the only proof there is.** Measured 2026-08-29: every test item under `crates/vike-ml/src` is
/// the last thing in its file, so "some production line below a marker was scanned" is FALSE here
/// and could only be written by weakening it into something vacuous. This fixture holds the
/// mechanism directly instead, and every property the walk needs.
#[test]
fn the_test_module_cut_excludes_only_the_test_module() {
    // Every fixture row is a string literal, so the needles inside them are data rather than calls;
    // this file lives under `tests/` and the scan below reads `src/` only, so it never sees them.
    let file = [
        "//! House style: naïve f64 folds, pure, in-file `#[cfg(test)]`.",
        "fn shipped_before() -> f64 {",
        "    x.exp()",
        "}",
        "",
        "#[cfg(test)]",
        "mod first_tests {",
        "    fn fixture() -> f64 {",
        "        y.ln()",
        "    }",
        "}",
        "",
        "fn shipped_after() -> f64 {",
        "    f64::powf(z, 2.0)",
        "}",
        "",
        "#[cfg(all(test, feature = \"whatever\"))]",
        "mod gated_tests {",
        "    fn fixture() -> f64 {",
        "        y.log10()",
        "    }",
        "}",
        "",
        "#[cfg(any(test, feature = \"test-support\"))]",
        "pub fn a_shipped_double() -> f64 {",
        "    q.tanh()",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests;",
        "",
        "fn shipped_last() -> f64 {",
        "    w.sin_cos().0",
        "}",
    ];
    let items = cfg_test_ranges(&file);
    assert_eq!(items.len(), 3, "all three TEST-ONLY items must be found: {items:?}");
    assert_eq!(items[0], (5, 11, true), "the braced module spans its own lines only");
    assert_eq!(items[1], (16, 22, true), "the `all(test, …)` module is test-only and is a range");
    assert_eq!(items[2], (28, 30, true), "the `mod tests;` declaration ends at its semicolon");
    // The control arm: the module doc on line 1 NAMES the attribute in backticks. If prose could
    // open a range, `items[0]` would start at 0 and every assertion here would still pass while the
    // gate scanned nothing at all.
    assert_eq!(items[0].0, 5, "a `#[cfg(test)]` inside a comment must not open a range");

    let banned = banned_needles();
    let hits: Vec<usize> = file
        .iter()
        .enumerate()
        .filter(|(i, line)| {
            !items.iter().any(|&(s, e, _)| *i >= s && *i < e)
                && !line.trim_start().starts_with("//")
                && banned.iter().any(|p| line.contains(p.as_str()))
        })
        .map(|(i, _)| i)
        .collect();
    assert_eq!(
        hits,
        [2, 13, 25, 32],
        "the scan must see the production call BEFORE the first test module (line 3), the one AFTER \
         it (line 14), the one inside the `any(test, …)` item that SHIPS (line 26) — this crate's \
         `test_support` module is exactly that shape — and the one after the `mod tests;` \
         declaration (line 33); and must NOT see either fixture call (lines 9 and 20). A `break` at \
         the first marker sees only line 3. Saw (zero-based): {hits:?}"
    );
}

/// Production code in this crate must reach a transcendental through the `libm` CRATE.
///
/// ⚠ Not redundant with the hash table. That table pins TWO functions; this crate also holds the
/// learner, the grid search, the importance and the fit cache, and a new transcendental in any of
/// them would be invisible to the corpus above.
///
/// Scope: every `.rs` under `src/`, recursively, MINUS each file's test-item ranges. There are NO
/// exemptions and there should not need to be: measured 2026-08-29, `crates/vike-ml/src` contains
/// three [`BANNED_FNS`] calls and ALL THREE are inside `gbdt_learner.rs`'s test module (its
/// synthetic `sin`/`cos` feature fixture), so this gate starts at a clean zero rather than at a
/// grandfathered list.
#[test]
fn production_code_calls_libm_not_the_platform() {
    let banned = banned_needles();
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let src = root.join("src");
    let mut found = Vec::new();
    let mut scanned: Vec<String> = Vec::new();
    // A test item whose end could not be located swallows the rest of its file exactly the way a
    // `break` would. That is the one QUIET failure of the range walk, so it is collected and
    // asserted rather than absorbed.
    let mut unclosed: Vec<String> = Vec::new();
    let mut stack = vec![src];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).expect("crate has a src/ directory") {
            let path = entry.expect("readable dir entry").path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                continue;
            }
            // `\` -> `/` so a reported path reads the same on the Windows dev box and on Linux.
            let rel = path.strip_prefix(root).unwrap_or(&path).to_string_lossy().replace('\\', "/");
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            let text = std::fs::read_to_string(&path).expect("readable source file");
            scanned.push(name);
            let lines: Vec<&str> = text.lines().collect();
            let test_items = cfg_test_ranges(&lines);
            for &(start, _, closed) in &test_items {
                if !closed {
                    unclosed.push(format!("  {rel}:{}", start + 1));
                }
            }
            for (i, line) in lines.iter().enumerate() {
                if test_items.iter().any(|&(start, end, _)| i >= start && i < end) {
                    continue; // inside a test item — not shipped
                }
                let code = line.trim_start();
                if code.starts_with("//") {
                    continue; // a doc comment naming `exp` is prose, not a call
                }
                for pat in &banned {
                    if line.contains(pat.as_str()) {
                        found.push(format!("  {rel}:{} {code}", i + 1));
                    }
                }
            }
        }
    }
    // Non-vacuity: an empty `found` is indistinguishable from a scan that opened nothing. The three
    // named files are where this gate earns its keep — the two converted sites, plus the one file
    // whose test module contains the only `sin`/`cos` calls in the crate (so if the range walk ever
    // broke, `gbdt_learner.rs` is where it would report a LOUD false positive rather than a silent
    // miss).
    for must in ["metrics.rs", "infer.rs", "gbdt_learner.rs"] {
        assert!(
            scanned.iter().any(|s| s == must),
            "the scan never opened {must}, so an empty result proves nothing about the files this \
             gate exists for. Scanned {} files.",
            scanned.len()
        );
    }
    assert!(
        unclosed.is_empty(),
        "a test item's closing line could not be located, so everything below it went UNSCANNED — \
         the exact hole a `break` leaves, wearing a different cause. See `cfg_test_ranges`: the end \
         is the item's own indentation followed by a lone `}}`, or a `;` for a `mod NAME;` \
         declaration.\n{}",
        unclosed.join("\n")
    );
    assert!(
        found.is_empty(),
        "production code must call the `libm` CRATE rather than `f64`'s platform-libm methods, so a \
         PROBABILITY out of this crate is a property of the model rather than of the box that ran \
         it. BOTH spellings are banned, `x.exp()` and `f64::exp(x)`: same inherent method, same \
         libcall (see `banned_needles`). `powi` is banned too — on MSVC a `dev` build makes it a \
         `pow()` libcall — and its cure is a MULTIPLICATION rather than `libm` when the base is a \
         literal:\n{}",
        found.join("\n")
    );
}
