//! The cross-platform PIN for this crate's TWO transcendental sites — the gate `vike-indicators`,
//! `vike-analytics` and `vike-mm` each carry, and which vike-ml's conversion landed WITHOUT.
//!
//! IEEE 754 requires `+ - * /` and `sqrt` to be correctly rounded and requires NOTHING of
//! `ln`/`exp`, so an `f64` METHOD call reaches whichever libm the PLATFORM ships — MSVC's CRT on
//! the Windows dev box, glibc on the CI box and every CI runner — and the two disagree in the last bit.
//! `crates/vike-ml/Cargo.toml`'s `libm` line names both sites as this crate's whole share of
//! `docs/decisions/0032-transcendentals-come-from-the-libm-crate-not-the-platform.md`, and both
//! already route through the `libm` CRATE. Nothing in the tree would have noticed the next edit
//! moving either one back.
//!
//! # What each row reaches, stated at its true size
//!
//! * `infer::GbdtModel::predict_proba` is **the probability a live binary decides on** — the whole
//!   point of this crate is that a trading binary predicts with no native dependency, so this is
//!   the number that leaves it. Everything UNDER the `exp` was already portable: `raw_score` is a
//!   plain `+` fold over leaf values and the walk selecting them is comparisons and integer bit
//!   tests. So the site's own doc is right that the conversion moves the probability by at most an
//!   ulp and cannot move a routing decision by itself — but "cannot move a routing decision" is a
//!   statement about a threshold nobody has pinned, and this row is what makes the value itself a
//!   property of the model rather than of the box.
//!
//! ⚠ **There was a SECOND row until `metrics.rs` was deleted, and its removal did not shrink what
//! this file covers.** It pinned `metrics::binary_logloss`'s two `libm::log` calls, on the argument
//! that the function was latent public-API surface whose first caller would be measuring `libm`
//! from its first run. That function had no caller in this workspace, its only import was the last
//! thing tying this crate to `vike-model`, and it went. This file's subject is "this crate's
//! transcendental sites"; there is now ONE, and the row above is still all of them. Do not re-add a
//! row for a function that no longer exists, and do not read the shorter table as reduced coverage.
//!
//! ⚠ The row is not redundant with this crate's existing gates, and the reason is a TOLERANCE.
//! `crates/vike-ml/tests/train_infer_equality.rs` and `crates/vike-ml/tests/real_model_golden.rs`
//! both budget `1e-12` for "one `exp` through two libms", stated in those words — so a last-bit
//! move is four orders inside their budget and passes them silently. Only a BIT comparison can see
//! it, which is what this file adds.
//!
//! # ⚠ The corpus is PURE ARITHMETIC, and that is load-bearing
//!
//! Every input is generated by an integer LCG plus `+ - * /`, never by `.sin()`/`.cos()`. Those are
//! themselves platform-dependent (MEASURED — `crates/vike-analytics/tests/libm_platform_probe.rs`'s
//! Part A sweeps them as its own control), so generating inputs with them would make both rows
//! diverge because of the INPUTS rather than because of the function under test.
//!
//! ```text
//! <cargo> test -p vike-ml --test libm_platform_probe
//! ```

use vike_ml::parse::parse_model_text;
use vike_model::libm_walk::{banned_needles, cfg_test_ranges};

/// The same committed two-tree binary model `crates/vike-ml/src/infer.rs`'s own unit tests parse.
///
/// ⚠ Its tree 1 has THREE leaves and its tree 0 has one, so `raw_score` takes at most THREE
/// distinct values however many feature rows are thrown at it. That single fact is what shapes the
/// `predict_proba` row below — see its comment.
const FIXTURE: &str = include_str!("fixtures/two_trees_binary_v4.txt");

// =================================================================================================
// The shared hashing/corpus machinery. Deliberately a per-crate COPY — see `Fnv`'s own doc for why
// every sibling probe carries the same one. ⚠ This pointed at `cfg_test_ranges`'s doc for that
// argument until decision 0074 moved the TEXT machinery out to `vike_model::libm_walk`; the parser
// is SHARED now and this is not, so the two no longer make one argument.
// =================================================================================================

/// FNV-1a over `f64::to_bits`, NaN canonicalised so a NaN's sign and payload — neither of which the
/// architecture pins — cannot report a divergence that is not one. The same hasher the sibling
/// probes use, so a row moved between crates hashes identically.
struct Fnv(u64);

impl Fnv {
    fn new() -> Self {
        Fnv(0xcbf2_9ce4_8422_2325)
    }
    fn push(&mut self, v: f64) {
        let bits = if v.is_nan() { 0x7ff8_0000_0000_0000u64 } else { v.to_bits() };
        for b in bits.to_le_bytes() {
            self.0 ^= u64::from(b);
            self.0 = self.0.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    fn hex(&self) -> String {
        format!("{:016x}", self.0)
    }
}

/// Deterministic pseudo-random `f64` in `(0, 1)` from a pure-integer LCG. No transcendental
/// anywhere in here, for the reason the module doc gives.
fn lcg(seed: &mut u64) -> f64 {
    *seed = seed.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
    ((*seed >> 11) as f64) / ((1u64 << 53) as f64)
}

/// Samples per row.
const SAMPLES: usize = 4096;

/// One row's verdict over its own corpus.
struct Row {
    label: &'static str,
    hash: String,
    n: usize,
    /// ⚠ NON-VACUITY GUARD — how many DISTINCT FINITE values the samples took. A row that collapses
    /// to one value hashes identically on every platform and reads as a PASS while pinning nothing.
    /// The analytics twin caught a real instance of exactly that (`overfit::pbo_cscv`).
    distinct: usize,
}

fn finish(label: &'static str, vals: &[f64]) -> Row {
    let mut h = Fnv::new();
    for &v in vals {
        h.push(v);
    }
    let mut bits: Vec<u64> = vals.iter().filter(|v| v.is_finite()).map(|v| v.to_bits()).collect();
    bits.sort_unstable();
    bits.dedup();
    Row { label, hash: h.hex(), n: vals.len(), distinct: bits.len() }
}

/// Smallest number of DISTINCT finite values a row may carry before its pin is treated as vacuous.
const MIN_DISTINCT: usize = 64;

// =================================================================================================
// The corpus.
// =================================================================================================

/// The covered function, folded over its own corpus.
///
/// Returns rows in a FIXED order; [`PLATFORM_INVARIANT`] is compared positionally, so a reordering
/// is a re-record rather than a silent re-pairing.
///
/// ⚠ This returned TWO rows, then ONE when `metrics.rs` was deleted, and TWO again now that the
/// TPE sampler moved into this crate and brought its probe. The count is not the point and never
/// was: each corpus is built and folded INDEPENDENTLY, so adding or removing one cannot move
/// another's hash - which is what let the arriving row keep the value recorded for it in
/// vike-backtest, and what let the departing one leave without a re-record.
fn production_rows() -> Vec<Row> {
    let mut out = Vec::new();

    // --- infer::GbdtModel::predict_proba — `libm::exp(-sigmoid * raw_score)`.
    //
    // ⚠ The SIGMOID is swept, not just the feature row, and that is a non-vacuity requirement
    // rather than thoroughness. The committed fixture's trees have one leaf and three leaves, so
    // `raw_score` takes at most THREE distinct values no matter how many rows are fed in — a corpus
    // over rows alone would report `distinct = 3` and hash identically on any two platforms that
    // happened to agree on three numbers. `sigmoid` is a genuine header-parsed parameter (LightGBM
    // writes `objective=binary sigmoid:N` and it is "not always 1.0", per `parse.rs`'s own doc), so
    // sweeping it is exercising the real configuration space, not manufacturing variety.
    //
    // Parsing a model per sigmoid is the honest way to do it: `Objective::Binary { sigmoid }` is
    // built by the parser and there is no public setter, and re-parsing also keeps the row covering
    // the header path that produces the value.
    {
        let mut s = 0x0fed_cba9_8765_4321u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        // Three features (`max_feature_idx=2`), with `feature_infos` of `[0:1] [0:9] [0:2]` — the
        // rows below span each range and overshoot it, because a split threshold is a `<=` and a
        // row outside the training range is an ordinary inference input rather than an error.
        let rows: [[f64; 3]; 8] = [
            [0.0, 0.0, 0.0],
            [1.0, 9.0, 2.0],
            [0.0, 3.0, 2.0],
            [1.0, 4.5, 0.0],
            [0.5, 4.4999, 1.0],
            [0.5, 4.5001, 1.0],
            [-3.0, -1.0, -1.0],
            [7.0, 40.0, 11.0],
        ];
        while vals.len() < SAMPLES {
            // Strictly positive: the parser refuses `sigmoid <= 0`, so a non-positive draw would be
            // an `unwrap` panic rather than a sample.
            let sigmoid = 0.01 + lcg(&mut s) * 8.0;
            let text = FIXTURE.replace("sigmoid:1", &format!("sigmoid:{sigmoid}"));
            let model = parse_model_text(&text).expect("the committed fixture parses");
            for row in &rows {
                vals.push(model.predict_proba(row));
            }
        }
        vals.truncate(SAMPLES);
        out.push(finish("infer::GbdtModel::predict_proba (exp)", &vals));
    }

    // --- tpe::TpeOptimizer - the ask/tell proposal stream.
    //
    // ⚠ This row came from `crates/vike-backtest/tests/libm_platform_probe.rs` with the sampler
    // it measures, and it arrives UNGATED where it used to sit behind `hist-replay` - so the
    // default roster lane runs it now instead of only the `datafusion-store` lane. The corpus,
    // the constants and the recorded hash are unchanged; both crates' hashing machinery is a
    // byte-identical per-crate copy, so the pin transferred rather than needing a re-record.
    out.extend(tpe_rows());

    out
}

/// Drive the TPE ask/tell loop and hash every proposed coordinate.
///
/// ⚠ The loop is driven rather than `gaussian`/`gaussian_pdf` called directly, and not only because
/// both are private. Driving the loop is the STRONGER pin: the failure that matters is not "the pdf
/// is one ulp out", it is "a different one of the `n_candidates` draws won the Expected-Improvement
/// argmax, and every proposal after it differs". A row over the pdf alone would report a last bit;
/// this row reports the re-routed search.
///
/// `n_startup` is deliberately small and the trial count large: `ask` samples UNIFORMLY — no
/// transcendental at all — until `trials.len() >= n_startup.max(2)`, so a corpus dominated by
/// startup draws would pin the LCG and call it a pin of the Parzen sampler. The assertion at the
/// bottom measures that ratio rather than trusting this paragraph.
fn tpe_rows() -> Vec<Row> {
    use vike_ml::tpe::{ParamDomain, TpeOptimizer};

    const TRIALS: usize = 64;
    const SEEDS: u64 = 48;
    const STARTUP: usize = 4;
    const DIMS: usize = 3;

    let mut vals = Vec::with_capacity(SEEDS as usize * TRIALS * DIMS);
    let mut startup_draws = 0usize;
    for seed in 0..SEEDS {
        let space = vec![
            ("x".to_string(), ParamDomain::continuous(-4.0, 6.5)),
            ("y".to_string(), ParamDomain::continuous(0.001, 25.0)),
            // An INTEGRAL axis beside the two continuous ones: it is rounded on the way out, so it
            // exercises the quantised path a real `[sweep]` table produces — where a last-bit move
            // in a proposal becomes a WHOLE-STEP move in the config that gets run.
            ("k".to_string(), ParamDomain::continuous_integral(1.0, 40.0)),
        ];
        let mut opt =
            TpeOptimizer::new(space, seed, 0.25).with_n_startup(STARTUP).with_n_candidates(24);
        for t in 0..TRIALS {
            let params = opt.ask();
            // ⚠ A PURE-ARITHMETIC objective. A `.sin()` bowl here would make the SCORES
            // platform-dependent, the good/bad split differ, and this row diverge because of the
            // objective rather than because of the sampler — the false positive the module doc
            // warns about, planted in the one place it would be hardest to see.
            let mut score = 0.0f64;
            for (i, v) in params.values().enumerate() {
                let centre = 0.5 + i as f64;
                score -= (v - centre) * (v - centre);
                vals.push(*v);
            }
            opt.tell(&params, score);
            if t < STARTUP {
                startup_draws += DIMS;
            }
        }
    }
    // Non-vacuity SPECIFIC to this row, beyond the shared `distinct` floor: prove the corpus is
    // mostly TPE proposals rather than uniform startup draws. Without it the row could pin the LCG
    // — portable by construction — and report a confident pass about a sampler it never reached.
    assert!(
        startup_draws * 4 < vals.len(),
        "startup (uniform, transcendental-free) draws are {startup_draws} of {} samples — this row \
         would be pinning the LCG rather than the Parzen sampler. Raise TRIALS or lower STARTUP.",
        vals.len()
    );
    vec![finish("tpe::TpeOptimizer (gaussian log+cos, gaussian_pdf exp)", &vals)]
}

/// ⚠ **ONE set of constants for EVERY platform — that is the entire claim.**
///
/// ⚠ **Every hash below is the literal `"RECORD"`, a PLACEHOLDER that fails by construction, and
/// that is deliberate.** The convention is the analytics twin's
/// (`crates/vike-analytics/tests/libm_platform_probe.rs`'s `PLATFORM_INVARIANT`): rows are
/// sometimes written on a box that cannot run cargo, and a plausible-looking hex literal invented
/// there is INDISTINGUISHABLE from a recorded one while pinning nothing. `"RECORD"` cannot match
/// any FNV output, so [`converted_functions_are_platform_invariant`] stays red until a human RUNS
/// this file on Linux/glibc AND on Windows/MSVC, confirms the two runs agree bit-for-bit, and
/// pastes the agreed hash in. **A red row spelled `"RECORD"` is an UNFINISHED RECORDING, not a
/// regression.**
///
/// ⚠ **Re-record by RUNNING, never by editing a digit**, and never from ONE box.
///
/// ⚠ **A per-platform table (`#[cfg(windows)]` / `#[cfg(unix)]`) is NOT a repair and must never be
/// added.** It would make the gate green by asserting that a probability may depend on the box.
/// ⚠ It is a TWO-row table again, the second row being the TPE sampler's, which arrived WITH the
/// sampler from vike-backtest carrying the hash recorded there. Before that it was two for a
/// different reason and then one: the removed row was
/// `("metrics::binary_logloss (log x2)", "b4aa8b5ff07afed5")`, and it is written out here rather
/// than merely dropped so that a reader who finds the old hash in git history knows it was RETIRED
/// with its function and is not a value somebody failed to re-record. The surviving hash is
/// unchanged: `production_rows` builds each corpus independently, so removing one cannot move the
/// other.
const PLATFORM_INVARIANT: [(&str, &str); 2] = [
    ("infer::GbdtModel::predict_proba (exp)", "cd322ade65352484"),
    ("tpe::TpeOptimizer (gaussian log+cos, gaussian_pdf exp)", "d80ed29b912b84e0"),
];

/// The cross-platform proof, as a GATE rather than a diff somebody has to remember to run.
///
/// NOT `#[ignore]`d: CI runs it on Linux every PR and `just t vike-ml` runs it on the Windows dev
/// box, both against the same committed table.
#[test]
fn converted_functions_are_platform_invariant() {
    let got = production_rows();
    assert_eq!(
        got.len(),
        PLATFORM_INVARIANT.len(),
        "row count drifted from PLATFORM_INVARIANT — it must be re-recorded"
    );

    let mut bad = Vec::new();
    for (r, (want_label, want_hash)) in got.iter().zip(PLATFORM_INVARIANT.iter()) {
        assert_eq!(&r.label, want_label, "row ORDER drifted — the compare is positional");
        if r.hash != *want_hash {
            bad.push(format!("  {:<40} want={want_hash} got={}", r.label, r.hash));
        }
    }

    // Non-vacuity BEFORE the hashes: a thin row is a defect whether or not its hash matched, and an
    // author re-recording a `"RECORD"` row must be told about it before pasting.
    let thin: Vec<String> = got
        .iter()
        .filter(|r| r.distinct < MIN_DISTINCT)
        .map(|r| format!("  {:<40} {} distinct finite of {} samples", r.label, r.distinct, r.n))
        .collect();
    assert!(
        thin.is_empty(),
        "a pinned row's corpus is too thin to detect a last-bit divergence: it would hash \
         identically on every platform and read as a PASS. For `predict_proba` the usual cause is \
         a sigmoid sweep that stopped sweeping — the fixture's trees give only THREE distinct raw \
         scores on their own. WIDEN the corpus, never lower MIN_DISTINCT ({MIN_DISTINCT}):\n{}",
        thin.join("\n")
    );

    if !bad.is_empty() {
        let paste: String =
            got.iter().map(|r| format!("    (\"{}\", \"{}\"),\n", r.label, r.hash)).collect();
        panic!(
            "\nvike-ml output moved away from the platform pin:\n{}\n\n\
             There is no tolerance here to widen, and hand-editing a digit defeats the gate.\n\
             ⚠ Do NOT reach for this crate's other gates to decide whether the move matters:\n\
             `train_infer_equality.rs` and `real_model_golden.rs` both budget 1e-12 for one `exp`\n\
             through two libms, so a last-bit move passes them silently. That is why this file is\n\
             a BIT comparison.\n\
             If the want= column reads RECORD this is an UNFINISHED RECORDING rather than a\n\
             regression: run this file on BOTH Windows and Linux, confirm they agree, paste.\n\
             Otherwise establish WHY first:\n\
               (a) an intended numeric change — re-record on BOTH boxes and pin the agreed hash; or\n\
               (b) a call site went back to `(…).exp()` / `(…).ln()`, in which case the two\n\
                   platforms will NOT agree and the fix is in the source, not here.\n\n\
             const PLATFORM_INVARIANT: [(&str, &str); {}] = [\n{paste}];\n",
            bad.join("\n"),
            got.len(),
        );
    }
}

/// The control arm for the non-vacuity threshold itself.
///
/// ⚠ Without this, `MIN_DISTINCT` is an assertion nobody has checked DISCRIMINATES. A `distinct`
/// computation that counted samples rather than distinct values would pass both rows above while
/// the guard did nothing.
#[test]
fn the_non_vacuity_check_discriminates() {
    let constant: Vec<f64> = (0..SAMPLES).map(|_| 0.5f64).collect();
    assert!(
        finish("control::constant", &constant).distinct < MIN_DISTINCT,
        "the non-vacuity check does not discriminate: a constant series passed it"
    );
    let nans: Vec<f64> = (0..SAMPLES).map(|_| f64::NAN).collect();
    assert_eq!(
        finish("control::nan", &nans).distinct,
        0,
        "an all-NaN row must report ZERO distinct FINITE values — the shape a broken corpus takes \
         here, since a model that failed to parse would fold NaNs rather than refusing outright"
    );
    // The degenerate `predict_proba` corpus this file's sigmoid sweep exists to avoid, run as a
    // real control: one model, many rows. If THIS ever passes the floor, the fixture has grown more
    // trees and the sigmoid sweep's justification needs rewriting rather than deleting.
    let model = parse_model_text(FIXTURE).expect("the committed fixture parses");
    let mut s = 0x2222_3333_4444_5555u64;
    let vals: Vec<f64> = (0..SAMPLES)
        .map(|_| {
            let row = [lcg(&mut s) * 2.0, lcg(&mut s) * 12.0, lcg(&mut s) * 3.0];
            model.predict_proba(&row)
        })
        .collect();
    assert!(
        finish("control::one-model", &vals).distinct < MIN_DISTINCT,
        "one fixture model over many rows produced {} distinct probabilities — the committed \
         two-tree fixture should give at most three. If it has grown, update the `predict_proba` \
         row's comment; do not simply delete this control.",
        finish("control::one-model", &vals).distinct
    );
}

// =================================================================================================
// The SOURCE half. The table above proves today's outputs agree; this stops the NEXT edit from
// reintroducing a platform call in a spot the corpus never reaches.
// =================================================================================================

/// Production code in this crate must reach a transcendental through the `libm` CRATE.
///
/// ⚠ Not redundant with the hash table. That table pins TWO functions; this crate also holds the
/// learner, the grid search, the importance and the fit cache, and a new transcendental in any of
/// them would be invisible to the corpus above.
///
/// Scope: every `.rs` under `src/`, recursively, MINUS each file's test-item ranges. There are NO
/// exemptions and there should not need to be: measured 2026-08-29, `crates/vike-ml/src` contains
/// three `vike_model::libm_walk::BANNED_FNS` calls and ALL THREE are inside `gbdt_learner.rs`'s
/// test module (its synthetic `sin`/`cos` feature fixture), so this gate starts at a clean zero
/// rather than at a grandfathered list.
///
/// # What was MEASURED on THIS crate, and why the shared walk is the right shape for it
///
/// The text machinery this gate runs on — `banned_needles` and `cfg_test_ranges` — moved to
/// `vike_model::libm_walk` under decision 0074, and the GENERAL argument for each choice (two
/// spellings rather than one, ranges rather than a `break`, the comment filter first, the
/// indentation rule rather than a brace count) lives there with it. What could not move is the
/// per-crate EVIDENCE that those choices bite HERE, so it is recorded below rather than lost with
/// the copy that used to carry it.
///
/// * **`powi` needs no exemption in this crate.** The shared list bans `powi` because MEASURED on
///   MSVC a `dev` build lowers `llvm.powi` to the CRT's `pow()`, so a crate that has one may need
///   an exemption table of its own. `crates/vike-ml/src` has no `powi` outside a test module to
///   exempt today, which is why this gate carries no such table.
///
/// * **The needle list's three blind spots do not occur here.** `<f64>::exp(x)` (the
///   angle-bracket spelling — the text carries `f64>::exp(`, which neither needle matches),
///   a call reached through a generic bound (`T: Float`), and a call split across two lines by
///   a `max_width` wrap are all invisible to `banned_needles`. None of the three occurs under
///   this crate's `src/` today. A list of spellings is an enumeration and an enumeration is
///   never a proof; this measurement is what stands in for one here, and it has to be retaken
///   the day it stops holding.
///
/// * **The RANGES buy INSURANCE in this crate rather than a fix, and that is the honest answer.**
///   Measured 2026-08-29: every test item under `crates/vike-ml/src` is the last thing in its
///   file, so a `break` at the first marker would change no verdict here today. What the ranges
///   buy is the day somebody splits `gbdt_learner.rs` (1677 lines, with its test module opening at
///   718) and leaves production code below the marker — this gate then does not silently stop
///   reading it while still reporting a confident zero.
///
/// * **The `any(test, …)` spelling is deliberately NOT a range, and this crate is precisely where
///   that matters.** `crates/vike-ml/src/test_support.rs` is gated exactly that way and SHIPS to
///   any consumer enabling `test-support`, so recognising it as a test item would take a shipped
///   module out of this gate's view.
///
/// * **The comment filter has to run FIRST, and this crate holds the prose mention that proves
///   it.** A whole-file `text.find("#[cfg(test)]")` truncates at the first occurrence of that
///   string ANYWHERE, a doc comment included, and a `//`-skipping filter applied afterwards cannot
///   rescue it because it runs on already-truncated text. `gbdt_learner.rs`'s module doc names the
///   attribute in backticks at line 110 — so a whole-file cut would discard 1,567 of that file's
///   1,677 lines and report a confident zero for it.
///
/// * **The indentation rule is exact on this crate's sources.** Verified 2026-08-29: every marker
///   under `crates/vike-ml/src` sits at column 0, so a lone `}` at the item's own indentation is
///   where rustfmt has put the end of every block this gate cuts.
///
/// * **No tree-shaped assertion in this crate could cover the range walk AT ALL**, which is why
///   the walk's proof is a PLANTED FIXTURE and why that fixture moving to
///   `crates/vike-model/tests/libm_walk_selftest.rs` costs this crate nothing it used to have.
///   Because every test item here is the last thing in its file (above), "some production line
///   below a marker was scanned" is FALSE against `crates/vike-ml/src` and could only be written
///   by weakening it into something vacuous. The `unclosed` assertion below is the part of the
///   mechanism this crate CAN still check against its own tree, and it is checked on every run.
#[test]
fn production_code_calls_libm_not_the_platform() {
    let banned = banned_needles();
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let src = root.join("src");
    let mut found = Vec::new();
    let mut scanned: Vec<String> = Vec::new();
    // A test item whose end could not be located swallows the rest of its file exactly the way a
    // `break` would. That is the one QUIET failure of the range walk, so it is collected and
    // asserted rather than absorbed.
    let mut unclosed: Vec<String> = Vec::new();
    let mut stack = vec![src];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).expect("crate has a src/ directory") {
            let path = entry.expect("readable dir entry").path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                continue;
            }
            // `\` -> `/` so a reported path reads the same on the Windows dev box and on Linux.
            let rel = path.strip_prefix(root).unwrap_or(&path).to_string_lossy().replace('\\', "/");
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            let text = std::fs::read_to_string(&path).expect("readable source file");
            scanned.push(name);
            let lines: Vec<&str> = text.lines().collect();
            let test_items = cfg_test_ranges(&lines);
            for &(start, _, closed) in &test_items {
                if !closed {
                    unclosed.push(format!("  {rel}:{}", start + 1));
                }
            }
            for (i, line) in lines.iter().enumerate() {
                if test_items.iter().any(|&(start, end, _)| i >= start && i < end) {
                    continue; // inside a test item — not shipped
                }
                let code = line.trim_start();
                if code.starts_with("//") {
                    continue; // a doc comment naming `exp` is prose, not a call
                }
                for pat in &banned {
                    if line.contains(pat.as_str()) {
                        found.push(format!("  {rel}:{} {code}", i + 1));
                    }
                }
            }
        }
    }
    // Non-vacuity: an empty `found` is indistinguishable from a scan that opened nothing. The named
    // files are where this gate earns its keep — the converted site, plus the one file whose test
    // module contains the only `sin`/`cos` calls in the crate (so if the range walk ever broke,
    // `gbdt_learner.rs` is where it would report a LOUD false positive rather than a silent miss).
    //
    // ⚠ `metrics.rs` was a third witness here and is DELETED, and it is worth saying how it failed
    // rather than just dropping the name: this assertion is what caught the deletion. The module
    // vanished, the scan quietly found one fewer file, and the loud panic below is the only reason
    // that did not read as a pass. That is the whole argument for naming witnesses by hand — a
    // scan whose input shrinks silently is the failure this pattern exists to make impossible.
    // Do not replace this list with a count; a count is what a deletion trivially satisfies.
    for must in ["infer.rs", "gbdt_learner.rs"] {
        assert!(
            scanned.iter().any(|s| s == must),
            "the scan never opened {must}, so an empty result proves nothing about the files this \
             gate exists for. Scanned {} files.",
            scanned.len()
        );
    }
    assert!(
        unclosed.is_empty(),
        "a test item's closing line could not be located, so everything below it went UNSCANNED — \
         the exact hole a `break` leaves, wearing a different cause. See `cfg_test_ranges`: the end \
         is the item's own indentation followed by a lone `}}`, or a `;` for a `mod NAME;` \
         declaration.\n{}",
        unclosed.join("\n")
    );
    assert!(
        found.is_empty(),
        "production code must call the `libm` CRATE rather than `f64`'s platform-libm methods, so a \
         PROBABILITY out of this crate is a property of the model rather than of the box that ran \
         it. BOTH spellings are banned, `x.exp()` and `f64::exp(x)`: same inherent method, same \
         libcall (see `banned_needles`). `powi` is banned too — on MSVC a `dev` build makes it a \
         `pow()` libcall — and its cure is a MULTIPLICATION rather than `libm` when the base is a \
         literal:\n{}",
        found.join("\n")
    );
}
