//! Past the history trim: the path-dependent exemption and per-indicator truncation invariance.

use vike_indicators::{make, registry};

use super::{fold_stream, synth_bars};

/// The bar count at which `hist_indicator!`'s history trim first fires for the DEEPEST retention
/// family: `WindowReach::Smoothed` floors at `KEEP_FLOOR` and the drain compacts at `keep * 2`.
/// Every other test in this file runs at 400 or fewer bars, which is BELOW it — so before this test
/// existed, the trim was never executed under test at all.
///
/// ⚠ The `WindowReach::Finite` family floors at `FINITE_FLOOR` instead, so its drain fires an order
/// of magnitude earlier and `on_bar_equals_vectorize_for_every_indicator`'s own 400 bars now cross
/// it. That is a gain, not a reason to lower this: the number here has to clear the DEEPEST family,
/// which is the one no shorter test reaches.
const PAST_THE_TRIM: usize = 1_200;

/// The whole point of [`PAST_THE_TRIM`] is that it EXCEEDS the trim threshold, so that is asserted
/// at COMPILE time rather than inside one test: a runtime `assert!` on two constants is a lint
/// (`clippy::assertions_on_constants`) precisely because it can never fire at a useful moment.
///
/// ⚠ It is DERIVED from the crate's own floor rather than restating it. This line used to read
/// `assert!(PAST_THE_TRIM > 512)` with a comment re-deriving 512 from `KEEP_FLOOR` by hand — a copy
/// that survives exactly until someone changes the floor, which is what `WindowReach` just did.
const _: () = assert!(PAST_THE_TRIM > 2 * vike_indicators::KEEP_FLOOR);

/// ⚠ **The gate that was missing when a real bug shipped.**
///
/// `hist_indicator!` drops history the batch kernel "provably cannot read". That is sound for a
/// bounded-window kernel and WRONG for a path-dependent one, which reads everything since the mount
/// — and six of the nine indicators `is_path_dependent` names are generated by that very macro
/// (`mcginley`, `ad`, `nvi`, `pvi`, `pvt`, `net_volume`). The macro's own comment asserted the
/// opposite, so the exemption was never applied and each of those six recomputed a cumulative sum
/// from a truncated start.
///
/// It shipped green because `on_bar_equals_vectorize_for_every_indicator` runs 400 bars and the trim
/// first fires at 512: the gate passed by never reaching the code. Length is the whole point of this
/// test, so it runs at [`PAST_THE_TRIM`] and asserts the trim was genuinely crossed.
#[test]
fn path_dependent_indicators_survive_a_series_past_the_trim() {
    let bars = synth_bars(PAST_THE_TRIM);
    let mut checked = 0usize;
    for meta in registry() {
        if meta.batch_only {
            continue;
        }
        let mut ind = make(meta.name).unwrap();
        if !ind.warmup_path_dependent() {
            continue;
        }
        let stream = fold_stream(ind.as_mut(), &bars);
        let batch = ind.vectorize(&bars);
        for (line, (s, b)) in stream.iter().zip(batch.iter()).enumerate() {
            for (i, (sv, bv)) in s.iter().zip(b.iter()).enumerate() {
                assert_eq!(
                    sv.to_bits(),
                    bv.to_bits(),
                    "{} line {line} bar {i}: streamed {sv} != batch {bv} — a path-dependent kernel \
                     had its history truncated, so it recomputed from a truncated start",
                    meta.name
                );
            }
        }
        checked += 1;
    }
    assert!(
        checked >= 6,
        "expected at least the six macro-generated path-dependent indicators (mcginley, ad, nvi, \
         pvi, pvt, net_volume); checked {checked} — if this dropped, the exemption may have been \
         narrowed and this gate is no longer watching them"
    );
}

/// The FULL registry at a length that actually crosses the trim.
///
/// `on_bar_equals_vectorize_for_every_indicator` is the same assertion at 400 bars — below the
/// threshold — so it proves the kernels agree while proving nothing about the trim. This is the
/// same property where the trim is live, for every indicator rather than only the path-dependent
/// ones: a bounded-window kernel whose declared `lookback_full` UNDER-reports its true reach would
/// be silently truncated too, and nothing else in this file would notice.
#[test]
fn on_bar_equals_vectorize_past_the_trim_for_every_indicator() {
    let bars = synth_bars(PAST_THE_TRIM);
    for meta in registry() {
        if meta.batch_only {
            continue;
        }
        let mut ind = make(meta.name).unwrap();
        let stream = fold_stream(ind.as_mut(), &bars);
        let batch = ind.vectorize(&bars);
        for (line, (s, b)) in stream.iter().zip(batch.iter()).enumerate() {
            for (i, (sv, bv)) in s.iter().zip(b.iter()).enumerate() {
                assert_eq!(
                    sv.to_bits(),
                    bv.to_bits(),
                    "{} line {line} bar {i} (past the history trim): {sv} != {bv}",
                    meta.name
                );
            }
        }
    }
}

/// The exemption must stay MEASURED, not assumed: every name `is_path_dependent` declares has to be
/// a real registry indicator that actually reports `warmup_path_dependent()`.
///
/// The bug this file now guards against was a claim about which indicators were affected that
/// nothing checked. A declared-but-absent name would make the exemption silently narrower than its
/// author believed — the identical failure, one level up.
#[test]
fn every_declared_path_dependent_indicator_exists_and_reports_itself() {
    for name in ["psar", "vwap", "mcginley", "obv", "ad", "nvi", "pvi", "pvt", "net_volume"] {
        let ind = make(name).unwrap_or_else(|| {
            panic!(
                "`{name}` is declared path-dependent but is \
             not in the registry — the declaration and the roster have drifted"
            )
        });
        assert!(
            ind.warmup_path_dependent(),
            "`{name}` is declared path-dependent but does not report it, so the macro's trim \
             exemption will not apply to it"
        );
    }
}

/// Accumulator kernels that are NOT truncation-invariant, and are therefore wrong past their own
/// drain threshold on any long series.
///
/// ⚠ **A RATCHET: it may shrink, never grow — and it is now EMPTY.** It held seventeen names, every
/// one of which routed through a batch kernel carrying a RUNNING ACCUMULATOR: a sliding
/// `sum += c[i] - c[i-n]` in `crates/vike-indicators/src/math.rs`'s `sma`, or a `run_sum`/`run_sum2`
/// pair in `crates/vike-indicators/src/indicators/statistics.rs`'s `batch_var`/`batch_zscore` and
/// `crates/vike-indicators/src/indicators/volatility.rs`'s `stddev_series`/`batch_hvol`, or the
/// `run_pv`/`run_v` and `run_clvv`/`run_v` pairs in
/// `crates/vike-indicators/src/indicators/overlap.rs`'s `batch_vwma` and
/// `crates/vike-indicators/src/indicators/volume.rs`'s `batch_cmf`.
///
/// Such a kernel's value at bar `i` carried rounding error from bar 0, so its window was
/// mathematically finite while its ARITHMETIC was not. Truncating history changed its bits, and **no
/// `KEEP_FACTOR` could fix that** — the error is a random walk, not a decaying tail. That is the
/// whole difference from the EMA/Wilder family, where a large enough factor genuinely is bit-exact.
/// All six kernels now RECOMPUTE their window, which makes the value a pure function of the window,
/// which is precisely the drain's precondition. Nothing pinned the old values: this crate ships no
/// golden fixtures and no downstream crate asserts an indicator value, so the change was free to
/// make.
///
/// ⚠ **The list must stay, empty, rather than being deleted with its assertions.** The gate below
/// asserts it in BOTH directions, so an empty list is what turns "no accumulator kernels exist" from
/// an unexamined belief into a merge gate: any future kernel that carries state across bars fails
/// `newly_broken` by name.
///
/// ⚠ `crates/vike-indicators/src/pairs.rs` still holds `run_sum`/`run_sum2` pairs and is
/// deliberately untouched: the pair seam's streaming macro pushes to `hist_a`/`hist_b` and NEVER
/// drains them, so `on_pair` and `vectorize_pair` both fold from bar zero and the truncation
/// question does not arise there. It would the day that seam grows a drain.
const NOT_TRUNCATION_INVARIANT: &[&str] = &[];

/// ⚠ **The trim's PRECONDITION, asserted directly — the gate #1183 needed and did not have.**
///
/// `hist_indicator!` drains to `keep` and re-runs the batch kernel over the retained tail, reading
/// only its last element (`indicators::stream_tail`). So the property the drain actually depends on
/// is not "streaming equals batch over 1200 bars"; it is:
///
/// ```text
///     last(vectorize(&bars[len - retained ..]))  ==  vectorize(&bars)[len - 1]
/// ```
///
/// for every `retained` the drain can leave behind, which is `keep ..= 2*keep - 1`.
///
/// ⚠ **`on_bar_equals_vectorize_past_the_trim_for_every_indicator` can only reach this by BRUTE
/// LENGTH, and it does not reach most of it.** The drain first fires at `2 * keep`, i.e. at
/// `128 * lookback_full + 2` bars, so at `PAST_THE_TRIM` it executes only for the shallowest
/// indicators — the rest of the registry it names is never truncated at all, and it passes by not
/// running the code. That is exactly how #1183's bug shipped, and raising the length is not the
/// answer: full coverage needs tens of thousands of bars at O(len × keep) per indicator, while
/// three `vectorize` calls at each indicator's OWN `keep` prove the same thing for the whole
/// registry in a fraction of a second.
///
/// NON-VACUOUS: `NOT_TRUNCATION_INVARIANT` is asserted to be exactly the failing set, in BOTH
/// directions — a name that starts passing must be removed (the ratchet), and a new failure fails
/// the test rather than being absorbed. With the list empty and the kernels unfixed, this test
/// fails; that is the state it was written in.
#[test]
fn every_trimmed_indicator_is_truncation_invariant() {
    let bars = synth_bars(4_000);
    let mut broken: Vec<String> = Vec::new();

    for meta in registry() {
        if meta.batch_only {
            continue;
        }
        let ind = make(meta.name).unwrap();
        // Only the macro-generated impls truncate. A hand-written incremental one folds from bar 0
        // and never drops a bar, so the question does not arise — and asking it anyway would report
        // a "failure" nothing could act on.
        if !ind.trims_history() || ind.warmup_path_dependent() {
            continue;
        }

        // ⚠ Read BOTH inputs off the indicator. `keep_for` grew a `WindowReach` argument when the
        // retention split in two, and a gate that reconstructed which family an indicator belongs
        // to would be testing its own copy of the answer rather than the drain's.
        let keep = vike_indicators::keep_for(ind.lookback_full(), ind.window_reach());
        let full = ind.vectorize(&bars);
        // The three retained lengths the drain can leave: the bound itself, one short of the next
        // compaction, and a midpoint. A kernel that is invariant at `keep` but not at `2*keep - 1`
        // is still wrong on a real chart, because the buffer spends most of its life in between.
        let retained = [keep, keep + keep / 2, (2 * keep).saturating_sub(1)];

        let mut bad = false;
        for r in retained {
            if r >= bars.len() {
                continue;
            }
            let tail = &bars[bars.len() - r..];
            let cut = ind.vectorize(tail);
            for (line, col) in cut.iter().enumerate() {
                let (a, b) = (col[col.len() - 1], full[line][bars.len() - 1]);
                // NaN == NaN by bits here, deliberately: a kernel that emits NaN where the full run
                // emits a number (or the reverse) is the WORST version of this bug, not an exempt
                // case. `bbands_pctb`'s `if bw != 0.0` guard does exactly that at tight params.
                if a.to_bits() != b.to_bits() {
                    bad = true;
                }
            }
        }
        if bad {
            broken.push(meta.name.to_string());
        }
    }

    let mut expected: Vec<String> =
        NOT_TRUNCATION_INVARIANT.iter().map(|s| (*s).to_string()).collect();
    broken.sort();
    expected.sort();

    let newly_broken: Vec<&String> = broken.iter().filter(|n| !expected.contains(n)).collect();
    let newly_fixed: Vec<&String> = expected.iter().filter(|n| !broken.contains(n)).collect();

    assert!(
        newly_broken.is_empty(),
        "{} indicator(s) are NOT truncation-invariant and are not declared: {newly_broken:?}\n\n\
         The `hist_indicator!` drain re-runs the batch kernel over a retained tail, so a kernel \
         that carries a running accumulator across bars returns a DIFFERENT number once history is \
         dropped — silently, past a threshold no short test reaches. Either make the kernel \
         recompute its window, or add the name to `NOT_TRUNCATION_INVARIANT` with the reason.",
        newly_broken.len()
    );
    assert!(
        newly_fixed.is_empty(),
        "{newly_fixed:?} are declared NOT truncation-invariant but now pass — the list is a \
         RATCHET, so delete those rows. Leaving them would let a real regression hide behind a \
         stale exception, which is how the bug this gate exists for reached `main`."
    );
}

/// The gate above is only as good as its SCOPE, so this pins the scope itself.
///
/// If `trims_history` ever returned `false` for the macro-generated impls, the gate would iterate
/// nothing and pass forever — the failure mode it exists to prevent, one level up. This asserts the
/// flag genuinely partitions the registry: the macro-generated majority trims, the hand-written
/// incremental ones do not, and both sides are non-empty.
#[test]
fn the_truncation_gate_actually_has_indicators_to_check() {
    let (mut trims, mut folds) = (0usize, 0usize);
    for meta in registry() {
        let ind = make(meta.name).unwrap();
        if ind.trims_history() {
            trims += 1;
        } else {
            folds += 1;
        }
    }
    assert!(
        trims > 100,
        "only {trims} indicators report trims_history — the gate has lost its scope"
    );
    assert!(
        folds > 5,
        "only {folds} hand-written impls — `trims_history` may have become universal"
    );

    // ...and the two shapes are what they claim. `sma` is hand-written incremental; `dpo` is
    // macro-generated. If either flipped, the gate would be asking the wrong population.
    assert!(!make("sma").unwrap().trims_history(), "`sma` is a hand-written incremental impl");
    assert!(make("dpo").unwrap().trims_history(), "`dpo` is generated by hist_indicator!");
}
