//! The cross-platform PIN for this crate's two transcendental sites — the gate `vike-indicators`,
//! `vike-analytics` and `vike-mm` each carry, and which vike-model's conversions landed WITHOUT.
//!
//! IEEE 754 requires `+ - * /` and `sqrt` to be correctly rounded and requires NOTHING of
//! `ln`/`exp`/`pow`, so an `f64` METHOD call reaches whichever libm the PLATFORM ships — MSVC's CRT
//! on the Windows dev box, glibc on the the CI box Linux boxes and every CI runner — and the two
//! disagree in the last bit.
//! `docs/decisions/0032-transcendentals-come-from-the-libm-crate-not-the-platform.md` is the
//! accepted verdict; both sites below already route through the `libm` CRATE, and until this file
//! existed nothing in the tree would have noticed the next edit moving either one back.
//!
//! # Why this crate is pinned ahead of most of the tree, in one line each
//!
//! * **`fair::p_up` reaches a POSTED QUOTE**, through four quantisers, none of which absorbs a last
//!   bit. Its own doc enumerates them and this file does not restate the argument — read it there
//!   (`crates/vike-model/src/fair.rs`'s `p_up`). The short version: a tick-snapped price, a
//!   quote-or-no-quote straddle guard, a strict-`<` argmin over the beta set, and a strict-`>`
//!   entry gate whose 1-ulp sensitivity is ALREADY a pinned property elsewhere
//!   (`crates/vike-backtest/src/cheap_np.rs` builds `f64::from_bits(e.to_bits() - 1)` to prove it).
//! * **`strategy::maker_params::ladder_size_mult` produces an ORDER QUANTITY**, and it is the one
//!   site in this workspace's `powi` census where the `libm` substitution was actually NEEDED —
//!   measured, `ratio.powi(k)` hashed `e77cac46a86678b1` on Windows/MSVC `dev` and
//!   `c42a98c72a627fca` on Linux/glibc `dev` over 500 ratios × 12 rungs. Two boxes running one
//!   ladder sized its rungs differently. That measurement is on the function's own doc; the row
//!   below is what stops it coming back.
//!
//! # ⚠ The corpus is PURE ARITHMETIC, and that is load-bearing
//!
//! Every input is generated by an integer LCG plus `+ - * /`, never by `.sin()`/`.cos()`. Those are
//! themselves platform-dependent (MEASURED — `crates/vike-analytics/tests/libm_platform_probe.rs`'s
//! Part A sweeps them as its own control), so generating inputs with them would make every row here
//! diverge because of the INPUTS rather than because of the function under test: a false positive
//! that reads exactly like a real one.
//!
//! # ⚠ One row is a CONTROL and must never be deleted as redundant
//!
//! `LadderParams::rungs Linear` calls no transcendental at all — it is `+`, `-` and `*`, every one
//! correctly rounded by IEEE 754 — so it is IDENTICAL on both boxes by construction. That is
//! exactly why it is here. It draws from the same LCG corpus as the `Geometric` row, so if the two
//! boxes ever disagree about IT, the divergence is in the INPUTS or in this harness and every other
//! row's verdict is void. The analytics twin makes the same point about its two agreeing rows: they
//! "are what made the other seven a finding rather than a broken harness".
//!
//! ```text
//! <cargo> test -p vike-model --test libm_platform_probe
//! ```

use vike_model::{LadderOffsetUnit, LadderParams, LadderSizeProfile, p_up};

// =================================================================================================
// The shared hashing/corpus machinery. Deliberately a per-crate COPY — see `cfg_test_ranges`'s doc.
// =================================================================================================

/// FNV-1a over `f64::to_bits`, NaN canonicalised so a NaN's sign and payload — neither of which the
/// architecture pins — cannot report a divergence that is not one. The same hasher the sibling
/// probes use, so a row moved between crates hashes identically.
struct Fnv(u64);

impl Fnv {
    fn new() -> Self {
        Fnv(0xcbf2_9ce4_8422_2325)
    }
    fn push(&mut self, v: f64) {
        let bits = if v.is_nan() { 0x7ff8_0000_0000_0000u64 } else { v.to_bits() };
        for b in bits.to_le_bytes() {
            self.0 ^= u64::from(b);
            self.0 = self.0.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    fn hex(&self) -> String {
        format!("{:016x}", self.0)
    }
}

/// Deterministic pseudo-random `f64` in `(0, 1)` from a pure-integer LCG.
///
/// ⚠ No transcendental anywhere in here, for the reason the module doc gives. The `as f64` of a
/// 53-bit integer is exact and the single division is correctly rounded, so the corpus is
/// bit-identical on every platform BY CONSTRUCTION — which is what makes a divergence in the OUTPUT
/// attributable to the function under test rather than to the inputs.
fn lcg(seed: &mut u64) -> f64 {
    *seed = seed.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
    ((*seed >> 11) as f64) / ((1u64 << 53) as f64)
}

/// Samples per row. Large enough that a last-bit disagreement on a rare input survives into the
/// hash rather than being rounded away — the trap the indicators twin fell into twice with a single
/// series, where two genuinely divergent indicators both reported "identical".
const SAMPLES: usize = 4096;

/// One row's verdict over its own corpus.
struct Row {
    label: &'static str,
    hash: String,
    /// How many samples were folded in.
    n: usize,
    /// ⚠ NON-VACUITY GUARD. A row whose corpus collapses to one value — or to all-NaN — hashes
    /// identically on every platform and reads as a PASS while pinning nothing. This is how many
    /// DISTINCT FINITE values the samples took, so a row reporting `distinct=1` is worthless rather
    /// than reassuring. The analytics twin caught a real instance of exactly that
    /// (`overfit::pbo_cscv`), which is why it is a field on EVERY row here rather than a check
    /// hand-applied to a chosen few.
    distinct: usize,
}

fn finish(label: &'static str, vals: &[f64]) -> Row {
    let mut h = Fnv::new();
    for &v in vals {
        h.push(v);
    }
    let mut bits: Vec<u64> = vals.iter().filter(|v| v.is_finite()).map(|v| v.to_bits()).collect();
    bits.sort_unstable();
    bits.dedup();
    Row { label, hash: h.hex(), n: vals.len(), distinct: bits.len() }
}

/// Smallest number of DISTINCT finite values a row may carry before its pin is treated as vacuous.
const MIN_DISTINCT: usize = 64;

// =================================================================================================
// The corpus.
// =================================================================================================

/// A ladder spec whose only varying parts are the ones `ladder_size_mult` reads.
///
/// `offset_step`/`offset_unit` are held fixed on purpose: they feed the rung OFFSET, which is plain
/// multiplication, and varying them would add distinct values to the hash that have nothing to do
/// with the site under test — inflating `distinct` into a number that no longer evidences the
/// `pow` being exercised.
fn ladder(profile: LadderSizeProfile, ratio: f64, levels: usize) -> LadderParams {
    LadderParams {
        levels,
        offset_step: 1.0,
        offset_unit: LadderOffsetUnit::HalfSpread,
        size_profile: profile,
        size_ratio: ratio,
    }
}

/// Every covered function, folded over its own corpus.
///
/// Returns rows in a FIXED order; [`PLATFORM_INVARIANT`] is compared positionally, so a reordering
/// is a re-record rather than a silent re-pairing.
fn production_rows() -> Vec<Row> {
    let mut out = Vec::new();

    // --- fair::p_up — `libm::log(s_now / s_open)` then `libm::erf(x / SQRT_2)`.
    //
    // The domain is the one the cheap_np taker and the Avellaneda-Stoikov maker actually occupy: a
    // spot ratio close to 1 (a five-minute window's move is basis points, not multiples), a
    // per-SECOND log-return sigma, and `t` strictly inside `[0, h)`. A wide ratio sweep would spend
    // most of the corpus on `p_up` values saturated at 0 or 1, where the `erf` is flat and a last
    // bit in the `log` cannot survive to the output — the row would then be dominated by samples
    // that CANNOT report a divergence, which is a quieter version of vacuity.
    //
    // ⚠ `t` is kept strictly below `h` for the corresponding reason: at `t == h` the `max(h - t,
    // 1e-9)` floor pins `denom` to one value and the row would pin the floor instead of the maths.
    // One in eight samples deliberately lands in the last instant of the window anyway, because
    // that IS where a live maker quotes hardest and the floor's behaviour is worth pinning too.
    {
        let mut s = 0x1234_5678_9abc_def0u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        for i in 0..SAMPLES {
            let beta = 0.05 + lcg(&mut s) * 3.0;
            let s_open = 100.0 + lcg(&mut s) * 60_000.0;
            // ±2% around the open — the range a five-minute crypto window actually moves in.
            let s_now = s_open * (0.98 + lcg(&mut s) * 0.04);
            let sigma = 1e-6 + lcg(&mut s) * 3e-3;
            let h = 60.0 + lcg(&mut s) * 540.0;
            let t = if i % 8 == 0 { h } else { lcg(&mut s) * h * 0.999 };
            vals.push(p_up(beta, s_now, s_open, sigma, t, h));
        }
        out.push(finish("fair::p_up (log + erf)", &vals));
    }

    // --- strategy::maker_params::ladder_size_mult, Geometric — `libm::pow(ratio, k as f64)`.
    //
    // ⚠ Driven through the PUBLIC `LadderParams::rungs` rather than by making the private
    // `ladder_size_mult` reachable. That is the stronger pin as well as the less invasive one: what
    // a maker rests is the `Vec<LadderLevel>` this returns, so the row covers the `max(0.0)` floor
    // and the level-0 special case alongside the power.
    //
    // The ratio sweep straddles 1.0 — `(0.35, 1.0)` decays deeper rungs, `(1.0, 3.35)` grows them —
    // because both are configurations an operator writes and `pow` behaves differently on either
    // side of 1. A ratio of EXACTLY 1.0 is not excluded but is measure-zero in this generator, and
    // it is the one value where the site is portable by accident (`pow(1, y)` is an exact special
    // case in C99 Annex F), so a corpus that landed on it often would overstate the pin.
    {
        let mut s = 0x0fed_cba9_8765_4321u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        while vals.len() < SAMPLES {
            let ratio = 0.35 + lcg(&mut s) * 3.0;
            let levels = 2 + (lcg(&mut s) * 30.0) as usize;
            for rung in ladder(LadderSizeProfile::Geometric, ratio, levels).rungs() {
                vals.push(rung.size);
            }
        }
        vals.truncate(SAMPLES);
        out.push(finish("maker_params::rungs Geometric (pow)", &vals));
    }

    // --- The CONTROL. `Linear` is `1.0 + k·(ratio − 1.0)` — `+`, `-`, `*` only, every one
    // correctly rounded by IEEE 754 — so it is bit-identical on both platforms BY CONSTRUCTION.
    //
    // ⚠ Do not delete this row as "pinning nothing". It draws from the same LCG corpus as the
    // `Geometric` row above, so it is the arm that distinguishes "the FUNCTION diverged" from "the
    // INPUTS diverged, or this harness is broken". If it ever goes red, no other row in this file
    // means anything until that is explained.
    {
        let mut s = 0x0fed_cba9_8765_4321u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        while vals.len() < SAMPLES {
            let ratio = 0.35 + lcg(&mut s) * 3.0;
            let levels = 2 + (lcg(&mut s) * 30.0) as usize;
            for rung in ladder(LadderSizeProfile::Linear, ratio, levels).rungs() {
                vals.push(rung.size);
            }
        }
        vals.truncate(SAMPLES);
        out.push(finish("maker_params::rungs Linear (CONTROL, no transcendental)", &vals));
    }

    out
}

/// ⚠ **ONE set of constants for EVERY platform — that is the entire claim.**
///
/// ⚠ **Every hash below is the literal `"RECORD"`, a PLACEHOLDER that fails by construction, and
/// that is deliberate.** The convention is the analytics twin's
/// (`crates/vike-analytics/tests/libm_platform_probe.rs`'s `PLATFORM_INVARIANT`): rows are
/// sometimes written on a box that cannot run cargo, and a plausible-looking hex literal invented
/// there is INDISTINGUISHABLE from a recorded one while pinning nothing — the single worst outcome
/// available here. `"RECORD"` cannot match any FNV output, so
/// [`converted_functions_are_platform_invariant`] stays red until a human RUNS this file on
/// Linux/glibc AND on Windows/MSVC, confirms the two runs agree bit-for-bit, and pastes the agreed
/// hash in. **A red row spelled `"RECORD"` is an UNFINISHED RECORDING, not a regression.**
///
/// ⚠ **Re-record by RUNNING, never by editing a digit**, and never from ONE box. If a recorded row
/// later goes red the question is which platform moved and why:
///   (a) an intended numeric change — re-record on both boxes and pin the hash they AGREE on; or
///   (b) a call site went back to the platform's libm, in which case the two boxes will NOT agree
///       and the fix is in the source, not here.
///
/// ⚠ **A per-platform table (`#[cfg(windows)]` / `#[cfg(unix)]`) is NOT a repair and must never be
/// added.** It would make the gate green by asserting the divergence was intended — the one
/// conclusion the `ladder_size_mult` measurement refutes.
const PLATFORM_INVARIANT: [(&str, &str); 3] = [
    ("fair::p_up (log + erf)", "4c0ac43bde5de02f"),
    ("maker_params::rungs Geometric (pow)", "0348c8e24f96128d"),
    ("maker_params::rungs Linear (CONTROL, no transcendental)", "183352c7d3052e6f"),
];

/// The cross-platform proof, as a GATE rather than a diff somebody has to remember to run.
///
/// NOT `#[ignore]`d: CI runs it on Linux every PR and `just t vike-model` runs it on the Windows
/// dev box, both against the same committed table.
#[test]
fn converted_functions_are_platform_invariant() {
    let got = production_rows();
    assert_eq!(
        got.len(),
        PLATFORM_INVARIANT.len(),
        "row count drifted from PLATFORM_INVARIANT — it must be re-recorded"
    );

    let mut bad = Vec::new();
    for (r, (want_label, want_hash)) in got.iter().zip(PLATFORM_INVARIANT.iter()) {
        assert_eq!(&r.label, want_label, "row ORDER drifted — the compare is positional");
        if r.hash != *want_hash {
            bad.push(format!("  {:<56} want={want_hash} got={}", r.label, r.hash));
        }
    }

    // The non-vacuity half is asserted BEFORE the hashes, deliberately: a thin row is a defect
    // whether or not its hash matched, and an author re-recording a `"RECORD"` row must be told
    // about it BEFORE pasting a hash that would pin nothing.
    let thin: Vec<String> = got
        .iter()
        .filter(|r| r.distinct < MIN_DISTINCT)
        .map(|r| format!("  {:<56} {} distinct finite of {} samples", r.label, r.distinct, r.n))
        .collect();
    assert!(
        thin.is_empty(),
        "a pinned row's corpus is too thin to detect a last-bit divergence: it would hash \
         identically on every platform and read as a PASS while proving nothing. WIDEN the input \
         ranges — never lower MIN_DISTINCT ({MIN_DISTINCT}):\n{}",
        thin.join("\n")
    );

    if !bad.is_empty() {
        let paste: String =
            got.iter().map(|r| format!("    (\"{}\", \"{}\"),\n", r.label, r.hash)).collect();
        panic!(
            "\nvike-model output moved away from the platform pin:\n{}\n\n\
             There is no tolerance here to widen, and hand-editing a digit defeats the gate.\n\
             A moved `p_up` is a moved QUOTE and a moved `rungs Geometric` is a moved ORDER SIZE.\n\
             If the want= column reads RECORD this is an UNFINISHED RECORDING rather than a\n\
             regression: run this file on BOTH Windows and Linux, confirm they agree, paste.\n\
             ⚠ If the CONTROL row moved, stop: the corpus or this harness is broken and no other\n\
             row's verdict means anything.\n\n\
             const PLATFORM_INVARIANT: [(&str, &str); {}] = [\n{paste}];\n",
            bad.join("\n"),
            got.len(),
        );
    }
}

/// The control arm for the non-vacuity threshold itself.
///
/// ⚠ Without this, `MIN_DISTINCT` is an assertion nobody has checked DISCRIMINATES. A `distinct`
/// computation that counted samples rather than distinct values — or a threshold accidentally set
/// to `0` — would pass every row above while the guard did nothing, and catching a check that
/// passes while doing nothing is the guard's entire job.
#[test]
fn the_non_vacuity_check_discriminates() {
    let constant: Vec<f64> = (0..SAMPLES).map(|_| 0.5f64).collect();
    assert!(
        finish("control::constant", &constant).distinct < MIN_DISTINCT,
        "the non-vacuity check does not discriminate: a constant series passed it"
    );
    assert_eq!(
        finish("control::nan", &(0..SAMPLES).map(|_| f64::NAN).collect::<Vec<f64>>()).distinct,
        0,
        "an all-NaN row must report ZERO distinct FINITE values — the analytics twin's vacuous row \
         was all-NaN rather than constant, and a `distinct` that counted NaNs would have passed it"
    );
    let mut s = 0xdead_beef_cafe_babeu64;
    let rich: Vec<f64> = (0..SAMPLES).map(|_| lcg(&mut s)).collect();
    assert!(
        finish("control::rich", &rich).distinct >= MIN_DISTINCT,
        "the corpus generator itself is degenerate — every row above is void"
    );
}

// =================================================================================================
// The SOURCE half. The table above proves today's outputs agree; this stops the NEXT edit from
// reintroducing a platform call in a spot no corpus reaches.
// =================================================================================================

/// The `f64` methods whose last bit is the PLATFORM's business rather than IEEE 754's, as bare
/// names. [`banned_needles`] renders each into the two spellings that reach it.
///
/// `sqrt` is deliberately absent and must stay absent: IEEE 754 requires it correctly rounded, so
/// it is identical on every box and there is nothing to convert it TO — `p_up`'s own `.sqrt()` is
/// exactly that case and its comment says so. `to_degrees`/`to_radians` are absent for the same
/// reason wearing a different disguise: std lowers each to one multiplication by a constant.
///
/// `powi` IS here, and in THIS crate that is not a precaution — it is the finding. MEASURED on
/// MSVC, a `dev` build lowers `llvm.powi` to the CRT's `pow()`, and
/// `crates/vike-model/src/strategy/maker_params.rs`'s `ladder_size_mult` is the one site in the
/// workspace's `powi` census where the two platforms actually disagreed
/// (`e77cac46a86678b1` vs `c42a98c72a627fca`). Its cure was `libm::pow` because the BASE is a
/// runtime `f64`; where the base is a literal 10 or 2 the cure is a MULTIPLICATION instead, and
/// `crates/vike-model/src` has no such site to exempt today.
const BANNED_FNS: [&str; 26] = [
    "powf", "ln", "log", "log2", "log10", "exp", "exp2", "exp_m1", "ln_1p", "sin", "cos", "tan",
    "powi", "atan", "atan2", "asin", "acos", "sinh", "cosh", "tanh", "cbrt", "hypot", "asinh",
    "acosh", "atanh", "sin_cos",
];

/// Every [`BANNED_FNS`] name in BOTH spellings that reach the platform's libm.
///
/// ⚠ The UFCS half is not decoration. A gate that bans `.exp(` and nothing else walks straight past
/// `f64::exp(x)` — the same inherent method, called through its fully-qualified path, compiling to
/// the same libcall. Neither spelling is more correct Rust and rustfmt rewrites neither into the
/// other, so which one an author reaches for is a coin flip. The `f64::NAME(` needle also covers
/// `std::primitive::f64::NAME(` and `core::primitive::f64::NAME(` for free, because both END with
/// exactly that pattern.
///
/// ⚠ **What it still cannot see, stated rather than implied:** `<f64>::exp(x)` (the angle-bracket
/// spelling — `f64>::exp(` is what appears, and no needle here ends in `>`), a call reached through
/// a generic bound (`T: Float`), and a call split across two lines by a `max_width` wrap. None of
/// the three occurs under this crate's `src/` today. A list of spellings is an enumeration, and an
/// enumeration is never a proof.
fn banned_needles() -> Vec<String> {
    BANNED_FNS.iter().flat_map(|f| [format!(".{f}("), format!("f64::{f}(")]).collect()
}

/// Every TEST-ONLY item's line range in one file, as `(start, end, closed)` — `start` inclusive,
/// `end` EXCLUSIVE, both zero-based; `closed` says whether the item's end was actually LOCATED
/// rather than assumed, so the one silent failure mode can be asserted on.
///
/// ⚠ **RANGES, never a `break` at the first marker, and in THIS crate that is a live difference
/// rather than insurance.** A `break` says "the shipped half of a file ends at its first test
/// module", which holds only when that module is LAST. Measured 2026-08-29 over
/// `crates/vike-model/src`: `strategy/maker_params.rs` carries 180 production lines below its first
/// marker (three test modules, the first at line 372 of 1045 — `HorizonMode`, `KappaMode` and the
/// toxicity bag all live below it) and `strategy/mod.rs` carries 42. A `break` would hand this gate
/// a confident zero over a fifth of the file that defines the maker's own parameter vocabulary.
/// `crates/vike-mm/src/platform_probe.rs` is where that failure was first measured, and where two
/// `libm` sites were found hiding in the discarded region.
///
/// ⚠ **TWO marker spellings are recognised.** `#[cfg(all(test, …))]` is unambiguously test-only and
/// is a range. `#[cfg(any(test, feature = "…"))]` is deliberately NOT — that attribute marks code
/// that SHIPS whenever the feature is on, and this crate holds the workspace's clearest example:
/// `crates/vike-model/src/strategy/mod.rs`'s `MockBroker` is `#[cfg(any(test, feature =
/// "test-support"))]` and is compiled into any consumer enabling `test-support`. Treating it as
/// test-only would take a shipped double out of this gate's view.
///
/// ⚠ **And the cut is LINE BY LINE with the comment filter FIRST.** A whole-file
/// `text.find("#[cfg(test)]")` truncates at the first occurrence of that string ANYWHERE, a doc
/// comment included, and a `//`-skipping filter applied afterwards cannot rescue it because it runs
/// on already-truncated text. This crate carries four such prose mentions today
/// (`change_journal.rs` has three, `venue_margin_support.rs` one), so a whole-file cut would blank
/// most of `change_journal.rs` and report a confident zero for it.
///
/// # How an item's end is found, and why by INDENTATION rather than by counting braces
///
/// A brace count needs to know which braces are code, which puts a Rust string/char/comment lexer
/// inside a gate — and this workspace's test modules are full of `format!("{}")` and of assert
/// messages continued with a trailing `\`, so a naive count is wrong on exactly the files that
/// matter. Indentation needs no lexer and is exact here for a STRUCTURAL reason: `cargo fmt
/// --check` is CI's first gate, so every file in the tree is rustfmt output, and rustfmt closes a
/// block with a `}` alone on a line at the block's OWN indentation. Verified over this crate
/// 2026-08-29: every marker under `crates/vike-model/src` sits at column 0.
///
/// Two ways it can be wrong, and only one is quiet. A line INSIDE the item that IS the closing
/// pattern ends the range early — the scan then resumes over test code, which is full of banned
/// spellings, so that failure is a LOUD false positive naming the line. No closing pattern at ALL
/// runs the range to EOF and is SILENT, which is the `break`'s behaviour; that is what `closed` is
/// for and why the caller asserts on it.
///
/// ⚠ **This is a per-crate COPY, deliberately rather than unnoticed.** Sharing it needs a crate
/// every one of these test targets can depend on; none has one, and adding the edge costs a
/// manifest change in every pinned crate to save eleven lines of string handling. A gate that lives
/// in another crate is also a gate the owning crate can be moved out from under — the same reason
/// `vike-indicators`, `vike-analytics` and `vike-mm` each hold their own rather than sharing one.
fn cfg_test_ranges(lines: &[&str]) -> Vec<(usize, usize, bool)> {
    /// The attribute spellings that open a TEST-ONLY item. See the doc above for why
    /// `#[cfg(any(test, …))]` is absent: that code SHIPS when its feature is on.
    const TEST_ITEM_ATTRS: [&str; 2] = ["#[cfg(test)]", "#[cfg(all(test,"];

    let mut items = Vec::new();
    let mut i = 0usize;
    while i < lines.len() {
        let trimmed = lines[i].trim_start();
        // Prose FIRST, for the reason the doc gives: a comment naming the attribute in backticks
        // must not be able to open a range.
        if trimmed.starts_with("//") || !TEST_ITEM_ATTRS.iter().any(|a| trimmed.starts_with(a)) {
            i += 1;
            continue;
        }
        let mut closing = " ".repeat(lines[i].len() - trimmed.len());
        closing.push('}');
        let mut opened = false;
        let mut end = lines.len();
        let mut closed = false;
        for (j, line) in lines.iter().enumerate().skip(i) {
            let tail = line.trim_end();
            if !opened {
                // The header may span lines (further attributes, the `mod` on the next line). It
                // ends either by opening a block or, for `#[cfg(test)] mod tests;`, at the `;`.
                if tail.ends_with('{') {
                    opened = true;
                } else if tail.ends_with(';') {
                    end = j + 1;
                    closed = true;
                    break;
                }
                continue;
            }
            if tail == closing {
                end = j + 1;
                closed = true;
                break;
            }
        }
        items.push((i, end, closed));
        i = end;
    }
    items
}

/// The RANGE walk, proved on a synthetic file as well as on the tree.
///
/// ⚠ **The tree-shaped half cannot replace this, which is why both exist.** The
/// `scanned_past_a_test_module` evidence the scan below collects is real, but it is evidence about
/// `maker_params.rs` and `strategy/mod.rs` AS THEY ARE TODAY — reorganise either so its test
/// modules go last and that assertion passes vacuously while the mechanism goes unproven. This
/// fixture holds the mechanism itself, and every property the walk needs: production before a test
/// module, a banned call INSIDE it, production after it, the `;` header form, the
/// `#[cfg(all(test, …))]` spelling, and the `#[cfg(any(test, …))]` spelling that must NOT be
/// excluded because it SHIPS.
#[test]
fn the_test_module_cut_excludes_only_the_test_module() {
    // Every fixture row is a string literal, so the needles inside them are data rather than calls;
    // this file lives under `tests/` and the scan below reads `src/` only, so it never sees them.
    let file = [
        "//! House style: naïve f64 folds, pure, in-file `#[cfg(test)]`.",
        "fn shipped_before() -> f64 {",
        "    x.exp()",
        "}",
        "",
        "#[cfg(test)]",
        "mod first_tests {",
        "    fn fixture() -> f64 {",
        "        y.ln()",
        "    }",
        "}",
        "",
        "fn shipped_after() -> f64 {",
        "    f64::powf(z, 2.0)",
        "}",
        "",
        "#[cfg(all(test, feature = \"whatever\"))]",
        "mod gated_tests {",
        "    fn fixture() -> f64 {",
        "        y.log10()",
        "    }",
        "}",
        "",
        "#[cfg(any(test, feature = \"test-support\"))]",
        "pub fn a_shipped_double() -> f64 {",
        "    q.tanh()",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests;",
        "",
        "fn shipped_last() -> f64 {",
        "    w.sin_cos().0",
        "}",
    ];
    let items = cfg_test_ranges(&file);
    assert_eq!(items.len(), 3, "all three TEST-ONLY items must be found: {items:?}");
    assert_eq!(items[0], (5, 11, true), "the braced module spans its own lines only");
    assert_eq!(items[1], (16, 22, true), "the `all(test, …)` module is test-only and is a range");
    assert_eq!(items[2], (28, 30, true), "the `mod tests;` declaration ends at its semicolon");
    // The control arm: the module doc on line 1 NAMES the attribute in backticks. If prose could
    // open a range, `items[0]` would start at 0 and every assertion here would still pass while the
    // gate scanned nothing at all.
    assert_eq!(items[0].0, 5, "a `#[cfg(test)]` inside a comment must not open a range");

    let banned = banned_needles();
    let hits: Vec<usize> = file
        .iter()
        .enumerate()
        .filter(|(i, line)| {
            !items.iter().any(|&(s, e, _)| *i >= s && *i < e)
                && !line.trim_start().starts_with("//")
                && banned.iter().any(|p| line.contains(p.as_str()))
        })
        .map(|(i, _)| i)
        .collect();
    assert_eq!(
        hits,
        [2, 13, 25, 32],
        "the scan must see the production call BEFORE the first test module (line 3), the one AFTER \
         it (line 14), the one inside the `any(test, …)` item that SHIPS (line 26) — this crate's \
         `MockBroker` is exactly that shape — and the one after the `mod tests;` declaration \
         (line 33); and must NOT see either fixture call (lines 9 and 20). A `break` at the first \
         marker sees only line 3. Saw (zero-based): {hits:?}"
    );
}

/// Production code in this crate must reach a transcendental through the `libm` CRATE.
///
/// ⚠ Not redundant with the hash table. That table pins TWO functions; this crate is the workspace
/// vocabulary — every venue, every strategy and every engine reads its types — and a new
/// transcendental in any of its other files would be invisible to the corpus while making a shared
/// primitive depend on which box ran it.
///
/// Scope: every `.rs` under `src/`, recursively, MINUS each file's test-item ranges. There are NO
/// exemptions and there should not need to be: measured 2026-08-29, `crates/vike-model/src`
/// contains not one call to any [`BANNED_FNS`] name outside a test item, so this gate starts at a
/// clean zero rather than at a grandfathered list.
#[test]
fn production_code_calls_libm_not_the_platform() {
    let banned = banned_needles();
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let src = root.join("src");
    let mut found = Vec::new();
    let mut scanned: Vec<String> = Vec::new();
    // Files where at least one NON-BLANK production line BELOW the first marker was scanned — the
    // property a `break` makes impossible. ⚠ Non-blank matters: two adjacent test modules are
    // separated by an empty line, and counting that line would make this assertion pass on files
    // that carry no production code below a marker at all.
    let mut scanned_past_a_test_module: Vec<String> = Vec::new();
    // A test item whose end could not be located swallows the rest of its file exactly the way a
    // `break` would. That is the one QUIET failure of the range walk, so it is collected and
    // asserted rather than absorbed.
    let mut unclosed: Vec<String> = Vec::new();
    let mut stack = vec![src];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).expect("crate has a src/ directory") {
            let path = entry.expect("readable dir entry").path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                continue;
            }
            // `\` -> `/` so a reported path reads the same on the Windows dev box and on Linux.
            let rel = path.strip_prefix(root).unwrap_or(&path).to_string_lossy().replace('\\', "/");
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            let text = std::fs::read_to_string(&path).expect("readable source file");
            scanned.push(name.clone());
            let lines: Vec<&str> = text.lines().collect();
            let test_items = cfg_test_ranges(&lines);
            for &(start, _, closed) in &test_items {
                if !closed {
                    unclosed.push(format!("  {rel}:{}", start + 1));
                }
            }
            let first_marker = test_items.first().map(|&(start, _, _)| start);
            for (i, line) in lines.iter().enumerate() {
                if test_items.iter().any(|&(start, end, _)| i >= start && i < end) {
                    continue; // inside a test item — not shipped
                }
                let code = line.trim_start();
                if code.starts_with("//") {
                    continue; // a doc comment naming `exp` is prose, not a call
                }
                if !code.is_empty()
                    && first_marker.is_some_and(|m| i > m)
                    && !scanned_past_a_test_module.contains(&name)
                {
                    scanned_past_a_test_module.push(name.clone());
                }
                for pat in &banned {
                    if line.contains(pat.as_str()) {
                        found.push(format!("  {rel}:{} {code}", i + 1));
                    }
                }
            }
        }
    }
    // Non-vacuity, aimed at the failure this scan is most likely to have: `src/` NESTS here
    // (`strategy/`), so a walk that stopped at the top level would still open ~45 files and report
    // a confident zero while never reading `maker_params.rs` — the one file with a MEASURED
    // cross-platform divergence in its history.
    for must in ["fair.rs", "maker_params.rs", "scalar.rs"] {
        assert!(
            scanned.iter().any(|s| s == must),
            "the scan never opened {must}, so an empty result proves nothing about the files this \
             gate exists for. Scanned {} files.",
            scanned.len()
        );
    }
    assert!(
        unclosed.is_empty(),
        "a test item's closing line could not be located, so everything below it went UNSCANNED — \
         the exact hole a `break` leaves, wearing a different cause. See `cfg_test_ranges`: the end \
         is the item's own indentation followed by a lone `}}`, or a `;` for a `mod NAME;` \
         declaration.\n{}",
        unclosed.join("\n")
    );
    // The non-vacuity assertion for the RANGE walk, and the one a `break` could not pass. Both
    // files named carry real production code BELOW a test module — measured 2026-08-29 at 180 and
    // 42 non-blank lines. If this goes red, the walk has reverted to treating the first marker as
    // the end of the shipped file.
    for must in ["maker_params.rs", "mod.rs"] {
        assert!(
            scanned_past_a_test_module.iter().any(|s| s == must),
            "no production line below {must}'s first test marker was scanned, so this gate has \
             gone blind to the region below every mid-file test module — which in this crate is \
             where `HorizonMode`, `KappaMode` and `MockBroker` live. Scanned past a test module: \
             {scanned_past_a_test_module:?}"
        );
    }
    assert!(
        found.is_empty(),
        "production code must call the `libm` CRATE rather than `f64`'s platform-libm methods, so a \
         POSTED QUOTE (`fair::p_up`) and an ORDER SIZE (`maker_params::ladder_size_mult`) do not \
         depend on which box computed them. BOTH spellings are banned, `x.exp()` and `f64::exp(x)`: \
         same inherent method, same libcall (see `banned_needles`). `powi` is banned too, and in \
         this crate that is the MEASURED case rather than a precaution — `ladder_size_mult` hashed \
         differently on MSVC and glibc as `ratio.powi(k)`. Where a base is the literal 10 or 2 the \
         cure is a MULTIPLICATION rather than `libm`; where it is a runtime f64 the cure is \
         `libm::pow`:\n{}",
        found.join("\n")
    );
}
