//! GUI indicator adapter — the per-window paint/colour state (`Active`) layered
//! over the shared `vike-indicators` compute core.
//!
//! The registry, the two orthogonal axes (picker [`Category`] vs render placement
//! [`RenderKind`]/[`OutputStyle`]) and the streaming [`Indicator`] trait ALL come
//! from `vike-indicators` (one source of truth, parity-gated against the Python
//! oracle `core/indicators/base.py`) and are re-exported here so the chart UI keeps
//! its `crate::indicators::…` paths. Only the egui colours + visibility and the
//! GUI-`Bar`→`vike_model::Bar` conversion live in this crate — that's paint state,
//! which has no place in the Qt-free compute core.
//!
//! ## Streaming overlays (why `Active` owns a live [`Indicator`])
//! `vike-indicators` proves `on_bar`-folded == `vectorize`, bit-for-bit. So rather
//! than a full-series `vectorize` every frame, each `Active` keeps a **persistent
//! streaming instance** folded over the **closed prefix only** (closed bars are
//! immutable and append-only), and [`Active::update`] does the cheapest correct
//! thing each frame:
//! - **no-op** when the closed series is unchanged (the common repaint frame),
//! - **[`Active::push_bar`]** — a single `on_bar` — when exactly one bar closed
//!   on top of an unchanged prefix (O(1)/O(window)),
//! - **[`Active::recompute_full`]** — reset + refold — only on a genuine
//!   structural change (first build, data reload, symbol/interval swap).
//!
//! The live *forming* bar — which mutates in place up to ~60×/s and which a
//! streaming fold cannot un-see — never touches the persistent instance: it is
//! previewed each call on a throwaway [`clone_box`], instead of the full-history
//! refold this path used to trigger.
//!
//! ⚠ **That clone is NOT "the tiny streaming state (O(window) bytes)", and a live
//! tick is NOT "microseconds regardless of history depth".** This paragraph said
//! both, and both are false for the ~150 indicators generated by
//! `vike_indicators`' `hist_indicator!`: those stream by history-RECOMPUTE and
//! carry a retained `hist: Vec<Bar>`, so `clone_box` deep-copies it EVERY FRAME.
//! Measured at `vwma`'s registry maximum `period = 400` under the old retention:
//! **4.6 MB and 1006 µs per frame** — 276 MB/s at 60 fps, most of a frame budget,
//! for ONE overlay, before any arithmetic runs.
//!
//! It is now bounded rather than merely smaller: `vike_indicators::keep_for` gives
//! a finite-window kernel `lookback_full + slack` instead of a multiple of it, which
//! is what took that same clone to ~7.8 µs. The claim above was written when every
//! streaming indicator really did carry O(window) state, and it survived the change
//! that made it untrue — the reason this correction names the measurement rather
//! than just softening the wording.
//!
//! ⚠ A USER-written indicator is worse still: its `Indicator` is the Rhai
//! interpreter, so `clone_box().on_bar(..)` is a full `RhaiIndicator` clone plus one
//! script evaluation per frame, and `recompute_full` is O(bars) interpreter calls on
//! the paint thread.
//!
//! Because the fold sequence (closed…, then forming) is exactly `vectorize`'s,
//! the on-screen values, lines, styles, colours and labels are bit-identical to
//! what a full recompute would have drawn — this is purely an efficiency design.
//!
//! [`clone_box`]: vike_indicators::BoxedClone::clone_box

use crate::model::Bar;
use std::sync::OnceLock;

// Metadata + discovery come straight from the compute crate (no local duplicate). `Indicator`,
// `ParamSpec` and `UserFactory` ride along because they are the vocabulary a caller needs to BUILD
// one of the user studies below — without them a shell crate would have to take its own
// `vike-indicators` edge to name the types this module's own API already traffics in.
pub use vike_indicators::{
    Category, Indicator, IndicatorMeta, OutputStyle, ParamSpec, RenderKind, UserFactory, get,
    registry,
};

/// The USER-written studies this process was given — the chart's SECOND lookup path, empty until a
/// binary installs one.
///
/// ## Why a second registry rather than rows in `vike_indicators::registry()`
///
/// `registry()` is the CLOSED, parity-gated built-in catalog: a `OnceLock<Vec<IndicatorMeta>>`
/// built by one function inside a crate that cannot compile a scripting engine. Making it
/// installable-from-outside would turn the one static catalog in this tree into mutable startup
/// state, and — the deciding objection — it would merge two name spaces that are deliberately
/// disjoint: `vike_script::user_indicator_conflict` REFUSES a user file called `sma.rhai` exactly
/// so that `vike_indicators::get("sma")` has one meaning. Every consumer that resolves through
/// `get`/`registry` (`vike_script`'s host bindings, `vike_studio`, backtest seed sizing) would
/// silently start seeing user files.
///
/// So the chart opts in instead: [`get_any`] is the union, [`get`] stays the built-ins alone.
///
/// ⚠ This crate learns NOTHING about scripts. It takes an already-built `&'static IndicatorMeta`
/// whose own (private) factory does the constructing, so the seam is generic — a future
/// non-Rhai user indicator installs through the same door and `vike-chart` gains no dependency.
static USER_STUDIES: OnceLock<Vec<&'static IndicatorMeta>> = OnceLock::new();

/// Installs the user-written studies, once per process, at startup.
///
/// Same shape and the same reasoning as `vike_script::install_user_indicators`: a BINARY resolves
/// the directory and does the I/O, then hands over already-built descriptors. A second call is an
/// `Err` naming both counts rather than silently keeping or replacing the first set — two callers
/// believing they own this would both be wrong somewhere.
///
/// The rejections, all checked BEFORE anything is stored (so a bad batch installs nothing):
///
/// - a row that is not [`IndicatorMeta::is_user`] — a built-in smuggled into the user list would
///   appear twice in the picker and, worse, would make "is this mine?" a question about which list
///   it came from rather than about the row itself;
/// - a name already taken by a built-in. [`get_any`] resolves built-ins FIRST, so such a row would
///   simply never be constructed — it would sit in the picker, add a study, and plot the BUILT-IN.
///   `vike_script::user_indicator_conflict` already refuses this at load; refusing it here too is
///   what makes the guarantee hold for any other installer.
/// - two rows in the SAME batch claiming one name. `get_any` finds the first, so the second is a
///   decoy: a distinct picker row that silently adds the first one's indicator. That is the
///   shadowing bug above wearing user clothes, and the argument for refusing it is identical —
///   `vike_script::load_user_indicators` already cannot produce one (a stem is a filename, and a
///   collision is a diagnostic there), which is exactly why this seam has to check it: the door is
///   generic, and the guarantee must not rest on the one installer that happens to be careful.
pub fn install_user_studies(studies: Vec<&'static IndicatorMeta>) -> Result<(), String> {
    for (i, s) in studies.iter().enumerate() {
        if !s.is_user() {
            return Err(format!(
                "`{}` is a built-in indicator, not a user study; installing it here would list it \
                 twice and make `is_user` disagree with which registry it came from",
                s.name
            ));
        }
        if get(s.name).is_some() {
            return Err(format!(
                "`{}` is already the name of a built-in indicator; `get_any` resolves built-ins \
                 first, so this study would be pickable and yet never plot its own values",
                s.name
            ));
        }
        if studies[..i].iter().any(|e| e.name == s.name) {
            return Err(format!(
                "`{}` is claimed by two studies in one install; `get_any` answers with the first, \
                 so the second would be a picker row that silently adds the first one's indicator",
                s.name
            ));
        }
    }
    let n = studies.len();
    USER_STUDIES.set(studies).map_err(|_| {
        format!(
            "user studies are already installed ({} of them); install_user_studies is a \
             once-per-process call made by a binary at startup, and this second call of {n} would \
             have silently done nothing",
            USER_STUDIES.get().map(Vec::len).unwrap_or(0)
        )
    })
}

/// The installed user studies, in install order. Empty when a binary installed none — which is the
/// ordinary state, and is what keeps the picker byte-identical for anyone who has never written one.
pub fn user_registry() -> &'static [&'static IndicatorMeta] {
    USER_STUDIES.get().map(Vec::as_slice).unwrap_or(&[])
}

/// Look up an indicator by name across BOTH registries — the chart's resolution rule.
///
/// Built-ins win. That ordering is not a tie-break preference, it is the guarantee that no user
/// file can change what an existing workspace's `"sma"` means; [`install_user_studies`] refuses a
/// shadowing name outright so the ordering never has to be observed.
///
/// ⚠ An unknown name still answers `None`, exactly as [`get`] does. That is load-bearing for
/// persistence: a workspace stores studies BY NAME, and `WinState::add_indicator` is already a
/// silent no-op for a name it cannot resolve — so a saved workspace naming a user indicator whose
/// file has since been deleted, renamed or broken degrades the same way an unknown built-in
/// always has, instead of panicking on a missing prototype.
pub fn get_any(name: &str) -> Option<&'static IndicatorMeta> {
    get(name).or_else(|| user_registry().iter().copied().find(|m| m.name == name))
}

/// Convert one GUI bar-index render [`Bar`] to the compute `vike_model::Bar`:
/// `o/h/l/c/v` → `open/high/low/close/volume`, `ot` (open-time ms) → `ts`;
/// tick-derived fields (funding/bid/ask/symbol) are `None` for OHLCV render bars.
fn to_model_bar(b: &Bar) -> vike_model::Bar {
    vike_model::Bar {
        ts: b.ot,
        open: b.o,
        high: b.h,
        low: b.l,
        close: b.c,
        volume: b.v,
        funding: None,
        bid: None,
        ask: None,
        symbol: None,
    }
}

/// TradingView "Inputs → Source" parity: the price series an indicator computes
/// off, instead of always `close`. `Close` (the default) is a **bit-identical
/// no-op** — [`Source::value`] returns `bar.c` unchanged, so the streaming path and
/// the vike-indicators parity gate stay byte-for-byte identical. The derived series
/// (`Hl2`/`Hlc3`/`Ohlc4`) are the standard TradingView midpoint/typical/average
/// prices. Applied purely in this GUI adapter layer (see [`Active::model_bar`]) —
/// the parity-gated compute core is never touched.
#[derive(Clone, Copy, PartialEq, Eq, Default, Debug)]
pub enum Source {
    #[default]
    Close,
    Open,
    High,
    Low,
    /// `(high + low) / 2` — TradingView `hl2` (median price).
    Hl2,
    /// `(high + low + close) / 3` — TradingView `hlc3` (typical price).
    Hlc3,
    /// `(open + high + low + close) / 4` — TradingView `ohlc4` (average price).
    Ohlc4,
}

impl Source {
    pub const ALL: [Source; 7] = [
        Source::Close,
        Source::Open,
        Source::High,
        Source::Low,
        Source::Hl2,
        Source::Hlc3,
        Source::Ohlc4,
    ];
    pub fn label(self) -> &'static str {
        match self {
            Source::Close => "Close",
            Source::Open => "Open",
            Source::High => "High",
            Source::Low => "Low",
            Source::Hl2 => "hl2",
            Source::Hlc3 => "hlc3",
            Source::Ohlc4 => "ohlc4",
        }
    }
    /// The chosen price for one GUI render [`Bar`]. `Close` returns `bar.c`
    /// unchanged (the identity — keeps the default path bit-identical).
    pub fn value(&self, bar: &Bar) -> f64 {
        match self {
            Source::Close => bar.c,
            Source::Open => bar.o,
            Source::High => bar.h,
            Source::Low => bar.l,
            Source::Hl2 => (bar.h + bar.l) / 2.0,
            Source::Hlc3 => (bar.h + bar.l + bar.c) / 3.0,
            Source::Ohlc4 => (bar.o + bar.h + bar.l + bar.c) / 4.0,
        }
    }
}

/// TradingView "symbol" input parity: the FOREIGN symbol an indicator computes
/// off, instead of the window's own primary. `None` (the default) means "this
/// chart's symbol" — a **bit-identical no-op**: the study folds over the primary
/// bars exactly as before this field existed, so the vike-indicators parity gate
/// stays byte-for-byte identical. When set, `vike-app` looks up that `(venue,
/// symbol)`'s live [`crate::model::ChartState`] (subscribing its feed like a
/// Compare overlay), re-indexes its bars onto the primary timeline via
/// [`align_source_bars`], and folds the study over THOSE — so an RSI of ETHUSDT
/// can display on a BTCUSDT chart. Pure data (`vike-chart` never does the lookup —
/// it has no cross-symbol registry); it is the study's stored source-of-truth,
/// carried on [`Active`], edited in the ƒx picker, and persisted in the workspace.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct SourceSymbol {
    /// Data venue (`"binance"`/`"bybit"`/`"okx"`) — the same string `WinState::venue`
    /// and `vike_app_core::workspace::series_key` use to route the feed.
    pub venue: String,
    /// Instrument symbol on that venue (e.g. `"ETHUSDT"`).
    pub symbol: String,
}

/// Foreign-source study (TradingView "symbol" input): re-index a foreign symbol's
/// bar series onto the PRIMARY chart's timeline so an indicator folded over the
/// result is index-aligned to the primary x-axis (one value per primary bar) —
/// exactly like a same-symbol study, so the renderer needs no special case. For
/// each primary bar, the aligned bar is the foreign bar whose open-time (`ot`) is
/// the latest at-or-before the primary bar's `ot` (a forward-fill: same-interval
/// feeds are ~1:1 by `ot`, so this is an EXACT match on almost every bar, carrying
/// the previous foreign bar forward only across a foreign gap). Primary bars BEFORE
/// the first foreign bar clamp to that first foreign bar (a short flat lead-in until
/// the foreign history covers the range). Each aligned bar carries the FOREIGN
/// `o/h/l/c/v/ot` (so both the fold and its O(1) change-probe fingerprint track the
/// foreign data) but keeps the PRIMARY bar's `t` (bar index x), so nothing about the
/// primary x-placement shifts. Empty `foreign` ⇒ empty result ⇒ the study renders
/// nothing until the foreign feed syncs. Pure, O(P + F) — both inputs are `ot`-sorted
/// ascending (the ChartState invariant).
pub fn align_source_bars(primary: &[Bar], foreign: &[Bar]) -> Vec<Bar> {
    if foreign.is_empty() {
        return Vec::new();
    }
    let mut out = Vec::with_capacity(primary.len());
    let mut j = 0usize; // foreign cursor (monotonic — both slices are ot-ascending)
    for p in primary {
        // advance while the NEXT foreign bar still opens at-or-before this primary bar
        while j + 1 < foreign.len() && foreign[j + 1].ot <= p.ot {
            j += 1;
        }
        let mut b = foreign[j]; // clamps to foreign[0] for primary bars before it
        b.t = p.t; // keep the primary x-index; foreign OHLCV/ot ride along
        out.push(b);
    }
    out
}

/// O(1) fingerprint of a render bar's mutable fields (open-time + OHLCV bit-patterns,
/// FNV-1a). Lets [`Active::update`] tell "same series" from "one bar appended" from
/// "the last bar changed in place" without rehashing the whole window each frame.
fn bar_fp(b: &Bar) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for x in
        [b.ot as u64, b.o.to_bits(), b.h.to_bits(), b.l.to_bits(), b.c.to_bits(), b.v.to_bits()]
    {
        h ^= x;
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    h
}

/// Per-plot dash pattern (TradingView "Style" parity — the line-style picker next
/// to each plot's colour): `Solid` / `Dashed` / `Dotted`. Maps in `render.rs` onto
/// `egui_plot::LineStyle` (`solid()` / `dashed_loose()` / `dotted_dense()`) and
/// applies to Line/Band-style output lines. `Solid` (the default) keeps the render
/// path pixel-identical to before this field existed.
#[derive(Clone, Copy, PartialEq, Eq, Default, Debug)]
pub enum LineDash {
    #[default]
    Solid,
    Dashed,
    Dotted,
}

impl LineDash {
    pub const ALL: [LineDash; 3] = [LineDash::Solid, LineDash::Dashed, LineDash::Dotted];
    pub fn label(self) -> &'static str {
        match self {
            LineDash::Solid => "Solid",
            LineDash::Dashed => "Dashed",
            LineDash::Dotted => "Dotted",
        }
    }
}

/// One indicator output line's paint state (chart-UX bundle T8 — was an inline
/// `(name, series, style, color)` tuple): the streaming `series` buffer plus the
/// user-tunable paint attributes. `name`/`style` are static (from the `OutSpec`);
/// `color` seeds from the rotation [`PALETTE`] and `width` from a kind/style
/// default ([`default_width`]) — both then live-editable via the settings dialog.
/// `series` alone rebuilds on a refold; `color`/`width`/`line_style` survive a
/// reconfigure (see [`Active::set_params`]). T10 will persist `color`+`width`.
pub struct OutputLine {
    pub name: &'static str,
    /// streaming buffer — index-aligned to the chart bars, one value per `on_bar`.
    pub series: Vec<f64>,
    pub style: OutputStyle,
    pub color: egui::Color32,
    /// stroke width for Line/Band styles (Dots use a fixed radius, Histograms a
    /// fixed bar width, so their stored `width` is inert — kept for uniformity).
    pub width: f32,
    /// Per-plot dash pattern (TradingView "Style" line-style picker). Default
    /// [`LineDash::Solid`] — pixel-identical to the pre-field render path.
    pub line_style: LineDash,
    /// Per-plot show/hide (TradingView "Style" parity): `false` skips this line in
    /// the renderer without removing the indicator. Default `true`.
    pub visible: bool,
}

/// One oscillator reference level's paint state (TradingView RSI "Style" parity —
/// each of `spec.bands`' levels, e.g. RSI 30/50/70, gets its OWN colour + show
/// toggle instead of one shared colour). `value` is the static level from
/// `spec.bands`; `color` seeds from the historic `Color32::from_gray(80)` gray and
/// `show` from `true`, so the default render is pixel-identical to the pre-per-level
/// single-`band_color` path. Both are then live-editable via the settings dialog.
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct BandLevel {
    pub value: f64,
    pub color: egui::Color32,
    pub show: bool,
}

/// Default translucent fill colours for the overbought (above the top band) /
/// oversold (below the bottom band) zones — TradingView RSI "Style" parity. Green
/// above / red below at a low alpha so the plotted line stays legible through them.
/// Non-const (`from_rgba_unmultiplied` premultiplies at runtime), so returned from
/// helpers rather than stored as consts.
pub fn ob_fill_default() -> egui::Color32 {
    egui::Color32::from_rgba_unmultiplied(76, 175, 80, 30) // green wash
}
pub fn os_fill_default() -> egui::Color32 {
    egui::Color32::from_rgba_unmultiplied(239, 83, 80, 30) // red wash
}

/// Default stroke width for a freshly-built output line — today's `render.rs`
/// values preserved pixel-for-pixel: overlay bands `1.0`, other overlay lines
/// `1.5`, oscillator lines `1.4`. Dots/Histograms ignore width (fixed radius /
/// bar width), so their value is cosmetic.
fn default_width(kind: RenderKind, style: OutputStyle) -> f32 {
    match kind {
        RenderKind::Overlay if style == OutputStyle::Band => 1.0,
        RenderKind::Overlay => 1.5,
        RenderKind::Oscillator => 1.4,
    }
}

/// Per-window active indicator instance — the GUI paint state wrapping a
/// `vike-indicators` [`IndicatorMeta`]: its output lines (one per `OutSpec`), each
/// carrying a render style + rotation colour + width, plus a visibility toggle and
/// the live parameter values. Holds a **persistent streaming [`Indicator`]** folded
/// over `committed_len` leading bars so a live append costs one `on_bar`, not a full
/// `vectorize` (see the module docs).
pub struct Active {
    pub uid: u64,
    pub spec: &'static IndicatorMeta,
    /// computed output lines (one per `spec.outputs`), each a series buffer + its
    /// editable paint attributes (see [`OutputLine`]).
    pub outputs: Vec<OutputLine>,
    /// live parameter values, index-aligned to `spec.params`; seeded from each
    /// `ParamSpec::default` and reconfigured via [`Active::set_params`]. Empty for
    /// paramless indicators (Vwap, Obv).
    pub params: Vec<f64>,
    pub visible: bool,
    /// Show/hide this oscillator's reference band levels (TradingView "Style" parity):
    /// master gate over `bands` in the renderer. Default `true`; inert for indicators
    /// with no bands (`bands` empty).
    pub show_bands: bool,
    /// Per-level reference bands (TradingView RSI "Style" parity), seeded from
    /// `spec.bands` — each level carries its OWN editable colour + show toggle (was a
    /// single shared `band_color`). Defaults (gray, show=true) keep the render
    /// pixel-identical until recoloured. Empty for indicators with no bands.
    pub bands: Vec<BandLevel>,
    /// Shade the overbought zone (above the top band) green and the oversold zone
    /// (below the bottom band) red with a translucent fill (TradingView RSI "Style"
    /// parity). Default `false` — so the pane is pixel-identical to today until
    /// enabled. Inert for indicators with no bands.
    pub show_ob_os_fill: bool,
    /// Overbought / oversold fill colours (see [`ob_fill_default`]/[`os_fill_default`]),
    /// live-editable via the settings dialog. Only painted when `show_ob_os_fill`.
    pub ob_fill: egui::Color32,
    pub os_fill: egui::Color32,
    /// TradingView "Inputs → Source" (chart source selector): the price series this
    /// indicator computes off, applied in the GUI adapter's [`Active::model_bar`]
    /// conversion (NOT the parity-gated compute core). Default [`Source::Close`] is a
    /// bit-identical no-op — the streaming fold and every vike-indicators parity test
    /// stay byte-for-byte unchanged. Changing it triggers a refold (see the vike-app
    /// apply path), exactly like a param change.
    pub source: Source,
    /// TradingView "symbol" input: the FOREIGN symbol this study computes off
    /// instead of the window's own primary. `None` (the default) = the primary —
    /// **bit-identical** to the pre-field path (the compute core never sees this
    /// field; `vike-app` reads it to decide which bars to fold). When `Some`,
    /// `vike-app` feeds this `Active` the foreign symbol's bars re-indexed onto the
    /// primary timeline (see [`align_source_bars`]) — so the fold, the series and
    /// the render all stay index-aligned to the primary x-axis. Editing it (in the
    /// ƒx picker) triggers a structural refold next frame, exactly like a param or
    /// [`Source`] change. See [`SourceSymbol`].
    pub source_symbol: Option<SourceSymbol>,
    /// live streaming instance, folded over exactly `committed_len` leading bars.
    ind: Box<dyn Indicator>,
    /// number of bars folded into `ind` and reflected in every `outputs[*].series`.
    committed_len: usize,
    /// fingerprints of the first and last committed bars — the O(1) change probe.
    fp_first: u64,
    fp_last: u64,
    /// The forming-bar preview, memoized on that bar's fingerprint.
    ///
    /// ⚠ **The preview is the dominant per-frame cost of an overlay, and it was recomputed on every
    /// frame whether or not a tick had arrived.** [`Active::update`]'s preview clones the indicator
    /// and folds one bar through it; for a `hist_indicator!` indicator that fold is
    /// `vike_indicators`' `stream_tail`, which RE-RUNS THE WHOLE BATCH KERNEL over all retained
    /// history and keeps the last element. Measured on the CI box at period 1000, `high_low_52w` costs
    /// **534 µs per frame** — at 60 fps that is 3.2% of a core for one overlay, spent identically
    /// each frame while the forming bar sits unchanged between ticks.
    ///
    /// A chart repaints far more often than a venue ticks, so most of those frames recompute a value
    /// that cannot have moved. `None` means "no valid preview cached".
    ///
    /// ⚠ **Validity has TWO conditions, and only one of them is the forming bar.** The cached value
    /// also depends on the committed state (`ind`, `params`, `source`, `source_symbol`), so anything
    /// that moves those must invalidate. Every such path funnels through
    /// [`Active::recompute_full`] — `set_params` calls it, `vike-app`'s Source apply calls it, and
    /// `update`'s own structural branch calls it — which is why the invalidation lives there rather
    /// than being restated at each call site. ⚠ It CANNOT be keyed on the closed-prefix
    /// fingerprints alone: `recompute_full` re-derives the SAME `fp_first`/`fp_last` from the same
    /// bars, so a param or source change leaves `prefix_unchanged` TRUE on the next frame and a
    /// prefix-keyed cache would serve a stale preview.
    forming: Option<(u64, Vec<f64>)>,
}

// vike _OVERLAY_COLORS rotation (chart.py:31) — BLUE, purple, cyan, green, pink,
// then the amber smoothing-MA default.
const PALETTE: [egui::Color32; 6] = [
    egui::Color32::from_rgb(87, 165, 255),
    egui::Color32::from_rgb(168, 85, 247),
    egui::Color32::from_rgb(38, 198, 218),
    egui::Color32::from_rgb(102, 187, 106),
    egui::Color32::from_rgb(236, 64, 122),
    egui::Color32::from_rgb(245, 166, 35),
];

impl Active {
    pub fn new(uid: u64, spec: &'static IndicatorMeta, bars: &[Bar]) -> Self {
        // Per-line paint metadata (name/style/colour/width) is built once; only the
        // `series` buffer grows/rebuilds thereafter (colour/width survive reconfig).
        let outputs = spec
            .outputs
            .iter()
            .enumerate()
            .map(|(i, o)| OutputLine {
                name: o.name,
                series: Vec::new(),
                style: o.style,
                color: PALETTE[i % PALETTE.len()],
                width: default_width(spec.kind, o.style),
                line_style: LineDash::Solid,
                visible: true,
            })
            .collect();
        // Params seed from the registry defaults (`make()` == `make_with(defaults)`
        // bit-for-bit, so the initial `ind` below stays consistent with `params`).
        let params = spec.params.iter().map(|p| p.default).collect();
        // Per-level bands seed from `spec.bands`, each in the historic gray + shown —
        // pixel-identical to the old single `band_color` path until recoloured.
        let bands = spec
            .bands
            .iter()
            .map(|&value| BandLevel { value, color: egui::Color32::from_gray(80), show: true })
            .collect();
        let mut a = Active {
            uid,
            spec,
            outputs,
            params,
            visible: true,
            show_bands: true,
            bands,
            show_ob_os_fill: false,
            ob_fill: ob_fill_default(),
            os_fill: os_fill_default(),
            source: Source::Close, // identity — bit-identical to the pre-source fold
            source_symbol: None,   // primary symbol — bit-identical to the pre-field fold

            // `build`, not the old `(spec.make)()`: a USER study's constructor is a closure that
            // clones a compiled prototype, which a bare `fn` pointer cannot reach. For a built-in
            // `build` IS `(spec.make)()` — see `IndicatorMeta::build`, and the
            // `no_builtin_row_carries_a_factory` gate that keeps that arm the only one they take.
            ind: spec.build(),
            committed_len: 0,
            fp_first: 0,
            fp_last: 0,
            forming: None,
        };
        a.recompute_full(bars);
        a
    }

    /// Per-frame entry: keep the overlay in sync with the chart series as cheaply
    /// as possible. `closed` is the immutable append-only prefix; `forming` is the
    /// live bar still mutating in place (if any).
    ///
    /// Two tiers (see the module docs):
    /// - **committed** — the persistent fold advances over `closed` only: no-op on
    ///   an unchanged series, one streamed [`push_bar`] when exactly one bar closed
    ///   on top of an unchanged prefix, full refold on any structural change.
    ///   Matching the head **and** boundary fingerprints proves the committed
    ///   prefix is unchanged, making the single-`on_bar` fast path exact.
    /// - **speculative** — the forming bar is previewed each call on a throwaway
    ///   [`clone_box`] of the streaming state and appended to the output buffers
    ///   WITHOUT committing, so a forming-bar tick costs O(state), not O(history).
    ///   The fold sequence (closed… then forming) is exactly `vectorize`'s, so the
    ///   preview stays bit-identical to a full rebuild.
    ///
    /// [`push_bar`]: Active::push_bar
    /// [`clone_box`]: vike_indicators::BoxedClone::clone_box
    pub fn update(&mut self, closed: &[Bar], forming: Option<&Bar>) {
        let n = closed.len();
        let fp_first_now = closed.first().map_or(0, bar_fp);
        let fp_last_now = closed.last().map_or(0, bar_fp);

        let prefix_unchanged =
            n == self.committed_len && fp_first_now == self.fp_first && fp_last_now == self.fp_last;
        if prefix_unchanged {
            // drop last frame's speculative value (if any); the commit stands.
            self.truncate_to_committed();
        } else if n == self.committed_len + 1
            && self.committed_len > 0
            && fp_first_now == self.fp_first
            && bar_fp(&closed[self.committed_len - 1]) == self.fp_last
        {
            // exactly one bar closed on top of an unchanged prefix → stream it.
            // (`push_bar` clears the forming memo itself — see its doc for why the invariant lives
            // in the callee rather than being restated at each call site.)
            self.truncate_to_committed();
            self.push_bar(&closed[self.committed_len]);
        } else {
            // structural change (first build, reload, symbol swap) → refold == `vectorize`.
            self.recompute_full(closed);
        }

        // Speculative forming-bar preview on a throwaway clone — never committed, and MEMOIZED on
        // the forming bar's fingerprint. See the `forming` field for why this dominates the frame
        // and why the memo cannot be keyed on the closed-prefix probe.
        if let Some(f) = forming {
            let fp = bar_fp(f);
            if self.forming.as_ref().map(|(k, _)| *k) != Some(fp) {
                let vals = self.ind.clone_box().on_bar(&self.model_bar(f));
                self.forming = Some((fp, vals));
            }
            // `unwrap` is total: the branch above stores `Some` whenever it does not already match.
            let vals = &self.forming.as_ref().unwrap().1;
            for (k, slot) in self.outputs.iter_mut().enumerate() {
                slot.series.push(vals.get(k).copied().unwrap_or(f64::NAN));
            }
        } else {
            // No forming bar this frame: drop the memo rather than let it survive a
            // forming -> none -> forming cycle, where the reappearing bar could hash equal to the
            // old one while the committed state moved underneath it.
            self.forming = None;
        }
    }

    /// Trim every output buffer back to the committed prefix, discarding the
    /// speculative forming-bar value appended by the previous [`update`] call.
    ///
    /// [`update`]: Active::update
    fn truncate_to_committed(&mut self) {
        for slot in &mut self.outputs {
            slot.series.truncate(self.committed_len);
        }
    }

    /// Convert one GUI [`Bar`] to the compute `vike_model::Bar`, applying the
    /// TradingView "Source" selector (chart source selector): the model bar's
    /// **`close` is replaced by [`Source::value`]** (the chosen price series) while
    /// `open`/`high`/`low` stay as-is. MOST single-series indicators (SMA, EMA, RSI,
    /// MACD, …) read `close`, so this makes them compute off the source. **v1
    /// limitation:** range/OHLC indicators (ATR, Stochastic, PSAR, …) still read the
    /// TRUE `high`/`low`, so a non-`Close` source only shifts their `close` input —
    /// acceptable for a first cut. When `source == Close` this is the exact identity
    /// of the free `to_model_bar` (`Source::value` returns `bar.c`), so the streaming
    /// fold and the vike-indicators parity gate stay bit-for-bit unchanged.
    fn model_bar(&self, b: &Bar) -> vike_model::Bar {
        let mut mb = to_model_bar(b);
        mb.close = self.source.value(b);
        mb
    }

    /// Fold ONE freshly-appended bar through the streaming `on_bar` and push its
    /// value onto each output line — O(1) or O(window), never a full recompute. The
    /// caller must guarantee `bar` truly follows the `committed_len` bars already
    /// folded (that is what [`update`] verifies); otherwise use [`recompute_full`].
    ///
    /// [`update`]: Active::update
    /// [`recompute_full`]: Active::recompute_full
    pub fn push_bar(&mut self, bar: &Bar) {
        // ⚠ Advancing `ind` invalidates the forming-preview memo, and the invalidation belongs HERE
        // rather than at the call site. This method is `pub` and its own doc invites external use
        // ("the caller must guarantee `bar` truly follows the `committed_len` bars already folded"),
        // so a caller that honours that contract exactly would otherwise still corrupt the memo:
        // `push_bar` leaves `fp_first` untouched and sets `fp_last` to the new bar, so the NEXT
        // `update` with the extended slice sees `prefix_unchanged == true`, takes neither clearing
        // branch, and serves a preview folded through the PREVIOUS committed state.
        //
        // Nothing outside this file calls it today (the only three call sites are `update`'s
        // one-bar branch, this definition, and `recompute_full`'s refold loop), so that was a latent
        // trap rather than a live defect — which is exactly the kind that survives review.
        self.forming = None;
        let mb = self.model_bar(bar);
        let vals = self.ind.on_bar(&mb);
        for (k, slot) in self.outputs.iter_mut().enumerate() {
            // on_bar arity always equals outputs.len() (registry-gated); the fallback
            // just keeps buffers length-aligned if that ever failed to hold.
            slot.series.push(vals.get(k).copied().unwrap_or(f64::NAN));
        }
        self.committed_len += 1;
        if self.committed_len == 1 {
            self.fp_first = bar_fp(bar);
        }
        self.fp_last = bar_fp(bar);
    }

    /// Rebuild every output line from scratch: reset the streaming instance and
    /// refold `on_bar` over the whole window. Bit-identical to `vectorize(bars)` (the
    /// crate's parity gate) and leaves `ind` folded over exactly `bars`, so a later
    /// [`push_bar`] continues correctly. Use on a full data reload / symbol change /
    /// indicator (re)config.
    ///
    /// [`push_bar`]: Active::push_bar
    pub fn recompute_full(&mut self, bars: &[Bar]) {
        // ⚠ THE ONE invalidation point for the forming-preview memo, and it must stay here.
        // Every way the preview can move without the closed prefix moving — a param change
        // (`set_params`), a `Source` change (`vike-app`'s apply path), a source-symbol change —
        // routes through this method, and each of them re-derives the SAME `fp_first`/`fp_last`
        // from the same bars. So the prefix probe cannot see them, and a memo keyed on it alone
        // would serve a stale value.
        self.forming = None;
        self.ind.reset();
        for slot in &mut self.outputs {
            slot.series.clear();
        }
        self.committed_len = 0;
        self.fp_first = 0;
        self.fp_last = 0;

        // ⚠ **The bar-by-bar fold is QUADRATIC for a history-recompute indicator, and it hangs the
        // GUI on a long chart.** `push_bar` calls `on_bar`, which for every `hist_indicator!`
        // indicator is `vike_indicators`' `stream_tail`: re-run the whole batch kernel over all
        // retained history and keep the last element. Folding `n` bars that way is
        // O(n x retained x period). Measured: at 200,000 bars with `high_low_52w` at period 1000
        // this sat for OVER AN HOUR before being killed — a user who loads a long chart and adds
        // that indicator gets a frozen window, with no error and no progress.
        //
        // The batch path answers the same question in ONE pass, O(bars x period), and it is the
        // PARITY REFERENCE: `vike_indicators`' whole contract is `on_bar`-fold == `vectorize`
        // bit-for-bit, gated by `tests/parity.rs`. So the series is taken from `vectorize`, and the
        // fold is used only to bring `ind` into its streaming state.
        //
        // ⚠ That state fold is over the RETAINED TAIL, not the whole history, and the equivalence
        // is exactly what `every_trimmed_indicator_is_truncation_invariant` already proves:
        // `last(vectorize(&bars[len - retained..])) == vectorize(&bars)[len - 1]` for every
        // `retained` the drain can leave. `keep_for` is that bound. It still costs O(keep^2 x
        // period) — ~10^9 for the deepest case rather than ~10^13, a stall instead of a hang — and
        // going further would need the kernels to expose a last-value entry point.
        //
        // ⚠ ONLY for `trims_history()` indicators. A hand-written incremental impl
        // (`vike-indicators`' `base.rs`: `obv`, `vwap`, `sma`, …) folds from bar zero and is
        // path-dependent by construction — seeding it from a suffix would be a WRONG NUMBER, and
        // those are O(1) per bar anyway, so the old path is both required and cheap for them.
        if self.ind.trims_history() && !bars.is_empty() {
            let model: Vec<vike_model::Bar> = bars.iter().map(|b| self.model_bar(b)).collect();
            let cols = self.ind.vectorize(&model);
            for (k, slot) in self.outputs.iter_mut().enumerate() {
                slot.series = cols.get(k).cloned().unwrap_or_else(|| vec![f64::NAN; bars.len()]);
            }
            let keep = vike_indicators::keep_for(self.ind.lookback_full(), self.ind.window_reach());
            for mb in &model[model.len().saturating_sub(keep)..] {
                self.ind.on_bar(mb);
            }
            self.committed_len = bars.len();
            self.fp_first = bar_fp(&bars[0]);
            self.fp_last = bar_fp(&bars[bars.len() - 1]);
        } else {
            for b in bars {
                self.push_bar(b);
            }
        }
    }

    /// Reconfigure this indicator to a new parameter set and refold over the
    /// closed bars (chart-UX bundle T8). Stores `p`, then **rebuilds** the
    /// streaming instance via `spec.build_with(&p)` — NOT `reset()`, which
    /// preserves the OLD instance's params — and finally `recompute_full`s the
    /// series. The result is bit-identical to a fresh `Active` folded at `p`
    /// (the reconfig parity gate, `tests::set_params_refold_matches_fresh_build`).
    ///
    /// Only `series`+`ind` change: the per-line `color`/`width` (possibly
    /// user-edited in the settings dialog) are left untouched. `bars_closed`
    /// is the immutable closed prefix; the forming-bar preview re-runs next
    /// [`Active::update`] on the new `ind`.
    pub fn set_params(&mut self, p: Vec<f64>, bars_closed: &[Bar]) {
        self.ind = self.spec.build_with(&p);
        self.params = p;
        self.recompute_full(bars_closed);
    }

    pub fn is_overlay(&self) -> bool {
        self.spec.kind == RenderKind::Overlay
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn gb(i: usize, c_shift: f64) -> Bar {
        let base = 100.0 + (i as f64 * 0.31).sin() * 3.0;
        Bar {
            t: i as f64,
            ot: 1_700_000_000_000 + i as i64 * 60_000,
            o: base,
            h: base + 1.0 + c_shift.abs(),
            l: base - 1.0,
            c: base + c_shift,
            v: 500.0 + i as f64,
        }
    }

    fn closed_bars(n: usize) -> Vec<Bar> {
        (0..n).map(|i| gb(i, 0.3)).collect()
    }

    /// Oracle: a fresh `Active` folded over closed+forming in one go — by the
    /// vike-indicators parity gate this equals `vectorize` bit-for-bit.
    fn oracle(
        spec: &'static IndicatorMeta,
        closed: &[Bar],
        forming: Option<&Bar>,
    ) -> Vec<Vec<f64>> {
        let mut all: Vec<Bar> = closed.to_vec();
        if let Some(f) = forming {
            all.push(*f);
        }
        let a = Active::new(1, spec, &all);
        a.outputs.iter().map(|o| o.series.clone()).collect()
    }

    fn assert_bits_eq(got: &[Vec<f64>], want: &[Vec<f64>], ctx: &str) {
        assert_eq!(got.len(), want.len(), "{ctx}: line count");
        for (li, (g, w)) in got.iter().zip(want.iter()).enumerate() {
            assert_eq!(g.len(), w.len(), "{ctx}: line {li} length");
            for (i, (a, b)) in g.iter().zip(w.iter()).enumerate() {
                assert_eq!(a.to_bits(), b.to_bits(), "{ctx}: line {li}[{i}] diverged: {a} vs {b}");
            }
        }
    }

    /// The live *forming* bar mutating in place must be previewed speculatively —
    /// bit-identical outputs to a full rebuild, WITHOUT recommitting history
    /// (`committed_len` stays at the closed count across every tick).
    #[test]
    fn forming_ticks_preview_without_committing() {
        for name in ["sma", "macd", "psar", "vwap", "obv", "bollinger"] {
            let spec = get(name).unwrap_or_else(|| panic!("{name} not registered"));
            let closed = closed_bars(40);
            let mut a = Active::new(7, spec, &closed);
            for k in 0..5 {
                let forming = gb(40, 0.1 * k as f64 - 0.2);
                a.update(&closed, Some(&forming));
                assert_eq!(a.committed_len, 40, "{name}: forming tick must not commit");
                let got: Vec<Vec<f64>> = a.outputs.iter().map(|o| o.series.clone()).collect();
                assert_bits_eq(&got, &oracle(spec, &closed, Some(&forming)), name);
            }
        }
    }

    /// Bar close: the old forming bar joins the closed prefix (one streamed
    /// `on_bar`, no refold) and a new forming bar previews on top; dropping the
    /// forming bar entirely truncates the preview.
    #[test]
    fn bar_close_promotes_and_new_forming_previews() {
        for name in ["sma", "macd"] {
            let spec = get(name).unwrap_or_else(|| panic!("{name} not registered"));
            let mut closed = closed_bars(40);
            let mut a = Active::new(7, spec, &closed);

            let forming = gb(40, 0.25);
            a.update(&closed, Some(&forming));
            closed.push(forming); // the bar closes exactly as last previewed

            let forming2 = gb(41, -0.1);
            a.update(&closed, Some(&forming2));
            assert_eq!(a.committed_len, 41, "{name}: closed bar must commit");
            let got: Vec<Vec<f64>> = a.outputs.iter().map(|o| o.series.clone()).collect();
            assert_bits_eq(&got, &oracle(spec, &closed, Some(&forming2)), name);

            // no forming bar → outputs shrink back to the committed prefix
            a.update(&closed, None);
            let got: Vec<Vec<f64>> = a.outputs.iter().map(|o| o.series.clone()).collect();
            assert_bits_eq(&got, &oracle(spec, &closed, None), name);
        }
    }

    /// Structural change (history reload / symbol swap shrinking the series)
    /// still falls back to a full refold and stays parity-exact.
    #[test]
    fn structural_change_refolds() {
        let spec = get("sma").unwrap();
        let closed = closed_bars(40);
        let mut a = Active::new(7, spec, &closed);
        let shorter = closed_bars(25);
        a.update(&shorter, None);
        assert_eq!(a.committed_len, 25);
        let got: Vec<Vec<f64>> = a.outputs.iter().map(|o| o.series.clone()).collect();
        assert_bits_eq(&got, &oracle(spec, &shorter, None), "sma shrink");
    }

    /// Independent oracle for a *reconfigured* indicator: fold a fresh
    /// `make_with(name, p)` instance straight through `on_bar` over `bars`,
    /// one buffer per output line. This path does NOT touch `Active::set_params`,
    /// so comparing against it proves `set_params` truly applies `p` — a
    /// `reset()`-in-place reconfig would silently keep the old params and diverge.
    fn fold_with_params(name: &str, p: &[f64], bars: &[Bar]) -> Vec<Vec<f64>> {
        let nlines = get(name).unwrap().outputs.len();
        let mut ind = vike_indicators::make_with(name, p).unwrap();
        let mut lines = vec![Vec::<f64>::new(); nlines];
        for b in bars {
            let vals = ind.on_bar(&to_model_bar(b));
            for (k, line) in lines.iter_mut().enumerate() {
                line.push(vals.get(k).copied().unwrap_or(f64::NAN));
            }
        }
        lines
    }

    /// `set_params` reconfig is bit-identical to a fresh `make_with(p)` fold, and
    /// is PATH-INDEPENDENT: reconfiguring from some *other* params to `p` equals
    /// going straight to `p` (proves the streaming instance is rebuilt via
    /// `make_with`, not `reset()`-in-place which would silently keep the old
    /// params). The reconfig parity invariant — the T8 gate.
    #[test]
    fn set_params_refold_matches_fresh_build() {
        let cases: &[(&str, &[f64])] = &[
            ("sma", &[7.0]),
            ("ema", &[50.0]),
            ("rsi", &[9.0]),
            ("bollinger", &[10.0, 1.5]),
            ("macd", &[5.0, 40.0, 3.0]),
        ];
        for (name, p) in cases {
            let spec = get(name).unwrap();
            let bars = closed_bars(60);
            let want = fold_with_params(name, p, &bars);

            // default → other → p : a path-independent reconfig lands on p's series.
            let mut a = Active::new(1, spec, &bars);
            a.set_params(vec![3.0; p.len()], &bars);
            a.set_params(p.to_vec(), &bars);
            let got: Vec<Vec<f64>> = a.outputs.iter().map(|o| o.series.clone()).collect();
            assert_bits_eq(&got, &want, name);
            assert_eq!(a.params, p.to_vec(), "{name}: params stored");
        }
    }

    /// The chart source selector's parity-safety contract: the DEFAULT
    /// [`Source::Close`] fold is bit-identical to the pre-source path (identity
    /// `model_bar`), and switching to a derived source (`Hlc3`) genuinely moves the
    /// series. Proven for close-reading indicators (SMA/EMA/RSI). Guards the invariant
    /// that keeps the vike-indicators parity gate untouched: Close is a no-op.
    #[test]
    fn source_close_is_identity_and_hlc3_diverges() {
        for name in ["sma", "ema", "rsi"] {
            let spec = get(name).unwrap();
            // c_shift != 0 so hlc3 = (h+l+c)/3 differs from c on every bar.
            let bars = closed_bars(60);

            // Default Active is Close-sourced → identical to the oracle full build.
            let base = Active::new(1, spec, &bars);
            let base_series: Vec<Vec<f64>> =
                base.outputs.iter().map(|o| o.series.clone()).collect();
            assert_bits_eq(&base_series, &oracle(spec, &bars, None), name);
            assert_eq!(base.source, Source::Close, "{name}: default source is Close");

            // Switch to hlc3 + refold → the series must actually change.
            let mut hlc3 = Active::new(1, spec, &bars);
            hlc3.source = Source::Hlc3;
            hlc3.recompute_full(&bars);
            let hlc3_series: Vec<Vec<f64>> =
                hlc3.outputs.iter().map(|o| o.series.clone()).collect();
            let changed = base_series
                .iter()
                .zip(&hlc3_series)
                .any(|(b, h)| b.iter().zip(h).any(|(x, y)| x.to_bits() != y.to_bits()));
            assert!(changed, "{name}: hlc3 source must move the series off close");
        }
    }

    /// [`Source::value`] computes the standard TradingView price series off a GUI bar.
    #[test]
    fn source_value_computes_tradingview_series() {
        let b = Bar { t: 0.0, ot: 0, o: 10.0, h: 20.0, l: 4.0, c: 16.0, v: 0.0 };
        assert_eq!(Source::Close.value(&b), 16.0);
        assert_eq!(Source::Open.value(&b), 10.0);
        assert_eq!(Source::High.value(&b), 20.0);
        assert_eq!(Source::Low.value(&b), 4.0);
        assert_eq!(Source::Hl2.value(&b), (20.0 + 4.0) / 2.0);
        assert_eq!(Source::Hlc3.value(&b), (20.0 + 4.0 + 16.0) / 3.0);
        assert_eq!(Source::Ohlc4.value(&b), (10.0 + 20.0 + 4.0 + 16.0) / 4.0);
    }

    /// A same-interval foreign series aligns 1:1 onto the primary timeline by `ot`,
    /// so a study folded over the aligned bars is EXACTLY a study folded over the
    /// foreign bars directly (only the x-index `t` is re-stamped to the primary's).
    /// This is the core correctness claim of the foreign-source feature.
    #[test]
    fn align_source_one_to_one_when_ots_match() {
        // primary and foreign share the SAME open-times (same interval) but differ in OHLCV.
        let primary: Vec<Bar> = (0..30).map(|i| gb(i, 0.3)).collect();
        let foreign: Vec<Bar> = (0..30)
            .map(|i| {
                let mut b = gb(i, -0.4);
                b.o += 50.0;
                b.h += 50.0;
                b.l += 50.0;
                b.c += 50.0; // a clearly-different price series, same ot grid
                b
            })
            .collect();
        let aligned = align_source_bars(&primary, &foreign);
        assert_eq!(aligned.len(), primary.len());
        for (i, (a, f)) in aligned.iter().zip(&foreign).enumerate() {
            assert_eq!(a.ot, f.ot, "bar {i}: foreign ot carried");
            assert_eq!(a.c.to_bits(), f.c.to_bits(), "bar {i}: foreign close carried");
            assert_eq!(a.t.to_bits(), primary[i].t.to_bits(), "bar {i}: primary x-index kept");
        }
        // Folding SMA over the aligned bars == folding over the foreign bars (t is inert).
        let spec = get("sma").unwrap();
        let a_aligned = Active::new(1, spec, &aligned);
        let a_foreign = Active::new(2, spec, &foreign);
        assert_bits_eq(
            &a_aligned.outputs.iter().map(|o| o.series.clone()).collect::<Vec<_>>(),
            &a_foreign.outputs.iter().map(|o| o.series.clone()).collect::<Vec<_>>(),
            "sma over aligned == over foreign",
        );
    }

    /// A foreign GAP (a missing bar) forward-fills the previous foreign bar; a
    /// primary bar BEFORE the first foreign bar clamps to foreign[0]; the result is
    /// always exactly `primary.len()` long and carries the primary x-indices.
    #[test]
    fn align_source_forward_fills_gaps_and_clamps_lead_in() {
        let mk = |ot: i64, c: f64| Bar { t: 0.0, ot, o: c, h: c, l: c, c, v: 1.0 };
        // primary every 60s from t=0..=300 (6 bars)
        let primary: Vec<Bar> =
            (0..6).map(|i| Bar { t: i as f64, ..mk(i as i64 * 60_000, 10.0 + i as f64) }).collect();
        // foreign STARTS LATE (at 60s) and is MISSING the 120s bar → gap.
        let foreign = vec![
            mk(60_000, 100.0),
            /* gap at 120_000 */ mk(180_000, 300.0),
            mk(240_000, 400.0),
        ];
        let aligned = align_source_bars(&primary, &foreign);
        assert_eq!(aligned.len(), 6);
        // bar0 (ot 0 < first foreign 60_000) clamps to foreign[0]
        assert_eq!(aligned[0].c, 100.0);
        assert_eq!(aligned[0].t, 0.0, "primary x-index kept even on the clamp");
        assert_eq!(aligned[1].c, 100.0); // ot 60_000 exact
        assert_eq!(aligned[2].c, 100.0); // ot 120_000 gap → carry 60_000's bar forward
        assert_eq!(aligned[3].c, 300.0); // ot 180_000 exact
        assert_eq!(aligned[4].c, 400.0); // ot 240_000 exact
        assert_eq!(aligned[5].c, 400.0); // ot 300_000 past the last foreign bar → carry last
    }

    /// Empty foreign ⇒ empty alignment (the study renders nothing until the foreign
    /// feed syncs — `Active::update(&[], None)` yields empty series).
    #[test]
    fn align_source_empty_foreign_is_empty() {
        let primary: Vec<Bar> = (0..5).map(|i| gb(i, 0.1)).collect();
        assert!(align_source_bars(&primary, &[]).is_empty());
        assert!(align_source_bars(&[], &[]).is_empty());
    }

    /// A fresh `Active` defaults to the PRIMARY source (`source_symbol == None`),
    /// the byte-identical no-op — the invariant that keeps every existing render and
    /// the vike-indicators parity gate untouched.
    #[test]
    fn default_active_has_no_source_symbol() {
        let spec = get("sma").unwrap();
        let a = Active::new(1, spec, &closed_bars(10));
        assert_eq!(a.source_symbol, None, "default study computes off the primary symbol");
    }

    /// Per-line colour/width edits (the paint metadata a user tweaks in the T8
    /// dialog) MUST survive a `set_params` refold — only `series`+`ind` change.
    #[test]
    fn set_params_preserves_line_color_and_width() {
        let spec = get("macd").unwrap();
        let bars = closed_bars(60);
        let mut a = Active::new(9, spec, &bars);
        let before: Vec<u64> = a.outputs[2].series.iter().map(|v| v.to_bits()).collect();

        // user edits on line 0: a non-PALETTE colour + a non-default width.
        let custom = egui::Color32::from_rgb(1, 2, 3);
        a.outputs[0].color = custom;
        a.outputs[0].width = 4.25;

        a.set_params(vec![5.0, 40.0, 3.0], &bars); // fast/slow/signal all changed

        assert_eq!(a.outputs[0].color, custom, "line colour must survive set_params");
        assert_eq!(a.outputs[0].width, 4.25, "line width must survive set_params");
        let after: Vec<u64> = a.outputs[2].series.iter().map(|v| v.to_bits()).collect();
        assert_ne!(before, after, "series must actually recompute on set_params");
    }

    // ---------------------------------------------------------------- user studies

    /// A stand-in for a compiled user prototype: `close * scale`, where `scale` is the one
    /// declared parameter. Deliberately NOT any built-in's formula, so a series that matches it
    /// can only have come from the factory.
    #[derive(Clone)]
    struct Scaled {
        scale: f64,
        last: f64,
    }

    impl Indicator for Scaled {
        fn on_bar(&mut self, bar: &vike_model::Bar) -> Vec<f64> {
            self.last = bar.close * self.scale;
            vec![self.last]
        }
        fn vectorize(&self, bars: &[vike_model::Bar]) -> Vec<Vec<f64>> {
            vec![bars.iter().map(|b| b.close * self.scale).collect()]
        }
        fn value(&self) -> Vec<f64> {
            vec![self.last]
        }
        fn reset(&mut self) {
            self.last = f64::NAN;
        }
        fn name(&self) -> &str {
            "scaled"
        }
    }

    /// A user study named `name` whose single line is `close * scale` (default scale 2).
    fn user_scaled(name: &str) -> &'static IndicatorMeta {
        IndicatorMeta::user(
            name,
            "Scaled Close",
            RenderKind::Overlay,
            vec![vike_indicators::ParamSpec {
                name: "scale",
                default: 2.0,
                min: 0.0,
                max: 10.0,
                step: 0.5,
            }],
            &|raw: &[f64]| {
                Box::new(Scaled { scale: raw.first().copied().unwrap_or(2.0), last: f64::NAN })
            },
        )
    }

    /// `Active` over a USER study plots the FACTORY's values.
    ///
    /// Non-vacuous in the strongest available way: a user row's built-in `make` slot is
    /// `vike_indicators`' `unbuilt`, which panics. Reverting `Active::new` to `(spec.make)()`
    /// does not make this read a wrong number — it aborts the test binary. The `close * 2`
    /// assertion on top proves the series is this prototype's and not some built-in's.
    #[test]
    fn an_active_over_a_user_study_folds_the_factorys_indicator() {
        let spec = user_scaled("scaled_active");
        let bars = closed_bars(12);
        let a = Active::new(1, spec, &bars);
        assert_eq!(a.outputs.len(), 1, "a user study is single-output");
        assert_eq!(a.outputs[0].name, "scaled_active", "the line is named for the indicator");
        assert_eq!(a.params, vec![2.0], "params seed from the declared default");
        for (i, b) in bars.iter().enumerate() {
            assert_eq!(
                a.outputs[0].series[i].to_bits(),
                (b.c * 2.0).to_bits(),
                "bar {i}: the series must be the user prototype's own values"
            );
        }
        assert!(a.is_overlay(), "this one declared RenderKind::Overlay");
    }

    /// `set_params` on a user study reaches the factory too, and the streaming/append fast path
    /// keeps agreeing with a full rebuild.
    ///
    /// Non-vacuous twice over: `set_params`' old `(self.spec.make_with)(&p)` is the panicking
    /// placeholder for a user row, and a `set_params` that stored `p` without rebuilding would
    /// leave the series at `close * 2` while `params` claimed 4.
    #[test]
    fn set_params_on_a_user_study_rebuilds_through_the_factory() {
        let spec = user_scaled("scaled_params");
        let mut closed = closed_bars(20);
        let mut a = Active::new(2, spec, &closed);
        a.set_params(vec![4.0], &closed);
        assert_eq!(a.params, vec![4.0]);
        for (i, b) in closed.iter().enumerate() {
            assert_eq!(a.outputs[0].series[i].to_bits(), (b.c * 4.0).to_bits(), "bar {i}");
        }
        // ...and the one-bar-closed fast path in `update` stays on the reconfigured instance.
        let next = gb(20, 0.4);
        closed.push(next);
        a.update(&closed, None);
        assert_eq!(a.outputs[0].series[20].to_bits(), (next.c * 4.0).to_bits());
    }

    /// The two registries are a UNION at [`get_any`] and disjoint everywhere else.
    ///
    /// This is the only test in this module that installs, because `install_user_studies` is a
    /// once-per-process `OnceLock` and the lib tests share one process.
    ///
    /// Non-vacuous: before this seam `get` was the only lookup, so `get_any("scaled_installed")`
    /// could not resolve at all — and the built-in half asserts the union did not disturb `get`.
    #[test]
    fn install_makes_a_user_study_resolvable_by_name_without_disturbing_the_builtins() {
        let mine = user_scaled("scaled_installed");
        install_user_studies(vec![mine]).expect("first install");

        assert!(get("scaled_installed").is_none(), "the built-in catalog stays closed");
        let found = get_any("scaled_installed").expect("resolvable through the union");
        assert!(found.is_user());
        assert_eq!(user_registry().len(), 1);

        // A built-in still resolves, and still reports itself as a built-in.
        let sma = get_any("sma").expect("built-ins resolve through the union too");
        assert!(!sma.is_user());
        assert!(std::ptr::eq(sma, get("sma").unwrap()), "and it is the SAME row `get` returns");

        // An unknown name is still `None` — the property persistence leans on (see `get_any`).
        assert!(get_any("no_such_indicator_anywhere").is_none());

        // A second install is refused, naming both counts.
        let err = install_user_studies(vec![user_scaled("scaled_second")]).unwrap_err();
        assert!(err.contains("already installed"), "{err}");
        assert_eq!(user_registry().len(), 1, "...and the first set is untouched");
    }

    /// A built-in smuggled into the user list, a user study that would shadow a built-in, and two
    /// studies claiming one name are all refused BEFORE anything is stored.
    ///
    /// Non-vacuous: without the shadow check `get_any` would resolve built-ins first and the
    /// study would be pickable yet never plot its own values — a bug with no error message
    /// anywhere. The duplicate arm is the same bug between two USER rows, and it fails on the
    /// SECOND row specifically, so a check that only looked at `studies[0]` still passes the first
    /// two asserts. Checked here rather than only through the install above because all three must
    /// fail without consuming the `OnceLock` (every assert below can run after it is already set).
    #[test]
    fn install_refuses_a_builtin_row_a_shadowing_name_and_a_duplicate() {
        let builtin = get("sma").expect("sma is a built-in");
        let err = install_user_studies(vec![builtin]).unwrap_err();
        assert!(err.contains("built-in indicator"), "{err}");

        let shadow = user_scaled("sma");
        let err = install_user_studies(vec![shadow]).unwrap_err();
        assert!(err.contains("already the name of a built-in"), "{err}");

        // Two DISTINCT `IndicatorMeta`s (each its own leak) claiming one name — the shape a
        // non-Rhai installer could hand over, since only a filesystem stem is unique for free.
        let dupes = vec![user_scaled("scaled_dupe"), user_scaled("scaled_dupe")];
        let err = install_user_studies(dupes).unwrap_err();
        assert!(err.contains("claimed by two studies"), "{err}");
    }
}

#[cfg(test)]
mod forming_memo_tests {
    use super::*;

    fn gb(i: usize, c_shift: f64) -> Bar {
        let base = 100.0 + (i as f64 * 0.31).sin() * 3.0;
        Bar {
            t: i as f64,
            ot: 1_700_000_000_000 + i as i64 * 60_000,
            o: base,
            h: base + 1.0 + c_shift.abs(),
            l: base - 1.0,
            c: base + c_shift,
            v: 500.0 + i as f64,
        }
    }

    fn closed_bars(n: usize) -> Vec<Bar> {
        (0..n).map(|i| gb(i, 0.3)).collect()
    }

    fn last(a: &Active) -> f64 {
        *a.outputs[0].series.last().unwrap()
    }

    /// ⚠ **The memoized preview must equal the unmemoized one on every path** — the memo is a
    /// speed change, and any divergence is a WRONG NUMBER DRAWN ON THE CHART with nothing to catch
    /// it (no gate pins an overlay's values).
    ///
    /// This drives the sequence an adversarial review constructed against the first version of the
    /// memo, where the invalidation sat at `update`'s CALL SITE instead of inside `push_bar`:
    ///
    ///   update(closed[..40], Some(f))   -> memo := (fp(f), preview folded over 40 bars)
    ///   push_bar(b)                     -> `ind` advances to 41; memo SURVIVED
    ///   update(closed[..41], Some(f))   -> served the 40-bar preview
    ///
    /// The last call reaches the memo because `push_bar` leaves `fp_first` untouched and sets
    /// `fp_last` to the new bar, so `prefix_unchanged` is TRUE and neither clearing branch runs.
    ///
    /// NON-VACUOUS: the assertion compares against a FRESHLY built `Active` folded over the same
    /// 41 closed bars, so it fails on any stale value rather than agreeing with itself. `push_bar`
    /// has no caller outside this file today, which is precisely why this was a latent trap rather
    /// than a visible bug — and why it needs a test rather than a comment.
    #[test]
    fn an_external_push_bar_cannot_leave_a_stale_forming_preview() {
        let spec = get("sma").expect("sma is registered");
        let mut closed = closed_bars(40);
        let mut a = Active::new(7, spec, &closed);
        let f = gb(41, 0.25);

        a.update(&closed, Some(&f));

        let b = gb(40, 0.10);
        a.push_bar(&b);
        closed.push(b);

        a.update(&closed, Some(&f));
        let memoized = last(&a);

        let mut fresh = Active::new(8, spec, &closed);
        fresh.update(&closed, Some(&f));
        let expected = last(&fresh);

        assert_eq!(
            memoized.to_bits(),
            expected.to_bits(),
            "the forming preview after an external `push_bar` must be folded through the CURRENT \
             committed state ({expected}), not the previous one ({memoized}) — the memo outlived \
             the `ind` it was computed from"
        );
    }

    /// The memo must also be transparent on the ordinary paths, so the win cannot come from
    /// serving a wrong value cheaply. Each arm compares against a fresh `Active`.
    #[test]
    fn the_forming_memo_is_transparent_on_every_ordinary_path() {
        let spec = get("sma").expect("sma is registered");
        let closed = closed_bars(40);
        let f1 = gb(41, 0.25);
        let f2 = gb(41, 0.90); // same index, different close -> different fingerprint

        let mut a = Active::new(1, spec, &closed);
        let mut fresh = Active::new(2, spec, &closed);

        // repeated identical forming bar (the HIT path), then a moved one (the MISS path),
        // then back — each must match a fresh fold.
        for f in [&f1, &f1, &f2, &f1] {
            a.update(&closed, Some(f));
            fresh.recompute_full(&closed);
            fresh.update(&closed, Some(f));
            assert_eq!(
                last(&a).to_bits(),
                last(&fresh).to_bits(),
                "memoized preview diverged from a fresh fold on forming close {}",
                f.c
            );
        }

        // ...and a param change with the SAME closed bars, which re-derives the SAME
        // `fp_first`/`fp_last` — the case a prefix-keyed memo would get wrong.
        a.set_params(vec![5.0], &closed);
        a.update(&closed, Some(&f1));
        let mut after = Active::new(3, spec, &closed);
        after.set_params(vec![5.0], &closed);
        after.update(&closed, Some(&f1));
        assert_eq!(
            last(&a).to_bits(),
            last(&after).to_bits(),
            "a param change must invalidate the memo: the closed-prefix fingerprints are identical \
             across it, so nothing else would"
        );
    }
}

#[cfg(test)]
mod build_cost_tests {
    use super::*;

    fn gb(i: usize) -> Bar {
        let base = 100.0 + (i as f64 * 0.31).sin() * 3.0;
        Bar {
            t: i as f64,
            ot: 1_700_000_000_000 + i as i64 * 60_000,
            o: base,
            h: base + 1.0,
            l: base - 1.0,
            c: base + 0.3,
            v: 500.0 + i as f64,
        }
    }

    /// ⚠ **Building an overlay must not be QUADRATIC in history** — a hang is a correctness problem
    /// from the user's side, not a performance nicety.
    ///
    /// `recompute_full` used to fold bar-by-bar through `push_bar`, and `on_bar` for a
    /// `hist_indicator!` indicator re-runs the batch kernel over all retained history. That makes
    /// construction O(bars x retained x period). At 200,000 bars with `high_low_52w` at period 1000
    /// it measured at OVER AN HOUR before being killed — the GUI simply freezes when a user adds
    /// that indicator to a long chart.
    ///
    /// This bounds it by WALL CLOCK deliberately, rather than by asserting an implementation shape.
    /// The budget is deliberately loose (seconds, not milliseconds) so it cannot flake on a loaded
    /// CI box while still being thousands of times under the pre-fix behaviour — the failure this
    /// guards is minutes-to-hours, not tens of milliseconds.
    ///
    /// NON-VACUOUS: `high_low_52w` at its MAXIMUM period is the deepest kernel in the registry, and
    /// the bar count is large enough that the old path could not finish. Revert `recompute_full`'s
    /// batch arm and this test does not fail — it hangs, which is the point.
    #[test]
    fn building_a_deep_overlay_over_a_long_history_is_not_quadratic() {
        let spec = get("high_low_52w").expect("high_low_52w is registered");
        let bars: Vec<Bar> = (0..30_000).map(gb).collect();

        let t0 = std::time::Instant::now();
        let mut a = Active::new(1, spec, &[]);
        a.set_params(vec![1000.0], &bars);
        let elapsed = t0.elapsed();

        assert_eq!(a.outputs[0].series.len(), bars.len(), "every bar gets a value");
        assert!(
            elapsed.as_secs() < 20,
            "building a period-1000 overlay over {} bars took {elapsed:?} — the bar-by-bar fold is \
             back, and it is O(bars x retained x period). A user adding this indicator to a long \
             chart sees a frozen window.",
            bars.len()
        );
    }

    /// The batch arm must produce the SAME series the fold does — it is a speed change only.
    ///
    /// Compares `recompute_full`'s output against `Indicator::vectorize` directly, bit-for-bit, for
    /// both a trimming indicator (takes the new arm) and a hand-written incremental one (takes the
    /// old arm, and must keep taking it — seeding a path-dependent impl from a suffix would be a
    /// wrong number).
    #[test]
    fn the_batch_build_matches_the_fold_bit_for_bit() {
        let bars: Vec<Bar> = (0..2_000).map(gb).collect();
        let model: Vec<vike_model::Bar> = bars.iter().map(to_model_bar).collect();

        for name in ["midpoint", "doji", "linearreg", "sma", "obv", "vwap"] {
            let spec = get(name).unwrap_or_else(|| panic!("{name} is registered"));
            let a = Active::new(1, spec, &bars);
            let expected = spec.build().vectorize(&model);
            for (k, slot) in a.outputs.iter().enumerate() {
                assert_eq!(slot.series.len(), bars.len(), "{name} line {k} length");
                for (i, v) in slot.series.iter().enumerate() {
                    assert_eq!(
                        v.to_bits(),
                        expected[k][i].to_bits(),
                        "{name} line {k} bar {i}: built {v}, vectorize {}",
                        expected[k][i]
                    );
                }
            }
        }
    }
}
