//! GUI indicator adapter — the per-window paint/colour state (`Active`) layered
//! over the shared `vike-indicators` compute core.
//!
//! The registry, the two orthogonal axes (picker [`Category`] vs render placement
//! [`RenderKind`]/[`OutputStyle`]) and the streaming [`Indicator`] trait ALL come
//! from `vike-indicators` (one source of truth, parity-gated against the Python
//! oracle `core/indicators/base.py`) and are re-exported here so the chart UI keeps
//! its `crate::indicators::…` paths. Only the egui colours + visibility and the
//! GUI-`Bar`→`vike_marketdata::Bar` conversion live in this crate — that's paint state,
//! which has no place in the Qt-free compute core.
//!
//! ## Streaming overlays (why `Active` owns a live [`Indicator`])
//! `vike-indicators` proves `on_bar`-folded == `vectorize`, bit-for-bit. So rather
//! than a full-series `vectorize` every frame, each `Active` keeps a **persistent
//! streaming instance** folded over the **closed prefix only** (closed bars are
//! immutable and append-only), and [`Active::update`] does the cheapest correct
//! thing each frame:
//! - **no-op** when the closed series is unchanged (the common repaint frame),
//! - **[`Active::push_bar`]** — a single `on_bar` — when exactly one bar closed
//!   on top of an unchanged prefix (O(1)/O(window)),
//! - **[`Active::recompute_full`]** — reset + refold — only on a genuine
//!   structural change (first build, data reload, symbol/interval swap).
//!
//! The live *forming* bar — which mutates in place up to ~60×/s and which a
//! streaming fold cannot un-see — never touches the persistent instance: it is
//! previewed each call on a throwaway [`clone_box`], instead of the full-history
//! refold this path used to trigger.
//!
//! ⚠ **That clone is NOT "the tiny streaming state (O(window) bytes)", and a live
//! tick is NOT "microseconds regardless of history depth".** This paragraph said
//! both, and both are false for the ~150 indicators generated by
//! `vike_indicators`' `hist_indicator!`: those stream by history-RECOMPUTE and
//! carry a retained `hist: Vec<Bar>`, so `clone_box` deep-copies it EVERY FRAME.
//! Measured at `vwma`'s registry maximum `period = 400` under the old retention:
//! **4.6 MB and 1006 µs per frame** — 276 MB/s at 60 fps, most of a frame budget,
//! for ONE overlay, before any arithmetic runs.
//!
//! It is now bounded rather than merely smaller: `vike_indicators::keep_for` gives
//! a finite-window kernel `lookback_full + slack` instead of a multiple of it, which
//! is what took that same clone to ~7.8 µs. The claim above was written when every
//! streaming indicator really did carry O(window) state, and it survived the change
//! that made it untrue — the reason this correction names the measurement rather
//! than just softening the wording.
//!
//! ⚠ A USER-written indicator is worse still: its `Indicator` is the Rhai
//! interpreter, so `clone_box().on_bar(..)` is a full `RhaiIndicator` clone plus one
//! script evaluation per frame, and `recompute_full` is O(bars) interpreter calls on
//! the paint thread.
//!
//! Because the fold sequence (closed…, then forming) is exactly `vectorize`'s,
//! the on-screen values, lines, styles, colours and labels are bit-identical to
//! what a full recompute would have drawn — this is purely an efficiency design.
//!
//! [`clone_box`]: vike_indicators::BoxedClone::clone_box

use crate::model::Bar;
use std::sync::OnceLock;
use vike_ui_theme::metrics::stroke;
use vike_ui_theme::value::chart;

// Metadata + discovery come straight from the compute crate (no local duplicate). `Indicator`,
// `ParamSpec` and `UserFactory` ride along because they are the vocabulary a caller needs to BUILD
// one of the user studies below — without them a shell crate would have to take its own
// `vike-indicators` edge to name the types this module's own API already traffics in.
pub use vike_indicators::{
    Category, Indicator, IndicatorMeta, OutputStyle, ParamSpec, RenderKind, UserFactory, get,
    registry,
};

/// The USER-written studies this process was given — the chart's SECOND lookup path, empty until a
/// binary installs one.
///
/// ## Why a second registry rather than rows in `vike_indicators::registry()`
///
/// `registry()` is the CLOSED, parity-gated built-in catalog: a `OnceLock<Vec<IndicatorMeta>>`
/// built by one function inside a crate that cannot compile a scripting engine. Making it
/// installable-from-outside would turn the one static catalog in this tree into mutable startup
/// state, and — the deciding objection — it would merge two name spaces that are deliberately
/// disjoint: `vike_script::user_indicator_conflict` REFUSES a user file called `sma.rhai` exactly
/// so that `vike_indicators::get("sma")` has one meaning. Every consumer that resolves through
/// `get`/`registry` (`vike_script`'s host bindings, `vike_studio`, backtest seed sizing) would
/// silently start seeing user files.
///
/// So the chart opts in instead: [`get_any`] is the union, [`get`] stays the built-ins alone.
///
/// ⚠ This crate learns NOTHING about scripts. It takes an already-built `&'static IndicatorMeta`
/// whose own (private) factory does the constructing, so the seam is generic — a future
/// non-Rhai user indicator installs through the same door and `vike-chart` gains no dependency.
static USER_STUDIES: OnceLock<Vec<&'static IndicatorMeta>> = OnceLock::new();

/// Installs the user-written studies, once per process, at startup.
///
/// Same shape and the same reasoning as `vike_script::install_user_indicators`: a BINARY resolves
/// the directory and does the I/O, then hands over already-built descriptors. A second call is an
/// `Err` naming both counts rather than silently keeping or replacing the first set — two callers
/// believing they own this would both be wrong somewhere.
///
/// The rejections, all checked BEFORE anything is stored (so a bad batch installs nothing):
///
/// - a row that is not [`IndicatorMeta::is_user`] — a built-in smuggled into the user list would
///   appear twice in the picker and, worse, would make "is this mine?" a question about which list
///   it came from rather than about the row itself;
/// - a name already taken by a built-in. [`get_any`] resolves built-ins FIRST, so such a row would
///   simply never be constructed — it would sit in the picker, add a study, and plot the BUILT-IN.
///   `vike_script::user_indicator_conflict` already refuses this at load; refusing it here too is
///   what makes the guarantee hold for any other installer.
/// - two rows in the SAME batch claiming one name. `get_any` finds the first, so the second is a
///   decoy: a distinct picker row that silently adds the first one's indicator. That is the
///   shadowing bug above wearing user clothes, and the argument for refusing it is identical —
///   `vike_script::load_user_indicators` already cannot produce one (a stem is a filename, and a
///   collision is a diagnostic there), which is exactly why this seam has to check it: the door is
///   generic, and the guarantee must not rest on the one installer that happens to be careful.
pub fn install_user_studies(studies: Vec<&'static IndicatorMeta>) -> Result<(), String> {
    for (i, s) in studies.iter().enumerate() {
        if !s.is_user() {
            return Err(format!(
                "`{}` is a built-in indicator, not a user study; installing it here would list it \
                 twice and make `is_user` disagree with which registry it came from",
                s.name
            ));
        }
        if get(s.name).is_some() {
            return Err(format!(
                "`{}` is already the name of a built-in indicator; `get_any` resolves built-ins \
                 first, so this study would be pickable and yet never plot its own values",
                s.name
            ));
        }
        if studies[..i].iter().any(|e| e.name == s.name) {
            return Err(format!(
                "`{}` is claimed by two studies in one install; `get_any` answers with the first, \
                 so the second would be a picker row that silently adds the first one's indicator",
                s.name
            ));
        }
    }
    let n = studies.len();
    USER_STUDIES.set(studies).map_err(|_| {
        format!(
            "user studies are already installed ({} of them); install_user_studies is a \
             once-per-process call made by a binary at startup, and this second call of {n} would \
             have silently done nothing",
            USER_STUDIES.get().map(Vec::len).unwrap_or(0)
        )
    })
}

/// The installed user studies, in install order. Empty when a binary installed none — which is the
/// ordinary state, and is what keeps the picker byte-identical for anyone who has never written one.
pub fn user_registry() -> &'static [&'static IndicatorMeta] {
    USER_STUDIES.get().map(Vec::as_slice).unwrap_or(&[])
}

/// Look up an indicator by name across BOTH registries — the chart's resolution rule.
///
/// Built-ins win. That ordering is not a tie-break preference, it is the guarantee that no user
/// file can change what an existing workspace's `"sma"` means; [`install_user_studies`] refuses a
/// shadowing name outright so the ordering never has to be observed.
///
/// ⚠ An unknown name still answers `None`, exactly as [`get`] does. That is load-bearing for
/// persistence: a workspace stores studies BY NAME, and `WinState::add_indicator` is already a
/// silent no-op for a name it cannot resolve — so a saved workspace naming a user indicator whose
/// file has since been deleted, renamed or broken degrades the same way an unknown built-in
/// always has, instead of panicking on a missing prototype.
pub fn get_any(name: &str) -> Option<&'static IndicatorMeta> {
    get(name).or_else(|| user_registry().iter().copied().find(|m| m.name == name))
}

/// Convert one GUI bar-index render [`Bar`] to the compute `vike_marketdata::Bar`:
/// `o/h/l/c/v` → `open/high/low/close/volume`, `ot` (open-time ms) → `ts`;
/// tick-derived fields (funding/bid/ask/symbol) are `None` for OHLCV render bars.
fn to_model_bar(b: &Bar) -> vike_marketdata::Bar {
    vike_marketdata::Bar {
        ts: b.ot,
        open: b.o,
        high: b.h,
        low: b.l,
        close: b.c,
        volume: b.v,
        funding: None,
        bid: None,
        ask: None,
        symbol: None,
    }
}

/// TradingView "Inputs → Source" parity: the price series an indicator computes
/// off, instead of always `close`. `Close` (the default) is a **bit-identical
/// no-op** — [`Source::value`] returns `bar.c` unchanged, so the streaming path and
/// the vike-indicators parity gate stay byte-for-byte identical. The derived series
/// (`Hl2`/`Hlc3`/`Ohlc4`) are the standard TradingView midpoint/typical/average
/// prices. Applied purely in this GUI adapter layer (see [`Active::model_bar`]) —
/// the parity-gated compute core is never touched.
#[derive(Clone, Copy, PartialEq, Eq, Default, Debug)]
pub enum Source {
    #[default]
    Close,
    Open,
    High,
    Low,
    /// `(high + low) / 2` — TradingView `hl2` (median price).
    Hl2,
    /// `(high + low + close) / 3` — TradingView `hlc3` (typical price).
    Hlc3,
    /// `(open + high + low + close) / 4` — TradingView `ohlc4` (average price).
    Ohlc4,
}

impl Source {
    pub const ALL: [Source; 7] = [
        Source::Close,
        Source::Open,
        Source::High,
        Source::Low,
        Source::Hl2,
        Source::Hlc3,
        Source::Ohlc4,
    ];
    pub fn label(self) -> &'static str {
        match self {
            Source::Close => "Close",
            Source::Open => "Open",
            Source::High => "High",
            Source::Low => "Low",
            Source::Hl2 => "hl2",
            Source::Hlc3 => "hlc3",
            Source::Ohlc4 => "ohlc4",
        }
    }
    /// The chosen price for one GUI render [`Bar`]. `Close` returns `bar.c`
    /// unchanged (the identity — keeps the default path bit-identical).
    pub fn value(&self, bar: &Bar) -> f64 {
        match self {
            Source::Close => bar.c,
            Source::Open => bar.o,
            Source::High => bar.h,
            Source::Low => bar.l,
            Source::Hl2 => (bar.h + bar.l) / 2.0,
            Source::Hlc3 => (bar.h + bar.l + bar.c) / 3.0,
            Source::Ohlc4 => (bar.o + bar.h + bar.l + bar.c) / 4.0,
        }
    }
}

/// TradingView "symbol" input parity: the FOREIGN symbol an indicator computes
/// off, instead of the window's own primary. `None` (the default) means "this
/// chart's symbol" — a **bit-identical no-op**: the study folds over the primary
/// bars exactly as before this field existed, so the vike-indicators parity gate
/// stays byte-for-byte identical. When set, `vike-desktop` looks up that `(venue,
/// symbol)`'s live [`crate::model::ChartState`] (subscribing its feed like a
/// Compare overlay), re-indexes its bars onto the primary timeline via
/// [`align_source_bars`], and folds the study over THOSE — so an RSI of ETHUSDT
/// can display on a BTCUSDT chart. Pure data (`vike-chart` never does the lookup —
/// it has no cross-symbol registry); it is the study's stored source-of-truth,
/// carried on [`Active`], edited in the ƒx picker, and persisted in the workspace.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct SourceSymbol {
    /// Data venue (`"binance"`/`"bybit"`/`"okx"`) — the same string `WinState::venue`
    /// and `vike_app_core::ui::workspace::series_key` use to route the feed.
    pub venue: String,
    /// Instrument symbol on that venue (e.g. `"ETHUSDT"`).
    pub symbol: String,
}

/// Foreign-source study (TradingView "symbol" input): re-index a foreign symbol's
/// bar series onto the PRIMARY chart's timeline so an indicator folded over the
/// result is index-aligned to the primary x-axis (one value per primary bar) —
/// exactly like a same-symbol study, so the renderer needs no special case. For
/// each primary bar, the aligned bar is the foreign bar whose open-time (`ot`) is
/// the latest at-or-before the primary bar's `ot` (a forward-fill: same-interval
/// feeds are ~1:1 by `ot`, so this is an EXACT match on almost every bar, carrying
/// the previous foreign bar forward only across a foreign gap). Primary bars BEFORE
/// the first foreign bar clamp to that first foreign bar (a short flat lead-in until
/// the foreign history covers the range). Each aligned bar carries the FOREIGN
/// `o/h/l/c/v/ot` (so both the fold and its O(1) change-probe fingerprint track the
/// foreign data) but keeps the PRIMARY bar's `t` (bar index x), so nothing about the
/// primary x-placement shifts. Empty `foreign` ⇒ empty result ⇒ the study renders
/// nothing until the foreign feed syncs. Pure, O(P + F) — both inputs are `ot`-sorted
/// ascending (the ChartState invariant).
pub fn align_source_bars(primary: &[Bar], foreign: &[Bar]) -> Vec<Bar> {
    if foreign.is_empty() {
        return Vec::new();
    }
    let mut out = Vec::with_capacity(primary.len());
    let mut j = 0usize; // foreign cursor (monotonic — both slices are ot-ascending)
    for p in primary {
        // advance while the NEXT foreign bar still opens at-or-before this primary bar
        while j + 1 < foreign.len() && foreign[j + 1].ot <= p.ot {
            j += 1;
        }
        let mut b = foreign[j]; // clamps to foreign[0] for primary bars before it
        b.t = p.t; // keep the primary x-index; foreign OHLCV/ot ride along
        out.push(b);
    }
    out
}

/// O(1) fingerprint of a render bar's mutable fields (open-time + OHLCV bit-patterns,
/// FNV-1a). Lets [`Active::update`] tell "same series" from "one bar appended" from
/// "the last bar changed in place" without rehashing the whole window each frame.
fn bar_fp(b: &Bar) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for x in
        [b.ot as u64, b.o.to_bits(), b.h.to_bits(), b.l.to_bits(), b.c.to_bits(), b.v.to_bits()]
    {
        h ^= x;
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    h
}

/// Per-plot dash pattern (TradingView "Style" parity — the line-style picker next
/// to each plot's colour): `Solid` / `Dashed` / `Dotted`. Maps in `render.rs` onto
/// `egui_plot::LineStyle` (`solid()` / `dashed_loose()` / `dotted_dense()`) and
/// applies to Line/Band-style output lines. `Solid` (the default) keeps the render
/// path pixel-identical to before this field existed.
#[derive(Clone, Copy, PartialEq, Eq, Default, Debug)]
pub enum LineDash {
    #[default]
    Solid,
    Dashed,
    Dotted,
}

impl LineDash {
    pub const ALL: [LineDash; 3] = [LineDash::Solid, LineDash::Dashed, LineDash::Dotted];
    pub fn label(self) -> &'static str {
        match self {
            LineDash::Solid => "Solid",
            LineDash::Dashed => "Dashed",
            LineDash::Dotted => "Dotted",
        }
    }
}

/// One indicator output line's paint state (chart-UX bundle T8 — was an inline
/// `(name, series, style, color)` tuple): the streaming `series` buffer plus the
/// user-tunable paint attributes. `name`/`style` are static (from the `OutSpec`);
/// `color` seeds from the rotation [`PALETTE`] and `width` from a kind/style
/// default ([`default_width`]) — both then live-editable via the settings dialog.
/// `series` alone rebuilds on a refold; `color`/`width`/`line_style` survive a
/// reconfigure (see [`Active::set_params`]). T10 will persist `color`+`width`.
pub struct OutputLine {
    pub name: &'static str,
    /// streaming buffer — index-aligned to the chart bars, one value per `on_bar`.
    pub series: Vec<f64>,
    pub style: OutputStyle,
    pub color: egui::Color32,
    /// stroke width for Line/Band styles (Dots use a fixed radius, Histograms a
    /// fixed bar width, so their stored `width` is inert — kept for uniformity).
    pub width: f32,
    /// Per-plot dash pattern (TradingView "Style" line-style picker). Default
    /// [`LineDash::Solid`] — pixel-identical to the pre-field render path.
    pub line_style: LineDash,
    /// Per-plot show/hide (TradingView "Style" parity): `false` skips this line in
    /// the renderer without removing the indicator. Default `true`.
    pub visible: bool,
}

/// One oscillator reference level's paint state (TradingView RSI "Style" parity —
/// each of `spec.bands`' levels, e.g. RSI 30/50/70, gets its OWN colour + show
/// toggle instead of one shared colour). `value` is the static level from
/// `spec.bands`; `color` seeds `None` and `show` seeds `true`. Both are then live-editable
/// via the settings dialog.
///
/// `color` is an OVERRIDE, like each colour of [`crate::options::ChartOptions`]: `None` is "the
/// theme's analysis line" ([`crate::colors::ChartColors::level_line`]), resolved when the level is
/// painted and when the dialog's swatch shows it, so a level nobody coloured follows a theme
/// change; `Some` is the user's pick. A constructor has no `egui::Context` to read a theme from,
/// which is why the seed is "unset" rather than a colour.
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct BandLevel {
    pub value: f64,
    pub color: Option<egui::Color32>,
    pub show: bool,
}

/// Default translucent fill colours for the overbought (above the top band) /
/// oversold (below the bottom band) zones — TradingView RSI "Style" parity. Green
/// above / red below at a low alpha so the plotted line stays legible through them. The
/// colours are `ui-theme.toml`'s `chart` rows `OVERBOUGHT_FILL` / `OVERSOLD_FILL`.
pub fn ob_fill_default() -> egui::Color32 {
    chart::OVERBOUGHT_FILL
}
pub fn os_fill_default() -> egui::Color32 {
    chart::OVERSOLD_FILL
}

/// Default stroke width for a freshly-built output line, a step of
/// [`stroke`]: overlay bands `HAIRLINE`, every other line `LINE` (an oscillator
/// line was `1.4` before the widths took the scale). Dots/Histograms ignore
/// width (fixed radius / bar width), so their value is cosmetic.
fn default_width(kind: RenderKind, style: OutputStyle) -> f32 {
    match kind {
        RenderKind::Overlay if style == OutputStyle::Band => stroke::HAIRLINE,
        RenderKind::Overlay | RenderKind::Oscillator => stroke::LINE,
    }
}

/// Per-window active indicator instance — the GUI paint state wrapping a
/// `vike-indicators` [`IndicatorMeta`]: its output lines (one per `OutSpec`), each
/// carrying a render style + rotation colour + width, plus a visibility toggle and
/// the live parameter values. Holds a **persistent streaming [`Indicator`]** folded
/// over `committed_len` leading bars so a live append costs one `on_bar`, not a full
/// `vectorize` (see the module docs).
pub struct Active {
    pub uid: u64,
    pub spec: &'static IndicatorMeta,
    /// computed output lines (one per `spec.outputs`), each a series buffer + its
    /// editable paint attributes (see [`OutputLine`]).
    pub outputs: Vec<OutputLine>,
    /// live parameter values, index-aligned to `spec.params`; seeded from each
    /// `ParamSpec::default` and reconfigured via [`Active::set_params`]. Empty for
    /// paramless indicators (Vwap, Obv).
    pub params: Vec<f64>,
    pub visible: bool,
    /// Show/hide this oscillator's reference band levels (TradingView "Style" parity):
    /// master gate over `bands` in the renderer. Default `true`; inert for indicators
    /// with no bands (`bands` empty).
    pub show_bands: bool,
    /// Per-level reference bands (TradingView RSI "Style" parity), seeded from
    /// `spec.bands` — each level carries its OWN editable colour + show toggle (was a
    /// single shared `band_color`). Defaults (no colour chosen — the theme's level line —
    /// and show=true) hold until recoloured. Empty for indicators with no bands.
    pub bands: Vec<BandLevel>,
    /// Shade the overbought zone (above the top band) green and the oversold zone
    /// (below the bottom band) red with a translucent fill (TradingView RSI "Style"
    /// parity). Default `false` — so the pane is pixel-identical to today until
    /// enabled. Inert for indicators with no bands.
    pub show_ob_os_fill: bool,
    /// Overbought / oversold fill colours (see [`ob_fill_default`]/[`os_fill_default`]),
    /// live-editable via the settings dialog. Only painted when `show_ob_os_fill`.
    pub ob_fill: egui::Color32,
    pub os_fill: egui::Color32,
    /// TradingView "Inputs → Source" (chart source selector): the price series this
    /// indicator computes off, applied in the GUI adapter's [`Active::model_bar`]
    /// conversion (NOT the parity-gated compute core). Default [`Source::Close`] is a
    /// bit-identical no-op — the streaming fold and every vike-indicators parity test
    /// stay byte-for-byte unchanged. Changing it triggers a refold (see the vike-desktop
    /// apply path), exactly like a param change.
    pub source: Source,
    /// TradingView "symbol" input: the FOREIGN symbol this study computes off
    /// instead of the window's own primary. `None` (the default) = the primary —
    /// **bit-identical** to the pre-field path (the compute core never sees this
    /// field; `vike-desktop` reads it to decide which bars to fold). When `Some`,
    /// `vike-desktop` feeds this `Active` the foreign symbol's bars re-indexed onto the
    /// primary timeline (see [`align_source_bars`]) — so the fold, the series and
    /// the render all stay index-aligned to the primary x-axis. Editing it (in the
    /// ƒx picker) triggers a structural refold next frame, exactly like a param or
    /// [`Source`] change. See [`SourceSymbol`].
    pub source_symbol: Option<SourceSymbol>,
    /// live streaming instance, folded over exactly `committed_len` leading bars.
    ind: Box<dyn Indicator>,
    /// number of bars folded into `ind` and reflected in every `outputs[*].series`.
    committed_len: usize,
    /// fingerprints of the first and last committed bars — the O(1) change probe.
    fp_first: u64,
    fp_last: u64,
    /// The forming-bar preview, memoized on that bar's fingerprint.
    ///
    /// ⚠ **The preview is the dominant per-frame cost of an overlay, and it was recomputed on every
    /// frame whether or not a tick had arrived.** [`Active::update`]'s preview clones the indicator
    /// and folds one bar through it; for a `hist_indicator!` indicator that fold is
    /// `vike_indicators`' `stream_tail`, which RE-RUNS THE WHOLE BATCH KERNEL over all retained
    /// history and keeps the last element. Measured on the CI box at period 1000, `high_low_52w` costs
    /// **534 µs per frame** — at 60 fps that is 3.2% of a core for one overlay, spent identically
    /// each frame while the forming bar sits unchanged between ticks.
    ///
    /// A chart repaints far more often than a venue ticks, so most of those frames recompute a value
    /// that cannot have moved. `None` means "no valid preview cached".
    ///
    /// ⚠ **Validity has TWO conditions, and only one of them is the forming bar.** The cached value
    /// also depends on the committed state (`ind`, `params`, `source`, `source_symbol`), so anything
    /// that moves those must invalidate. Every such path funnels through
    /// [`Active::recompute_full`] — `set_params` calls it, `vike-desktop`'s Source apply calls it, and
    /// `update`'s own structural branch calls it — which is why the invalidation lives there rather
    /// than being restated at each call site. ⚠ It CANNOT be keyed on the closed-prefix
    /// fingerprints alone: `recompute_full` re-derives the SAME `fp_first`/`fp_last` from the same
    /// bars, so a param or source change leaves `prefix_unchanged` TRUE on the next frame and a
    /// prefix-keyed cache would serve a stale preview.
    forming: Option<(u64, Vec<f64>)>,
}

// vike _OVERLAY_COLORS rotation (chart.py:31) — BLUE, purple, cyan, green, pink,
// then the amber smoothing-MA default.
// The six colours are `ui-theme.toml`'s `chart` rows `SERIES_1`..`SERIES_6`, in this order.
const PALETTE: [egui::Color32; 6] = [
    chart::SERIES_1,
    chart::SERIES_2,
    chart::SERIES_3,
    chart::SERIES_4,
    chart::SERIES_5,
    chart::SERIES_6,
];

impl Active {
    pub fn new(uid: u64, spec: &'static IndicatorMeta, bars: &[Bar]) -> Self {
        // Per-line paint metadata (name/style/colour/width) is built once; only the
        // `series` buffer grows/rebuilds thereafter (colour/width survive reconfig).
        let outputs = spec
            .outputs
            .iter()
            .enumerate()
            .map(|(i, o)| OutputLine {
                name: o.name,
                series: Vec::new(),
                style: o.style,
                color: PALETTE[i % PALETTE.len()],
                width: default_width(spec.kind, o.style),
                line_style: LineDash::Solid,
                visible: true,
            })
            .collect();
        // Params seed from the registry defaults (`make()` == `make_with(defaults)`
        // bit-for-bit, so the initial `ind` below stays consistent with `params`).
        let params = spec.params.iter().map(|p| p.default).collect();
        // Per-level bands seed from `spec.bands`, each shown and with no colour chosen: it
        // paints in the theme's level line until recoloured (see `BandLevel`).
        let bands =
            spec.bands.iter().map(|&value| BandLevel { value, color: None, show: true }).collect();
        let mut a = Active {
            uid,
            spec,
            outputs,
            params,
            visible: true,
            show_bands: true,
            bands,
            show_ob_os_fill: false,
            ob_fill: ob_fill_default(),
            os_fill: os_fill_default(),
            source: Source::Close, // identity — bit-identical to the pre-source fold
            source_symbol: None,   // primary symbol — bit-identical to the pre-field fold

            // `build`, not the old `(spec.make)()`: a USER study's constructor is a closure that
            // clones a compiled prototype, which a bare `fn` pointer cannot reach. For a built-in
            // `build` IS `(spec.make)()` — see `IndicatorMeta::build`, and the
            // `no_builtin_row_carries_a_factory` gate that keeps that arm the only one they take.
            ind: spec.build(),
            committed_len: 0,
            fp_first: 0,
            fp_last: 0,
            forming: None,
        };
        a.recompute_full(bars);
        a
    }

    /// Per-frame entry: keep the overlay in sync with the chart series as cheaply
    /// as possible. `closed` is the immutable append-only prefix; `forming` is the
    /// live bar still mutating in place (if any).
    ///
    /// Two tiers (see the module docs):
    /// - **committed** — the persistent fold advances over `closed` only: no-op on
    ///   an unchanged series, one streamed [`push_bar`] when exactly one bar closed
    ///   on top of an unchanged prefix, full refold on any structural change.
    ///   Matching the head **and** boundary fingerprints proves the committed
    ///   prefix is unchanged, making the single-`on_bar` fast path exact.
    /// - **speculative** — the forming bar is previewed each call on a throwaway
    ///   [`clone_box`] of the streaming state and appended to the output buffers
    ///   WITHOUT committing, so a forming-bar tick costs O(state), not O(history).
    ///   The fold sequence (closed… then forming) is exactly `vectorize`'s, so the
    ///   preview stays bit-identical to a full rebuild.
    ///
    /// [`push_bar`]: Active::push_bar
    /// [`clone_box`]: vike_indicators::BoxedClone::clone_box
    pub fn update(&mut self, closed: &[Bar], forming: Option<&Bar>) {
        let n = closed.len();
        let fp_first_now = closed.first().map_or(0, bar_fp);
        let fp_last_now = closed.last().map_or(0, bar_fp);

        let prefix_unchanged =
            n == self.committed_len && fp_first_now == self.fp_first && fp_last_now == self.fp_last;
        if prefix_unchanged {
            // drop last frame's speculative value (if any); the commit stands.
            self.truncate_to_committed();
        } else if n == self.committed_len + 1
            && self.committed_len > 0
            && fp_first_now == self.fp_first
            && bar_fp(&closed[self.committed_len - 1]) == self.fp_last
        {
            // exactly one bar closed on top of an unchanged prefix → stream it.
            // (`push_bar` clears the forming memo itself — see its doc for why the invariant lives
            // in the callee rather than being restated at each call site.)
            self.truncate_to_committed();
            self.push_bar(&closed[self.committed_len]);
        } else {
            // structural change (first build, reload, symbol swap) → refold == `vectorize`.
            self.recompute_full(closed);
        }

        // Speculative forming-bar preview on a throwaway clone — never committed, and MEMOIZED on
        // the forming bar's fingerprint. See the `forming` field for why this dominates the frame
        // and why the memo cannot be keyed on the closed-prefix probe.
        if let Some(f) = forming {
            let fp = bar_fp(f);
            if self.forming.as_ref().map(|(k, _)| *k) != Some(fp) {
                let vals = self.ind.clone_box().on_bar(&self.model_bar(f));
                self.forming = Some((fp, vals));
            }
            // `unwrap` is total: the branch above stores `Some` whenever it does not already match.
            let vals = &self.forming.as_ref().unwrap().1;
            for (k, slot) in self.outputs.iter_mut().enumerate() {
                slot.series.push(vals.get(k).copied().unwrap_or(f64::NAN));
            }
        } else {
            // No forming bar this frame: drop the memo rather than let it survive a
            // forming -> none -> forming cycle, where the reappearing bar could hash equal to the
            // old one while the committed state moved underneath it.
            self.forming = None;
        }
    }

    /// Trim every output buffer back to the committed prefix, discarding the
    /// speculative forming-bar value appended by the previous [`update`] call.
    ///
    /// [`update`]: Active::update
    fn truncate_to_committed(&mut self) {
        for slot in &mut self.outputs {
            slot.series.truncate(self.committed_len);
        }
    }

    /// Convert one GUI [`Bar`] to the compute `vike_marketdata::Bar`, applying the
    /// TradingView "Source" selector (chart source selector): the model bar's
    /// **`close` is replaced by [`Source::value`]** (the chosen price series) while
    /// `open`/`high`/`low` stay as-is. MOST single-series indicators (SMA, EMA, RSI,
    /// MACD, …) read `close`, so this makes them compute off the source. **v1
    /// limitation:** range/OHLC indicators (ATR, Stochastic, PSAR, …) still read the
    /// TRUE `high`/`low`, so a non-`Close` source only shifts their `close` input —
    /// acceptable for a first cut. When `source == Close` this is the exact identity
    /// of the free `to_model_bar` (`Source::value` returns `bar.c`), so the streaming
    /// fold and the vike-indicators parity gate stay bit-for-bit unchanged.
    fn model_bar(&self, b: &Bar) -> vike_marketdata::Bar {
        let mut mb = to_model_bar(b);
        mb.close = self.source.value(b);
        mb
    }

    /// Fold ONE freshly-appended bar through the streaming `on_bar` and push its
    /// value onto each output line — O(1) or O(window), never a full recompute. The
    /// caller must guarantee `bar` truly follows the `committed_len` bars already
    /// folded (that is what [`update`] verifies); otherwise use [`recompute_full`].
    ///
    /// [`update`]: Active::update
    /// [`recompute_full`]: Active::recompute_full
    pub fn push_bar(&mut self, bar: &Bar) {
        // ⚠ Advancing `ind` invalidates the forming-preview memo, and the invalidation belongs HERE
        // rather than at the call site. This method is `pub` and its own doc invites external use
        // ("the caller must guarantee `bar` truly follows the `committed_len` bars already folded"),
        // so a caller that honours that contract exactly would otherwise still corrupt the memo:
        // `push_bar` leaves `fp_first` untouched and sets `fp_last` to the new bar, so the NEXT
        // `update` with the extended slice sees `prefix_unchanged == true`, takes neither clearing
        // branch, and serves a preview folded through the PREVIOUS committed state.
        //
        // Nothing outside this file calls it today (the only three call sites are `update`'s
        // one-bar branch, this definition, and `recompute_full`'s refold loop), so that was a latent
        // trap rather than a live defect — which is exactly the kind that survives review.
        self.forming = None;
        let mb = self.model_bar(bar);
        let vals = self.ind.on_bar(&mb);
        for (k, slot) in self.outputs.iter_mut().enumerate() {
            // on_bar arity always equals outputs.len() (registry-gated); the fallback
            // just keeps buffers length-aligned if that ever failed to hold.
            slot.series.push(vals.get(k).copied().unwrap_or(f64::NAN));
        }
        self.committed_len += 1;
        if self.committed_len == 1 {
            self.fp_first = bar_fp(bar);
        }
        self.fp_last = bar_fp(bar);
    }

    /// Rebuild every output line from scratch: reset the streaming instance and
    /// refold `on_bar` over the whole window. Bit-identical to `vectorize(bars)` (the
    /// crate's parity gate) and leaves `ind` folded over exactly `bars`, so a later
    /// [`push_bar`] continues correctly. Use on a full data reload / symbol change /
    /// indicator (re)config.
    ///
    /// [`push_bar`]: Active::push_bar
    pub fn recompute_full(&mut self, bars: &[Bar]) {
        // ⚠ THE ONE invalidation point for the forming-preview memo, and it must stay here.
        // Every way the preview can move without the closed prefix moving — a param change
        // (`set_params`), a `Source` change (`vike-desktop`'s apply path), a source-symbol change —
        // routes through this method, and each of them re-derives the SAME `fp_first`/`fp_last`
        // from the same bars. So the prefix probe cannot see them, and a memo keyed on it alone
        // would serve a stale value.
        self.forming = None;
        self.ind.reset();
        for slot in &mut self.outputs {
            slot.series.clear();
        }
        self.committed_len = 0;
        self.fp_first = 0;
        self.fp_last = 0;

        // ⚠ **The bar-by-bar fold is QUADRATIC for a history-recompute indicator, and it hangs the
        // GUI on a long chart.** `push_bar` calls `on_bar`, which for every `hist_indicator!`
        // indicator is `vike_indicators`' `stream_tail`: re-run the whole batch kernel over all
        // retained history and keep the last element. Folding `n` bars that way is
        // O(n x retained x period). Measured: at 200,000 bars with `high_low_52w` at period 1000
        // this sat for OVER AN HOUR before being killed — a user who loads a long chart and adds
        // that indicator gets a frozen window, with no error and no progress.
        //
        // The batch path answers the same question in ONE pass, O(bars x period), and it is the
        // PARITY REFERENCE: `vike_indicators`' whole contract is `on_bar`-fold == `vectorize`
        // bit-for-bit, gated by `tests/parity.rs`. So the series is taken from `vectorize`, and the
        // fold is used only to bring `ind` into its streaming state.
        //
        // ⚠ That state fold is over the RETAINED TAIL, not the whole history, and the equivalence
        // is exactly what `every_trimmed_indicator_is_truncation_invariant` already proves:
        // `last(vectorize(&bars[len - retained..])) == vectorize(&bars)[len - 1]` for every
        // `retained` the drain can leave. `keep_for` is that bound. It still costs O(keep^2 x
        // period) — ~10^9 for the deepest case rather than ~10^13, a stall instead of a hang — and
        // going further would need the kernels to expose a last-value entry point.
        //
        // ⚠ ONLY for `trims_history()` indicators. A hand-written incremental impl
        // (`vike-indicators`' `base.rs`: `obv`, `vwap`, `sma`, …) folds from bar zero and is
        // path-dependent by construction — seeding it from a suffix would be a WRONG NUMBER, and
        // those are O(1) per bar anyway, so the old path is both required and cheap for them.
        if self.ind.trims_history() && !bars.is_empty() {
            let model: Vec<vike_marketdata::Bar> = bars.iter().map(|b| self.model_bar(b)).collect();
            let cols = self.ind.vectorize(&model);
            for (k, slot) in self.outputs.iter_mut().enumerate() {
                slot.series = cols.get(k).cloned().unwrap_or_else(|| vec![f64::NAN; bars.len()]);
            }
            let keep = vike_indicators::keep_for(self.ind.lookback_full(), self.ind.window_reach());
            for mb in &model[model.len().saturating_sub(keep)..] {
                self.ind.on_bar(mb);
            }
            self.committed_len = bars.len();
            self.fp_first = bar_fp(&bars[0]);
            self.fp_last = bar_fp(&bars[bars.len() - 1]);
        } else {
            for b in bars {
                self.push_bar(b);
            }
        }
    }

    /// Reconfigure this indicator to a new parameter set and refold over the
    /// closed bars (chart-UX bundle T8). Stores `p`, then **rebuilds** the
    /// streaming instance via `spec.build_with(&p)` — NOT `reset()`, which
    /// preserves the OLD instance's params — and finally `recompute_full`s the
    /// series. The result is bit-identical to a fresh `Active` folded at `p`
    /// (the reconfig parity gate, `tests::set_params_refold_matches_fresh_build`).
    ///
    /// Only `series`+`ind` change: the per-line `color`/`width` (possibly
    /// user-edited in the settings dialog) are left untouched. `bars_closed`
    /// is the immutable closed prefix; the forming-bar preview re-runs next
    /// [`Active::update`] on the new `ind`.
    pub fn set_params(&mut self, p: Vec<f64>, bars_closed: &[Bar]) {
        self.ind = self.spec.build_with(&p);
        self.params = p;
        self.recompute_full(bars_closed);
    }

    pub fn is_overlay(&self) -> bool {
        self.spec.kind == RenderKind::Overlay
    }
}

#[path = "indicators_tests.rs"]
#[cfg(test)]
mod indicators_tests;

#[path = "forming_memo_tests.rs"]
#[cfg(test)]
mod forming_memo_tests;

#[path = "build_cost_tests.rs"]
#[cfg(test)]
mod build_cost_tests;
