//! The generated-registry TEXT both hosts share: the header line, one `#[path]` module per found
//! folder, and a quoted name list for a roster constant. Pure functions of strings.
//!
//! Nothing more lives here on purpose: each host's resolver (`user_strategy_by_name`,
//! `user_study_entry`/`run_user_study`) and the doc text on its rosters are that host's own, and a
//! host's whole render is `header` + `module_lines` + its own text over `quoted_list`.
//!
//! A `#[path]` is a forward-slash absolute path: rustc accepts one on Windows, and it needs no
//! escaping inside the quoted literal.

use super::scan::Found;

/// The generated file's first line, newline included: who wrote it, and that it is never committed.
pub fn header(host: &str) -> String {
    format!("// @generated by {host}/build.rs — NEVER committed, lives in OUT_DIR.\n")
}

/// One `#[path = "<entry>"]` + `pub mod user_<name>;` pair per folder, in the given (sorted scan)
/// order, backslashes rendered as `/`. Empty input renders `""`.
pub fn module_lines(found: &[Found]) -> String {
    let mut src = String::new();
    for f in found {
        let path = f.entry.display().to_string().replace('\\', "/");
        src.push_str(&format!("#[path = \"{path}\"]\npub mod user_{};\n", f.name));
    }
    src
}

/// `"a", "b"` — each name quoted, comma-separated, for a `&[&str]` roster literal. Empty input
/// renders `""`.
pub fn quoted_list(names: &[&str]) -> String {
    let quoted: Vec<String> = names.iter().map(|n| format!("\"{n}\"")).collect();
    quoted.join(", ")
}
