//! The cross-platform PIN for this crate's transcendental sites — the simulator half of what was
//! one probe while the simulator lived inside `vike-backtest`. It was SPLIT when the simulator left
//! that crate (docs/decisions/0087): the two sites that decide a FILL came here with their code, and
//! `crates/vike-backtest/tests/libm_platform_probe.rs` keeps the ranking site (`objective.rs`) and
//! the harness's own source walk. The corpora, the hasher and the recorded hashes moved verbatim —
//! every row folds its own seeded corpus, so a row hashes identically whichever file holds it.
//!
//! IEEE 754 requires `+ - * /` and `sqrt` to be correctly rounded and requires NOTHING of
//! `ln`/`exp`/`pow`/`cos`, so an `f64` METHOD call reaches whichever libm the PLATFORM ships —
//! MSVC's CRT on the Windows dev box, glibc on the the CI box Linux boxes and every CI runner — and the
//! two disagree in the last bit. `crates/vike-sim/Cargo.toml`'s `libm` line names the two sites this
//! crate converted for that reason, and
//! `docs/decisions/0032-transcendentals-come-from-the-libm-crate-not-the-platform.md` is the
//! accepted verdict.
//!
//! # What each pinned row actually decides — read this before ranking a red row as cosmetic
//!
//! * [`PLATFORM_INVARIANT`]'s `impact::AlmgrenChriss::impact_frac` is a **FILL PRICE**. Its result
//!   is ADDED to the engine's flat slippage and multiplied into the executed price
//!   (`crates/vike-fills/src/broker_sim.rs`'s `adverse_fill_price`, reached through
//!   `crates/vike-sim/src/engine/sim_broker.rs`'s `SimBroker::slippage_for`), so it lands on the
//!   equity curve of every bar-mode backtest that opts the model in. It is also the worst case under
//!   0032's classify-a-power-by-its-BASE rule: base AND exponent are arbitrary runtime `f64`s
//!   (`AC_ALPHA = 0.891`, `AC_BETA = 0.600`).
//! * `queue_model::ProbQueueModel` decides **WHETHER A RESTING ORDER FILLS**.
//!   `crates/vike-sim/src/queue_model.rs`'s `ProbFunc` — its `f` weights the front-vs-back
//!   attribution of a depth decrease, so it moves the estimated queue ahead of a resting maker —
//!   a backtest can fill on one box and not on the other.
//!
//! `.sqrt()` calls are not covered and need no coverage: IEEE 754 requires `sqrt` correctly
//! rounded, so it is already identical on every box.
//!
//! # ⚠ The corpus is PURE ARITHMETIC, and that is load-bearing
//!
//! Every input is generated by an integer LCG plus `+ - * /`, never by `.sin()`/`.cos()`. Those are
//! themselves platform-dependent (MEASURED — `crates/vike-analytics/tests/libm_platform_probe.rs`'s
//! Part A sweeps them as its control), so generating inputs with them would make every row below
//! diverge because of the INPUTS rather than because of the function under test: a false positive
//! that reads exactly like a real one.
//!
//! ```text
//! <cargo> test -p vike-sim --test libm_platform_probe
//! ```

use vike_model::libm_walk::{banned_needles, cfg_test_ranges};
use vike_sim::{AlmgrenChriss, ImpactInputs, ImpactModel, ProbQueueModel, QueueModel};

// =================================================================================================
// The hashing/corpus machinery, deliberately a per-crate COPY. Decision 0074 moved the TEXT parser
// the SOURCE half below walks with — and ONLY the text parser — into `vike_model::libm_walk`; the
// hasher and the corpus stay beside the table they pin.
// =================================================================================================

/// FNV-1a over `f64::to_bits`, NaN canonicalised so a NaN's sign and payload — neither of which the
/// architecture pins — cannot report a divergence that is not one. The same hasher the sibling
/// probes use, so a row moved between crates hashes identically (which is what let the rows below
/// move here from `vike-backtest` without re-recording).
struct Fnv(u64);

impl Fnv {
    fn new() -> Self {
        Fnv(0xcbf2_9ce4_8422_2325)
    }
    fn push(&mut self, v: f64) {
        let bits = if v.is_nan() { 0x7ff8_0000_0000_0000u64 } else { v.to_bits() };
        for b in bits.to_le_bytes() {
            self.0 ^= u64::from(b);
            self.0 = self.0.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    fn hex(&self) -> String {
        format!("{:016x}", self.0)
    }
}

/// Deterministic pseudo-random `f64` in `(0, 1)` from a pure-integer LCG.
///
/// ⚠ No transcendental anywhere in here, for the reason the module doc gives. The `as f64` of a
/// 53-bit integer is exact and the single division is correctly rounded, so the corpus is
/// bit-identical on every platform BY CONSTRUCTION — which is what makes a divergence in the
/// OUTPUT attributable to the function under test rather than to the inputs.
fn lcg(seed: &mut u64) -> f64 {
    *seed = seed.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
    ((*seed >> 11) as f64) / ((1u64 << 53) as f64)
}

/// Samples per row. Large enough that a last-bit disagreement on a rare input survives into the
/// hash rather than being rounded away — the trap the indicators twin fell into twice with a single
/// series, where two genuinely divergent indicators both reported "identical".
const SAMPLES: usize = 4096;

/// One row's verdict over its own corpus.
struct Row {
    label: &'static str,
    hash: String,
    /// How many samples were folded in.
    n: usize,
    /// ⚠ NON-VACUITY GUARD. A row whose corpus collapses to one value — or to all-NaN — hashes
    /// identically on every platform and reads as a PASS while pinning nothing. This is how many
    /// DISTINCT FINITE values the samples took, so a row reporting `distinct=1` is worthless
    /// rather than reassuring. The analytics twin caught a real instance of exactly that
    /// (`overfit::pbo_cscv`), which is why this is a field on EVERY row rather than a check
    /// hand-applied to a chosen few.
    distinct: usize,
}

fn finish(label: &'static str, vals: &[f64]) -> Row {
    let mut h = Fnv::new();
    for &v in vals {
        h.push(v);
    }
    let mut bits: Vec<u64> = vals.iter().filter(|v| v.is_finite()).map(|v| v.to_bits()).collect();
    bits.sort_unstable();
    bits.dedup();
    Row { label, hash: h.hex(), n: vals.len(), distinct: bits.len() }
}

/// Smallest number of DISTINCT finite values a row may carry before its pin is treated as vacuous.
const MIN_DISTINCT: usize = 64;

// =================================================================================================
// The corpus.
// =================================================================================================

/// Every covered function, folded over its own corpus.
///
/// Returns rows in a FIXED order; [`PLATFORM_INVARIANT`] is compared positionally, so a reordering
/// is a re-record rather than a silent re-pairing.
fn production_rows() -> Vec<Row> {
    let mut out = Vec::new();

    // --- impact::AlmgrenChriss::impact_frac — `libm::pow(nu * T, alpha)` + `libm::pow(nu, beta)`
    //
    // The published calibration is swept ALONGSIDE randomised coefficient sets rather than alone:
    // `AlmgrenChriss`'s fields are all `pub`, a profile can set any of them, and a site that is
    // portable only at its default parameters is portable by accident. `exec_time` is swept too —
    // it is the one input reaching BOTH `pow` calls (it builds `nu`, and it multiplies back into
    // the permanent term's base).
    {
        let mut s = 0x1234_5678_9abc_def0u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        for i in 0..SAMPLES {
            // Alternate the published calibration with a randomised one, so the row covers the
            // configuration that actually ships AND the space around it.
            let model = if i % 2 == 0 {
                AlmgrenChriss::with_exec_time(0.25 + lcg(&mut s) * 4.0)
            } else {
                AlmgrenChriss {
                    gamma: 0.05 + lcg(&mut s) * 1.0,
                    alpha: 0.30 + lcg(&mut s) * 1.4,
                    eta: 0.02 + lcg(&mut s) * 0.6,
                    beta: 0.20 + lcg(&mut s) * 1.2,
                    exec_time: 0.25 + lcg(&mut s) * 4.0,
                }
            };
            let input = ImpactInputs {
                qty: 1.0 + lcg(&mut s) * 250_000.0,
                avg_volume: 1_000.0 + lcg(&mut s) * 5_000_000.0,
                sigma: 1e-4 + lcg(&mut s) * 0.12,
            };
            vals.push(model.impact_frac(&input));
        }
        out.push(finish("impact::AlmgrenChriss::impact_frac (pow x2)", &vals));
    }

    // --- queue_model::ProbQueueModel — `ProbFunc::f` through the PUBLIC trait verb.
    //
    // ⚠ `ProbFunc::f` is a PRIVATE method and is deliberately not made reachable in order to pin
    // it: the consumer that matters is `on_depth_change`, and driving `f` through the verb the
    // tick-replay engine actually calls is the STRONGER pin — it covers the attribution arithmetic
    // wrapped around the call as well. `st.front_qty` after the fold IS the estimated queue ahead
    // of the order, i.e. the quantity a fill decision reads.
    //
    // Two rows, because the two arms are two different libm calls and one of them has a parameter.
    // `Log` is `libm::log(1 + x)` unconditionally. `Power(n)` is `libm::pow(x, n)`, which returns
    // `x` EXACTLY at the default `n = 1` (libm's `pow` takes a `y is ±1` branch ahead of any
    // arithmetic — the site's own doc says so), and is a real transcendental at every other
    // exponent. The `Power` row therefore sweeps `n` AWAY from 1: pinning `n = 1` would pin the one
    // value at which the site is portable by accident.
    {
        let mut s = 0x0fed_cba9_8765_4321u64;
        let m = ProbQueueModel::log();
        let mut vals = Vec::with_capacity(SAMPLES);
        for _ in 0..SAMPLES {
            let level = 10.0 + lcg(&mut s) * 50_000.0;
            let mut st = m.on_new_order(level);
            // A trade FIRST, so `cum_trade_qty` is non-zero and the `chg_net` netting is exercised
            // rather than short-circuited.
            m.on_trade(&mut st, lcg(&mut s) * level * 0.4);
            let new_qty = level * (0.05 + lcg(&mut s) * 0.9);
            m.on_depth_change(&mut st, level, new_qty);
            vals.push(st.front_qty);
        }
        out.push(finish("queue_model::ProbQueueModel::log (log)", &vals));
    }
    {
        let mut s = 0x2222_3333_4444_5555u64;
        let mut vals = Vec::with_capacity(SAMPLES);
        for _ in 0..SAMPLES {
            // n strictly away from 1.0 — see the note above.
            let n = 1.15 + lcg(&mut s) * 2.5;
            let m = ProbQueueModel::power(n);
            let level = 10.0 + lcg(&mut s) * 50_000.0;
            let mut st = m.on_new_order(level);
            m.on_trade(&mut st, lcg(&mut s) * level * 0.4);
            let new_qty = level * (0.05 + lcg(&mut s) * 0.9);
            m.on_depth_change(&mut st, level, new_qty);
            vals.push(st.front_qty);
        }
        out.push(finish("queue_model::ProbQueueModel::power (pow)", &vals));
    }

    out
}

/// ⚠ **ONE set of constants for EVERY platform — that is the entire claim.**
///
/// These three rows were recorded in `crates/vike-backtest/tests/libm_platform_probe.rs` on both
/// platforms and MOVED here with the code they pin, hashes unchanged: each row folds its own seeded
/// corpus, so nothing about a row depends on which file (or which other rows) surround it.
///
/// ⚠ **Re-record by RUNNING, never by editing a digit**, and never from ONE box. If a row goes red
/// the question is which platform moved and why:
///   (a) an intended numeric change — re-record on both boxes and pin the hash they AGREE on; or
///   (b) a call site went back to the platform's libm, in which case the two boxes will NOT agree
///       and the fix is in the source, not here.
///
/// ⚠ **A per-platform table (`#[cfg(windows)]` / `#[cfg(unix)]`) is NOT a repair and must never be
/// added.** It would make the gate green by asserting the divergence was intended — the one
/// conclusion this whole exercise refutes.
const PLATFORM_INVARIANT: [(&str, &str); 3] = [
    ("impact::AlmgrenChriss::impact_frac (pow x2)", "a42b7a7410b0b803"),
    ("queue_model::ProbQueueModel::log (log)", "2b16a2b6cc394c1a"),
    ("queue_model::ProbQueueModel::power (pow)", "c5a36e38ac3cdc04"),
];

/// The cross-platform proof, as a GATE rather than a diff somebody has to remember to run.
///
/// NOT `#[ignore]`d: CI runs it on Linux every PR and `just t vike-sim` runs it on the Windows dev
/// box, both against the same committed table — so the two platforms are held equal without anyone
/// diffing two terminal windows.
#[test]
fn converted_functions_are_platform_invariant() {
    let got = production_rows();
    let want = &PLATFORM_INVARIANT;
    let table = "PLATFORM_INVARIANT";
    assert_eq!(got.len(), want.len(), "row count drifted from {table} — it must be re-recorded");

    let mut bad = Vec::new();
    for (r, (want_label, want_hash)) in got.iter().zip(want.iter()) {
        assert_eq!(
            &r.label, want_label,
            "row ORDER drifted from {table} — the compare is positional"
        );
        if r.hash != *want_hash {
            bad.push(format!("  {:<48} want={want_hash} got={}", r.label, r.hash));
        }
    }

    // The non-vacuity half is asserted BEFORE the hashes, deliberately: a thin row is a defect
    // whether or not its hash matched, and an author re-recording a row must be told about it
    // BEFORE pasting a hash that would pin nothing.
    let thin: Vec<String> = got
        .iter()
        .filter(|r| r.distinct < MIN_DISTINCT)
        .map(|r| format!("  {:<48} {} distinct finite of {} samples", r.label, r.distinct, r.n))
        .collect();
    assert!(
        thin.is_empty(),
        "a pinned row's corpus is too thin to detect a last-bit divergence: it would hash \
         identically on every platform and read as a PASS while proving nothing. WIDEN the input \
         ranges — never lower MIN_DISTINCT ({MIN_DISTINCT}):\n{}",
        thin.join("\n")
    );

    if !bad.is_empty() {
        let paste: String =
            got.iter().map(|r| format!("    (\"{}\", \"{}\"),\n", r.label, r.hash)).collect();
        panic!(
            "\nvike-sim output moved away from {table}:\n{}\n\n\
             There is no tolerance here to widen, and hand-editing a digit defeats the gate.\n\
             Establish WHY before re-recording:\n\
               (a) an intended numeric change — re-record on BOTH boxes and pin the agreed hash; or\n\
               (b) a call site changed which libm it reaches, in which case the two platforms will\n\
                   NOT agree and the fix is in the source, not here.\n\n\
             const {table}: [(&str, &str); {}] = [\n{paste}];\n",
            bad.join("\n"),
            got.len(),
        );
    }
}

/// The control arm for the non-vacuity threshold itself.
///
/// ⚠ Without this, `MIN_DISTINCT` is an assertion nobody has checked DISCRIMINATES. A `distinct`
/// computation that counted samples rather than distinct values — or a threshold accidentally set
/// to `0` — would pass every row above while the guard did nothing, and catching a check that
/// passes while doing nothing is the guard's entire job.
#[test]
fn the_non_vacuity_check_discriminates() {
    let constant: Vec<f64> = (0..SAMPLES).map(|_| 0.5f64).collect();
    let r = finish("control::constant", &constant);
    assert!(
        r.distinct < MIN_DISTINCT,
        "the non-vacuity check does not discriminate: a constant series reported {} distinct",
        r.distinct
    );
    let nans: Vec<f64> = (0..SAMPLES).map(|_| f64::NAN).collect();
    assert_eq!(
        finish("control::nan", &nans).distinct,
        0,
        "an all-NaN row must report ZERO distinct FINITE values — the analytics twin's vacuous row \
         was all-NaN rather than constant, and a `distinct` that counted NaNs would have passed it"
    );
    let mut s = 0xdead_beef_cafe_babeu64;
    let rich: Vec<f64> = (0..SAMPLES).map(|_| lcg(&mut s)).collect();
    assert!(
        finish("control::rich", &rich).distinct >= MIN_DISTINCT,
        "the corpus generator itself is degenerate — every row above is void"
    );
}

// =================================================================================================
// The SOURCE half. The table above proves today's outputs agree; this stops the NEXT edit from
// reintroducing a platform call in a spot no corpus reaches.
// =================================================================================================

/// Production code in this crate must reach a transcendental through the `libm` CRATE.
///
/// ⚠ Not redundant with the hash table. That pins THREE functions; this crate carries a dozen
/// source files, and a new call site in any of the others — `engine.rs` and `sim_broker.rs` are
/// the fill engine itself — would be invisible to every corpus above while quietly making a fill
/// price depend on which box ran the replay.
///
/// Scope: every `.rs` under `src/`, recursively, MINUS each file's `#[cfg(test)]` item ranges. The
/// text machinery it walks with — `banned_needles` and `cfg_test_ranges`, from
/// `vike_model::libm_walk` — is shared with the sibling probes (decision 0074), and the general
/// argument for each lives there. What could NOT move is the per-crate evidence below.
///
/// # What the shared needle list cannot see, MEASURED against this crate's `src/`
///
/// `banned_needles` misses three spellings: the angle-bracket one (`<f64>::exp(x)`), a call reached
/// through a generic bound (`T: Float`, `num_traits::Float::exp`), and a call split across two
/// lines by a `max_width` wrap. **None of the three occurs under `crates/vike-sim/src` today**
/// (measured 2026-09-27, when this file was split off). A list of spellings is an enumeration and
/// an enumeration is never a proof, so that sentence is a measurement rather than a reassurance.
///
/// # Why locating an item's end by INDENTATION is exact over this crate
///
/// `cfg_test_ranges` finds an item's end by indentation rather than by counting braces, which is
/// safe only where the tree really is rustfmt output. Measured over `crates/vike-sim/src`
/// 2026-09-27: seven of the eight test markers sit at column 0 and open the file's LAST item; the
/// eighth is `crates/vike-sim/src/latency.rs`'s test-only `LatencyGate::new`, an indented
/// `#[cfg(test)]` on one method, whose end the walk finds by that method's own indentation.
#[test]
fn production_code_calls_libm_not_the_platform() {
    let banned = banned_needles();
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let src = root.join("src");
    let mut found = Vec::new();
    let mut scanned: Vec<String> = Vec::new();
    // A `#[cfg(test)]` item whose end could not be located swallows the rest of its file exactly
    // the way a `break` would. That is the one QUIET failure of the range walk, so it is collected
    // and asserted rather than absorbed.
    let mut unclosed: Vec<String> = Vec::new();
    let mut stack = vec![src];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).expect("crate has a src/ directory") {
            let path = entry.expect("readable dir entry").path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                continue;
            }
            // `\` -> `/` so a path reads the same on the Windows box.
            let rel = path.strip_prefix(root).unwrap_or(&path).to_string_lossy().replace('\\', "/");
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            let text = std::fs::read_to_string(&path).expect("readable source file");
            scanned.push(name);
            let lines: Vec<&str> = text.lines().collect();
            let test_items = cfg_test_ranges(&lines);
            for &(start, _, closed) in &test_items {
                if !closed {
                    unclosed.push(format!("  {rel}:{}", start + 1));
                }
            }
            for (i, line) in lines.iter().enumerate() {
                if test_items.iter().any(|&(start, end, _)| i >= start && i < end) {
                    continue; // inside a `#[cfg(test)]` item — not shipped
                }
                let code = line.trim_start();
                if code.starts_with("//") {
                    continue; // a doc comment naming `exp` is prose, not a call
                }
                for pat in &banned {
                    if line.contains(pat.as_str()) {
                        found.push(format!("  {rel}:{} {code}", i + 1));
                    }
                }
            }
        }
    }
    // Non-vacuity, aimed at the failure this scan is most likely to have: `src/` NESTS here
    // (`engine/`), so a walk that stopped at the top level would still open files and report a
    // confident zero while never reading the fill engine.
    for must in ["impact.rs", "queue_model.rs", "sim_broker.rs"] {
        assert!(
            scanned.iter().any(|s| s == must),
            "the scan never opened {must}, so an empty result proves nothing about the files this \
             gate exists for. Scanned {} files.",
            scanned.len()
        );
    }
    assert!(
        unclosed.is_empty(),
        "a `#[cfg(test)]` item's closing line could not be located, so everything below it went \
         UNSCANNED — the exact hole a `break` leaves, wearing a different cause. See \
         `vike_model::libm_walk::cfg_test_ranges`: the end is the item's own indentation followed \
         by a lone `}}`, or a `;` for a `mod NAME;` declaration.\n{}",
        unclosed.join("\n")
    );
    assert!(
        found.is_empty(),
        "production code must call the `libm` CRATE rather than `f64`'s platform-libm methods, so a \
         FILL PRICE does not depend on which box ran the replay — `crates/vike-sim/Cargo.toml`'s \
         `libm` line names the two sites and this file's module doc what each one's last bit \
         decides. BOTH spellings are banned, `x.exp()` and `f64::exp(x)`: same inherent method, \
         same libcall (see `vike_model::libm_walk::banned_needles`). `powi` is banned too — on MSVC \
         a `dev` build makes it a `pow()` libcall — and its cure is a MULTIPLICATION rather than \
         `libm`:\n{}",
        found.join("\n")
    );
}
