//! `vike-cli secrets template` — the EMPTY credential grid, written to stdout.
//!
//! Split out of `cmd/secrets.rs` (code-layout phase 2, task 10). The reason it takes no destination
//! argument, and so can never truncate a live store, is argued in that module's doc.

use vike_secrets::SECRETS_FILE;

use super::*;

/// The header the emitted grid carries. Separate constant so the test below can assert the two
/// warnings a reader most needs are present without matching the whole banner.
pub(super) const TEMPLATE_HEADER: &str = "\
# vike credential store — TEMPLATE, generated by `vike-cli secrets template`.
#
# Every name below is DERIVED from the venue roster (vike_model::venues::VENUES) crossed with the
# tiers and suffixes in vike_model::credential_keys. Nothing here is hand-listed, so a venue added
# to the roster appears here the same day.
#
# HOW TO USE IT: fill in the values for the venues you actually trade and DELETE every other line.
# An EMPTY value is equivalent to an absent key — the venue stays on paper — so leaving the blanks
# is harmless, merely noisy.
#
# ⚠ ARMING IS NOT A CREDENTIAL QUESTION ALONE. `policy.venues.<venue>`, a settings row written with
#   `vike-cli config set`, is a ceiling consulted BEFORE the credential is read, and it defaults to
#   `paper` for every venue. Filling a key in here arms nothing by itself.
#
# ⚠ THIS GRID IS NOT COMPLETE, and the gap is structural. It covers the venues whose credentials
#   are spelled {VENUE}_{TIER}_{SUFFIX}. Venues with a BESPOKE shape — the FX brokers, which use a
#   login/password pair rather than a key/secret — cannot be derived from any central table in this
#   workspace; their keys live only in each bridge's own `crates/bridges/<venue>/src/config.rs`,
#   which is the authority for them. Write those by hand.
#
# ⚠ LEGACY TIER SPELLINGS ARE OMITTED ON PURPOSE. `credential_keys()` also yields the pre-rename
#   `MAINNET` tier, because the loader still reads it. Emitting it here would teach a deprecated
#   spelling to somebody writing their first store, so this grid stops at SIM/DEMO/LIVE.
";

/// Emit the empty credential grid on **stdout**.
///
/// Writes no file and takes no path — see this module's *Read-only, always* section for why there
/// is no `--out`. Pure apart from the printing: [`template_body`] builds the whole string, so the
/// grammar is unit-tested without capturing stdout.
///
/// # ⚠ On a MIGRATED box this command is a TRAP, and the redirection is why
///
/// Its whole documented use is `vike-cli secrets template > settings/secrets.env`, and every doc,
/// skill and refusal message in this tree names it as HOW TO CREATE THE STORE. Once
/// `<project>/settings/db/vike.db` exists that redirect writes a file **nothing reads** —
/// `vike_secrets::backend_in` answers `Database` for every process on the box — and it exits 0. The
/// operator then fills in venue keys, restarts, and every venue is still on paper with a store
/// sitting there looking correct: the live gate wearing the fresh-install answer, which is the exact
/// failure class `vike_secrets::ShadowedStore` exists to name.
///
/// So the grid is still printed and a FINDING goes to stderr beside it, naming the database and the
/// two verbs that act on it. A finding rather than a refusal, for this command's own house rule
/// (`list`, `path` and `set` all warn and proceed) and because the grid keeps a legitimate use on any
/// box — it is a SHAPE, and reading the key names for a venue is not a write.
///
/// ⚠ **On an unmigrated box the behaviour is byte-identical**, stdout and stderr both: the probe
/// runs, answers `Files`, and prints nothing. That matters because this output is redirected into
/// real stores by real runbooks.
///
/// ⚠ `--file` is not honoured for the probe, the same call `run_path` makes and for the same reason:
/// that flag aims the VENUE store at an arbitrary path for inspection, and a database that happens
/// to sit beside some unrelated `.env` is not this project's store.
pub(super) fn run_template(args: &Args, ctx: &Ctx<'_>) -> Result<(), String> {
    let body = template_body(args.venue.as_deref())?;
    print!("{body}");
    // ⚠ No `args.file` guard here any more, and its absence is the point: `parse` REFUSES `--file`
    // on this subcommand (see its own note), so this warning cannot be switched off by a flag. It
    // used to be, which meant the ONE effect `--file` had on `template` was to silence the sentence
    // saying the redirection below it writes a file nothing reads.
    if let vike_secrets::Backend::Database(db) =
        vike_secrets::backend_in(&settings_dir_of(ctx.settings_dir, ctx.settings_dir_override))
    {
        eprintln!(
            "⚠ this box has MIGRATED: the settings database {} holds the credentials, and \
             `{}` is no longer read. Redirecting this grid into that file would write \
             something nothing loads. To put a key in the store that answers:\n    \
             printf %s \"$SECRET\" | vike-cli secrets set KEY\n  \
             (`vike-cli secrets migrate` is what created the database; `vike-cli secrets path` \
             prints both locations.)",
            db.display(),
            SECRETS_FILE
        );
    }
    Ok(())
}

/// Build the template text. PURE — the testable half of [`run_template`].
///
/// `venue` filters to one roster id; `None` emits the whole grid. An unknown id is an ERROR naming
/// the roster rather than an empty emission, because a silent empty file is indistinguishable from
/// "this venue needs no credentials" and would be redirected straight over a store.
pub(super) fn template_body(venue: Option<&str>) -> Result<String, String> {
    use vike_model::VENUES;
    use vike_model::credential_keys::starter_keys;

    let venues: Vec<&str> = match venue {
        None => VENUES.to_vec(),
        Some(v) => {
            let lower = v.to_lowercase();
            if !VENUES.contains(&lower.as_str()) {
                return Err(format!("unknown venue '{v}' — the roster is: {}", VENUES.join(", ")));
            }
            vec![VENUES.iter().find(|r| **r == lower).copied().expect("membership just checked")]
        }
    };

    // ⚠ The key names are COMPOSED in `vike_model::credential_keys::starter_keys`, not here, and
    // that is not a style preference: `crates/vike-ops/tests/settings/settings_registry/walk_and_grid.rs`'s
    // `generated_key_sites` reads a call to `credential_key` as "this crate READS these variables"
    // and would then demand the whole grid's worth of `SETTINGS` rows for `vike-cli`. This command
    // reads none of them — it prints names. `starter_keys`' doc carries the full argument.
    let mut out = String::from(TEMPLATE_HEADER);
    for v in venues {
        out.push_str(&format!("\n# ── {v} ──\n"));
        // `starter_keys` emits the credential rows first and the attribution rows (if any) after,
        // so a single latch puts the note immediately before the first attribution row and never
        // again. A previous version tested the tail of `out`, which re-emitted the note before the
        // SECOND attribution key because the tail was by then the first key's own line.
        let mut noted = false;
        for key in starter_keys(v) {
            if !noted && (key.ends_with("_BROKER_CODE") || key.ends_with("_BUILDER_CODE")) {
                out.push_str("# optional — affiliate/builder attribution, absent = unattributed\n");
                noted = true;
            }
            out.push_str(&key);
            out.push_str("=\n");
        }
    }
    Ok(out)
}

#[cfg(test)]
mod template_shape_tests {
    use super::template_body;

    /// The attribution note appears at most ONCE per venue. An earlier version tested the tail of
    /// the buffer and re-emitted it before every attribution key after the first.
    #[test]
    fn the_attribution_note_is_not_repeated() {
        let body = template_body(None).unwrap();
        let notes = body.matches("affiliate/builder attribution").count();
        let venues_with_attribution = vike_model::VENUES
            .iter()
            .filter(|v| !vike_model::venues::attribution::attribution_for(v).is_none())
            .count();
        assert_eq!(
            notes, venues_with_attribution,
            "the note must appear exactly once per attributed venue"
        );
    }
}
