//! Registry rows — candlestick patterns (patterns.py).
use super::*;

pub(super) fn rows() -> Vec<IndicatorMeta> {
    use Category::*;
    use RenderKind::*;
    vec![
        // ---- candlestick patterns (patterns.py) ----
        pattern!("doji", "Doji", Doji),
        pattern!("engulfing", "Engulfing", Engulfing),
        pattern!("hammer", "Hammer", Hammer),
        pattern!("inverted_hammer", "Inverted Hammer", InvertedHammer),
        pattern!("hanging_man", "Hanging Man", HangingMan),
        pattern!("shooting_star", "Shooting Star", ShootingStar),
        pattern!("dragonfly_doji", "Dragonfly Doji", DragonflyDoji),
        pattern!("gravestone_doji", "Gravestone Doji", GravestoneDoji),
        pattern!("longlegged_doji", "Long-Legged Doji", LongleggedDoji),
        pattern!("rickshaw_man", "Rickshaw Man", RickshawMan),
        pattern!("takuri", "Takuri", Takuri),
        pattern!("marubozu", "Marubozu", Marubozu),
        pattern!("closing_marubozu", "Closing Marubozu", ClosingMarubozu),
        pattern!("spinning_top", "Spinning Top", SpinningTop),
        pattern!("high_wave", "High Wave", HighWave),
        pattern!("long_line", "Long Line", LongLine),
        pattern!("short_line", "Short Line", ShortLine),
        pattern!("belt_hold", "Belt Hold", BeltHold),
        pattern!("opening_marubozu", "Opening Marubozu", OpeningMarubozu),
        pattern!("doji_star", "Doji Star", DojiStar),
        pattern!("harami", "Harami", Harami),
        pattern!("harami_cross", "Harami Cross", HaramiCross),
        pattern!("piercing", "Piercing", Piercing),
        pattern!("dark_cloud_cover", "Dark Cloud Cover", DarkCloudCover),
        pattern!("counterattack", "Counterattack", Counterattack),
        pattern!("meeting_lines", "Meeting Lines", MeetingLines),
        pattern!("separating_lines", "Separating Lines", SeparatingLines),
        pattern!("matching_low", "Matching Low", MatchingLow),
        pattern!("on_neck", "On Neck", OnNeck),
        pattern!("in_neck", "In Neck", InNeck),
        pattern!("thrusting", "Thrusting", Thrusting),
        pattern!("kicking", "Kicking", Kicking),
        pattern!("kicking_by_length", "Kicking by Length", KickingByLength),
        pattern!("homing_pigeon", "Homing Pigeon", HomingPigeon),
        pattern!("gap_side_side_white", "Gapping Side-by-Side White", GapSideSideWhite),
        pattern!("tasuki_gap", "Tasuki Gap", TasukiGap),
        pattern!("morning_star", "Morning Star", MorningStar),
        pattern!("evening_star", "Evening Star", EveningStar),
        pattern!("morning_doji_star", "Morning Doji Star", MorningDojiStar),
        pattern!("evening_doji_star", "Evening Doji Star", EveningDojiStar),
        pattern!("three_white_soldiers", "Three White Soldiers", ThreeWhiteSoldiers),
        pattern!("three_black_crows", "Three Black Crows", ThreeBlackCrows),
        pattern!("identical_three_crows", "Identical Three Crows", IdenticalThreeCrows),
        pattern!("three_inside", "Three Inside", ThreeInside),
        pattern!("three_outside", "Three Outside", ThreeOutside),
        pattern!("three_line_strike", "Three-Line Strike", ThreeLineStrike),
        pattern!("three_stars_in_south", "Three Stars in the South", ThreeStarsInSouth),
        pattern!("abandoned_baby", "Abandoned Baby", AbandonedBaby),
        pattern!("advance_block", "Advance Block", AdvanceBlock),
        pattern!("stalled_pattern", "Stalled Pattern", StalledPattern),
        pattern!("two_crows", "Two Crows", TwoCrows),
        pattern!("upside_gap_two_crows", "Upside Gap Two Crows", UpsideGapTwoCrows),
        pattern!("tristar", "Tristar", Tristar),
        pattern!("unique_three_river", "Unique Three River", UniqueThreeRiver),
        pattern!("stick_sandwich", "Stick Sandwich", StickSandwich),
        pattern!("ladder_bottom", "Ladder Bottom", LadderBottom),
        pattern!("concealing_baby_swallow", "Concealing Baby Swallow", ConcealingBabySwallow),
        pattern!("rise_fall_three_methods", "Rising/Falling Three Methods", RiseFallThreeMethods),
        pattern!("mat_hold", "Mat Hold", MatHold),
        pattern!("hikkake", "Hikkake", Hikkake),
        pattern!("hikkake_mod", "Modified Hikkake", HikkakeMod),
        pattern!("xside_gap_three_methods", "Up/Down-side Gap Three Methods", XsideGapThreeMethods),
        pattern!("breakaway", "Breakaway", Breakaway),
    ]
}
